### ISSUE TITLE
Setting/ changing password for superuser/admin user

### ISSUE THREAD

**Issue by aditya1808** [zalando/postgres-operator#1000]
Hi, how do we set passowrd for super user during installation of cluster?
i couldnt find much. I could only get below info which needs to be set in manifest file
  **users:
    # database owner
    zalando:
    - superuser
    - createdb**

but it doesnt have any field for password for that user. And also what is the procedure to change once set admin password? Any documents available could be shared. thanks

**Comment by aditya1808** [comment]
@CyberDem0n Could you please point to  any documentation available for setting passwords for superuser in manifest file? In our setup we want to have control over what password is set for superuser. Is there a way to set it? And also, is there a way to change it once cluster is up and running??

**Comment by CyberDem0n** [comment]
Operator generates passwords automatically (except infrastructure roles) and puts them into the [secrets](https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#connect-to-the-postgres-cluster-via-psql). The secret name is generated based on the cluster name and user name.

In case if the secret object already exists, operator will read it and use the password from there instead of generating it.

There is no good story for changing superuser and replication password, but you can do it manually: 
1. secret objects
2. connect to postgres and change passwords there
3. do the rolling restart, first replicas and then primary

**Comment by aditya1808** [comment]
@CyberDem0n Thanks for the info.. one last thing.

you said we can change password using secret objects. 
Is there a way to change just the secret objects with our "new password" and somehow make the cluster read from it or its necessary for the cluster to restart inorder to take the new password into effect.

**Comment by CyberDem0n** [comment]
Secrets are propagated into pods as environment variables, which are later used to generate `postgres.yml` config file.

Instead of rotating pods you can update `postgres.yaml` on every pod with new passwords and run `patronictl reload`. But replicas likely will be restarted by Patroni.

**Comment by aditya1808** [comment]
@CyberDem0n  Actually ,one more last thing :) (sorry to bother you so much)
as i understood there are three ways
1) modify postgres.yml inside pod and do patronictl reload ( this will restard replicas)
OR
2) modify secrets and do rolling upgrade 
OR
3)connect to postgres and change passwords there (?) will this require restarting cluster as well?!

**Comment by CyberDem0n** [comment]
you have to:
1. modify secrets
2. connect to postgres and change passwords
3. rotate pods OR update postgres.yml + reload

**Comment by aditya1808** [comment]
@CyberDem0n why do i need to do all of them in sequence?
if i can change password by connecting to postgres, why is changing secret required?
and why is rotating pods required as well? im kinda lost here.

as i understood, it stores passwords in secrets during installation. Secrets are propagated into pods as environment variables, which are later used to generate postgres.yml config file.

**Comment by CyberDem0n** [comment]
Patroni NEEDS to know password in order to connect to the postgres.
The password is coming from the secret object.
If the secret object wasn't changed after the next pod restart it will not be able to start streaming from primary due to the password being wrong.

**Comment by aditya1808** [comment]
@CyberDem0n Oh okay..kinda getting into the picture now..
so modifying secrets is for the purpose of patroni..

**connect to postgres and change passwords** -> i believe this is for postgresql itself..
is there anyother way? instead of connecting to db and changing password? something similar to changing secret and or modifying some config file?

**Comment by FxKu** [comment]
@aditya1808 nope. If you want control over this it requires manual interaction. And it's not planned to change this behavior.

**Comment by Jan-M** [comment]
@aditya1808 I would go back to start, why do you want to set the passwords? The intention is to have this procedure of bootstrapping handsfree and the PWs not leaving the K8s environment and thus use secrets only.

If you for some reason need to change them I think methods here have been outlined. E.g. log into master pod, change password using psql and update respective secret.

**Comment by aditya1808** [comment]
@Jan-M we want to have control over what password is set and also we want to be able to change it sometime in future. 
Anyways thanks for the info. It was helpful. Closing the issue

**Comment by aditya1808** [comment]
@CyberDem0n Need info regarding standby user. could you share any docs regarding this. Couldnt find any. Once cluster is up and If in case i change superuser password, is it necessary to change this as well ? will it have any impact?
