### ISSUE TITLE
Can we set toleration for connection pooler pods?

### ISSUE THREAD

**Issue by vishu-roy12** [zalando/postgres-operator#1002]
Hi,

Wanted to ask if we can set toleration for connection pooler pods? I cant see where to put the toleration block for connection pooler. I tried to set the same in cluster manifest, its working for cluster pods but not for connection pooler pods.

So what i want is, to schedule the connection pooler pods on the tainted node pools, currently, its getting scheduled on other node pools.

**Comment by Jan-M** [comment]
Similar to image pull secrets, missing feature and or bug, so feel free to dive into the Go code.

**Comment by FxKu** [comment]
With #1464 pod tolerations will be reused for pooler pods, too. So configurable, but only indirectly.
