### ISSUE TITLE
StatefulSet sync when pod is terminating.

### ISSUE THREAD

**Issue by yanchenko-igor** [zalando/postgres-operator#1005]
We had an issue with a pod stuck in Terminating state due to the issues with a node. I am thinking that ignoring pods in terminating state would be a best solution for this issue (possibly with a timeout). So for example if pod stuck in Terminating state, we compare desired replicas with existing replicas minus amount of pods that are being in Terminating state longer than the timeout, after a pod termination we would need to decrease amount of replicas. i would like to hear your suggestions before trying to implement something like this.

**Comment by Jan-M** [comment]
Quick glance this is a nice idea but will likely not add that much value.

If a pod is stuck in terminating at least on AWS it means that the EBS volume (data volume) is also still in use and cannot be attached to another node.

Thus if you add more instances you essentially need to initialize a new replica/data volume. That can be a good idea if cluster are small, but will essentially take much longer bigger clusters where it will likely be slower than the pod being stuck in terminating.

Ultimately I would opt for the operator not dealing too much with this, and leaving as much of those dealings for Kubernetes. Stuck pods and volumes are an infrastructure problem.

**Comment by yanchenko-igor** [comment]
@Jan-M I actually created a PR to kubernetes to handle this https://github.com/kubernetes/kubernetes/pull/91907 and I believe that would be much better if it was accepted in kubernetes. Thanks anyway.

**Comment by Jan-M** [comment]
@yanchenko-igor Thank you for your input and idea.
