### ISSUE TITLE
Add support for backup retention period for logical backup

### ISSUE THREAD

**Issue by SandeepPissay** [zalando/postgres-operator#1008]
When postgres operator is configured with logical backup and if postgresql cluster has logical backup enabled, the operator creates a cronjob with the specified schedule. The default cronjob dumps all the databases in the postgres cluster to a S3 endpoint. Currently there is no way to cleanup old backups in the S3 endpoint, this is also called out here  -https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#logical-backups. I'm filing an issue to address this with backup retention support. 

Please let me know if there is already an issue tracking this or someone has put down their thougts on how to solve this.

**Comment by blacs30** [comment]
A workaround could be a lifecycle configuration in the s3 bucket (minio supports it too) to delete versions after x days. Of course I'd also like to the operator handling this.

**Comment by sushiMix** [comment]
Hello, How do you ensure that the logical backup data can be removed to perform a correct restore process ?

**Comment by FxKu** [comment]
Closing since #1337 has been merged.
