### ISSUE TITLE
Setting configuration ( wal_keep_segments ) in manifest file

### ISSUE THREAD

**Issue by aditya1808** [zalando/postgres-operator#1010]
Hi,
Is there a way to set 
**remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
wal_keep_segments: 900**

in manifest file?

**Comment by FxKu** [comment]
Try to set them [here](https://github.com/zalando/postgres-operator/blob/master/manifests/complete-postgres-manifest.yaml#L37).

**Comment by aditya1808** [comment]
@FxKu Hi, I tried setting it there but its not reflecting in the configuration in pod

![image](https://user-images.githubusercontent.com/6763803/84380626-458e7780-ac05-11ea-8889-1992ca3bc88f.png)

$patronictl show-config - 
![image](https://user-images.githubusercontent.com/6763803/84380769-89817c80-ac05-11ea-8c32-2385c80e6c6e.png)

**Comment by FxKu** [comment]
ah that is restricted, we had an issue before, see #968
