### ISSUE TITLE
warning: it tries to create postgres-pod role binding - even when it already exists

### ISSUE THREAD

**Issue by ReSearchITEng** [zalando/postgres-operator#1018]
Even if they exist:
```
oc get rolebinding | grep postgres
postgres-operator                      19d
postgres-pod                           19d

oc get sa | grep postgres
postgres-operator                       2         18d
postgres-pod                            2         18d
```
We still get this warning. When it already exists, I suggest downgrade the message to debug and change message to "already exists and failed to recreate" - (if intention is to recreate it).
```time="2020-06-12T15:49:56Z" level=warning msg="Pods and/or Patroni may misfunction due to the lack of permissions: could not create role binding \"postgres-pod\" : rolebindings.rbac.authorization.k8s.io \"postgres-pod\" is forbidden: User \"system:serviceaccount:namespace:postgres-operator\" cannot get resource \"rolebindings\" in API group \"rbac.authorization.k8s.io\" in the namespace \"namespace\"" pkg=controller```

**Comment by FxKu** [comment]
The problem has to do with reading existing `RoleBindings` to check if a creation is necessary. You're lacking that permission although the postgres-operator service account [should have it](https://github.com/zalando/postgres-operator/blob/master/manifests/operator-service-account-rbac.yaml#L188). Can you check, if it's missing in your case?

**Comment by ReSearchITEng** [comment]
well, it should be there.. Let's close it, we'll reopen if we face it again.
