### ISSUE TITLE
PodEnvironmentConfigMap per cluster

### ISSUE THREAD

**Issue by yanchenko-igor** [zalando/postgres-operator#1025]
I would like to restart pods after editing pod_environment_configmap option (or configmap itself). but because it is an operator option it requires to restart an operator pod and manually restart pods. I would like to have a similar option per cluster, so sync would update statefulset and restart pods when I change this option. Does this make sense or am I doing something wrong?

**Comment by FxKu** [comment]
Should be solved with cluster-specific env variables #1794
