### ISSUE TITLE
Add helm repo

### ISSUE THREAD

**Issue by sergeyshaykhullin** [zalando/postgres-operator#1026]
Add helm chart repo, because manual installation with pulling git repo is not comfortable =/
Maybe i lost something? You have tarballs inside repo, does they hosted somewhere?

Some repo hosting options: https://helm.sh/docs/topics/chart_repository/

```sh
helm repo add zalando https://whatever
```

**Comment by sergeyshaykhullin** [comment]
I found index.yaml file. Should i use github cdn for repo registering?

**Comment by jiwanovski87** [comment]
@sergeyshaykhullin Have you solved this? Which url do you have taken?

**Comment by jiwanovski87** [comment]
Okay I found it myself....
- postgress-operator: `helm repo add [LOCALREPONAME] https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator`
- - postgress-operator-ui: `helm repo add [LOCALREPONAME] https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator-ui`

Note: you have to replace the [LOCALREPONAME]
