### ISSUE TITLE
[Question] Single/multiple postgres and logical backups

### ISSUE THREAD

**Issue by sergeyshaykhullin** [zalando/postgres-operator#1032]
I have one pg cluster with multiple databases and logical backups enabled.
Backups are made for all cluster databases, any way i can sepatare to backups per db?

Does having pg cluster per database is a best practise?

**Comment by FxKu** [comment]
Yes, we usually recommend to our teams to go with one database per cluster. Of course, there can be scenarios where it might make more sense to keep stuff at one place, e.g. on app / micro service talking to multiple DBs. I think, you'd also want to dump everything.

But, in case you have apps talking only to certain DBs, maybe doing crazy stuff and kill postgres, you get downtine with all DBs and services. So going with multiple clusters can protect you there.

**Comment by sergeyshaykhullin** [comment]
@FxKu Can i restore specific db from whole cluster dump?
