### ISSUE TITLE
Logical backup create bucket if not exists

### ISSUE THREAD

**Issue by sergeyshaykhullin** [zalando/postgres-operator#1033]
I am using logical backup to minio cluster

```yaml
logical_backup_s3_bucket: "backups"
```

But specified bucket for backups should be created manually

**Comment by FxKu** [comment]
Yes, you must create the bucket in advance.

**Comment by sergeyshaykhullin** [comment]
So does operator can create("provision") bucket if it not exists?

**Comment by sergeyshaykhullin** [comment]
I found bucket provisioning in minio helm chart. That solves my problem https://github.com/helm/charts/blob/d1efe909ac55e6cc68fbc6f7b6263be2d20cdff5/stable/minio/values.yaml#L228

**Comment by aditya1808** [comment]
hi @sergeyshaykhullin,
Could you share parameters you used in pg-operator to do logicalbackup to a minio cluster. I have same usecase and not exactly able to figure out what parameters to define in pg-operator helm chart.
Thanks!
