### ISSUE TITLE
high activity on a table cause cause canceling statement on the secondary and failing backups

### ISSUE THREAD

**Issue by usernkey** [zalando/postgres-operator#1039]
Our backup with the following error.

pg_dump: error: Dumping the contents of table "xx" failed: PQgetResult() failed.
pg_dump: error: Error message from server: ERROR:  canceling statement due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.
pg_dump: error: The command was: COPY xx (xx, xx, xx, xx, xx, xx, xx) TO stdout;
pg_dumpall: error: pg_dump failed on database "xx", exiting

This seems a well-know issue that requires a change in postgresql.conf to give the secondary the time to finish the call.

https://pganalyze.com/docs/log-insights/standby/B95

Unfortunately, I don't a way to push additional configuration in postgresql.conf  and this settings are not available as environment variables.

**Comment by usernkey** [comment]
It is possible to pass custom configuration to Postress using the parameter field https://github.com/zalando/postgres-operator/blob/master/docs/reference/cluster_manifest.md. We used this to pass the hot_standby_feedback.

**Comment by tkolodziej** [comment]
Did you find solution for this problem ? I have same situation. 
I've already changed the postgres manifest with parameters 
```
  postgresql:
    parameters:
      max_standby_archive_delay: "180"
      max_standby_streaming_delay: "180"
```
but backup job still failing after a few seconds.

**Comment by tkolodziej** [comment]
Now I see... `hot_standby_feedback: "on"` works for me too.

**Comment by sergeyshevch** [comment]
I guess that it has correct workaround solution that also was helped to me. Maybe we can close this?

**Comment by usernkey** [comment]
@sergeyshevch  ok

**Comment by IlyaSemenov** [comment]
@tkolodziej I think it should be "180s" not just "180".
