### ISSUE TITLE
Changing volume size doesnt trigger rolling upgrade.

### ISSUE THREAD

**Issue by aditya1808** [zalando/postgres-operator#1043]
im trying to change pvc size by modifying "volume" parameter in manifest file of already deployed cluster
IT doesnt seem to work. Rolling upgrade is not triggered and neither did pvc volume size increased.

Is it possible to change pvc volume size jst by modifying the manifest?

**Comment by FxKu** [comment]
Usually for EBS volumes, increasing the volume size works from changing it in the Postgres cluster manifest. It does not trigger a rolling update. This is what we wanted to avoid when implementing this feature.

Which environment are you using? Have a look at the operator pod logs to see if there are errors regarding the resize.

**Comment by markusjevringsesame** [comment]
We're on gcp, and we have this issues as well. The only complaint in the log we have is that it complains about being unable to *shrink* volumes, whereas what we actually want to do is *grow* our volumes. We ended up manually resizing the volume through the google cloud console, so postgres clearly picks up the resized volume just fine. It's just that the operator is unable to actually perform the resizing.

**Comment by aditya1808** [comment]
Hi @FxKu , im able to see error in operator pod logs

![image](https://user-images.githubusercontent.com/6763803/87216898-7b885e00-c361-11ea-96df-11154a3f7739.png)

Can you provide some insight on this? what does it mean by **not compatible with existing resizing providers**.
Do we have an option to specify which provider to use?

kindly share any documentation available for this. Thank you.

**Comment by aditya1808** [comment]
@CyberDem0n Could you please have a look at this and tell whats missing?
Why does it say **volume is incompativle with available resizing providers?**

Does pg-operator expects volume to be EBS only? im kinda lost. Could you help shed some light on this? may be some documentation on what PV does pg-operator support. 
Thanks!

**Comment by FxKu** [comment]
@aditya1808 Until recently the resize method only worked for EBS volumes. Recently, the `storage_resize_mode` got introduced with #958 and I think in your case, you should choose the `pvc` option. It will be included in the next release, or you use the most recent image (`registry.opensource.zalan.do/acid/postgres-operator:v1.5.0-27-gf3ddce8-dirty`).

**Comment by FxKu** [comment]
Closing this one now, as with the new `v1.6.0` release you can now use the K8s-native resize mode via PVCs.
