### ISSUE TITLE
pod antiaffinity not beeing apllied to cluster

### ISSUE THREAD

**Issue by haroonb** [zalando/postgres-operator#1049]
Hello 

I'm currently trying to apply the pod antiaffinity for my cluster, so all pods don't run on the same worker.
I deployed in k8s with configmap and set `enable_pod_antiaffinity: "true"` and `pod_antiaffinity_topology_key: "kubernetes.io/hostname"`. But the operator doesn't update the statefulset or performes a rolling update. I can see that the configmap is updated and has the flag set to true, but the pods stay on the same worker.

I also can't see anything related to antiaffinity in the operator log, but I don't know how it should work together. I hope someone can assist me to figure this out.

Thanks for the suggestions and assistance.

regards

**Comment by FxKu** [comment]
You need to delete the operator pod to trigger a reload of the configuration. Changing the node affinity does trigger rolling updates. We cover this in our e2e tests.

**Comment by haroonb** [comment]
Thanks, scaling the pods worked.
