### ISSUE TITLE
could not create master endpoint

### ISSUE THREAD

**Issue by neelasha-09** [zalando/postgres-operator#1056]
Hi Team,

While trying to delete the resources using helm delete --purge for postgres-operator  and recreating the cluster with the same name we could see the below error.

reason: 'Create' could not create cluster: could not create master endpoint: could not create master endpoint: endpoints \"postgres-operator-cluster\" already exists"

Could you please have a look ?

**Comment by FxKu** [comment]
see my [comment in #1057](https://github.com/zalando/postgres-operator/issues/1057#issuecomment-657540755)

**Comment by FxKu** [comment]
will close this one in favor for #1057
