### ISSUE TITLE
Recreate clusters after helm delete operator

### ISSUE THREAD

**Issue by neelasha-09** [zalando/postgres-operator#1057]
Hi Team,

While trying to delete the resources using helm delete --purge for postgres-operator and recreating the cluster with the same name we could see the below error.

```
reason: 'could not create pod disruption budget: poddisruptionbudgets.policy \"postgres-postgres-operator-cluster-pdb\" already exists"  
```

Could you please have a look ?

**Comment by FxKu** [comment]
Deleting the operator does not delete running Postgres clusters. That's actually a feature :smiley:

**Comment by neelasha-09** [comment]
Hi Felix

Deleting the operator and recreating the *operator* with the same name
produces the error.

**Comment by FxKu** [comment]
If you run `helm delete postgres-operator` you delete the controller for Postgres CRDs but not the postgres clusters. If you check with `kubectl get postgresqls` you should still be able to see your `postgres-postgres-operator-cluster` listed in `Running` state. Therefore, trying to create that cluster again will fail with the message you've posted. It can happen that a DELETE event does not clean up all resources, see #498. I don't know if this happens in your case.

To properly remove a Postgres cluster run `kubectl delete postgresql postgres-postgres-operator-cluster`. Then all elements incl. PDB, endpoints etc. should be removed.

**Comment by neelasha-09** [comment]
Thanks Felix :)

**Comment by kahidna** [comment]
hi @FxKu I also tried do same (meaning reinit cluster with same name) but the error message still say 
`reason: 'Create' could not create cluster: could not create master endpoint: could not create master endpoint: endpoints \"acid-cluster-name" already exists.` 

even I reset the kubernetes cluster using kubeadm reset, delete the pv directory path, delete the docker images. the operator logs is same. Am I miss a step?

ps: my env :
- kubernetes 1.18.6
- postgres operator v1.5.0
- spilo 12 1.6-p3

**Comment by holgerson97** [comment]
I could fix this by delete both namespaces for operator and the desired cluster. When reapplying it still through that error. After 10min everything went to running. I then didn't ask questions anymore. I also had to go through that entire process a few times.
