### ISSUE TITLE
EBS resize failed when IAM role not present and ends up in questionable state.

### ISSUE THREAD

**Issue by Jan-M** [zalando/postgres-operator#106]
In the case of the operator running without the IAM role or without sufficient privileges to do the volume resize agains AWS API it statefulset is still updated to reflect the desired size while the volume stays at 10GB.

This should lead to either continues tries to resize the existing EBS volume (which may be less nice)

Or should lead to an unsuccesful sync of manifest and stateful set with repeated error message/logs that credentials/privileges are missing.

**Comment by FxKu** [comment]
Closing this one now, as we moved to native K8s volume resizing.
