### ISSUE TITLE
How to recover after logicalbackup?

### ISSUE THREAD

**Issue by aditya1808** [zalando/postgres-operator#1071]
I have gone through documentation and i found enough docs to enable logicalbackup to S3.
But how about recovery?
Is cloning  from S3 bucket only option to do recovery? 
Please help me find relevant docs.

**Comment by redscaresu** [comment]
not sure if this is best practice but I just do a manual restore where I have had to do one.

@vitobotta has blogged about it too, they wrote a python script to do it.

https://vitobotta.com/2020/02/05/postgres-kubernetes-zalando-operator/

**Comment by aditya1808** [comment]
@redscaresu Thanks for providing this. Although i have one question regarding backup.
According to docs, we can have logicalbackup run as  a cron job managed by operator.
But according to this , 
https://postgres-operator.readthedocs.io/en/latest/reference/cluster_manifest/#parameters-defining-how-to-clone-the-cluster-from-another-one

it talks about **s3_wal_path the url to S3 bucket containing the WAL archive of the cluster to be cloned. Optional.**

How can we have WAL archiving enabled? is it same as logical backup?
