### ISSUE TITLE
Helm delete spilo cluster is deleting underlying PVC

### ISSUE THREAD

**Issue by aditya1808** [zalando/postgres-operator#1075]
I have deployed a cluster with pg-operator. 
And it created statefulset along with PVCs as expected.

**https://github.com/helm/helm/issues/5156**
If you look at the above issue, helm del --purge shouldnt delete pvc along with the statefulset.
But in my case if i helm delete the cluster, its deleting the pvc.
Does pg-operator handles all this?? is this expected behavior?

**Comment by FxKu** [comment]
If you delete the Postgresql CR this triggers deletion of statefulset and, thus, PVCs. Actually, I thought deleting the chart with `--purge` does not delete the clusters, see #1057. So in your case everything is deleted? Statefulset, services, PDB?

**Comment by aditya1808** [comment]
@FxKu yes, in my case it delets statefulset, service, pvc and pdb
and i use delete --purge..

Is there any way not to delete PVCs?

**Comment by FxKu** [comment]
#1074 makes this configurable.

**Comment by FxKu** [comment]
finally supported with #2579
