### ISSUE TITLE
Chart: Operator UI Error with Target Namespace '*'

### ISSUE THREAD

**Issue by arichardet** [zalando/postgres-operator#1081]
The operator UI chart is not able to watch all namespaces by setting `targetNamespace: "*"` in the [values.yaml](https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator-ui/values.yaml#L41).

Below is the error when using helm convert:
```
F0729 08:34:30.661781   61134 convert.go:212] Error converting yaml to resources: error converting YAML to JSON: yaml: line 55: did not find expected alphabetic or numeric character
```

**Comment by FxKu** [comment]
Merged #1082. Thanks for providing the #PR and reminding us on this open issue.
