### ISSUE TITLE
Operator UI Port Forwarding Documentation Mistake

### ISSUE THREAD

**Issue by sonaysevik** [zalando/postgres-operator#1093]
When following documentation, UI  port forwarding command is as follows: 

> `kubectl port-forward svc/postgres-operator-ui 8081:8081`

But working on Windows, I got:

> kubectl port-forward svc/postgres-operator-ui 8081:8081
>  error: Service postgres-operator-ui does not have a service port 8081

Then, when run 
![Capture](https://user-images.githubusercontent.com/2042557/89815965-90f9cf00-db3d-11ea-9dec-e693fa6f50ec.PNG)

So I thought the internal 8081 in fact should be 80 as:

>  kubectl port-forward svc/postgres-operator-ui 8081:80  

And it worked. Either there is an OS dependent discrepancy or the default port has changed without documentation update.

**Comment by FxKu** [comment]
Regarding [this](https://github.com/zalando/postgres-operator/blob/0508266219c9aa8235862ecaa089e082aa97672c/ui/manifests/service.yaml#L13) line, I think you're right and we have to update the docs. You want to open a PR and contribute your findings?

**Comment by sonaysevik** [comment]
Yes! Would love to :) 

Thanks, will open it soon.
