### ISSUE TITLE
How to port forward service?

### ISSUE THREAD

**Issue by softshipper** [zalando/postgres-operator#1094]
Hi all 

I have created a database cluster and following services are also have been created:

```
databaker-users-db          ClusterIP   10.245.227.1     <none>        5432/TCP   52d
databaker-users-db-config   ClusterIP   None             <none>        <none>     52d
databaker-users-db-repl     ClusterIP   10.245.156.119   <none>        5432/TCP   52d
```  

I would like to forward the service to localhost and tried as follows:

`kubectl port-forward service/databaker-users-db 5432:5432
`
and it shows me:

`error: cannot attach to *v1.Service: invalid service 'databaker-users-db': Service is defined without a selector`

What am I doing wrong?  

Thanks

**Comment by FxKu** [comment]
We don't define selectors on the master service. See the discussion in #340 

You can port-forward to the master pod, and for your app take the service name to connect.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is there any recommended way on how to find the master pod? Would be good to know, stumbled over the same problem.

**Comment by Rohmilchkaese** [comment]
@h0jeZvgoxFepBQ2C look at the logs

```
2023-08-29 09:13:49,620 INFO: no action. I am (kaas-db-0), the leader with the lock
2023-08-29 09:13:59,612 INFO: no action. I am (kaas-db-0), the leader with the lock
``

**Comment by digitalstudium** [comment]
kubectl port-forward --namespace <namespace-name> pod/<master-pod-name> 5432:5432

where <master-pod-name> is a pod with a master role.
