### ISSUE TITLE
Cannot Resize The Storage Of Cluster From Patroni UI

### ISSUE THREAD

**Issue by KumarAshish155** [zalando/postgres-operator#1098]
Hi,

We created a Postgres cluster with 50GB of storage from Patroni UI. We later tried to increase the cluster from the UI itself, it could not resize the cluster and gave the following error.

```
time="2020-08-11T13:01:32Z" level=debug msg="updating persistent volume \"pvc-xxxxxxxxxxxxxxxxxxxxxx\" to 55" cluster-name=patroni/acid-maps-geocoding pkg=cluster worker=2
time="2020-08-11T13:01:36Z" level=debug msg="resizing the filesystem on the volume \"pvc-xxxxxxxxxxxxxxxxxxxxxx\"" cluster-name=patroni/acid-maps-geocoding pkg=cluster worker=2
time="2020-08-11T13:01:36Z" level=warning msg="error while syncing cluster state: could not sync persistent volumes: could not sync volumes: could not resize the filesystem on pod \"patroni/acid-maps-geocoding-0\": could not execute: command terminated with exit code 1" cluster-name=patroni/acid-maps-geocoding pkg=cluster worker=2
time="2020-08-11T13:01:36Z" level=error msg="could not sync cluster: could not sync persistent volumes: could not sync volumes: could not resize the filesystem on pod \"patroni/acid-maps-geocoding-0\": could not execute: command terminated with exit code 1" cluster-name=patroni/acid-maps-geocoding pkg=controller worker=2
time="2020-08-11T13:01:36Z" level=info msg="Event(v1.ObjectReference{Kind:\"postgresql\", Namespace:\"patroni\", Name:\"acid-maps-geocoding\", UID:\"cf4fc913-be7a-44bc-9d2c-0fce2b0366b4\", APIVersion:\"acid.zalan.do/v1\", ResourceVersion:\"42498804\", FieldPath:\"\"}): type: 'Warning' reason: 'Sync' could not sync cluster: could not sync persistent volumes: could not sync volumes: could not resize the filesystem on pod \"patroni/acid-maps-geocoding-0\": could not execute: command terminated with exit code 1"
```

Patroni Image :- ```registry.opensource.zalan.do/acid/postgres-operator:v1.5.0```

**Comment by FxKu** [comment]
Not sure what you mean with Patroni UI? The operator UI? Could be that it fails due to missing permissions (e.g. no IAM role specified in config) or it's not supported by you cloud provider (the feature works only an AWS EBS). Have a look at my comment [here](https://github.com/zalando/postgres-operator/issues/1048#issuecomment-656167141), where I mention a new feature available in the current master.

**Comment by FxKu** [comment]
In case you are using AWS with EBS and it#s a permission issue, check my hint [here](https://github.com/zalando/postgres-operator/issues/1089#issuecomment-673529291).

**Comment by Jan-M** [comment]
Essentially the log tells you the "resize2fs" call to resize filesystem fails, so privileges on that very last level and action. Likely you have too little privileges configured for pod.

The "volume" resize should already happen.
