### ISSUE TITLE
Databases per Cluster - Best practice

### ISSUE THREAD

**Issue by timmy59100** [zalando/postgres-operator#1099]
Hello
I've read somewhere that you recommend one cluster per database/app. Could someone clarify what's the best practice here?
We initially planned to do one cluster per environment (dev/prod) and put all databases there.

**Comment by FxKu** [comment]
When you refer to somewhere, maybe it was [here](https://github.com/zalando/postgres-operator/issues/1032#issuecomment-648667634) :smiley: ? Not much to add here. When you run databases in the cloud and with k8s be prepared that they can failover more often and ideally you want to keep the impact as low as possible. So yes I would advice to have one cluster per database/app.

**Comment by timmy59100** [comment]
Yes, exactly, I somehow couldn't find this issue. Thanks for clarification.
