### ISSUE TITLE
Postgres Minor Version Update Questions

### ISSUE THREAD

**Issue by sonaysevik** [zalando/postgres-operator#1100]
Hello,

I have some questions around releasing minor updates on a HA setup of Postgres on Kubernetes.

Thanks to documentation and  @FxKu for help that I know:

1. Manually build a new Spilo image and push to Docker registry 
2. Manually update Operator Configuration's docker_image field
3.  Operator triggers a rolling update starting from replicas one after another and finishes updates of replicas
4. Switches master to one of the replicas.

My questions are:
1. In the documentation it says that the switching master to the updated replica, might take up to 5 seconds, does this cause failing client requests, downtime? Do you use a connection pooler like pgbouncer or a load balancer to pause connections during which? 
2.  If you have thousands of instances to update, what solution do you generally follow? I guess you automate that docker_image update part in a way as well.

Thanks a lot for your help.

**Comment by Jan-M** [comment]
Hi @sonaysevik 

yes, we have the deployments to our Kubernetes infrastructure automated. Kind of a classic staged deployment to a few selected k8s clusters and end 2 end test. Then to all K8s test clusters. And then we release (operator version, spilo version) to production K8s clusters. This hits all production clusters in segments, if we should ever do something wrong to not take out everything.

As for the per cluster upgrade, we essentially do what the operator does by default. Update replicas and then switch master. This does indeed incur a minimal connection loss for all applications. It is a good moment for applications to see if they are resilient and quickly recover for loss of connections.

We will at some point in the future elaborate on this in a blog post.
