### ISSUE TITLE
How to spread cluster pods over separate nodes?

### ISSUE THREAD

**Issue by timmy59100** [zalando/postgres-operator#1106]
Hi
In our clusters the master and every replica pod is scheduled on the same node. Isn't it supposed to spread on different nodes in case of node failure? 
How would I set this?
Thanks

**Comment by FxKu** [comment]
You could enable pod [anti affinity](https://github.com/zalando/postgres-operator/blob/0d81f972a17ef8697479e93f4ecc6df052b70729/manifests/configmap.yaml#L40). If that still doesn't work maybe it's due to some label selectors, policies etc. that scheduling always happens to the same node?

**Comment by timmy59100** [comment]
The anti affinity options works.
Thanks!
