### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by rur0** [zalando/postgres-operator#1109]
Is arm64 support planned?

**Comment by Jan-M** [comment]
We do not have this on our radar and as correctly pointed out first step may be Spilo or a compatilve ARM Postgres Docker Image. I don't see us investing time into this if this is anything but super easy.

**Comment by goshlanguage** [comment]
For most projects I've worked on, converting from `docker build` to `docker buildx build` with the flags for the archs you want to support is sufficient. 

I don't see in `spilo` where the image build is but I'd be happy to test this.

**Comment by xiaolin8** [comment]
xiaolin8/spilo-12:1.6-p5

**Comment by slyons** [comment]
Having this for ARM would be super helpful for local testing

**Comment by Crapworks** [comment]
Are there any news on that? I see that all issues about ARM versions have been closed, but I still don't see any documentation on where to find it.

**Comment by RachadAbiChahine** [comment]
Hello I rebuild the operator image for arm64 waiting the official release 
https://hub.docker.com/repository/docker/rachadac/postgres-operator/general
