### ISSUE TITLE
OperatorConfiguration secret_name_template not honoured

### ISSUE THREAD

**Issue by curionim** [zalando/postgres-operator#1116]
Hi guys,
I deployed an operator with this configuration `secret_name_template:` "{username}-{{ .SERVICE_NAME }}-postgres-credentials"`
When I create a cluster, two secrets are created, one with the above name, and another one with the original template: secret_name_template: "{username}.{cluster}.credentials.{tprkind}.{tprgroup}"

The cluster pods use the password from the latter, therefore ignoring the template which I configured.

Is there some other configuration that I need to change to use only the template I specified?

Thanks,
Michele

**Comment by Jan-M** [comment]
I see a misleading `.` above. 

Can you check postgres operator startup logs. should log the pattern.

Operator version?

Double check spelling.

**Comment by curionim** [comment]
I cannot reproduce this issue after clearing everything and restarting from scratch. 
I think there was another OperatorConfiguration resource deployed in the default namespace, which was being used by the operator, instead of the one defined in the specific namespace.
This could be a separate issue, but I cannot prove it at the moment.
