### ISSUE TITLE
OperatorConfiguration option `pod_environment_secret` is ignored

### ISSUE THREAD

**Issue by npiganeau** [zalando/postgres-operator#1117]
I'm running the operator with CRD configuration.
When I set the `kubernetes.pod_environment_secret` option to any value, it has no effect: the operator ignores it silently.
In particular, setting the value to a non existent secret still gives the same behaviour.

It is worth mentioning that setting `kubernetes.pod_environment_configmap` works as expected.

**Comment by FxKu** [comment]
The `pod_environment_secret` feature has only been merged recently and is not part of any release yet. Good reminder that we should get `v1.6.0` out.

**Comment by npiganeau** [comment]
Thanks for your answer. Looking forward to `v1.6.0`.
