### ISSUE TITLE
translate docs to Chinese

### ISSUE THREAD

**Issue by adevjoe** [zalando/postgres-operator#1118]
Hi, 

I am planning to translate documents to Chinese.

So put Chinese documents in docs/zh_CN, it's ok?

**Comment by Jan-M** [comment]
I don't see why it would not be ok.

Thanks for offering to do the work.

**Comment by Jan-M** [comment]
Personally I have looked into improving documentation and also presentation of documentation. So if people want to help, my personal favorite right now would be to move to `vuepress` which also would support multiple languages.

https://vuepress.vuejs.org/

**Comment by adevjoe** [comment]
I'm testing multiple languages in `https://postgres-operator-cn.readthedocs.io/`. `vuepress` is a good static site generator, maybe we can move to `vuepress`.
