### ISSUE TITLE
Pooler and replicas

### ISSUE THREAD

**Issue by vitobotta** [zalando/postgres-operator#1119]
Hi,

I am a bit confused about the pooler. I have a cluster with master and 2 replicas, and have enabled the pooler, which has itself two instances. Before I was using both the master service and the -repl service in my app to send writes to the master and reads to the replicas. But what if I use the pooler service? Are all the queries always sent to the master? Thanks in advance for any clarification.

**Comment by mboutet** [comment]
From my understanding, the pooler does not load balance queries between the master and the replicas. If you take a look in the pooler's pod environment variables, you can see that `PGHOST` is set to the master's service hostname. What you could do is deploy another custom pgpool deployment that points to the replicas service. You would then have the operator's managed pooler for read/write and your custom pgpool deployment for read-only.

**Comment by vitobotta** [comment]
Hi @mboutet, thanks for the clarification. Do you think it's convenient to do it or should I just stick with normal connections for now while I don't have much traffic? I have quite a bit of resources allocated to Postgres and a max connections limit of 500.

**Comment by Jan-M** [comment]
Pooler toggle for replica service is comming, too. Otherwise yes, as described above the the current pooler only directs all queries to the master.

Quick solution is copy service/deployment yourself and point to replica service.

**Comment by vitobotta** [comment]
Nice, thanks @Jan-M
