### ISSUE TITLE
Disable resync for specific cluster

### ISSUE THREAD

**Issue by asafo** [zalando/postgres-operator#1123]
Hello

We have several issues / use-cases where after initial creation of cluster,
W'ed like the operator to not sync it anymore:

1. Auto-scaling the Statefulset. (editing its 'replicas' field)
2. Changing the port name in the service (e.g: postgresql -> tcp-postgresql, for Istio protocol indication)

In our case, We don't need the operator the synchronize this specific cluster from the CRD anymore.
But we'd like to be able to use the operator to create additional clusters.

Of course, this can be solved in more straight-forward way, i.e: implementing features to control the port name, and to not sync replicas.
But a general feature to ignore particular cluster (CRD, e.g:by labeling) would cover more such cases.

Thanks

**Comment by Jan-M** [comment]
@FxKu we have a detach annotation I think. If you remove it again the operator will start managing again.

However I don't feel this is in scope for the operator, all you are looking for seems to be a statefulset bootstrapper.

**Comment by FxKu** [comment]
Yes, this is already possible: https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#operators-with-defined-ownership-of-certain-postgres-clusters.

Add the controller annotation and the operator will ignore this cluster. Remove it and it's synced again.

**Comment by asafo** [comment]
Thanks!
