### ISSUE TITLE
How to update cluster after changing postgresql parameters

### ISSUE THREAD

**Issue by ciori** [zalando/postgres-operator#1141]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Kubernetes
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

I deployed the postgres cluster with the max_connections value inside the parameters section of the postgresql cluster.yaml and everything is working.

But now I have to change that value, and when I do "kubectl apply -f ..." of the modified clustert.yaml I see that postgres pods are restarting one by one and that the postgresql CRD inside kubernetes has the updated parameter, however, when I look into the postgres pod (psql and then "show max_connections;") I see the old value. Deleting and restaring the operator pod does not resolve the problem.

What is the right way to update the postgres cluster after changing these kind of parameters? Is it possibile to do without completely deleting the cluster?

**Comment by FxKu** [comment]
This should be the workflow for these parameters, but I think max_connections in particular requires something different. Just a Postgres restart not a rolling update (although I would have believed this has the same effect). There's already a PR for this: https://github.com/zalando/postgres-operator/pull/1103

Can you check postgresql.conf file in the container? Does it have the new value? So then maybe restart Postgres, e.g. with `patronictl restart $SCOPE`

**Comment by FxKu** [comment]
Closing since #1103 got merged
