### ISSUE TITLE
GCS Support for standby cluster

### ISSUE THREAD

**Issue by fcrespofastly** [zalando/postgres-operator#1146]
Hey folks! 

First of all, congrats for the postgres-operator project, it's awesome!

This issue it's more like a question. We're Google Cloud heavy users and we are already streaming wal logs to GCS via walg. Cloning a cluster works perfectly fine, but I was hoping to setup a standby cluster too.

By looking at the spec I see `s3_wal_path` as the only possible of way of configuring wal streaming to the standby, so I was wondering if it's on your roadmap to support it. If it's on your roadmap, I'd like to know when do you think it would be available, otherwise I'm happy to submit a PR if I may have some guidance.

Thanks again!

**Comment by FxKu** [comment]
Neither on the roadmap nor planned. But, I can imagine most GCS users would love to see a PR for this one. Oh, actually there is one: https://github.com/zalando/postgres-operator/pull/1058

Maybe you can test for us, if this branch works for you? Then we can move forward there and merge.

**Comment by fcrespofastly** [comment]
@FxKu thanks for pointing me to the PR! 



> Maybe you can test for us, if this branch works for you? Then we can move forward there and merge.

I can do it, but if it works for him I guess it is ok to merge anyways right?

**Comment by FxKu** [comment]
I would really appreciate a test from you because I can not easily test it myself atm. It's better, when I know it has been tested by another GCS user. Thanks.

**Comment by fcrespofastly** [comment]
No worries @FxKu, I'll find some time to test his branch. I'm just going to ask him to rebase to have the most updated and closest to the future release version :)

**Comment by fcrespofastly** [comment]
Added a comment:

https://github.com/zalando/postgres-operator/pull/1058#issuecomment-700720107

**Comment by FxKu** [comment]
Closing since #1446 got merged. Will be included in the next 1.8.0 release (~ jan/feb 2022).
