### ISSUE TITLE
Standby cluster: how to configure?

### ISSUE THREAD

**Issue by Samusername** [zalando/postgres-operator#1150]
registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
k8s, Minio
Not in production, testing.
Type of issue: question.

Hi!

I would have a question if someone could try to help.

Side notes, with Minio S3 buckets: 
Clone functionality works ok. (Minio is in other, active, "data center".) 
Logical backups functionality has worked also.

Next, I tried to define "standby:", "standby cluster". S3 bucket is in Minio.
Docs: 
https://postgres-operator.readthedocs.io/en/latest/reference/cluster_manifest/
https://postgres-operator.readthedocs.io/en/latest/user/

I tried, on standby cluster side:

I removed "spec:  clone:..." ( from earlier "cloning" exercise).

And following was set in yaml:
<pre> ...
 spec:
   standby:
     s3_wal_path: "s3://mybucket/spilo/mydbcluster/[uid]/wal"
 ... </pre>

Is that correct? 
Active cluster stores WAL (WAL-G) archives to that location in Minio: [s3_wal_path]/wal_005 and [s3_wal_path]/basebackups_005.

On standby side:

ConfigMap has the access info to Minio (Minio is located in other DC).
Is ConfigMap correct place or not?

Then, when standby cluster starts up, there appears in logs:
> ...
> trying to bootstrap a new standby leader
> ...
> **not healthy enough** for leader race
> **bootstrap_standby_leader in progress**
(repeats the same)

It does not start up.

My ConfigMap, on standby side:

<pre>
 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: postgres-pod-config  
   namespace: default
 data:
   BACKUP_SCHEDULE: "*/8 * * * *" 
   USE_WALG_BACKUP: "true"
   BACKUP_NUM_TO_RETAIN: "14"
   AWS_ACCESS_KEY_ID: [xxx access key]
   AWS_SECRET_ACCESS_KEY: [yyy secret key]
   AWS_ENDPOINT: http://miniourlinternal.x.y.z
   #AWS_REGION: "eu-west-1"
   AWS_S3_FORCE_PATH_STYLE: "true"
   WALG_DISABLE_S3_SSE: "true"
   wal_s3_bucket: "mybucket"
</pre>

Following is set in postgres-operator values.yaml: pod_environment_configmap: "default/postgres-pod-config".

**Comment by Samusername** [comment]
In following example, "spec:    clone:" section is not needed:
https://github.com/zalando/postgres-operator/blob/master/manifests/standby-manifest.yaml

**Comment by Samusername** [comment]
I tried to set (replaced data section with following):
<pre>
data:
  AWS_S3_FORCE_PATH_STYLE: "true"
  WALG_DISABLE_S3_SSE: "true"
  USEWALG_RESTORE: "true"
  CLONE_METHOD: CLONE_WITH_WALE
  CLONE_AWS_ACCESS_KEY_ID: ACCESS_KEY
  CLONE_AWS_SECRET_ACCESS_KEY: SECRET_KEY
  CLONE_AWS_ENDPOINT: http://neo-minio.neo0011.dyn.nesc.nokia.net
  #CLONE_AWS_REGION: "eu-west-1"
  CLONE_WAL_S3_BUCKET: "mybucket"
  CLONE_WAL_BUCKET_SCOPE_SUFFIX: "[uid]"
  CLONE_TARGET_TIME: "2020-09-30T03:00:03+00:00" # time in the WAL archive that we want to restore
  CLONE_SCOPE: mydbcluster
  wal_s3_bucket: "mybucket"
</pre>

Then:
> 2020-09-30 06:24:09,016 INFO: Lock owner: None; I am mydbcluster-0
> 2020-09-30 06:24:09,163 INFO: trying to bootstrap a new cluster
> 2020-09-30 06:24:09,164 INFO: Running custom bootstrap script: envdir "/run/etc/wal-e.d/env-clone-mydbcluster" python3 /scripts/clone_with_wale.py --recovery-target-time="2020-09-30T03:00:03+00:00"
> 2020-09-30 06:24:19,517 INFO: Lock owner: None; I am mydbcluster-0
> 2020-09-30 06:24:19,517 INFO: not healthy enough for leader race
> 2020-09-30 06:24:19,571 INFO: bootstrap in progress
> 2020-09-30 06:24:29,517 INFO: Lock owner: None; I am mydbcluster-0
> 2020-09-30 06:24:29,517 INFO: not healthy enough for leader race
> 2020-09-30 06:24:29,517 INFO: bootstrap in progress
> (repeats that)

**Comment by Samusername** [comment]
The pod/container is executed with "runAsNonRoot: true" and "privileged: true".

**Comment by FxKu** [comment]
Can you check the Postgres logs, too, please? Was this cluster running before as a normal cluster? Not sure, if you can then turn it into a standby by editing the manifest. I think it has to freshly bootstrapped.

**Comment by Samusername** [comment]
Hi!
I remove the standby cluster always, with helm delete (etc.), before trying again.
So, standby cluster is always installed from scratch.
I tried also with:
  US**E_W**ALG_RESTORE: "true"
  in addition to: USEWALG_RESTORE: "true"

But similar results. (I tried without CLONE_ variables and with those, in ConfigMap.)

The log files in postgres container are empty. Size: zero. patronictl show-config is also empty "{}".

"standby_cluster:" looks like following in postgres.yaml, in the running container:

<pre>
    standby_cluster:
      create_replica_methods:
      - bootstrap_standby_with_wale
      - basebackup_fast_xlog
      restore_command: envdir "/run/etc/wal-e.d/env-standby" /scripts/restore_command.sh "%f" "%p"
</pre>

**Comment by Samusername** [comment]
Following files exist under **env** folder:
<pre>
2020-09-30 12:51:44,896 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_ACCESS_KEY_ID
2020-09-30 12:51:44,896 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
</pre>

Is that enough in standby cluster case?
Similar files do not exist under **env-standby** folder 
/run/etc/wal-e.d/**env-standby**/
in the container.  (Only asking / trying to check.)

List of files in env and in env-standby directories in logs, attached:
[env_parts_of_logs.txt](https://github.com/zalando/postgres-operator/files/5305672/env_parts_of_logs.txt)

**Comment by Samusername** [comment]
After a timeout, I have seen also following in logs:

**Comment by Samusername** [comment]
(Mistakenly closed by clicking something. Reopened right away.)

After a timeout, I have seen also following in logs:
...
Can not find any backups
2020-09-30 10:55:29,796 ERROR: Error creating replica using method bootstrap_standby_with_wale: envdir "/run/etc/wal-e.d/env-standby" bash /scripts/wale_restore.sh exited with code
=1
...

**Comment by Samusername** [comment]
Testing wale_restore.sh and commands inside it.

Following commands work sometimes when these are executed manually from command line in the container:

wale_restore.sh (checked manually: WALG_RESTORE is in use correctly)

Also wal-g backup-list:

envdir "/run/etc/wal-e.d/env-standby" wal-g backup-list 2> /dev/null > backuplist2.txt 

cat backuplist2.txt | sed '0,/^name\s*last_modified\s*/d' | sort -bk2 | tail -n1 | awk '{print $3;}' | sed 's/_.*$//'
00000001000000000000007E

So, those should work ok, sometimes, when those are executed manually.

Sometimes "wal-g backup-list" is stuck for a very long time. (For minutes or "forever".)

These may happen because of various reasons. Network, server, etc. etc. I would need to try to check.

**Comment by Samusername** [comment]
I tested with couple of latest "official" spilo images,
registry.opensource.zalan.do/acid/spilo-12:1.6-pX
https://github.com/zalando/spilo/releases
I did not see the "wal-g backup-list" problem with it, at least not yet.

**Comment by Samusername** [comment]
Trying with the spilo images. Still wale_restore.sh / wal-g do not return results?

"wal-g backup-list" and "wale_restore.sh ..." (with "envdir ... /scripts/wale_restore.sh ..." or with export env variables).
Those work, when those are executed **manually** (in the same patroni DB pod). 

Those seem to still get stuck when patroni start up procedures try to execute those.
With ps -ef, I can see the processes and arguments. I checked also /proc/<id>/environ, of the processes, e.g. of "wal-g backup-list" process.

After timeout, in logs of pod (still):
...
Can not find any backups
2020-10-02 11:01:56,221 ERROR: Error creating replica using method bootstrap_standby_with_wale: envdir "/run/etc/wal-e.d/env-standby" bash /scripts/wale_restore.sh exited with code=1
2020-10-02 11:01:56,221 ERROR: failed to bootstrap clone from remote master None
2020-10-02 11:01:56,221 INFO: Removing data directory: /home/postgres/pgdata/pgroot/data
2020-10-02 11:01:59,583 INFO: removing initialize key after failed attempt to bootstrap the cluster
...

**Comment by Samusername** [comment]
Still similar problems, with an "original" spilo image also.
After long timeout:
...
Can not find any backups
2020-10-02 11:01:56,221 ERROR: Error creating replica using method bootstrap_standby_with_wale: envdir "/run/etc/wal-e.d/env-standby" bash /scripts/wale_restore.sh exited with code=1

wal-g backup-list, etc are stuck in the pod. Those can be seen with ps command.
env-standby has following files:
ls env-standby/
AWS_INSTANCE_PROFILE  AWS_REGION  TMPDIR  USE_WALG_BACKUP  USE_WALG_RESTORE  WALE_LOG_DESTINATION  WALE_S3_PREFIX  WALG_S3_PREFIX  WALG_S3_SSE


Manual test:

I clean up env in terminal.
I set the same env variables which wal-g backup-list has.

I set the same env variables which wal-g backup-list has.
Then "wal-g backup-list" gets stuck.

It works if I copy:

cp env/AWS_* env-standby/   (AWS_ENTRYPOINT, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY AWS_S3_FORCE_PATH_STYLE)
cp env/WALG_DISABLE_S3_SSE  env-standby/
cp env/WALE_S3_ENDPOINT ./env-standby/

Then "wal-g backup-list" works:
envdir "/run/etc/wal-e.d/env-standby" wal-g backup-list

So, would someone know,
Q: Should some of those files be in env-standby? How it works / should work?

**Comment by Samusername** [comment]
CyberDem0n gave a hint in other place.

STANDBY_* fields were needed to be given also for S3 access.

Works now.

**Comment by memogarcia** [comment]
Any plan to document this behavior in the docs itself?
