### ISSUE TITLE
Extension is only installed on one database

### ISSUE THREAD

**Issue by Sephtenen** [zalando/postgres-operator#1155]
Operator image : registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
Running locally on [k3d](https://k3d.io/), not in production
Type : bug report (or misunderstanding of mine)
[Gist](https://gist.github.com/Sephtenen/0b55be30b19d32e89403c5e3196327bb)

Hi everyone,

I am facing an issue where the extension (timescaledb) is only installed in one of many `preparedDatabases`. I know it is a better practice to aim for one database per cluster, which we plan to do later.

I set up a minimal example to demonstrate this behavior :
1. Apply the manifest `test-postgres.yaml` (from the [gist](https://gist.github.com/Sephtenen/0b55be30b19d32e89403c5e3196327bb)), which creates 10 `preparedDatabases` with the timescaledb extension
1. Wait a bit until the databases are created
1. Run `for i in {1..10}; do echo ${i} && kubectl exec lysr-test-0 -- psql -U postgres -d test${i} -c 'select extname from pg_extension' | grep timescaledb; done`, which prints the database number, followed by `timescaledb` if it is installed on the database.

I would expect the extension to be installed on every database, but it is only installed on one of them (randomly it seems).

If I modify the manifest file slightly (e.g. by adding a "test11") and apply it again, it is (often) installed on one more database.

I did not find any restriction in the documentation regarding the number of extensions that can be added to a single manifest, but maybe I missed something ?

**Comment by FxKu** [comment]
Sounds very similar to #1130. Could you check with the `latest` image if the error also happens there?

**Comment by Sephtenen** [comment]
I did check #1130 but I did not sound _that_ similar to me.

Anyway, setting the image to `latest` solved the issue ! Thanks !

**Comment by FxKu** [comment]
Great! :smiley:
