### ISSUE TITLE
Bug in new pod environment secret feautre for v1.6

### ISSUE THREAD

**Issue by fmotrifork** [zalando/postgres-operator#1167]
- **Image version:** registry.opensource.zalan.do/acid/postgres-operator:v1.5.0-49-g38e1518-dirty
- **Runtime:** Kubernetes on IBM
- **Postgres Operator in production:** yes
- **Type of issue:** Bug report

The new `pod_environment_secret` feature does not handle namespaces correctly.

In the following line: https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/k8sres.go#L844 the operator uses the name of the secret as the namespace name.
This means that this only works if the name of the secret is the same as the name of the namespace the secret is in. And the same as the namespace where the Postgres Cluster is running.

**Comment by FxKu** [comment]
Fixed with #1177
