### ISSUE TITLE
Selecting password on install

### ISSUE THREAD

**Issue by roee-hershko** [zalando/postgres-operator#1183]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it** - cloud or metal? Kubernetes or OpenShift? Minikube
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

Hey, simple question - is it possible to select password instead of it being generated to secret?
we want to simplify our development environment setup and currently every time we install postgres it generates different password and we need to manually change it

**Comment by Jan-M** [comment]
why can you not get the value from the secret or leverage the secret and mount it?

You can do this though on second thought, you can leverage what we call "infrastructure" roles to create a user with a static password. however this role has 0 privileges by default, except monitoring, so you need more tweaking by setting `in role`. check docs.
