### ISSUE TITLE
Helm - did not find expected '-' indicator

### ISSUE THREAD

**Issue by roee-hershko** [zalando/postgres-operator#1191]
Hey,
when trying to install helm locally i am running the following commands:
```
git clone https://github.com/zalando/postgres-operator.git ./tmp
cd tmp
helm install postgres-operator ./charts/postgres-operator -n postgres-operator
```
and get the following error:
```
Error: failed to install CRD crds/operatorconfigurations.yaml: error parsing : error converting YAML to JSON: yaml: line 51: did not find expected '-' indicator
```

**Comment by FxKu** [comment]
Seems I've introduced an indentation error when switching to the v1 api. Can you check?

**Comment by FxKu** [comment]
Thanks @roee-hershko for raising this. A good reminder that we should include helm chart installation in our test pipelines.
