### ISSUE TITLE
Operator Helm chart with OperatorConfigurationCRD default values

### ISSUE THREAD

**Issue by dalbani** [zalando/postgres-operator#1197]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** GKE
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** feature request

The operator Helm chart ships with 2 default values file:
- https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/values.yaml
- https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/values-cr.yaml

The first one is to be used with `configTarget: ConfigMap`, the second with `configTarget: OperatorConfigurationCRD`.
But I couldn't find a way to actually *use* `values-cr.yaml` when deploying the operator with Helm.
I suppose I could copy/paste the whole content of `values-cr.yaml` in my own file and pass it to Helm.
But, for maintainability/readability reason, I'd prefer to keep *overridden* values only.
Is there a way to do that?

Here's an example of the `values.yaml` that I pass to Helm that triggers the issue:
```yaml
configTarget: OperatorConfigurationCRD
configGeneral:
  docker_image: registry.opensource.zalan.do/acid/spilo-12:1.6-p5
```

I then get this error:
```
Error: OperatorConfiguration.acid.zalan.do "postgres-operator" is invalid: []: Invalid value: ...
validation failure list:
  configuration.min_instances in body must be of type integer: "string"
  configuration.kubernetes.enable_pod_disruption_budget in body must be of type boolean: "string"
  configuration.kubernetes.enable_sidecars in body must be of type boolean: "string"
  ...
```

That's logical because Helm picks the default values from the chart's `values.yaml`, which contains values which are not compatible with `OperatorConfigurationCRD` (e.g. string vs int).

Is there an advanced feature in Helm that I missed to overcome that?
Or do I need to host my own fork of the chart where the content of `values.yaml` is replaced by `values-crd.yaml`?

**Comment by FxKu** [comment]
No need to copy paste stuff - just specify the `values-crd` file in the `helm install` command:

`helm install postgres-operator ./charts/postgres-operator -f ./charts/postgres-operator/values-crd.yaml`

This overrides settings from the values files.

**Comment by dalbani** [comment]
Oh, I simplified my situation too much and forgot to mention: I install the chart from a (private) Helm repository, not from the files of this Git project.
And I'm actually using Helmfile as well, not Helm directly.
So I can't really point to this `values-crd.yaml` AFAIK.

**Comment by Jan-M** [comment]
Maybe you are better of not using helm? I dont see what we can do here.

**Comment by dalbani** [comment]
I see that you closed the bug after you replied, but actually I do have suggestions on how to solve the problem.
Because "not using Helm" when a Helm chart is readily available is not really an option for me.

First, there would be the "quick and dirty" solution of publishing 2 differents Helm chart, for use with either `configTarget: ConfigMap` or `configTarget: OperatorConfigurationCRD`, under `https://opensource.zalando.com/postgres-operator/charts/postgres-operator/postgres-operator-%version%-{ConfigMap|OperatorConfigurationCRD}.tgz` for example.
But that solution is obviously not satisfactory, for maintenance reason.

Second option would be to make the chart have a single `values.yaml`, but still compatible with both `configTarget: ConfigMap` and `configTarget: OperatorConfigurationCRD`.
You know what, I've actually just submitted a basic implementation of this solution in https://github.com/zalando/postgres-operator/pull/1224.
I'm curious what you think of it.
