### ISSUE TITLE
Performance degrading on kubernetes

### ISSUE THREAD

**Issue by hakim** [zalando/postgres-operator#1207]
Hi guys,

I am deploying your solution on a k8s cluster and I started to hesitate to go live for our solution silple because I faced a performance issues, a simple select statement of a table that containt a million an half rows takes more than 10s which is note even comparable with bare metal postgres one instance database. the specs of the k8s I am ussing for production are the follwing:
1. 1 master, 05 slaves 
2. RAM: 5 postgres instances with the follwing manifest:
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: bba-cluster-ever
  namespace: eversuite
spec:
  teamId: "bba"
  volume:
    size: 200Gi
    storageClass: local-storage
  numberOfInstances: 2
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  users:
    everuser:   
    - superuser
    - createdb
    everuser_role: []  
  databases:
    eversuitedb: everuser   
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
    limits:
      cpu: 1000m
      memory: 4Gi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
    - hostssl all all 0.0.0.0/0 md5
    - host    all all 0.0.0.0/0 md5

  postgresql:
    version: "10"

3. the configmap specs:

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
data:
  
  api_port: "8080"
  aws_region: eu-central-1
  cluster_domain: cluster.local
  cluster_history_entries: "1000"
  cluster_labels: application:spilo
  cluster_name_label: cluster-name
 
  connection_pooler_max_db_connections: "400"
  connection_pooler_mode: "session"
 
  db_hosted_zone: db.example.com
  debug_logging: "false"
  default_cpu_limit: "2000m"
  default_cpu_request: 500m
  default_memory_limit: 4Gi
  default_memory_request: 4Gi
  docker_image: 172.16.8.2:5000/postgres-spilo-ppc64le
   enable_database_access: "true"
   enable_master_load_balancer: "false"
  enable_pod_antiaffinity: "true"
  enable_replica_load_balancer: "true"
  enable_shm_volume: "true"
  enable_teams_api: "false"
  logical_backup_docker_image: "registry.opensource.zalan.do/acid/logical-backup"
  logical_backup_s3_bucket: "my-bucket-url"
  logical_backup_s3_sse: "AES256"
  logical_backup_schedule: "30 00 * * *"
  master_dns_name_format: "{cluster}.{team}.{hostedzone}"
  pdb_name_format: "postgres-{cluster}-pdb"
   pod_deletion_wait_timeout: 10m
   pod_label_wait_timeout: 10m
  pod_management_policy: "ordered_ready"
  pod_role_label: spilo-role
    pod_service_account_name: "postgres-pod"
   pod_terminate_grace_period: 5m
  ready_wait_interval: 3s
  ready_wait_timeout: 30s
  repair_period: 5m
  replica_dns_name_format: "{cluster}-repl.{team}.{hostedzone}"
  replication_username: standby
  resource_check_interval: 3s
  resource_check_timeout: 10m
  resync_period: 30m
  ring_log_lines: "100"
  secret_name_template: "{username}.{cluster}.credentials"
   spilo_privileged: "false"
  super_username: postgres
   watched_namespace: "*"   
  workers: "4"

All the contianers are atteched to a local persistent volume which is rooted to a local directory in the slave server.

Can you explain what is going on, also I need to know how to restart the cluster, cuz if I deleted it and started again, some of the instances fails and sometimes the master too.

Thanks,

**Comment by Jan-M** [comment]
Hi Hakim, unfortunately I feel question number 1 falls outside the realm of the operator and becomes more a question for a mailinglist or people familiar and wanting to answer Postgres question in regards to performance. Postgres on K8s or locally can perform very well when setup properly and resources are sufficient.

For the question about restarting Postgres, on Kubernetes this would be achievable with deleting pods, but I cannot judge your setup and durability of volumes.

If you delete the Postgres manifest the Postgres operator will delete all the involved objects and once they are all removed you can recreate the manifest and will get an empty cluster. If this does not work, potentially your volumes are not cleaned up.

Please also leverage current Postgres version via the operator: 12, not 10, (13 is wip)

**Comment by hakim** [comment]
Hi @Jan-M 

Thanks for the quick answer but I am new to zalando and you might notice that it wasn't easy to get it up and running under ppc64le architecture, any way, two inquiries please;
despite that choosing postgresql 10 is basically the vendor recomendation for his web application, I faced a problem when deleting the cluster and recreate it again, I have attached  a local persistent volume to each instance, one or more instances failed when I try to connect to postgres inside the container which is not the case when createing a new cluster, if I went live, It will be a disaster. Second, I need a favor from you to show me a good place where I can find people whom are expert in this matter (kubernetes with postgressql  cluster).

Big thanks,
