### ISSUE TITLE
missing operator-ui helm chart value imagePullSecret

### ISSUE THREAD

**Issue by Thunderbolt32** [zalando/postgres-operator#1210]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.5.0-p3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** no
- **Type of issue?**  feature request

The postgres-operator-ui helm chart is missing the parameter imagePullSecret

**Comment by FxKu** [comment]
merged your PR
