### ISSUE TITLE
What postgres image tag should I use to use in-place upgrade?

### ISSUE THREAD

**Issue by MohamedMSaeed** [zalando/postgres-operator#1237]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
 registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** 
 GCP K8s 
- **Are you running Postgres Operator in production?** 
 yes
- **Type of issue?** 
 question

I'm trying to upgrade my pg_servers from v11 to v13. I found that the operator can do it easily using "spilo 13" as mentioned [here](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#minor-and-major-version-upgrade)

I'm using this helm chart [here](https://github.com/zalando/postgres-operator/tree/master/charts) which defines postgres image with spilo v 12 "registry.opensource.zalan.do/acid/spilo-12:1.6-p3". 

Does this image do the upgrade in-place as mentioned in your docs? if not, what image should I use?

**Comment by FxKu** [comment]
You were a little too early with your question. We did a release by now which includes this functionality, but manual work is still involved. See our updated [docs](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#minor-and-major-version-upgrade) on this.

**Comment by MohamedMSaeed** [comment]
@FxKu 

Thanks for your answer. 

I'm closing this issue :smile:
