### ISSUE TITLE
Cluster never becomes Ready when enabling synchronous_mode_strict

### ISSUE THREAD

**Issue by lchdev** [zalando/postgres-operator#1249]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it ?** Bare Metal K8s
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

I tried to bootstrap a new minimal cluster with the following manifest:

```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: default
spec:
  teamId: acid
  volume:
    size: 1Gi
  numberOfInstances: 3       
  postgresql:
    version: "12"
  patroni:
    synchronous_mode: true
    synchronous_mode_strict: true
```

While the StatefulSet and pods are running, the cluster is stuck with "Creating" status. It seems that patroni is unable to elect the master node which never gets the label "master" (it remains "promoted" forever). After 10 minutes, the operator gives up and the cluster  appears as "SyncFailed".

```
$ kubectl get postgresql
NAME                   TEAM   VERSION   PODS   VOLUME   CPU-REQUEST   MEMORY-REQUEST   AGE     STATUS
acid-minimal-cluster   acid   12        3      1Gi                                     4m19s   Creating

$ kubectl get pods -l application=spilo -L spilo-role
NAME                     READY   STATUS    RESTARTS   AGE     SPILO-ROLE
acid-minimal-cluster-0   1/1     Running   0          6m1s    promoted
acid-minimal-cluster-1   1/1     Running   0          5m41s
acid-minimal-cluster-2   1/1     Running   0          5m23s
```

Patroni logs on the "promoted pod" are not very helpful, all i can see is the following lines repeating:

```
2020-12-10 14:57:26,486 INFO: Lock owner: None; I am acid-minimal-cluster-0
2020-12-10 14:57:26,486 INFO: not healthy enough for leader race
2020-12-10 14:57:26,486 INFO: post_bootstrap in progress
```

Note that if I remove the `synchronous_mode_strict: true` line from the manifest, everything is fine and the cluster is fully operational in less than 2 minutes.

Since I'm fairly new to the postgres operator and Patroni, I don't really know where to look next.

Any help would be appreciated.

**Comment by FxKu** [comment]
Does it also happen with the latest operator and spilo release?

**Comment by lchdev** [comment]
I just upgraded the Operator to v1.6.0 and this solves the issue ! 

Thanks
