### ISSUE TITLE
Helm chart for 1.6.0 not available on chart repository

### ISSUE THREAD

**Issue by ailox** [zalando/postgres-operator#1271]
- **Which image of the operator are you using?** none yet
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** cloud and metal
- **Are you running Postgres Operator in production?** not yet
- **Type of issue?** feature request, or bug in automatic release

I have added the https://opensource.zalando.com/postgres-operator/charts/postgres-operator chart repository for easy installation. Sadly the 1.6.0 is not available, only 1.5.0, without support for PSQL13

It seems the repository is a github page built from this repository.
Is there a way I can help bumping the helm chart release? Is this method of installation even still supported?

Happy Holidays. :snowman:

**Comment by patrickleet** [comment]
https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator/index.yaml

**Comment by patrickleet** [comment]
Use `https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator/` as repo url

**Comment by FxKu** [comment]
I think, I once choose to publish it via the `gh-pages` branch. Just merged the master in there, so maybe it works now.

**Comment by patrickleet** [comment]
it is :)

The ui is still separate though.

Functionally I don't really see the difference.

**Comment by FxKu** [comment]
Can we close it then? Not getting what you mean with "ui is still separate"? 1.6.0 should also be there. Yes it comes with its own chart.

**Comment by ailox** [comment]
I'm closing this ticket, since the 1.6.0 is available in the repository once again.

Using https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator/ Is not a good workaround, as it does not contain the old versions but only the latest one, so I'm happy the relase was pushed to https://opensource.zalando.com/postgres-operator/charts/postgres-operator .

The UI is from my point of view not in the scope of this issue, and would deserve its own.

**Comment by patrickleet** [comment]
> Not getting what you mean with "ui is still separate"?

I didn't open the issue..
