### ISSUE TITLE
[1.6.0] cannot convert int64 to float64 

### ISSUE THREAD

**Issue by vitobotta** [zalando/postgres-operator#1277]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Self managed Rancher cluster
- **Are you running Postgres Operator in production?** [yes | no]
Yes, but I am testing the upgrade from 1.5.0 to 1.6.0 in a throwaway cluster
- **Type of issue?** [Bug report, question, feature request, etc.]
I think bug

Hi,

I am testing the upgrade of the operator from 1.5.0 to 1.6.0. I actually use Pulumi to install the Helm chart but it's like installing manually basically - I have been using this for a while with no problems.

When I try to install 1.6.0 the upgrade fails because of "convert int64 to float64 " errors when updating the CRDs. I can't figure out which fields are causing this. I have commented out values like workers / min_instances / max_instances so to use the defaults according to an old, similar issue, but it doesn't make any difference. How can I find which fields are causing the problem?

These are the values I am using for the chart:

```
  const customValues = {
      configTarget: "OperatorConfigurationCRD",
      configKubernetes: {
        enable_pod_antiaffinity: true,
        pod_environment_configmap: "postgres-pod-config",
        watched_namespace: "*",
        enable_init_containers: true,
        enable_pod_disruption_budget: true,
        enable_sidecars: true,
        spilo_privileged: false
      },
      configAwsOrGcp: {
        aws_region: s3Region,
        aws_endpoint: s3Endpoint,
        wal_s3_bucket: s3Bucket
      },
      configLoadBalancer: {
        enable_master_load_balancer: false,
        enable_replica_load_balancer: false
      },
      configDebug: {
        debug_logging: true,
        enable_database_access: true
      },
      configLogicalBackup: {
        logical_backup_docker_image: logicalBackupsImage,
        logical_backup_s3_access_key_id: s3AccessKeyId,
        logical_backup_s3_bucket: s3Bucket,
        logical_backup_s3_region: s3Region,
        logical_backup_s3_endpoint: s3Endpoint,
        logical_backup_s3_secret_access_key: s3SecretAccessKey,
        logical_backup_s3_sse: logicalBackupS3SSE,
        logical_backup_schedule: logicalBackupDefaultSchedule
      },
      configGeneral: {
        enable_crd_validation: true,
        enable_shm_volume: true,
        // workers: 4,
        // min_instances: -1,
        // max_instances: -1,
      },
      configTeamsApi: {
        enable_team_superuser: false,
        enable_teams_api: false
      },
```

Thanks in advance :)

**Comment by FxKu** [comment]
Have you tried with debug mode `-v=9` or something to find out which field it is? We have't introduced any new CRD minimum/maximum fields. Only migrated them to apiVersion `v1`.

**Comment by vitobotta** [comment]
Hi @FxKu :)

I tried with verbose output but I only get a lot of text with the definition of all the fields, and then at the end I just have "cannot convert int64 to float64". It doesn't really say which field it is :(

**Comment by vitobotta** [comment]
This is on K8s 1.19 BTW

**Comment by vitobotta** [comment]
For example when it fails for "operatorconfigurations.acid.zalan.do" I get this: https://ybin.me/p/5bfcd9babc3411f0#ssXXcAYknqENC413F8TM2MjBowPkuxEJH5xj5kns1EI=

Do you see anything useful? Thanks

**Comment by FxKu** [comment]
I think by now I'm pretty sure it has to do with the `enable_ebs_gp3_migration_max_size` which is not set in the example OperatorConfiguration and we have no internal coalesce for this case. Try to set it to `1000`.
