### ISSUE TITLE
Service is not updated when OperatorConfiguration changes

### ISSUE THREAD

**Issue by haslersn** [zalando/postgres-operator#1300]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

~When changing `enableMasterLoadBalancer` to `true` on a PostgreSQL resource, then the Service type is not updated to `LoadBalancer`.~

Likewise, when changing `db_hosted_zone` in the `OperatorConfiguration` resource, then the Service's `external-dns.alpha.kubernetes.io/hostname` annotation is not updated.

Please tell me if this issue is surprising for you. Then I will try to give more details on how to reproduce.

## Workaround

~My workaround unfortunately leads to a downtime of the service:~

~Delete the affected Service. Now, because of #1299, it's also required to~ delete (in order to recreate) the postgres-operator Pod.

**Comment by FxKu** [comment]
@haslersn toggling `enableMasterLoadBalancer` should trigger an update of the master service almost immediately. Check the operator logs if this doesn't work. Does the type change on the next sync event or not at all?

Changes to the configuration are not applied automatically. This works only via restarting the operator as you mentioned which then syncs all existing clusters and should update the service annotations. So deleting services should not be required at all.

**Comment by haslersn** [comment]
You are right. However, I was in the impression that toggling `enableMasterLoadBalancer` does not trigger an update, because it sometimes takes a long time (~5 minutes) until the update is triggered.

**Comment by FxKu** [comment]
Yes, depending on you environment it can take some time until the load balancer is active. Experienced this too on AWS. Anyway, I will close this issue then. Thanks for raising it and coming back again.

**Comment by haslersn** [comment]
No, this is not the cause of the problem. Please reopen.

I said that the Service is not updated very fast by the operator. It sometimes takes more than 5 minutes until the operator performs an update on the Service (such as setting the `type` to `LoadBalancer`).

Slow load balancer is not a thing on my cluster, because it's an on-premise cluster with MetalLB where we obtain a `loadBalancerIP` in a matter of <5 seconds, but of course only after the Service is updated by postgres-operator.

**Comment by haslersn** [comment]
Also, it the problem does not seem to be restricted to `enableMasterLoadBalancer`, but possibly to all fields of the PostgreSQL resource. It was just that with `enableMasterLoadBalancer` we experienced the problem first and most often, because that's a field we happened to need to change for a few PostgreSQL clusters.
