### ISSUE TITLE
[Question] What is the version of the timescaledb extension supported with Postgres Operator v1.6.0

### ISSUE THREAD

**Issue by pratapagiri** [zalando/postgres-operator#1313]
What is the version of the timescaledb extension supported with Postgres Operator v1.6.0

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes 
- **Type of issue:** Question

**Comment by FxKu** [comment]
This has to do with the Spilo image that supports Timescale 2.0 not the operator. The image build from the master has it: `registry.opensource.zalan.do/acid/spilo-cdp-13:2.0-p150` and the next Spilo release image will have it, too. You can configure the Spilo image the operator should use by default in its [configuration](https://github.com/zalando/postgres-operator/blob/master/docs/reference/operator_parameters.md#general).

**Comment by dalbani** [comment]
I "hijack" to this question to inquire about this image `spilo-cdp-13`.
Where does it come from? What does `cdp` stands for?
Is it updated more regularly than the "usual" Spilo image (https://github.com/zalando/spilo/tags)?
Thanks!

**Comment by FxKu** [comment]
`cdp` is our internal build tool. Spilo images with this tag can be seen as `dev` versions, so yes they are updated more often. But it should be fine for you to stick to release version without the `cdp` tag. The new release `registry.opensource.zalan.do/acid/spilo-13:2.0-p4` contains Timescale 2.0.1.
