### ISSUE TITLE
psql: error: could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by balibebas** [zalando/postgres-operator#1316]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** n/a
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** K3s via K3D
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Documentation issue

I followed the quick start and, since I'm not using Minikube, dropped into the "Connect to PostgreSQL" section of the "User Guide" which suggests to simply connect to Postgres as follows once `PGPASSWORD` and `PGSSLMODE` are set:

```sh
psql -U postgres -p 6432
```

Resulting in the following error:

```term
psql: error: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.6432"?
```

My port-forward was running so I did a:

```
kubectl exec -it acid-minimal-cluster-0 -- bash
```

And confirmed I was able to access the database that way. Then I tried connecting again from outside the Pod using SQLPro for Postgres and it also couldn't connect. Then I tried adding the host like to connect from command line outside the Pod:

```sh
psql -U postgres -p 6432 -h localhost
```

And receive the same error mentioned above:

```term
psql: error: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.6432"?
```

At which point I stopped and restarted my port forward and was only then able to connect. This was a bit confusing as quickstarts should generally be, well, quick. So my suggestions:

- [ ] Add the `-h` flag to the `pgsql` connect command for both the User Guide and README
- [ ] Explain to the user they are supposed to run the connect command outside the pod (it's not obvious)
- [ ] Note that running `psql` from outside the pod requires `psql` installed (somewhat obvious but not completely)

As to why the port forwarder acts flaky when attempting to connect without `-h` I cannot say. But what I can say as that if users cannot easily finish the quickstart they're likely to bail on using the operator.

**Comment by FxKu** [comment]
@balibebas thanks for raising this. It was indeed not working without `-h localhost`. In the quickstart, however, we are setting the PGHOST variable. So there, it's not needed.

**Comment by balibebas** [comment]
Thanks for the change!
