### ISSUE TITLE
Should pg_hba settings work with spilo 13 / spilo 2.0-p2?

### ISSUE THREAD

**Issue by Samusername** [zalando/postgres-operator#1320]
Hi!

Background: We have spilo and postgres-operator under testing in a production pipe.
 
Q: Should pg_hba work with spilo version from December 2020, with postgres-operator? 

pg_hba has been set in comments in github, of postgres-operator:
https://github.com/zalando/postgres-operator/tree/v1.6.0/manifests
complete-postgres-manifest.yaml
On December, 17th:
Link: [complete-postgres-manifest history](https://github.com/zalando/postgres-operator/commits/master/manifests/complete-postgres-manifest.yaml)
Direct link: [link](https://github.com/zalando/postgres-operator/commit/a63ad49ef8101bb58725d892151279cd751df5c0#diff-cdb5d1a4b81bbd32d91b2d19c108d27e6df322708d4502c5a6c13985de4787de).

I cannot define pg_hba:
    pg_hba:
      - hostssl all all 0.0.0.0/0 md5
      - host    all all 0.0.0.0/0 md5

pg_hba has been mentioned in weeks ago in following discussion:
https://github.com/zalando/postgres-operator/issues/1275

E.g. spilo 13, spilo-13:2.0-p2.

With older versions of spilo, we have been able to set pg_hba in the manifest yaml.

Older working pg_hba.conf versus new without pg_hba:

<details>
  <summary>Click to expand!</summary>
Older way (with older version of patroni/spilo), 
pg_hba was possible to be included:

\# Do not edit this file manually!
\# It will be overwritten by Patroni!
**hostssl all all 0.0.0.0/0 md5**
**host    all all 0.0.0.0/0 md5**
local   all             all                                   trust
hostssl all             +zalandos    127.0.0.1/32       pam
host    all             all          127.0.0.1/32       md5
hostssl all             +zalandos    ::1/128            pam
host    all             all          ::1/128            md5
hostssl replication     standby      all                md5
hostnossl all           all          all                reject
hostssl all             +zalandos    all                pam
hostssl all             all          all                md5

With December version of spilo, pg_hba cannot be set in the manifest yaml. Then pg_hba.conf looks like following:

cat ./pgdata/pgroot/data/pg_hba.conf
\# Do not edit this file manually!
\# It will be overwritten by Patroni!
local   all             all                             trust
hostssl all             +zalandos    127.0.0.1/32       pam
host    all             all          127.0.0.1/32       md5
hostssl all             +zalandos    ::1/128            pam
host    all             all          ::1/128            md5
hostssl replication     standby      all                md5
hostnossl all           all          all                reject
hostssl all             +zalandos    all                pam
hostssl all             all          all                md5
</details>

PG 12 or PG 13.

Problems can be seen with nossl connections, it seems. (reject)

**Comment by Samusername** [comment]
Closing this still.
I need to check some more things.
I will reopen, if there will still be problems.

**Comment by Samusername** [comment]
An older case:
https://github.com/zalando/postgres-operator/issues/330

**Comment by Samusername** [comment]
Possible following explains the behavior regarding pg_hba.conf:
Earlier: the pg_hba defs from the manifest yaml were added in the beginning of the pg_hba.conf file.

Now:
The whole pg_hba.conf gets generated (overwritten) with the pg_hba definition from the manifest yaml.

First impression: maybe that / the new way is correct way to do it.

**Comment by FxKu** [comment]
Yes, before it was appending lines to the default config generated by spilo. Now it does a full override. Therefore, replication connection is missing. We should update the example in the manifest to something like:
```
- local all all trust
- host replication standby all md5
- host all all all md5
```

Only `host` will  work, as `libpq` first tries to connect with SSL anyway.
