### ISSUE TITLE
Combine chart values files into a single file 

### ISSUE THREAD

**Issue by apeschel** [zalando/postgres-operator#1344]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. head of master
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** N/A
- **Are you running Postgres Operator in production?** no
- **Type of issue?** feature request

It sounds like the ConfigMap based configuration is deprecated, in favor of the OperatorCRD based configuration. Could we switch the default value in values.yaml to "OperatorConfigurationCRD" and remove the values-crd.yaml file?

The README could be updated to inform users they could set `configtarget=ConfigMap` to use the older style ConfigMap based configuration. The instructions on using the CRD install could be removed.

**Comment by FxKu** [comment]
Yes, should be combined and being able to serve either ConfigMap or CRD-based config. We already have a PR for this #1224

**Comment by FxKu** [comment]
Done
