### ISSUE TITLE
values-crd.yaml unknown field

### ISSUE THREAD

**Issue by apeschel** [zalando/postgres-operator#1346]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** Head of master
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** N/A
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

Trying to use the values-crd.yaml currently on the head of master results in this error:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(OperatorConfiguration.configuration.logical_backup): unknown field "logical_backup_job_prefix" in do.zalan.acid.v1.OperatorConfi
guration.configuration.logical_backup
```

v1.6.0 works fine, so it looks like this is a regression.

**Comment by FxKu** [comment]
This is a new option which was introduced after the v1.6.0 release. Such an error usually means that the CRD on your system isn't yet aware of it. If you delete a helm release CRDs are not deleted. Thus, when you install a chart again, the CRDs are not updated and the new option might be missing.

As it [exists](https://github.com/zalando/postgres-operator/blob/0cce565b651000639f6758444c12b3397e68c2cf/charts/postgres-operator/crds/operatorconfigurations.yaml#L388) in the current master. I suggest you remove the config CRDs and try install again.
