### ISSUE TITLE
pod_environment_secret is not passed along to backup cronjob

### ISSUE THREAD

**Issue by CaptainChemnitz4711** [zalando/postgres-operator#1348]
Hi,

we are currently using the backup functionality of the operator, which creates a cronjob within kubernetes that regularly executes logical backups as described [here ](https://postgres-operator.readthedocs.io/en/latest/administrator/#logical-backups) 
For this we can pass along _logical_backup_s3_secret_access_key_ in order to provide access to the storage. However this is currently passed in a configmap which is insecure. We therefore tried to use the _pod_environment_secret_ mechanism in order to mount a custom secret which holds the credentials necessary upload the backup to storage. 

It turned out that the secrets configured with _pod_environment_secret_ are only considered / mounted on the operator itself. They are not present on the cronjob created by the operator to do the backups. Which leaves the whole backup mechanism insecure in terms of credential management.

I would suggest to either consider the _pod_environment_secret_ also for creating the cronjob or to introduce a new variable specifically used for the logical backup.
 
- **Which image of the operator are you using?** 
   ---> registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Type of issue?** [Bug report, question, feature request, etc.]
   --> BugReport / feature request

**Comment by laukaichung** [comment]
Same. I was wondering if it is possible to pass `pod_environment_configmap` to logical backup cron jobs so that I can need to hardcode the S3 credentials to the `configLogicalBackup` section. Is it supported?

**Comment by robertlandrum** [comment]
I've created a PR to address this issue.  https://github.com/zalando/postgres-operator/pull/2097

**Comment by yajo** [comment]
Possibly related (or duplicate): #2050

**Comment by FxKu** [comment]
Closing as #2051 got merged
