### ISSUE TITLE
Feature: Release new patch version w/ fixes

### ISSUE THREAD

**Issue by ailox** [zalando/postgres-operator#1351]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**Bare Metal K8s
- **Are you running Postgres Operator in production?** trying to
- **Type of issue?** feature request

When installing the current helm chart *1.6.0* on a fresh cluster, the installation fails with error:
```
CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.configuration.properties.teams_api.properties.teams_api_url): unknown field "defaults"
```

this is due to a typo ( "defaults" → "default") that was fixed in #1305, but the changes are only in `master` and not released.

For now a valid workaround is to point helm to the release artifacts https://github.com/zalando/postgres-operator/archive/2c3cd3ae02fe032d8d1036161318bb5f6c0e7056.tar.gz but a better solution would be to create a new release that could be tracked. Alternatively the current one could be updated.

**Comment by ailox** [comment]
I have the feeling this also causes #1352, which also runs into a problem with an invalid CRD.

**Comment by FxKu** [comment]
Yes it's about time for a new bugfix release. We are planning to do it next week.

**Comment by FxKu** [comment]
The new `v1.6.1` release contains the fix. Just merged the master into the `gh-pages` branch where we publish the helm charts. Closing this issue then. Thanks for raising it.
