### ISSUE TITLE
Operator runasuser/runasgroup configs not working

### ISSUE THREAD

**Issue by tommasopozzetti** [zalando/postgres-operator#1359]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal?** Kubernetes 1.19
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

If the following configs are set in the operator as defaults they seem to be ignored
```
  spilo_runasuser: xxxx
  spilo_runasgroup: xxxx
```
while if they get set in the postgresql resource they work as expected, setting the properties on the postgres pods
```
  spiloRunAsUser: xxxx
  spiloRunAsGroup: xxxx
```

I think the issue is a typo in the annotation of the two configs [here](https://github.com/zalando/postgres-operator/blob/master/pkg/util/config/config.go#L31) and [here](https://github.com/zalando/postgres-operator/blob/master/pkg/util/config/config.go#L32) which should be `name` rather than `json`

**Comment by FxKu** [comment]
@tommasopozzetti that is indeed a typo. Can you change it to `name` and create a PR? Thanks!

**Comment by tommasopozzetti** [comment]
@FxKu I opened #1361 to address the issue

**Comment by cortopy** [comment]
@FxKu would it be possible to reopen this issue? as per comments in the PR, this doesn't seem to be fixed
