### ISSUE TITLE
Unable to backup data into minio

### ISSUE THREAD

**Issue by illyaSlobozhanin** [zalando/postgres-operator#1363]
- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** Test into prod
- **Type of issue?** question

Using operator v. 1.6.0 
manual installation from the manifest directory
 
On postgres pod I've got the only log connected with backup. With no errors
```
/scripts/postgres_backup.sh - producing a new backup
INFO Doing full backup.
INFO Calling pg_start_backup()
INFO Walking ...
INFO Starting part 1 ...
INFO Finished writing part 1.
```

but I don't see any backups in minio bucket

Configuration. (using ConfigMap)

- wal_s3_bucket: "postgres-backup"
- pod_environment_configmap: "postgresql-pod-config"

postgresql-pod-config data

- BACKUP_SCHEDULE: "*/5 * * * *" 
- BACKUP_NUM_TO_RETAIN: "14"
- USE_WALG_BACKUP: "true" 
- AWS_ENDPOINT: "http://minio-service:9000"
- AWS_ACCESS_KEY_ID: "access"
- AWS_SECRET_ACCESS_KEY: "secret"
- WALG_DISABLE_S3_SSE: "true"
- USE_WALG_RESTORE: "false"

But no backups exist in minio bucket.
Only repeated log on postgresql pod 

> INFO: Lock owner: airflow-pg-0; I am airflow-pg-0
> INFO: no action. i am the leader with the lock
> LOG {ticks: 0, maint: 0, retry: 0}

Cluster manifest 

```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: user1-pg
  namespace: ns
  labels:
    team: user1
spec:
  teamId: user1
  numberOfInstances: 1
  enableConnectionPooler: false
  patroni:
    synchronous_mode: true
  postgresql:
    version: "12"
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 1Gi
  users:
    user1: []
  databases:
    user1_db: user1
  volume:
    size: 10Gi
    storageClass: "..."
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: key
            operator: In
            values:
              - value
```

More info. Cluster is installing in another namespace than operator with

- watched_namespace: "*"

If replicas 2, e.g. on replica pod log
```
INFO: bootstrap from leader 'airflow-pg-0' in progress
Can not find any backups
ERROR: Error creating replica using method wal_e: envdir /run/etc/wal-e.d/env bash /scripts/wale_restore.sh exited with code=1
1024+0 records in
1024+0 records out
16777216 bytes (17 MB, 16 MiB) copied, 0.0101076 s, 1.7 GB/s
Lock owner: airflow-pg-0; I am airflow-pg-1
bootstrap from leader 'airflow-pg-0' in progress
NOTICE: base backup done, waiting for required WAL segments to be archived
...
WARNING: still waiting for all required WAL segments to be archived (60 seconds elapsed)
HINT: Check that your archive_command is executing properly. You can safely cancel this backup, but the database backup will not be usable without all the WAL segments.
```

And the same warning with hint repeats every minute.

UPDATE. 
After setting 
`USE_WALG_BACKUP = false`

As I see in https://github.com/zalando/postgres-operator/issues/1190

I see some progress
```
2021-02-12 13:58:39.226 - /scripts/postgres_backup.sh - I was called as: /scripts/postgres_backup.sh /home/postgres/pgdata/pgroot/data
2021-02-12 13:58:39.585 - /scripts/postgres_backup.sh - producing a new backup
wal_e.main INFO MSG: starting WAL-E
DETAIL: The subcommand is "backup-push".
STRUCTURED: time=2021-02-12T13:58:39.725401-00 pid=35
2021-02-12 13:58:40.281 44 LOG Starting pgqd 3.3
2021-02-12 13:58:40.282 44 LOG auto-detecting dbs ...
wal_e.operator.backup INFO MSG: start upload postgres version metadata
DETAIL: Uploading to s3://postgres-backup/spilo/airflow-pg/d038cb19-1a65-4f6a-959d-bbe468cd95e9/wal/12/basebackups_005/base_000000010000000000000004_00000096/extended_version.txt.
STRUCTURED: time=2021-02-12T13:58:41.301967-00 pid=35
wal_e.operator.backup WARNING MSG: blocking on sending WAL segments
DETAIL: The backup was not completed successfully, but we have to wait anyway. See README: TODO about pg_cancel_backup
STRUCTURED: time=2021-02-12T13:58:41.308207-00 pid=35
```

**Comment by sdudoladov** [comment]
Hi @illyaSlobozhanin  :)

Can you please add Spilo, `minio`, and k8s versions ?

**Comment by CyberDem0n** [comment]
BTW, spilo is tested with minio and it works without issues: https://github.com/zalando/spilo/blob/master/postgres-appliance/tests/docker-compose.yml#L7-L37

**Comment by illyaSlobozhanin** [comment]
Thanks all! @sdudoladov @CyberDem0n 
Investigated source of wal-e. It's not working with other s3-compatible storages (or at least minio)  cuz u cannot disable SSE header (hardcoded in wal-e source). 
It works only with wal-g.

But returning to my initial problem need to add 
```
AWS_S3_FORCE_PATH_STYLE: "true"
```

Full working pod-configmap
```
  BACKUP_SCHEDULE: "* */12 * * * *" # Every 12 hours
  BACKUP_NUM_TO_RETAIN: "14" =
  USE_WALG_BACKUP: "true" =
  AWS_ENDPOINT: "http://minio-service:9000"
  AWS_ACCESS_KEY_ID: "key"
  AWS_SECRET_ACCESS_KEY: "access"
  WALG_DISABLE_S3_SSE: "true"
  USE_WALG_RESTORE: "false"
  AWS_S3_FORCE_PATH_STYLE: "true"
```

**Comment by elmariofredo** [comment]
For anyone intrested in this issue it is related to https://github.com/wal-e/wal-e/issues/404  which is fixed in PR, but seems that wal-e is abadoned project and you should use wal-g instead.
