### ISSUE TITLE
1.6.1 Cannot upgrade operator - " unknown field "logical_backup_job_prefix" 

### ISSUE THREAD

**Issue by vitobotta** [zalando/postgres-operator#1370]
- **Which image of the operator are you using?**
registry.opensource.zalan.do/acid/postgres-operator:v1.6.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
Kubernetes
- **Are you running Postgres Operator in production?** [yes | no]
yes
- **Type of issue?** 
Not sure, perhaps bug

Hi, I am testing the upgrade from 1.6.0 to 1.6.1 in a temp cluster and the validation of the chart fails on upgrade with " unknown field "logical_backup_job_prefix" in do.zalan.acid.v1.OperatorConfiguration.configuration.logical_backup".

Is it a known issue?

Thanks

**Comment by FxKu** [comment]
Sort of :smiley: You have to update the existing CRD. See #1346

**Comment by vitobotta** [comment]
Oh sorry I didn't notice there was an issue about the same thing :)

**Comment by vitobotta** [comment]
Hi @FxKu I updated the CRDs before upgrading the chart and the operator was upgraded without any errors. It did restart the pods of the PG cluster, but it didn't change the Spilo image, which remained set to p2 instead of the new p4. Do I have to update it manually? What happens to the PG clusters when the operator is upgraded and the pods get restarted? Thanks!

**Comment by vitobotta** [comment]
I updated the image manually and it seems to be OK. So is this the correct procedure when upgrading the operator?

- update the CRDs with the new versions
- upgrade the operator with the helm chart
- wait for the operator to restart the pg cluster pods
- update the spilo image in the statefulset and wait for the pods to be restarted

Thanks
