### ISSUE TITLE
no able to change wal_keep_segments

### ISSUE THREAD

**Issue by pgvirtuoso** [zalando/postgres-operator#1389]
I am trying to change wal_keep_segments to 20. This is part of the yaml manifest:

![image](https://user-images.githubusercontent.com/67527003/109564838-9bff5700-7aaf-11eb-8ada-8b174ed00d5e.png)

But wal_keep_segments keep at 8, is not changing.

**Comment by FxKu** [comment]
You cannot change it. See: https://github.com/zalando/postgres-operator/issues/968
