### ISSUE TITLE
Configurable CRD creation by operator

### ISSUE THREAD

**Issue by ant31** [zalando/postgres-operator#1393]
- **Which image of the operator are you using?** e.g. 
registry.opensource.zalan.do/acid/postgres-operator:v1.6.1

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Baremetal k8s
- **Are you running Postgres Operator in production?** [yes | no] 
yes
- **Type of issue?** 
feature request.

Currently it's not possible to start the operator without a ClusterRoleBinding because it register itself the `operatorconfigurations.acid.zalan.do` which requires cluster wide permission. 
It also makes it more complex to run multiple operator in different namespaces. 

The CRD has to be registered only  once, when deploying an additional operator instance in a namespace there CRD definition should already exist. 

Currently both the usage AND the creation of the `operatorconfigurations.acid.zalan.do` are both parameterize with the same envvar. 

I propose to separate it in two vars or at least to add one: 
"REGISTER_OPERATORCONFIGURATION:  true"
So it can be turned off
 
Only need to add a condition here (from what I can tell):
https://github.com/zalando/postgres-operator/blob/41858a702ce678ee05351f58d942628f2b0f4426/pkg/controller/controller.go#L310

**Comment by ant31** [comment]
I can make the PR if the change is ok

**Comment by FxKu** [comment]
The operator creates two CRDs: `postgresqls.acid.zalan.do` and `operatorconfigurations.acid.zalan.do`. I think there was a proposal to make this configurable before. We then would need different RBAC depending on what the user chooses (no `create` privilege for CRDs and yes - role binding). For the name, I would vote for something like EnableCRDCreation (registration? installation?) to be aligned with the other flags we have.

Are you aware that you can already run two and more operators next to each other using a [CONTROLLER_ID](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#operators-with-defined-ownership-of-certain-postgres-clusters)? But, I think even then the RBAC is a valid point.

**Comment by ant31** [comment]
Also it's a good practice to give least privileged roles when possible.

I prefer 'registration' 
Yes I am using controller_id but in multiple namespace.

**Comment by ant31** [comment]
fixed in #1733
