### ISSUE TITLE
Cluster rebuild doesn't reflect Patroni state for synchronous_mode

### ISSUE THREAD

**Issue by hudec** [zalando/postgres-operator#1396]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.1 
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question
I have 3 node cluster:
{
  "members": [
    {
      "name": "rob-census-0",
      "role": "leader",
      "state": "running",
      "api_url": "http://10.233.127.108:8008/patroni",
      "host": "10.233.127.108",
      "port": 5432,
      "timeline": 220,
      "pending_restart": true
    },
    {
      "name": "rob-census-1",
      "role": "sync_standby",
      "state": "running",
      "api_url": "http://10.233.79.141:8008/patroni",
      "host": "10.233.79.141",
      "port": 5432,
      "timeline": 220,
      "pending_restart": true,
      "lag": 0
    },
    {
      "name": "rob-census-2",
      "role": "replica",
      "state": "running",
      "api_url": "http://10.233.108.183:8008/patroni",
      "host": "10.233.108.183",
      "port": 5432,
      "timeline": 220,
      "pending_restart": true,
      "lag": 0
    }
  ]
}

In the case of some cluster changes via operator the next workflow is done:
Sync -> syncStatefulSet -> recreatePods with parameters
switchoverCandidates - any pod except master (shouldn't be only pod, which is sync_standby?)
In recreatePods all pods except master are rotated.
At the end the switchover is requested (in fact it's a failover, why?)
Due to pods rotations the pods (Postgres instances) are not fully synchronized.
The response from Patroni is failure

The events generated for the case of max_connections change:
0s          Normal   Killing   pod/rob-census-1   Stopping container postgres
1s          Normal   Update    postgresql/rob-census   Performing rolling update
1s          Normal   Update    postgresql/rob-census   Performing rolling update
0s          Normal   SuccessfulCreate   statefulset/rob-census   create Pod rob-census-1 in StatefulSet rob-census successful
0s          Normal   Scheduled          pod/rob-census-1         Successfully assigned postgres/rob-census-1 to brhlik.i.cz
0s          Normal   Pulled             pod/rob-census-1         Container image "registry.i.cz:5000/spilo-13:2.0-p5-icz" already present on machine
0s          Normal   Created            pod/rob-census-1         Created container postgres
0s          Normal   Started            pod/rob-census-1         Started container postgres
0s          Normal   Killing            pod/rob-census-2         Stopping container postgres
0s          Normal   SuccessfulCreate   statefulset/rob-census   create Pod rob-census-2 in StatefulSet rob-census successful
0s          Normal   Scheduled          pod/rob-census-2         Successfully assigned postgres/rob-census-2 to sojka.i.cz
0s          Normal   Pulled             pod/rob-census-2         Container image "registry.i.cz:5000/spilo-13:2.0-p5-icz" already present on machine
0s          Normal   Created            pod/rob-census-2         Created container postgres
0s          Normal   Started            pod/rob-census-2         Started container postgres
0s          Normal   Switchover         postgresql/rob-census    Switching over from "rob-census-0" to "postgres/rob-census-1"
0s          Normal   Switchover         postgresql/rob-census    Switching over from "rob-census-0" to "postgres/rob-census-2"
0s          Normal   Switchover         postgresql/rob-census    Successfully switched over from "rob-census-0" to "postgres/rob-census-1"
0s          Normal   Switchover         postgresql/rob-census    Successfully switched over from "rob-census-0" to "postgres/rob-census-2"
0s          Normal   Switchover         postgresql/rob-census    Switchover from "rob-census-0" to "postgres/rob-census-2" FAILED: <nil>
0s          Normal   Killing            pod/rob-census-0         Stopping container postgres
0s          Normal   Scheduled          pod/rob-census-0         Successfully assigned postgres/rob-census-0 to straka.i.cz
0s          Normal   SuccessfulCreate   statefulset/rob-census   create Pod rob-census-0 in StatefulSet rob-census successful
0s          Normal   Pulled             pod/rob-census-0         Container image "registry.i.cz:5000/spilo-13:2.0-p5-icz" already present on machine
0s          Normal   Created            pod/rob-census-0         Created container postgres
0s          Normal   Started            pod/rob-census-0         Started container postgres
0s          Normal   Update             postgresql/rob-census    Rolling update done - pods have been recreated

and the final Patroni cluster is
{
  "members": [
    {
      "name": "rob-census-0",
      "role": "replica",
      "state": "running",
      "api_url": "http://10.233.127.88:8008/patroni",
      "host": "10.233.127.88",
      "port": 5432,
      "timeline": 221,
      "pending_restart": true,
      "lag": 0
    },
    {
      "name": "rob-census-1",
      "role": "sync_standby",
      "state": "running",
      "api_url": "http://10.233.79.149:8008/patroni",
      "host": "10.233.79.149",
      "port": 5432,
      "timeline": 221,
      "pending_restart": true,
      "lag": 0
    },
    {
      "name": "rob-census-2",
      "role": "leader",
      "state": "running",
      "api_url": "http://10.233.108.188:8008/patroni",
      "host": "10.233.108.188",
      "port": 5432,
      "timeline": 221,
      "pending_restart": true
    }
  ]
}
Here I can see an opportunity to make a correct switch from former master rob-census-0 to sync_standby 
replica rob-census-1. To make Patroni happy?

**Comment by FxKu** [comment]
Sounds duplicate to #1360
