### ISSUE TITLE
Enabling backups messes up the pods

### ISSUE THREAD

**Issue by gmldba** [zalando/postgres-operator#1410]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** AWS EKS
- **Are you running Postgres Operator in production?** no
- **Type of issue?** When adding wal_s3_buckets to the configmap, one replica pod is rebuilt but patroni never comes back online and the cluster is stucked. I take out the wal_s3_bucket from operator configmap and all comes back to normal. What could it be? All the PostgreSQL logs saya is FATAL ERROR database is starting up. How can I troubleshoot this?

**Comment by FxKu** [comment]
Sounds like [this](https://github.com/zalando/postgres-operator/issues/1279) problem.
