### ISSUE TITLE
Can't connect without port-forwarding

### ISSUE THREAD

**Issue by alexrainman** [zalando/postgres-operator#1418]
I am running the cluster on GKE.

Running this command i can get the services:

```
kubectl get svc -l application=spilo -L spilo-role
```

But, i cannot connect to the load balancer public IP. I can connect to the pods using port-forwarding but, that's not practical as the master pod is being rotated by the operator.

How i can connect without port-forwarding?
How i can stop the master for being rotated?

**Comment by fourstepper** [comment]
Could you point us to the configuration of postgres-operator of yours?

**Comment by alexrainman** [comment]
I am using the default configuration from the manifests folder.

**Comment by alexrainman** [comment]
This is driving me crazy. I cannot find anywhere how to fix this issue.

**Comment by FxKu** [comment]
If it's rotated constantly on each SYNC have a look at #1401

Creating a port-forward should work to connect to the DB. Do you get an error? Have you set PGPASSWORD and PGSSLMODE=require env variable beforehand for the user you choose?

When using LoadBalancer run a describe on the service to find out the actual host url to be used with tools like psql. Plus, it can be that you have to add you IP (range) under allowedSourceRanges in the Postgres manifest.

**Comment by alexrainman** [comment]
Yeah, it was all about adding ip addresses to allowedSourceRanges in CIDR format. Doing that i was able to connect from my laptop but, i still cannot connect from another VM running on GCP.

Any ideas?

**Comment by alexrainman** [comment]
Fixed.
