### ISSUE TITLE
postgres operator UI - custom teams list (with multiple entries) is not working

### ISSUE THREAD

**Issue by zagr0** [zalando/postgres-operator#1439]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?
registry.opensource.zalan.do/acid/postgres-operator:v1.6.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
AWS K8s
- **Are you running Postgres Operator in production?**
yes
- **Type of issue?**
Bug report

When I try to use more than one entry in the teams list I get error when deploy UI with helm
```
$ helm upgrade postgres-operator-ui postgres-operator-ui/postgres-operator-ui --install --version 1.6.2 --namespace postgres-operator -f values-test.yaml

Error: UPGRADE FAILED: cannot patch "postgres-operator-ui" with kind Deployment: Deployment.apps "postgres-operator-ui" is invalid: spec.template.labels: Invalid value: "dev,stage,uat,test": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

values-test.yml:
```
envs:
  teams:
  - "dev"
  - "stage"
  - "uat"
  - "test"
```
related to [#1375](https://github.com/zalando/postgres-operator/pull/1375) and [#1373](https://github.com/zalando/postgres-operator/issues/1373)

**Comment by FxKu** [comment]
@zagr0 thanks for raising. I wonder why we even need the team in labels. Will remove and update the chart.
