### ISSUE TITLE
cluster-init-script

### ISSUE THREAD

**Issue by dekelmidlink** [zalando/postgres-operator#1454]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.2

registry.opensource.zalan.do/acid/postgres-operator:v1.6.2

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]

AWS K8s

- **Are you running Postgres Operator in production?** [yes | no]

no

- **Type of issue?** [Bug report, question, feature request, etc.]

question, feature request?

Thanks for any help from advanced! 
My team wants to move from bitnami postgres helm chart to zlanado postgres operator. I am having trouble to setup init script which was very easy to implement with Bitnami Helm Chart https://github.com/bitnami/charts/tree/master/bitnami/postgresql#initialize-a-fresh-instance 

I am having hard time to implement it on the operator. I tried to search for a way to add init script to the Spilo container but I didn't got to anywhere. 

How would you implement init sciprt for your clusters?

**Comment by FxKu** [comment]
https://github.com/zalando/postgres-operator/issues/775#issuecomment-572514922

**Comment by dekelmidlink** [comment]
> #775 (comment)

I need it on different clusters. Do you have an example for init script implementation?
