### ISSUE TITLE
How to specify connection pooler custom settings ?

### ISSUE THREAD

**Issue by mbarecki** [zalando/postgres-operator#1465]
Which image of the operator are you using? registry.opensource.zalan.do/acid/postgres-operator:v1.6.2
    Where do you run it - cloud or metal? Kubernetes or OpenShift? Bare Metal K8s
    Are you running Postgres Operator in production? yes
    Type of issue? question 

Hello,

Let me start with saying that postgres-operator is great and working really nice!

We have a database deployment with a connection pooler where we need to specify the `client_idle_timeout` setting. Since it can not be set in the manifest we are using a custom pgbouncer image.

This works but requires to keep our custom image in sync with postgres-operator releases so having possibility to specify it in database manifest would simplify deployment.

I would like to ask what would be recommended approach for adding such settings to connection pooler ?

Is there a plan maybe to add support for `parameters` in `connectionPooler` section as it is already present for `postgresql` ?

**Comment by FxKu** [comment]
Actually, you are doing it right by using a customized image. The operators job should only be to spin up the pooler deployment. Ok, there are some options to choose the schema, user and connections and so on, but it was designed that you could easily change the docker image using another connection pooler. We will not add pooler specific settings to the operator. Thus you don't have to fear to always sync your image with the current development. We can plan to put the pooler image in the OS repo - like with the logical backup - to make it transparent how the default pooler image is configured.

**Comment by mbarecki** [comment]
Hello @FxKu, thank you for reply and information.

This case is solved.
