### ISSUE TITLE
Logical Backup scheduling failed due to long name

### ISSUE THREAD

**Issue by DanArlowski** [zalando/postgres-operator#1470]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
 registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
 AWS EKS
- **Are you running Postgres Operator in production?** [yes | no]
yes
- **Type of issue?**
bug report

When giving a too long name, the logical backup jobs fails to schedule - 
```
time="2021-04-25T06:41:31Z" level=error msg="could not sync cluster: could not sync the logical backup job: could not create missing logical backup job: could not create k8s cron job: CronJob.batch \"logical-backup-an-unexepctionally-long-name-db-cluster\" is invalid: metadata.name: Invalid value: \"logical-backup-an-unexepctionally-long-name-db-cluster\": must be no more than 52 characters" cluster-name=ns/an-unexepctionally-long-namedb-cluster pkg=controller worker=0
time="2021-04-25T06:41:31Z" level=info msg="Event(v1.ObjectReference{Kind:\"postgresql\", Namespace:\"ns\", Name:\"an-unexepctionally-long-name-cluster\", UID:\"**REDACTED**\", APIVersion:\"acid.zalan.do/v1\", ResourceVersion:\"16106123\", FieldPath:\"\"}): type: 'Warning' reason: 'Sync' could not sync cluster: could not sync the logical backup job: could not create missing logical backup job: could not create k8s cron job: CronJob.batch \"logical-backup-an-unexepctionally-long-name-db-cluster\" is invalid: metadata.name: Invalid value: \"logical-backup-an-unexepctionally-long-name-db-cluster\": must be no more than 52 characters"
```

**suggested fix**
apply a check and trim name to 52 chars.

**suggested workaround**
give your resource short names (resources should be less then 37 chars long in order for all to go smoothly)

**Comment by FxKu** [comment]
The `logical-backup-` prefix for the job is [configurable](https://github.com/zalando/postgres-operator/pull/1287) since `v1.6.1`. And with that version the name will also be [truncated](https://github.com/zalando/postgres-operator/pull/1208) if it's still too long. So consider upgrading your operator to the latest version.
