### ISSUE TITLE
[helm chart] wrong data types in postgres-operator/values.yaml

### ISSUE THREAD

**Issue by flypenguin** [zalando/postgres-operator#1481]
- **Which image:** N/A
- **Where do you run it:** aks, azure
- **Production?** no (not yet maybe ;)
- **Type of issue?** bug report
- **PR Available!!** (#1480)

## description

the data types in values.yaml are "wrong". if you just perform an "helm install" then the installation fails with a LOT of error messages about wrong data types.

for example configGeneral.enable_crd_validation is '"true"' (i.e. a string value) in the values.yaml file, but should be just 'true' (a yaml boolean value).

weirdly, #configPostgresPodResources.default_cpu_limit is expected to be string although a numerical value (wrong as well?), just like configConnectionPooler.connection_pooler_default_cpu_limit.

this commit fixes it. AFTER applying you can just do this:

    helm upgrade -i pg-operator zalando/pg-operator

TESTED WITH 1.6.2.

see also:

    https://git.io/J3z4S

**Comment by FxKu** [comment]
We've now merged (#1224) the two `values.yaml` files. So there should be no more such errors regardless if you choose OperatorConfigurarion CRD or ConfigMap as your config target.
