### ISSUE TITLE
Sync/Recreate Infrastructure Roles on operator startup

### ISSUE THREAD

**Issue by Jan-M** [zalando/postgres-operator#149]
It would be very helpful for the most basic rotation or in case of mistakes in infrastructure role secret if we would create all roles again on startup. This should include altering existing infrastructure roles and changing their password.

- [ ] on startup change password of existing infrastructure roles to what is currently in the secret.

**Comment by Jan-M** [comment]
As we now found out the problem is actually that the once created secrets for the infrastructure roles still contain a password. So theses need to be updated along the way. @alexeyklyukin

**Comment by CyberDem0n** [comment]
:+1:
