### ISSUE TITLE
How to remove infrastructure, PAM and admin role

### ISSUE THREAD

**Issue by xzizka** [zalando/postgres-operator#1530]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes 
- **Type of issue?** question

I am trying to deploy the most basic deployment with postgres-operator. When you deploy "plain" PostgreSQL, the only role deployed there is _postgres_.

```
postgres=# \du+
                                     List of roles
 Role name  |                         Attributes                         | Member of | Description 
------------+------------------------------------------------------------+-----------+-------------
 postgres   | Superuser, Create role, Create DB, Replication             | {}        | 
```
I deployed postgres-operator using HELM 3 with the following values.yaml file
[https://pastebin.com/rnzbbipN](https://pastebin.com/rnzbbipN)

and with the following cluster manifest
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: postgres
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  postgresql:
    version: "13"
```
This gave me the following:
```
postgres=# \du+
                                           List of roles
 Role name  |                         Attributes                         | Member of | Description 
------------+------------------------------------------------------------+-----------+-------------
 admin      | Create DB, Cannot login                                    | {}        | 
 postgres   | Superuser, Create role, Create DB, Replication, Bypass RLS | {}        | 
 robot_zmon | Cannot login                                               | {}        | 
 standby    | Replication                                                | {}        | 
 zalandos   | Create DB, Cannot login                                    | {}        | 

```
What I want to achieve is to remove the _robot_zmon_ , _zalandos_ and _admin_ role.

I tried to comment everythin in the postgres-operator _configTeamsApi_ section, comment _infrastructure_roles_secret_name_ , _infrastructure_roles_secrets_ and _pam_role_name_. It has no effect on it.

I found, that even if I comment parameters related to _zalandos_ and _admin_ role, there defaults in the CRD, that place there the default value.
https://github.com/zalando/postgres-operator/blob/53fb540c3577c2d7c273e2b4fed23e6c874eadfe/charts/postgres-operator/crds/operatorconfigurations.yaml#L460
https://github.com/zalando/postgres-operator/blob/53fb540c3577c2d7c273e2b4fed23e6c874eadfe/charts/postgres-operator/crds/operatorconfigurations.yaml#L476

I also found, that these roles are part of the spilo image.
https://github.com/zalando/spilo/commit/33e73910af5ac0db41b02e664d4d292198aedb42
So I am not sure, if it is not required for cluster run...

Is it possible to remove the roles I mentioned without revriting of e.g. CDR definition? Can it cause any issues?
Does exists any configuration option in postgres-operator, that will prevent creation of these roes

Thank you for your help
Ondrej

**Comment by FxKu** [comment]
These roles come from Spilo. You can safely delete `robot_zmon` and `zalandos`. `admin` is actually a useful role for human user to do administrative tasks. If you don't want to have these roles at all, I'm afraid you have to create your own custom Spilo image.
