### ISSUE TITLE
Not able to pull registry.opensource.zalan.do/acid/postgres-operator:v1.6.3

### ISSUE THREAD

**Issue by BaskiGIT** [zalando/postgres-operator#1541]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [gke]
- **Are you running Postgres Operator in production?** [no]
- **Type of issue?** [Bug report]

Some general remarks when posting a bug report:
- Please, check the operator, pod (Patroni) and postgresql logs first. When copy-pasting many log lines please do it in a separate GitHub gist together with your Postgres CRD and configuration manifest.
- If you feel this issue might be more related to the [Spilo](https://github.com/zalando/spilo/issues) docker image or [Patroni](https://github.com/zalando/patroni/issues), consider opening issues in the respective repos.

**Comment by FxKu** [comment]
Likely just temporarily not available. Does it still not work for you?

**Comment by BaskiGIT** [comment]
Hi yes it was because of a network issue - we can close this
