### ISSUE TITLE
How to upgrade operator itself?

### ISSUE THREAD

**Issue by Nizarius** [zalando/postgres-operator#1542]
Hi! I can't find in docs the way to upgrade the operator. Without that, I can't update cluster's postgresql version. 

What is the most appropriate way for upgrading the postgres operator?

**Comment by fabionitto** [comment]
I'm using version 1.5.0 on production, and I also need to upgrade the operator to version 1.6.3, and you appreciate some docs about it..

**Comment by christiancorbin** [comment]
Agreed. I'm sure I can figure it out using the helm chart, but it would be nice to have a documented procedure to make sure any caveats are covered?

**Comment by d3hof** [comment]
+1

**Comment by FxKu** [comment]
Added a small paragraph in the admin docs: https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#upgrading-the-operator
