### ISSUE TITLE
Cannot clone cluster from physical backup.

### ISSUE THREAD

**Issue by imcitius** [zalando/postgres-operator#1546]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Scaleway hosted K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

Hello
I’m trying to use physical backup/restore with postgres operator.
I’ve created postgres-pod configmap with this env config:
```    BACKUP_NUM_TO_RETAIN = "7"
    BACKUP_SCHEDULE      = "*/15 * * * *"
    AWS_REGION            = local.backup.region
    AWS_ENDPOINT          = local.backup.endpoint
    AWS_ACCESS_KEY_ID     = data.vault_generic_secret.s3.data["s3_key_id"]
    AWS_SECRET_ACCESS_KEY = data.vault_generic_secret.s3.data["s3_secret_key"]
    WAL_S3_BUCKET         = local.backup.bucket
    WALE_BACKUP_THRESHOLD_PERCENTAGE = "100"
    USE_WALG_BACKUP = "true"
    USE_WALG_RESTORE = "true"
    CLONE_AWS_ENDPOINT            = local.backup.endpoint
    CLONE_AWS_REGION              = local.backup.region
    CLONE_AWS_ACCESS_KEY_ID       = data.vault_generic_secret.s3.data["s3_key_id"]
    CLONE_AWS_SECRET_ACCESS_KEY   = data.vault_generic_secret.s3.data["s3_secret_key"]
    CLONE_USE_WALG = "true"
```
Values is correctly filled by terraform on deploy.

With this configuration Spilo creates backups in `<bucket>/spilo/<namespace>-<cluster-name>/wal/…` path, but cloning from this backup does not work as expected, because it tries to find `<bucket>/spilo/<cluster-name>/wal/…` path which is not accessible, as `<namespace>` prefix is lost.

I've tried to add `CLONE_WAL_BUCKET_SCOPE_PREFIX` variable into configmap, but it does not help, resulting statefulset always has empty value of this variable.
May the problem be here?
https://github.com/zalando/postgres-operator/blob/ebb3204cdd7002742499c85b1df15b43a68f005b/pkg/cluster/k8sres.go#L1833
It seems that empty value is always injected.

**Comment by FxKu** [comment]
I think, it could be a similar issue then in #1279. Specify WAL bucket and AWS region via the respective config options.

**Comment by imcitius** [comment]
WAL bucket and AWS region was specified, it didnt helped.

I managed it to work setting WAL_BUCKET_SCOPE_PREFIX to empty value, to force backup path created without prefix.

I ended up with this config, which allows backup and clone like a charm:

```
    BACKUP_NUM_TO_RETAIN = "7"
    BACKUP_SCHEDULE      = "0 0 * * *"
    USE_WALG_BACKUP      = "true"

    AWS_REGION                       = local.backup.region
    AWS_ENDPOINT                     = local.backup.endpoint
    AWS_ACCESS_KEY_ID                = data.vault_generic_secret.s3.data["s3_key_id"]
    AWS_SECRET_ACCESS_KEY            = data.vault_generic_secret.s3.data["s3_secret_key"]
    WAL_BUCKET_SCOPE_PREFIX          = ""
    WAL_S3_BUCKET                    = local.backup.bucket
    WALE_BACKUP_THRESHOLD_PERCENTAGE = "100"

    CLONE_METHOD                  = "CLONE_WITH_WALG"
    CLONE_WAL_S3_BUCKET           = local.backup.bucket
    CLONE_USE_WALG_RESTORE        = "true"
    CLONE_AWS_ENDPOINT            = local.backup.endpoint
    CLONE_AWS_REGION              = local.backup.region
    CLONE_AWS_ACCESS_KEY_ID       = data.vault_generic_secret.s3.data["s3_key_id"]
    CLONE_AWS_SECRET_ACCESS_KEY   = data.vault_generic_secret.s3.data["s3_secret_key"]
    CLONE_WAL_BUCKET_SCOPE_PREFIX = var.project

```

**Comment by apeschel** [comment]
I ran into this same issue and dig some digging. I encountered 2 separate issues, which I have filed issues for:

* https://github.com/zalando/postgres-operator/issues/1553
* https://github.com/zalando/postgres-operator/issues/1552

It looks like the clone is supposed to happen by copying the `/run/etc/wal-e.d/env` from the original cluster to `/run/etc/wal-e.d/env-clone-<cluster>` on the new cluster, and then running `envdir /run/etc/wal-e.d/env-clone-<cluster>` to load the environment variables needed to restore the backups from the old cluster.

However, in practice is seems like the "copying" isn't really working at all. I'm not sure how physical backup restores are working for anyone on 1.6.3 at the moment -- it appears non-functional as is.

To confirm, take a compare `/run/etc/wal-e.d/env-clone-<cluster>` on the new cluster to `/run/etc/wal-e.d/env` on the original cluster, and see if the env vars match.

**Comment by apeschel** [comment]
@FxKu Can we get some attention on these issues, please? As far as I can tell, backup restoration does not work with the postgres-operator at the moment. Restoring from a backup requires fairly low level manual intervention to succeed.

I'm definitely willing to help contribute the fixes here, but the spilo logic is pretty complex and I'm having trouble getting through it with no guidance.

**Comment by imcitius** [comment]
@FxKu 
Please also check #1561 which has is nearly same problem, prevents deploy of standby cluster because another ENVs problem.

**Comment by FxKu** [comment]
I tried to cover your case better in our docs. Thanks for raising and give feedback. Helps to improve the Operator for our community :+1:

**Comment by franklouwers** [comment]
Did anyone ever get this working with a non-empty prefix?
