### ISSUE TITLE
How to allocate hugepages resource in postgres-operator

### ISSUE THREAD

**Issue by sskurapati** [zalando/postgres-operator#1549]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** k8s on centos 7
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

We are running all our services on centos 7 using docker-compose, now we are planning to use kubernetes.
I am running our pods on k8s on centos 7, and some of our pods require hugepages, so we enabled hugepages on the machine.

We are trying to use the Postgres operator for data-store deployment on Kubernetes. I am not able to allowcate hugepages resources in the operator.

While creating my own Postgres pod I can pass hugepages in resources like
```
resources:
      limits:
        cpu: 100m
        memory: 100Mi
        hugepages-2Mi: "300Mi"
      requests:
        cpu: 100m
        memory: 50Mi
        hugepages-2Mi: "300Mi"
```
 
**How can I achieve it with Postgres-operator?**

I am facing the following issue while creating Postgres cluster with operator:
```
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... Bus error (core dumped)
child process exited with exit code 135
initdb: removing data directory "/home/postgres/pgdata/pgroot/data"
pg_ctl: database system initialization failed
2021-07-05 13:02:27,414 INFO: removing initialize key after failed attempt to bootstrap the cluster
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 33, in <module>
    sys.exit(load_entry_point('patroni==2.0.2', 'console_scripts', 'patroni')())
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1457, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1351, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1247, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1240, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
/run/service/patroni: finished with code=1 signal=0
```

**Comment by sskurapati** [comment]
After applying this patch on statefulset, Postgres container is creating successfully.
kubectl patch statefulset data-store --type='json' -p='[
{   
    "op": "replace", 
    "path": "/spec/template/spec/containers/0/resources/requests/hugepages-2Mi", "value":"50Mi"
},
{
    "op": "replace", 
    "path": "/spec/template/spec/containers/0/resources/limits/hugepages-2Mi", "value":"50Mi"
}]'
From this what I understand is, if we pass hugepages as a resource while creating a pod it’s working, and I don’t see an option in Postgres-operator to set it.

please correct me if I am wrong.

**Comment by sskurapati** [comment]
Even on kubernetes document, it is mentioned as we have to request a resource for hugepages.
https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/

Is there any plan to support the feature to set hugepages resource limit from a manifest file?

**Comment by sskurapati** [comment]
@alexeyklyukin @FxKu @RafiaSabih @mkabilov @Jan-M 
Can someone please reply?

**Comment by marcellodesales** [comment]
@sskurapati any status on this?

**Comment by silenium-dev** [comment]
I guess the simplest way to do this, is passing through the `hugepages-2Mi` and `hugepages-1Gi` resource requests and limits from the `postgres` resource to the stateful set. I will look into it and maybe submit a pull request. This was also the suggestion from #1788
