### ISSUE TITLE
pg_hba.conf behaviour changed after updating spilo image

### ISSUE THREAD

**Issue by mseiwald** [zalando/postgres-operator#1555]
Hi,

I'm using a snippet like this in my postgres cluster manifest to allow non-ssl connections to the DB:

```  patroni:
    pg_hba:
    # allow non-ssl connections
    - host all all all md5
```

Previously  (with spilo image `registry.opensource.zalan.do/acid/spilo-12:1.6-p3`) my configuration was prepended to the default pg_hba.conf. After updating spilo (to `registry.opensource.zalan.do/acid/spilo-13:2.0-p7`) the config is completely replaced instead prepended.

Is this new behavious intended? Is there a way to get the old behaviour back or do I have to always supply the complete pg_hba.conf in every cluster manifest?

Kind regards,
Michael

Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** K8s 1.18 on Vmware
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report / clarification

**Comment by CyberDem0n** [comment]
In pg_hba.conf every line and especially the order of lines matter.
Before this change spilo was simply appending lines you provide to the already predefined list. It doesn't allow to correctly describe all hba configuration people want and therefore we changed the behavior from append to override.

**Comment by Arun-Trichy** [comment]
Hi Team,

In the latest versions, is there any other way to append to pg_hba.conf. As, it becomes tedious to override the entire configuration through the postgresql CRD.

```
patroni:
    pg_hba:
      - host all all all md5
      - local   all             all                                   trust
      - hostssl all             +zalandos    127.0.0.1/32       pam
      - host    all             all                127.0.0.1/32       md5
      - hostssl all             +zalandos    ::1/128            pam
      - host    all             all                ::1/128            md5
      - local   replication     standby                    trust
      - hostssl replication     standby all                md5
      - hostnossl all           all                all                reject
      - hostssl all             +zalandos    all                pam
      - hostssl all             all                all                md5
```

**Comment by StaNov** [comment]
@CyberDem0n Is there some wiki page with breaking changes of the major versions?

It would be great to have something like that to follow when upgrading, instead of trial & error approach.
