### ISSUE TITLE
nodeSelector and anti-affinity for connection pooler pods

### ISSUE THREAD

**Issue by thapabishwa** [zalando/postgres-operator#1563]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** AWS K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** question

How can I set nodeSelector and anti-affinity for connection pooler pods?

**Comment by FxKu** [comment]
duplicate to #1441
