### ISSUE TITLE
Feature request: ability to set pod_environment_secret and pod_environment_configmap on cluster resource

### ISSUE THREAD

**Issue by vladimirfx** [zalando/postgres-operator#1566]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** AWS K8s / Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** feature request

We need configuration flexibility for backup and logging configuration on a cluster basis. Use cases:
- per cluster backup conf (WAL_S3_BUCKET)
- per cluster logging conf (LOG_SHIP_SCHEDULE)
- per cluster vars for custom images

Similar requests:
https://github.com/zalando/postgres-operator/issues/907
https://github.com/zalando/postgres-operator/issues/1209
https://github.com/zalando/postgres-operator/issues/1422

And more in comments on other issues.

It is a relatively small change with a big impact on operator usability.

**Comment by cortopy** [comment]
another reason to go for this: configmap and secret are namespaced to the cluster. When automating deployments with helm, the secrets and configmap already exist if there is another cluster in the same namespace

If adding configuration to the `postgresql` CRD is not possible, then could we at least have a template for the name like

```yaml
pod_environment_configmap: "{cluster}-pod-environment-variables"
```
