### ISSUE TITLE
Offer more options for database in the manifest

### ISSUE THREAD

**Issue by a1exsh** [zalando/postgres-operator#158]
More than current `#databases: name->owner`, which is also confusing if you look at it alone:
https://github.com/zalando-incubator/postgres-operator/blob/master/manifests/minimal-postgres-manifest.yaml#L19

An object with properties `[owner, encoding, template, tablespace, ...]` should be supported.  Potentially, the full list from the `CREATE TABLE` statement: https://www.postgresql.org/docs/current/static/sql-createdatabase.html

**Comment by FxKu** [comment]
#843 goes in this direction, but operator should not become another migration tool. Will close for now.
