### ISSUE TITLE
preparedDatabases is not documented in Cluster manifest reference

### ISSUE THREAD

**Issue by ruckc** [zalando/postgres-operator#1580]
When looking at how to have databases initialized with specific extensions, I found references to [preparedDatabases](https://postgres-operator.readthedocs.io/en/latest/user/#from-databases-to-prepareddatabases) in the User section, but there is no schema definition in the [Cluster manifest](https://postgres-operator.readthedocs.io/en/latest/reference/cluster_manifest/#top-level-parameters) section of documentation.

**Comment by FxKu** [comment]
oh! Thanks for finding this small inconsistency. Will add in the next days.
