### ISSUE TITLE
Some notes: from a non-automatic recovery case, "interrupted while in recovery"

### ISSUE THREAD

**Issue by Samusername** [zalando/postgres-operator#1590]
Hi!

Only some notes, 
from a non-automatic recovery case, it seems:

August 6th, in logs:

rdbms-pg-cluster-1 pod-name:rdbms-pg-cluster-1 log:2021-08-06 00:00:00 UTC [14670]: [1-1] 610c7b80.394e 0 LOG: database system **was interrupted while in recovery** at log time **2021-07-09** 13:04:45 

HINT: If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.

It was not fixed at that time (in July). 
August 6th:

DETAIL: Latest checkpoint is at 0/2E000028 on timeline 34, but in the history of the requested timeline, the server forked off from that timeline at 0/2E000000.
FATAL: requested timeline 38 is not a child of this server's history 

Some logs:
[fatal_pg_pod_05.txt](https://github.com/zalando/postgres-operator/files/7029905/fatal_pg_pod_05.txt)

patronictl shows one db node (of three), in following state:
rdbms-pg-cluster-1	172.30.98.173	Replica	start failed	unknown
Or: starting

```| Member             | Host           | Role         | State    | TL | Lag in MB |
+--------------------+----------------+--------------+----------+----+-----------+
| rdbms-pg-cluster-0 | xxx.xx.181.149 | Leader       | running  | 41 |           |
| rdbms-pg-cluster-1 | xxx.xx.98.133  | Replica      | starting |    |   unknown |
| rdbms-pg-cluster-2 | xxx.xx.109.194 | Sync Standby | running  | 41 |         0 |
+--------------------+----------------+--------------+----------+----+-----------+
```

It was possible to recreate the broken db node / pod manually.

Q: Own script to try recover automatically? Other thoughts?

spilo-13:2.0-p4, Patroni 2.0.1
PostgreSQL 13.2
postgres-operator: v1.6.0

==================================
==================================

An other, different, case, 
only to mention, a pod may have been restarted again near the end, etc.:

```
pg_rewind exit code=1
...
WARNING:  terminating connection because of crash of another server process
...
pg_basebackup: error: could not initiate base backup: SSL SYSCALL error: EOF detected
pg_basebackup: removing data directory "/home/postgres/pgdata/pgroot/data"
...
1024+0 records in
1024+0 records out
16777216 bytes (17 MB, 16 MiB) copied, 0.0304379 s, 551 MB/s
...
pg_receivewal: not renaming "00000002000000040000001A.partial", segment is not complete
pg_receivewal: error: unexpected termination of replication stream: FATAL:  terminating connection due to administrator command
...
pg_receivewal: error: could not connect to server: Connection timed out   # This gets repeated then. A pod may have been restarted at some point also.
...
```
Output is from one of replica pods.

```
| Member             | Host           | Role    | State            | TL | Lag in MB |
+--------------------+----------------+---------+------------------+----+-----------+
| rdbms-pg-cluster-0 | xxx.xx.136.88  | Replica | creating replica |    |   unknown |
| rdbms-pg-cluster-1 | xxx.xx.171.103 | Replica | stopped          |    |   unknown |
| rdbms-pg-cluster-2 | xxx.xx.58.110  | Leader  | running          |  4 |           |
```

It was possible to recreate the broken db nodes manually.

**Comment by CyberDem0n** [comment]
>  FATAL: requested timeline 38 is not a child of this server's history

Pod restart should fix it. Honestly, it is not happening that often in order to invest too much time into it.

No matter what, there should be the proper monitoring in place that is supposed to detect replicas that are not streaming or lagging behind for too long.

> a pod may have been restarted again near the end, etc.:

It depends on which pod was restarted. If restarts are happening here and there, maybe this is not a proper environment for stateful workloads?

**Comment by Samusername** [comment]
Thank you for a comment!
PriorityClass has been in use for a short time. QoS is being set. (But that may be all, let's see.)

We also increase amount of resources for DB cluster now. 
( Those were small for these tests. )

Our aim is to try to keep the DB cluster healthy automatically in as many cases as possible. ( Like all do. )

**Comment by Samusername** [comment]
If stability problems will be noticed, I will create an other new ticket. I am closing this ticket now.
