### ISSUE TITLE
'/run/etc/wal-e.d/env': No such file or directory

### ISSUE THREAD

**Issue by mrszop** [zalando/postgres-operator#1604]
Hey folks,

- **Which image of the operator are you using?**
  - `registry.opensource.zalan.do/acid/postgres-operator:v1.6.3`

```shell
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS         CHART                           APP VERSION
postgres-operator       postgresql-operator     1               2021-09-01 02:12:30.762368 +0200 CEST   deployed       postgres-operator-1.6.3         1.6.3      
postgres-operator-ui    postgresql-operator     1               2021-09-01 02:21:44.929833 +0200 CEST   deployed       postgres-operator-ui-1.6.3      1.6.3   
```

- **Where do you run it**?
  - cloud Provider on Kubernetes
- **Are you running Postgres Operator in production?**
  - no, just first steps and testing purposes
- **Type of issue?**
  - question

I'm trying to trigger a manual backup as described [here](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#wal-archiving-and-physical-basebackups) with following command:

```shell
envdir "/run/etc/wal-e.d/env" /scripts/postgres_backup.sh "/home/postgres/pgdata/pgroot/data"
```

Unfortunately I'm getting:

```shell
chpst: fatal: unable to switch to directory: /run/etc/wal-e.d/env: file does not exist
```

which is actually true, no `/run/etc/wal-e.d/env` in here. Where is this file? My goal is to trigger a backup to s3.

Cheers

**Comment by kskalski** [comment]
It's not clear from documentation if that command should be run from a database pod or the operator pod, or maybe none of them, since neither contains a ``/run/etc/`` directory.

**Comment by FxKu** [comment]
from within the db pod (Spilo). Directory should be there. Check Spilo repo maybe.
