### ISSUE TITLE
Should be "added", not "overwritten" in pg_hba.conf

### ISSUE THREAD

**Issue by y-sira** [zalando/postgres-operator#1625]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.7.0`
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** GCP
- **Are you running Postgres Operator in production?** no
- **Type of issue?** feature request

Here is the default `pg_hba.conf`:

```shell-session
$ kubectl exec cluster-0 -- /bin/cat pgdata/pgroot/data/pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
local   all             all                                   trust
hostssl all             +zalandos    127.0.0.1/32       pam
host    all             all                127.0.0.1/32       md5
hostssl all             +zalandos    ::1/128            pam
host    all             all                ::1/128            md5
local   replication     standby                    trust
hostssl replication     standby all                md5
hostnossl all           all                all                reject
hostssl all             +zalandos    all                pam
hostssl all             all                all                md5
```

This manifest:

```diff
   postgresql:
     version: "13"
   patroni:
+    pg_hba:
+      - host      all          all       10.4.0.0/16    trust
```

introduces:

```
$ kubectl exec cluster-0 -- /bin/cat pgdata/pgroot/data/pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
host      all          all       10.4.0.0/16    trust
```

and then the cluster will be crashed soon due to missing replication lines.

I think the operator should add the custom line into the `pg_hba.conf`, not overwrite that file.

Anyway, thank you for your great operator!

**Comment by CyberDem0n** [comment]
I MUST be overwritten: https://github.com/zalando/postgres-operator/issues/1555#issuecomment-883058797
