### ISSUE TITLE
The chart directories contain .tgz files of past chart versions

### ISSUE THREAD

**Issue by stearz** [zalando/postgres-operator#1637]
The chart directories contain .tgz files of past chart versions:

![image](https://user-images.githubusercontent.com/22387558/136411776-97d0288d-af76-491d-bea0-7444d66bc276.png)
https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator

![image](https://user-images.githubusercontent.com/22387558/136411966-c22f3925-c170-4d97-b468-b771b470d14c.png)
https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator-ui

I don't think that this is intended as it will break in the future because helm wants to store the whole chart as a configmap that then will exceed 1 MB.

**Comment by FxKu** [comment]
Good to know. Let's follow up in #1671
