### ISSUE TITLE
PodDisruptionBudget blocks master disruption

### ISSUE THREAD

**Issue by ckotzbauer** [zalando/postgres-operator#1663]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal Kubernetes
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

Hi,
I came accross this situation yesterday while preparing a Kubernetes-Cluster-Update. We have this operator deployed, which runs a three-pod-postgres-cluster. When I'm correct there should be always only one master-postgres-pod which holds the `spilo-role: master` label.
The operator creates always a PodDisruptionBudget (even when this is disabled via helm-chart). When it is enabled, the `minAvailable` setting is set to `1`. From outside perspective this seems fine, but the PDBs-selector settings are using the `spilo-role: master` label where always only one pod is running, so no disruptions are allowed at all. From my point of view, there's no problem to drain the master-pod as one of the replicas will immediately take over, so the PDB should not include the `spilo-role: master` role.

Is this assumption correct or did I miss something? 😄 
Thanks!

**Comment by FxKu** [comment]
If you want to rotate nodes you can use the node_readiness_label the operator is watching. If it's removed a failover to one of the replicas will happen.

**Comment by ckotzbauer** [comment]
> If you want to rotate nodes you can use the `node_readiness_label` the operator is watching. If it's removed a failover to one of the replicas will happen.

But this does not solve the problem I described above. I don't want to remove labels from pods, I want to drain a node without getting errors, cause of a wrong configured pdb...

**Comment by ckotzbauer** [comment]
@FxKu I could do a PR to remove the `spilo-role: master` label from the PDB. Would that be okay?

**Comment by Jan-M** [comment]
@ckotzbauer If you use the node readiness label as Felix suggest, then the postgres operator should terminate the master pod and migration works.

Please do not remove the master label from the pdb. What we can look at making this in general configurable. for this you can propose a PR. E.g. no pdb for single pod clusters.

**Comment by ckotzbauer** [comment]
@Jan-M But the `kubectl drain` cannot handle the node-readiness label. From the `kubectl` perspective the pdb can't be "resolved" with its current labels.

**Comment by Kuzbekov** [comment]
In our case such configuration of pod disruption budget does not allows to downscale k8s cluster automatically as it blocks drain of the nodes where postgres master pods are scheduled. 
Currently the only way to allow autoscaler work as expected is disabling PDB in operator's config, but disabling PDB completely  could lead to unlikely situation when both replica and master pod would be unavailable. Therefore I suggest to make labels selector in PDB configurable and keep currents behavior in defaults.

**Comment by ibotty** [comment]
FYI: Rook is detecting drains and is updating PDBs using the following strategy.
 https://github.com/rook/rook/blob/master/design/ceph/ceph-managed-disruptionbudgets.md
Note that they solve a different problem with different tradeoffs.

Regarding PostgreSQL clusters, I can think of the following strategy.

 * Create a PDB with max unavailability of 1 for the `spilo-role: master` labeled pod,
 * run a canary pod on the same node as the `spilo-role: master` labeled pod,
 * when that pod gets evicted and the node is unscheduable, assume that the node is to be drained (*), and
 * (try to) failover to a replica.
 
 That would afaict detect the (client-side) node drain.  Am I missing something?

**Comment by thcdrt** [comment]
Hello,

I'm having the same issue as @ckotzbauer, when I want to upgrade my Kubernetes cluster for example, my cloud provider will drain nodes one by one, but it fails because of pod disruption budget.

I don't understand why there is the label selector "spilo-role: master" on the PDB. When the master is being terminated, the switchover is done automatically to the replica. 

Thomas

**Comment by baznikin** [comment]
I wanted to implement `node_readiness_label` on my clusters, but during testing I found out my managed k8s provider (DigitalOcean) doesn't set any labels for Ready nodes. Instead it set `annotation` for nodes, which are drained:

```
metadata:
  annotations:
    k8s.digitalocean.com/drain-start-time: "2023-01-13T12:22:07Z"
```

So, there is few possible use cases:

1. label added for Ready node, removed when node is going to recycle
1. label removed for Ready node, added when node is going to recycle
1. annotation added for Ready node, removed when node is going to recycle
1. annotation removed for Ready node, added when node is going to recycle

Only 1st case covered by `node_readiness_label` feature. It should be addressed somehow.

Simplest solution is watch for node `spec.unschedulable==true` or when taint `effect: NoSchedule; key: node.kubernetes.io/unschedulable` appeared. It have drawback - is engineer `kubectl cordon` node for some purpose master will be rotated.

**Comment by wzrdtales** [comment]
The PDB is essentially broken as of now.

The logic also makes no sense. If there is a ready to failover replica, why the PDB would be watching for a healthy master. It should look for a healthy failover ready replica.

**Comment by b1zzu** [comment]
Same problem here, we use AKS and when an update is triggered AKS doesn't provide any labels to determinate if the nodes are ready or not, and therefore the update gets stuck all the time.

**Comment by volodya953** [comment]
+1

**Comment by stromvirvel** [comment]
So this issue has been completed a month ago. What's the solution to the problem?
