### ISSUE TITLE
Add aggregate roles to Helm chart

### ISSUE THREAD

**Issue by Wikiwix** [zalando/postgres-operator#1668]
The available [aggregate roles](https://github.com/zalando/postgres-operator/blob/master/manifests/user-facing-clusterroles.yaml) should be available (at least as an option in the Helm chart.

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.7.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** K8s
- **Are you running Postgres Operator in production?** not yet
- **Type of issue?** feature request

I would be open to create a PR, but wanted to check on openness and whether the resources would be managed twice in the repo then?

**Comment by FxKu** [comment]
Please provide a PR yes. I mean most of the stuff in helm charts we already have to manage twice ...

**Comment by Wikiwix** [comment]
In case that PR went unnoticed: I provided a PR which is waiting for review :)
