### ISSUE TITLE
Remove helm2 support from helm chart

### ISSUE THREAD

**Issue by OlleLarsson** [zalando/postgres-operator#1677]
- **Which image of the operator are you using?** 
  - registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
  - k8s
- **Are you running Postgres Operator in production?**
  - No
- **Type of issue?**
  - Feature request :) ?

Helm2 has been deprecated for a long time now and I was surprised to see that it seems like the helm chart still supports helm2 as I got the following messages when installing the operator
```
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
```

I would say that it is time to remove helm2 support.

- Remove [crds.yaml template](https://github.com/zalando/postgres-operator/blob/v1.7.1/charts/postgres-operator/templates/crds.yaml)
- Remove [helm values](https://github.com/zalando/postgres-operator/blob/v1.7.1/charts/postgres-operator/values.yaml#L365-L368)
- Remove deprecated [helm hook annotation](https://github.com/zalando/postgres-operator/blob/v1.7.1/charts/postgres-operator/crds/operatorconfigurations.yaml#L7-L8) from crds

**Comment by FxKu** [comment]
Was it already that long ago? Felt like yesterday when these hooks had to be introduced :smile: 
Makes sense to me to remove them. Hope nobody starts crying then.

**Comment by OlleLarsson** [comment]
Okay maybe I exaggerated a little bit 😄 
https://helm.sh/blog/helm-v2-deprecation-timeline/
