### ISSUE TITLE
Ssl settings for connection pooler

### ISSUE THREAD

**Issue by sleepdan** [zalando/postgres-operator#1718]
- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?**  no
- **Type of issue?**  question

I use to connect to postgresql connection pooler (in my postgres cluster manifest set:
...
spec:
enableConnectionPooler: true). 
I want clients to connect using ssl certificates. How can I specify settings for tls for pgBouncer?

**Comment by FxKu** [comment]
duplicate to #1230
