### ISSUE TITLE
Major version upgrade, failed, when using: shared_preload_libraries: "pgaudit"

### ISSUE THREAD

**Issue by Samusername** [zalando/postgres-operator#1723]
3 DB pods DB cluster: Leader - sync - async.
From PG 13.4 to PG 14.0.
Latest postgres-operator and spilo image from [v1.7.1](https://github.com/zalando/postgres-operator/releases/tag/v1.7.1).

Without shared_preload_libraries: "pgaudit", all work ok:
Major version upgrade works ok in synchronous mode (Leader - sync - async) and in asynchronous mode (Leader - async - async ). It was tested.

Following problem may belong to some other forum, but I will mark following here also, in case someone has hints from where to look for help, or other ideas.

Major version upgrade problem:
We get following problem permanently, if we set following in use in manifest yaml:

```
  postgresql:
    parameters:
      shared_preload_libraries: "pgaudit"
```

inplace_upgrade.py gets executed:

time="2021-12-14T13:10:30Z" level=info msg="healthy cluster ready to upgrade, current: 130004 desired: 140000" cluster-name=rdbms-pg/acid-upgrade-test pkg=cluster worker=1
time="2021-12-14T13:10:30Z" level=info msg="Num 1000. triggering major version upgrade on pod acid-upgrade-test-1 of 3 pods" cluster-name=rdbms-pg/acid-upgrade-test pkg=cluster worker=1
time="2021-12-14T13:10:30Z" level=info msg="Num 1001. upgradeCommand: %!(EXTRA string=/usr/bin/python3 /scripts/inplace_upgrade.py 3 2>&1 | tee last_upgrade.log)" cluster-name=rdbms-pg/acid-upgrade-test pkg=cluster worker=1
time="2021-12-14T13:10:32Z" level=info msg="upgrade action triggered and command completed: 2021-12-14 13:10:31,248 inplace_upgrade INFO: No PostgreSQL configuration items changed, nothing to . Num 10." cluster-name=rdbms-pg/acid-upgrade-test pkg=cluster worker=1
time="2021-12-14T13:10:32Z" level=info msg="cluster has been synced" cluster-name=rdbms-pg/acid-upgrade-test pkg=controller worker=1

But version of Postgres does not get upgraded from 13.4 to 14.0 now, when shared_preload_libraries: "pgaudit" is in use.

Output of manual execution of inplace_upgrade.py:

<details>
  <summary>inplace_upgrade.py (Click to expand!)</summary>

postgres@acid-upgrade-test-1:~$ /usr/bin/python3 /scripts/inplace_upgrade.py 3
2021-12-14 13:14:13,884 inplace_upgrade INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-12-14 13:14:13,947 inplace_upgrade WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
2021-12-14 13:14:13,949 inplace_upgrade INFO: establishing a new patroni connection to the postgres cluster
2021-12-14 13:14:14,007 inplace_upgrade INFO: Cluster acid-upgrade-test is ready to be upgraded
2021-12-14 13:14:14,012 inplace_upgrade INFO: initdb config: [{'locale': 'en_US.utf-8'}, {'encoding': 'UTF8'}]
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /home/postgres/pgdata/pgroot/data_new ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/14/bin/pg_ctl -D /home/postgres/pgdata/pgroot/data_new -l logfile start

2021-12-14 13:14:14,841 inplace_upgrade INFO: Dropping extensions from the cluster which could be incompatible
2021-12-14 13:14:14,845 inplace_upgrade INFO: Executing "DROP EXTENSION IF EXISTS amcheck_next" in the database="postgres"
2021-12-14 13:14:14,849 inplace_upgrade INFO: Executing "DROP EXTENSION IF EXISTS amcheck_next" in the database="template1"
2021-12-14 13:14:14,850 inplace_upgrade INFO: Executing pg_upgrade --check
Performing Consistency Checks on Old Live Server
------------------------------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for user-defined encoding conversions              ok
Checking for user-defined postfix operators                 ok

*failure*
Consult the last few lines of "pg_upgrade_server.log" for
the probable cause of the failure.

connection to server on socket "/home/postgres/pgdata/pgroot/data_upgrade/.s.PGSQL.50432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?

could not connect to target postmaster started with the command:
"/usr/lib/postgresql/14/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/home/postgres/pgdata/pgroot/data_new" -o "-p 50432 -b -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c vacuum_defer_cleanup_age=0 -c timescaledb.restoring='on' -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/home/postgres/pgdata/pgroot/data_upgrade'" start
Failure, exiting
2021-12-14 13:14:15,335 inplace_upgrade ERROR: pg_upgrade --check failed, more details in the /home/postgres/pgdata/pgroot/data_upgrade
postgres@acid-upgrade-test-1:~$ exit
command terminated with exit code 1

</details>

<details>
  <summary>pg_upgrade_server.log (Click to expand!)</summary>

postgres@acid-upgrade-test-1:~/pgdata/pgroot/data_upgrade$ less pg_upgrade_server.log

-----------------------------------------------------------------
  pg_upgrade run on Tue Dec 14 13:21:50 2021
-----------------------------------------------------------------

command: "/usr/lib/postgresql/13/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/home/postgres/pgdata/pgroot/data" -o "-p 50432 -c autovacuum=off -c autovacuum_freeze_max_age=2000000000  -c listen_addresses='' -c unix_socket_permissions=0700" start >> "pg_upgrade_server.log" 2>&1
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2021-12-14 13:21:50 UTC [1004]: [1-1] 61b89a6e.3ec 0     FATAL:  lock file "postmaster.pid" already exists
2021-12-14 13:21:50 UTC [1004]: [2-1] 61b89a6e.3ec 0     HINT:  Is another postmaster (PID 66) running in data directory "/home/postgres/pgdata/pgroot/data"?
 stopped waiting
pg_ctl: could not start server
Examine the log output.

command: "/usr/lib/postgresql/14/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/home/postgres/pgdata/pgroot/data_new" -o "-p 50432 -b -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c vacuum_defer_cleanup_age=0 -c timescaledb.restoring='on' -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/home/postgres/pgdata/pgroot/data_upgrade'" start >> "pg_upgrade_server.log" 2>&1
waiting for server to start....2021-12-14 13:21:50 UTC [1032]: [1-1] 61b89a6e.408 0     LOG:  pgaudit extension initialized
2021-12-14 13:21:50 UTC [1032]: [2-1] 61b89a6e.408 0     LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
2021-12-14 13:21:50 UTC [1032]: [3-1] 61b89a6e.408 0     LOG:  pg_stat_kcache.linux_hz is set to 1000000
2021-12-14 13:21:50 UTC [1032]: [4-1] 61b89a6e.408 0     FATAL:  unrecognized configuration parameter "pg_stat_statements.max"
2021-12-14 13:21:50 UTC [1032]: [5-1] 61b89a6e.408 0     HINT:  make sure pg_stat_statements is loaded,
        and make sure pg_stat_kcache is present after pg_stat_statements in the shared_preload_libraries setting
2021-12-14 13:21:50 UTC [1032]: [6-1] 61b89a6e.408 0     LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.

</details>

-->
**FATAL**:  unrecognized configuration parameter "pg_stat_statements.max"
HINT:  make sure pg_stat_statements is loaded,
     and make sure pg_stat_kcache is present after pg_stat_statements in the shared_preload_libraries setting

I have taken needed parts from following fix in use in our postgres-operator compilation:
https://github.com/zalando/postgres-operator/pull/1715

I have tested with couple of manifest yamls, with the same problem as a result.
One of the manifest yamls:

<details>
  <summary>manifest yaml example (Click to expand!)</summary>
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-upgrade-test
  namespace: rdbms-pg
spec:
  teamId: "acid"
  dockerImage: "registry.opensource.zalan.do/acid/spilo-14:2.1-p3"

  patroni:
    synchronous_mode: true
    synchronous_mode_strict: true

  volume:
    size: 1Gi
  securityContext:
     runAsNonRoot: true
     runAsUser: 101
  numberOfInstances: 3
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  #databases:
  #  foo: zalando  # dbname: owner
  #preparedDatabases:
  #  bar: {}
  postgresql:
    version: "13"
    parameters:
      shared_preload_libraries: "pgaudit"
</details>

Q: How to solve / fix this? Where?

**Comment by CyberDem0n** [comment]
Well, the error is very specific to your configuration.
The major upgrade procedure can't be generalized to 100% of cases and it is very easy to break it by providing incompatible configuration or by creating certain objects in the database.

pg_upgrade gives you hints about what is wrong, you have to follow it's advises, i.e. add pg_stat_statements and pg_stat_kcache back (there could be something more) to shared_preload_libraries.

**Comment by Samusername** [comment]
Ok. I will try those. (We are searching from documentations.)

**Comment by Samusername** [comment]
Yes, certainly.

We have not touched: pg_stat_statements nor pg_stat_kcache.
We only added: shared_preload_libraries: "pgaudit"

But we will try to test with different combinations, also with pg_stat_kcache.

**Comment by Samusername** [comment]
Oh, ok. Then it may cause some problems. That is good to know!

I think addition of the mentioned entries below, helped:
```
  postgresql:
    version: "13" # and "14"
    parameters:
      shared_preload_libraries: "pgaudit,pg_stat_statements,pg_stat_kcache"
```

Well, that was simple and quick, at least this far.
Thank you!
