### ISSUE TITLE
Add secretAnnotations to postgresql cluster manifest

### ISSUE THREAD

**Issue by soosap** [zalando/postgres-operator#1736]
Currently only `serviceAnnotations` and `podAnnotations` are supported in the **postgresql** cluster manifest. Annotations are used for many things. I am using helm to manage my Kubernetes workloads. I also maintain a custom postgres helm chart tailored to my company needs.

Creating a postgres cluster works like a charm. The problem arises when I delete a cluster. It also wipes out all the associated secrets. One way to protect from `helm uninstall` wiping out the secrets is by providing the following annotation to all created secrets: `"helm.sh/resource-policy": keep`.

Unfortunately, as of today there is no `secretAnnotations` supported. I would like to request that feature as it greatly improves the integration of these crds into a helm-managed Kubernetes cluster.

**Comment by FxKu** [comment]
What's the reason for keeping secrets of a deleted Postgres cluster? For restoring purposes? In that case, the operator would create new secrets and update the passwords in the DB. Maybeeee, there can be a flag if secrets should be removed or not - I'm uncertain about yet another annotations option.

**Comment by soosap** [comment]
Hi Felix, I was actually fighting another problem https://github.com/zalando/postgres-operator/issues/1739 to get point in time recovery to work. I assumed that wiping out secrets and recreating them has some effect on backups being found by the restore script.

Thanks for clarifying the behaviour of secret management via the operator. Since the operator creates new secrets and updates them in the db accordingly, I do no longer have a need to keep my secrets around after deleting a cluster. Thus, being able to set annotations specifically to secrets is no longer necessary.

**Comment by dmotte** [comment]
@FxKu @excavador FYI I'm working on a fix for this, because #2579 doesn't make much sense if secrets are deleted. I will submit my PR shortly

**Comment by embik** [comment]
While this issue took a different turn due to the specific use case, is the original purpose (adding annotations to secrets) fulfilled? It stills seems to be an open issue, maybe it could be reopened? In my case, I would like for secrets to be synced to a different namespace with e.g. https://github.com/emberstack/kubernetes-reflector, but I don't see a way to add annotations to generated credentials secrets (apart from doing it manually).
