### ISSUE TITLE
When using ConfigMaps operator stiil need permission to create endpoints

### ISSUE THREAD

**Issue by evsasha** [zalando/postgres-operator#1740]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 'registry.opensource.zalan.do/acid/postgres-operator:v1.7.1'
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** OpenShift 4.6
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

When using ConfigMaps, the operator still needs permission to create endpoints.

The workaround is to manually add "create" permission to "endpoints" after installing the operator.

I saw a previous issue with the same problem https://github.com/zalando/postgres-operator/issues/1606 but didn't see any feedback from the issue's author.

Error in operator pod
```
time="2022-01-12T15:27:42Z" level=error msg="could not create cluster: could not create master endpoint: could not create master endpoint: endpoints is forbidden: User \"system:serviceaccount:postgres-operator:postgres-operator\" cannot create resource \"endpoints\" in API group \"\" in the namespace \"evg-test-2\"" cluster-name=evg-test-2/acid-test pkg=controller worker=6
```

My postres-operator config
```
apiVersion: acid.zalan.do/v1
configuration:
  ...
  kubernetes_use_configmaps: true
  ...
```

**Comment by evsasha** [comment]
UPD. We need a complete list of endpoint permissions on Openshift.
Because no matter where the operator is launched (h8s or OpenShift), it needs the rights to create and delete endpoints.
https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/cluster.go#L261-L275
```
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
 ```

**Comment by evsasha** [comment]
UPD. My issue same with  #1758 #1759

**Comment by FxKu** [comment]
@evsasha You've already linked the right code that has to be changed. When `kubernetes_use_configmaps` is set to true it should create ConfigMaps instead of Endpoints. Can you provide a PR and test with OpenShift? Because we use K8s.

**Comment by evsasha** [comment]
@FxKu hi, i checked the solution from #1759 on openshift 4.6. Its work correctly.
I am already using this solution in my Openshift cluster.
