### ISSUE TITLE
Major version upgrade from 13.4 to 14 fails at required library presence check (timescaledb)

### ISSUE THREAD

**Issue by shrumm** [zalando/postgres-operator#1752]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Azure Kubernetes Service (AKS) K8s v1.22
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** question / maybe bug

I run a 2 member Postgres cluster - 1 master and 1 replica. I've set `major_version_upgrade_mode` to `off` in the operator settings. I followed the instructions to do a major version upgrade, summarised below:
- I changed the postgresql version in the cluster spec from "13" to "14"
- Went into the master pod - `kubectl exec -it ...`
- Ran `python3 /scripts/inplace_upgrade.py 2`

It fails at the pg_upgrade check.
```text
Performing Consistency Checks on Old Live Server
------------------------------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for user-defined encoding conversions              ok
Checking for user-defined postfix operators                 ok
Checking for presence of required libraries                 fatal
Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    loadable_libraries.txt
```

Looking at `loadable_libraries.txt`
```text
could not load library "$libdir/timescaledb": FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: /home/postgres/pgdata/pgroot/data_new/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
	# Modify postgresql.conf:
	shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
	echo "shared_preload_libraries = 'timescaledb'" >> /home/postgres/pgdata/pgroot/data_new/postgresql.conf

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with:
	SET timescaledb.allow_install_without_preload = 'on';
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
In database: <...>
could not load library "$libdir/pg_stat_kcache": no connection to the server
In database: <...>
In database: <...>
In database: postgres
In database: <...>
In database: <...>
In database: template1
could not load library "$libdir/timescaledb-2.5.0": no connection to the server
In database: <...>
could not load library "$libdir/pg_stat_statements": no connection to the server
In database: <...>
In database: <...>
In database: postgres
In database: <...>
In database: <...>
In database: template1
```

I compared the contents of my current pg 13.4 postgresql.conf with the one in `data_new` directory and for some reason it does not contain timescaledb and pg_stat_statements in shared_preload_libraries.

```shell
postgres@acid-postgres-0:~/pgdata/pgroot$ diff data/postgresql.conf data_new/postgresql.conf
55c55
< shared_preload_libraries = 'bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache'
---
> shared_preload_libraries = 'pg_stat_statements,pgextwlist,pg_auth_mon,set_user,pg_cron,pg_stat_kcache'
70,79d69
<
< # recovery.conf
< primary_conninfo = 'user=standby passfile=/run/postgresql/pgpass host=10.244.31.114 port=5432 sslmode=prefer application_name=acid-postgres-0 gssencmode=prefer channel_binding=prefer'
< primary_slot_name = 'acid_postgres_0'
< recovery_target = ''
< recovery_target_lsn = ''
< recovery_target_name = ''
< recovery_target_time = ''
< recovery_target_timeline = 'latest'
< recovery_target_xid = ''
```

Is this expected or am I doing something wrong?

I even tried manually editing the data_new/postgresql.conf file to add timescaledb and re-running the python script - no luck.

**Comment by FxKu** [comment]
Which spilo version are you using? The latest release version `spilo-14:2.1-p3` ? Could be that previous versions do not support for this kind of upgrade?

**Comment by shrumm** [comment]
@FxKu I'm on the latest spilo - `spilo-14:2.1-p3`
```shell
kubectl describe pod acid-postgres-0 -n staging | grep Image
    Image:          registry.opensource.zalan.do/acid/spilo-14:2.1-p3
```

**Comment by shrumm** [comment]
Thank you @CyberDem0n - it works now!

for folks landing here with Google, you need to update your cluster manifest and add/update the spec as follows:

```yaml
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-cdp-14:2.1-p210
```

one more question @CyberDem0n - the reason I'm even looking at this is that my production db had some issues after a postmaster restart. Even though PGVERSION is set correctly as 13, sometimes spilo attempts to launch PG 14. It then fails saying the data folder is from an older postgres and the pod stays stuck in the 'starting...' phase when I run `patronictl list`.

Forcing a 'reinit' of the member fixes the issue but it happened twice now so I figured the best guarantee is to just upgrade to PG14. Do you know if this issue is also fixed in the new spilo image?

**Comment by Thorsten-Totemic** [comment]
@CyberDem0n I am trying to run the image `registry.opensource.zalan.do/acid/spilo-cdp-14:2.1-p210` as you suggested but it gives me lots of issues regarding timescaldb library not found. Could you help me understand what is the difference between official spilo image `registry.opensource.zalan.do/acid/spilo-14:2.1-p3` and the `cdp` image `registry.opensource.zalan.do/acid/spilo-cdp-14:2.1-p210`?

**Comment by CyberDem0n** [comment]
@Thorsten-Totemic which postgres versions are you upgrading from and to?
The Timescale version must exist for old and new Postgres versions, or upgrade won't work. For example it's not possible to upgrade from 9.6 directly to 13 or 14 because there is no common Timescale version between them.

**Comment by Thorsten-Totemic** [comment]
@CyberDem0n I am also upgrading from 13 to 14 and I ran into the same as @shrumm above. But when I used the `cdp` image as recommended it couldn't find the Timescale library. I was already on `registry.opensource.zalan.do/acid/spilo-14:2.1-p3` before I attempted to upgrade.

**Comment by CyberDem0n** [comment]
@Thorsten-Totemic please show at least some logs, the sentence `it couldn't find the Timescale library` doesn't describe the problem well enough.

**Comment by Thorsten-Totemic** [comment]
Our environment is now running back on `registry.opensource.zalan.do/acid/spilo-14:2.1-p3` without issues, so I am hesitant to reproduce the error with the other image and potentially cause further issues. Could you just help me understand the differences between our image and `cdp` image?
