### ISSUE TITLE
CrashLoopBackOff on Postgres-Operator rollout

### ISSUE THREAD

**Issue by Leke-Ariyo** [zalando/postgres-operator#1756]
- Which image of the operator are you using? 
- registry.opensource.zalan.do/acid/postgres-operator:v1.7.1 

- Where do you run it - cloud or metal? Kubernetes or OpenShift? [AWS K8s | GCP ... | Bare Metal K8s] - 
- I am not running it on cloud and it is on Kubernetes

- Are you running Postgres Operator in production? [yes | no]
- No

- Type of issue? [Bug report, question, feature request, etc.]
- Question: I just deployed postgres-operator but rollout of postgres-operator returns CrashLoopBackOff, 
The logs returns:

```
{"level":"info","msg":"Spilo operator v1.7.1\n","time":"2022-01-26T11:12:23Z"}
{"level":"error","msg":"could not create customResourceDefinition \"operatorconfigurations.acid.zalan.do\": Post \"https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions\": dial tcp 10.96.0.1:443: i/o timeout","pkg":"controller","time":"2022-01-26T11:12:53Z"}
{"level":"fatal","msg":"could not register Operator Configuration CustomResourceDefinition: Get \"https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/operatorconfigurations.acid.zalan.do\": dial tcp 10.96.0.1:443: i/o timeout","pkg":"controller","time":"2022-01-26T11:13:27Z"}

```
I currently use latest Chart version v1.7.1 and my kubernetes version is 1.22

**Comment by FxKu** [comment]
Maybe you can create the chart with `-v 9` option to get an idea where it fails. Looks like an RBAC issue.

**Comment by Leke-Ariyo** [comment]
Had networkpolicy yamls in the ```Templates/``` repo that was then disable with helm IF conditions and then, pod was running fine after re-sync-ing
