### ISSUE TITLE
CRDs categories is hardcoded to ["all"]

### ISSUE THREAD

**Issue by kichay** [zalando/postgres-operator#1779]
Hello.
It is not always convenient to have `*.acid.zalan.do` custom resources defined in `all` category. Can you specify your own custom category like `zalando` instead `all` or use (configurable with `values.yaml`) tempting here?

- https://github.com/zalando/postgres-operator/blob/v1.7.1/charts/postgres-operator/crds/operatorconfigurations.yaml#L19
- https://github.com/zalando/postgres-operator/blob/v1.7.1/charts/postgres-operator/crds/postgresqls.yaml#L19
- https://github.com/zalando/postgres-operator/blob/v1.7.1/charts/postgres-operator/crds/postgresteams.yaml#L19
- deploy with helm3
- I am running Postgres Operator in production (yes)
- feature request

**Comment by FxKu** [comment]
@kichay I made categories configurable now (new `crd_categories` option). Maybe we want to experiment with templating it for the chart and create a PR.

**Comment by kichay** [comment]
It's a good idea to make configurable categories in CRDs in chart too I think.

**Comment by FxKu** [comment]
@kichay sure, maybe you want to try it in a PR? :smiley:

**Comment by kichay** [comment]
https://github.com/zalando/postgres-operator/blob/v1.8.1/charts/postgres-operator/values.yaml#L26
