### ISSUE TITLE
Timescale license cannot be updated

### ISSUE THREAD

**Issue by StaNov** [zalando/postgres-operator#1795]
I want to use materialized views in timescale, therefore I need to update the timescale license from `apache` to `timescale`.

I tried this command:

    ALTER SYSTEM SET timescaledb.license = 'timescale';
    ERROR:  could not access file "$libdir/timescaledb-tsl-2.5.1": No such file or directory

The file is indeed not there:

    $ ls /usr/lib/postgresql/14/lib/timescaledb*
    /usr/lib/postgresql/14/lib/timescaledb-2.5.1.so
    /usr/lib/postgresql/14/lib/timescaledb.so

Is there some workaround for it?

I would suggest to add the license as an option to the cluster definition file.

Thank you for your work!

---

Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.7.1`
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Google cloud, kubernetes
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report / question
- **Postgres version** 14
- **Spilo version** `registry.opensource.zalan.do/acid/spilo-cdp-14:2.1-p210`

**Comment by CyberDem0n** [comment]
> Is there some workaround for it?

Build the Spilo image on your own with `--build-arg TIMESCALEDB_APACHE_ONLY=false`.

We will not distribute Spilo with the proprietary licensed library.
