### ISSUE TITLE
HPA integration to Zalando's CRD

### ISSUE THREAD

**Issue by AnisTigrini** [zalando/postgres-operator#1813]
Hi everyone, hope you are well.
I worked on integrating the horizontalPodAutoscaler feature in Zalando's CRD definition. 
That way, you can create a CRD that contains an HPA that will control the how to scale-up or down Zalando's StatefulSet.
Based on issue https://github.com/zalando/postgres-operator/issues/1790 and from what I was able to see, when you scale down, PVC are still remaining which can cause problems when StatefulSets are scaled back up. 
This was coded based on a previous version of the repository.
Here is the link for the repository : https://github.com/AnisTigrini/Zalando-Operator-HPA

**Comment by AnisTigrini** [comment]
Hi there, hope you are well, just doing a little follow up here.
Thanks,

**Comment by FxKu** [comment]
I will close this issue since #1790 is already there with more discussion. And there's also you PR #1820 (thanks btw) to follow up.
