### ISSUE TITLE
Failover instead of switchover during postgres-cluster update ?

### ISSUE THREAD

**Issue by aegaeonit** [zalando/postgres-operator#1815]
Operator version: v1.7.1

When updating a cluster (e.g. a new spilo image), I've noticed in the logs that the operator demotes the leader by performing a failover:

```
time="2022-03-17T09:54:02Z" level=debug msg="switching over from \"postgres-cluster-2\" to \"common/postgres-cluster-0\"" cluster-name=common/postgres-cluster pkg=cluster
time="2022-03-17T09:54:02Z" level=debug msg="making POST http request: http://10.2.0.15:8008/failover" cluster-name=common/postgres-cluster pkg=cluster
```

I'm wondering if this could not cause data loss in case the replicas are not synced with the leader when this occur ? Would it not be safer to use a switchover instead ?

**Comment by CyberDem0n** [comment]
Internally there is no difference between /failover and /switchover endpoints in Patroni.
