### ISSUE TITLE
Unable to create stanby cluster from "standby_host"

### ISSUE THREAD

**Issue by Subetov** [zalando/postgres-operator#1856]
- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [Bare Metal K8s]
- **Are you running Postgres Operator in production?** [no, planing to use]
- **Type of issue?** [Bug report]

Unable to create stanby cluster using **"standby_host"**.
I've used an [example](https://github.com/zalando/postgres-operator/blob/master/manifests/standby-manifest.yaml).
But getting such errors:
```
error: error validating "../pg-cluster-dc2.yml": error validating data: [ValidationError(postgresql.spec.standby): unknown field "standby_host" in do.zalan.acid.v1.postgresql.spec.standby, ValidationError(postgresql.spec.standby): missing required field "s3_wal_path" in do.zalan.acid.v1.postgresql.spec.standby]; if you choose to ignore these errors, turn validation off with --validate=false
The postgresql "postgres-standby" is invalid: spec.standby.s3_wal_path: Required value
```

**Comment by FxKu** [comment]
You must update your [CRD](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#upgrading-the-operator). And you want to use a feature that's only available with the next release. So either wait for that (this week) or use the `latest` operator image.

**Comment by Subetov** [comment]
@FxKu thank you very much for your reply.
My oversight, I looked at the documentation from the master branch.
I'll upgrade CRDs / operaor from master.
Thanks again.
Sorry to bother you.
