### ISSUE TITLE
ErrImagePull with 1.8.0 Operator 

### ISSUE THREAD

**Issue by knusperkrone** [zalando/postgres-operator#1860]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.8.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** kind
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

The 1.8.0 operator is not pullable
Same behaviour on minikube, kind and with local docker

```bash
$ docker pull registry.opensource.zalan.do/acid/postgres-operator-ui:v1.7.1
#... works
$ docker pull registry.opensource.zalan.do/acid/postgres-operator:v1.8.0                                                                                                                               
Error response from daemon: manifest for registry.opensource.zalan.do/acid/postgres-operator:v1.8.0 not found: manifest unknown: manifest unknown
```

**Comment by f3l1x98** [comment]
@knusperkrone I think you meant to say:
```
$ docker pull registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
#... works
$ docker pull registry.opensource.zalan.do/acid/postgres-operator:v1.8.0                                                                                                                               
Error response from daemon: manifest for registry.opensource.zalan.do/acid/postgres-operator:v1.8.0 not found: manifest unknown: manifest unknown
```
because I found the same issue.

**Comment by FxKu** [comment]
Patience. The build pipeline is failing due to flaky e2e tests. It should be available later this day.

**Comment by FxKu** [comment]
Should be there now. Also published helm charts via `gh-pages` branch.
