### ISSUE TITLE
Pods stuck in terminating status when performing rolling update after changing spilo docker image

### ISSUE THREAD

**Issue by yevon** [zalando/postgres-operator#1865]
I'm having issues when I build new versions of the spilo image and I try to deploy them to the cluster. It properly detects the change, but when it tries to perform the rolling update, it gets stuck into the Terminating state forever until I perform manually a "kubectl delete pod". I just have 2 nodes. Is there a way to specify the number of unavailable nodes (instead of %) when performing rolling updates?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.8.0
- Spilo image: registry.opensource.zalan.do/acid/spilo-14:2.1-p4
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
- Kubernetes bare metal k3s 1.23.6
- **Are you running Postgres Operator in production?** [yes | no]
- no
- **Type of issue?** [Bug report, question, feature request, etc.]
- Bug report / question

![image](https://user-images.githubusercontent.com/121157/164948039-64cb6455-e097-47c7-9ea2-490153082fb4.png)

![image](https://user-images.githubusercontent.com/121157/164948292-94af8e1d-e351-4bfd-bec8-b99f7ef5827d.png)

Operator logs:

`time="2022-04-23T21:53:24Z" level=debug msg="subscribing to pod \"education-postgres-db/acid-education-0\"" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:03:24Z" level=debug msg="unsubscribing from pod \"education-postgres-db/acid-education-0\" events" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:03:24Z" level=error msg="could not sync statefulsets: could not recreate pods: could not recreate replica pod \"education-postgres-db/acid-education-0\": pod deletion wait timeout" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:03:24Z" level=debug msg="syncing roles" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:03:24Z" level=debug msg="closing database connection" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:03:24Z" level=debug msg="syncing pooler is not required" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:03:24Z" level=info msg="cluster has been updated" cluster-name=education-postgres-db/acid-education pkg=controller worker=0
time="2022-04-23T22:08:09Z" level=info msg="SYNC event has been queued" cluster-name=education-postgres-db/acid-education pkg=controller worker=0
time="2022-04-23T22:08:09Z" level=info msg="there are 1 clusters running" pkg=controller
time="2022-04-23T22:08:09Z" level=info msg="syncing of the cluster started" cluster-name=education-postgres-db/acid-education pkg=controller worker=0
time="2022-04-23T22:08:09Z" level=debug msg="team API is disabled" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:09Z" level=debug msg="team API is disabled" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:09Z" level=info msg="syncing secrets" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:09Z" level=debug msg="secret education-postgres-db/education.acid-education.credentials.postgresql.acid.zalan.do already exists, fetching its password" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:09Z" level=debug msg="secret education-postgres-db/pooler.acid-education.credentials.postgresql.acid.zalan.do already exists, fetching its password" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:09Z" level=debug msg="secret education-postgres-db/postgres.acid-education.credentials.postgresql.acid.zalan.do already exists, fetching its password" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:09Z" level=debug msg="secret education-postgres-db/standby.acid-education.credentials.postgresql.acid.zalan.do already exists, fetching its password" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:09Z" level=debug msg="syncing master service" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:09Z" level=debug msg="final load balancer source ranges as seen in a service spec (not necessarily applied): [\"192.168.0.0/16\" \"10.0.0.0/8\" \"172.16.0.0/12\"]" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:09Z" level=debug msg="syncing replica service" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:10Z" level=debug msg="final load balancer source ranges as seen in a service spec (not necessarily applied): [\"192.168.0.0/16\" \"10.0.0.0/8\" \"172.16.0.0/12\"]" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:10Z" level=debug msg="syncing volumes using \"pvc\" storage resize mode" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:10Z" level=info msg="volume claims do not require changes" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:10Z" level=debug msg="syncing statefulsets" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:10Z" level=debug msg="found rolling update flag on pod \"acid-education-0\"" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:10Z" level=debug msg="found rolling update flag on pod \"acid-education-1\"" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:10Z" level=debug msg="2 / 2 pod(s) still need to be rotated" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:10Z" level=debug msg="making GET http request: http://10.42.0.86:8008/config" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:13Z" level=warning msg="could not get Postgres config from pod education-postgres-db/acid-education-0: could not make request: Get \"http://10.42.0.86:8008/config\": dial tcp 10.42.0.86:8008: connect: no route to host" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:13Z" level=debug msg="making GET http request: http://10.42.0.70:8008/config" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:25Z" level=debug msg="making GET http request: http://10.42.0.86:8008/patroni" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:28Z" level=debug msg="could not get member data of  pod education-postgres-db/acid-education-0 - skipping possible restart attempt: could not make request: Get \"http://10.42.0.86:8008/patroni\": dial tcp 10.42.0.86:8008: connect: no route to host" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:28Z" level=debug msg="making GET http request: http://10.42.0.70:8008/patroni" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:28Z" level=debug msg="performing rolling update" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:28Z" level=info msg="there are 2 pods in the cluster to recreate" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:28Z" level=debug msg="name=acid-education-0 phase=Running ip=10.42.0.86" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:28Z" level=debug msg="name=acid-education-1 phase=Running ip=10.42.0.70" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:28Z" level=debug msg="making GET http request: http://10.42.0.86:8008/patroni" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:31Z" level=error msg="failed to get Patroni state for pod: could not make request: Get \"http://10.42.0.86:8008/patroni\": dial tcp 10.42.0.86:8008: connect: no route to host" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:31Z" level=warning msg="error while syncing cluster state: could not sync statefulsets: could not recreate pods: postpone pod recreation until next Sync: recreation is unsafe because pods are being initialized" cluster-name=education-postgres-db/acid-education pkg=cluster
time="2022-04-23T22:08:31Z" level=error msg="could not sync cluster: could not sync statefulsets: could not recreate pods: postpone pod recreation until next Sync: recreation is unsafe because pods are being initialized" cluster-name=education-postgres-db/acid-education pkg=controller worker=0
time="2022-04-23T22:23:14Z" level=info msg="Shutting down... terminated"
time="2022-04-23T22:23:14Z" level=info msg="Http server shut down" pkg=apiserver
`

![image](https://user-images.githubusercontent.com/121157/164971872-e95e1117-0903-446f-ab7a-31f5769f05b0.png)

**Comment by yevon** [comment]
I just tried to put 4 nodes just in case was something due to a low number of instances in the rolling update but it didn't any change. If I describe the pod it says: finalizers: orphan

**Comment by FxKu** [comment]
@yevon can you sketch out a timeline of actions you did so I can try to replicate? I tested switchovers in a fresh minikube env and it worked for me. Saw no Pods stuck in `Terminating` state. We do have finalizers in place. Therefore, "finalizers: orphan" might be just a normal message in that regard.

**Comment by yevon** [comment]
Thanks @FxKu , what version of kubernetes did you use?

In my case is a k3s kubernetes cluster and only happens when updating the spilo image in the manifest, if I change the number of instances or other cluster options it works. What I do is:

1. Generate a new spilo docker image that is stored inside a private repository with authentication (Proper setup for pulling docker images from the private registry, image pull secrets specified at serviceaccount level).
2. Modify the private registry image tag in the cluster manifest file, and apply it with a kubeclt apply -f manifest... (Apply is correct?)
3. Check pod status, and it gets stuck into the Terminating status with the "orphan" finalizers. I just found an interesting article regarding orphan finalizers and how to debug them, I will check this later if I can get more info:

https://cloud.redhat.com/blog/the-hidden-dangers-of-terminating-namespaces

**Comment by yevon** [comment]
I said nothing! Just reinstalled my k3s cluster as I discovered that I had dangling resources for forcing terminations that avoided that postgres pods could be terminated. Now is working fine!
