### ISSUE TITLE
Operator `postgresqls` CRD and Helm Chart CRD out of sync

### ISSUE THREAD

**Issue by AllexVeldman** [zalando/postgres-operator#1868]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.8.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** DOKS
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

The CRD defined in https://github.com/zalando/postgres-operator/blob/cde88d3711d9ec395570ae8352b34632a2540ae3/charts/postgres-operator/crds/postgresqls.yaml#L596 does not match the CRD as patched by the operator itself https://github.com/zalando/postgres-operator/blob/cde88d3711d9ec395570ae8352b34632a2540ae3/pkg/apis/acid.zalan.do/v1/crds.go#L969

Full diff reported by ArgoCD:
![image](https://user-images.githubusercontent.com/59562474/165095470-f0137ff7-9a45-42e1-88b7-a353c4c12688.png)

Possibly related to https://github.com/zalando/postgres-operator/issues/1497

**Comment by FxKu** [comment]
@AllexVeldman thanks for noticing this inconsistency. Fixed with #1869

**Comment by AllexVeldman** [comment]
@FxKu Just applied v1.8.1, there seems to be a typo in the CRD yaml:

![image](https://user-images.githubusercontent.com/59562474/169763636-6aeb095e-840a-4913-8ba9-76e9007e5a1a.png)

**Comment by soluri** [comment]
This is also an issue in 1.8.2.
