### ISSUE TITLE
Add operator deployment readiness probes

### ISSUE THREAD

**Issue by dmvolod** [zalando/postgres-operator#1871]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s] kind
- **Are you running Postgres Operator in production?** [yes | no] no
- **Type of issue?** [Bug report, question, feature request, etc.] feature request

It would be nice to implement internally and create an embedded REST endpoints for operator readiness probe. Otherwise, there is no possible to analyse if operator correctly starting or not based on Deployment state.

**Comment by dmvolod** [comment]
We could probably extend embedded API server a bit to utilize it as probes target.

**Comment by caniko** [comment]
This will make #1870 easier to implement
