### ISSUE TITLE
Spilo env var generation refactoring breaks proxy support

### ISSUE THREAD

**Issue by stephan2012** [zalando/postgres-operator#1886]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.8.0`
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

The refactored env var generation (#1848) writes all [env var names uppercased](https://github.com/zalando/postgres-operator/blob/50dde2a21b0d13effa5220c0ab7e109b738abf59/pkg/cluster/k8sres.go#L942), which breaks [proxy support in Spilo](https://github.com/zalando/spilo/pull/661). Since env vars `http_proxy`, `https_proxy`, and `no_proxy` are a de-facto standard, the uppercasing should be removed.

**Comment by FxKu** [comment]
Hi @stephan2012. Good hint. I did not realize this is a breaking change. I will remove it again for the next bugfix release.

**Comment by Jan-M** [comment]
:+1:
