### ISSUE TITLE
Setting postgresql.parameters  tcp_keepalives_xxx  Failed

### ISSUE THREAD

**Issue by jicki** [zalando/postgres-operator#1887]
`Which image of the operator are you using?` registry.opensource.zalan.do/acid/postgres-operator:v1.8.0

`Where do you run it - cloud or metal? Kubernetes or OpenShift?`       Bare Metal K8s

`Are you running Postgres Operator in production?`         yes

`Type of issue? `  Bug report

### Setting parameters Failed

```bash
postgresql:
  version: "14"
  parameters:
    superuser_reserved_connections: "10"
    tcp_keepalives_count: "5"
    tcp_keepalives_idle: "300"
    tcp_keepalives_interval: "60"
```

```bash
postgres=# show superuser_reserved_connections;
 superuser_reserved_connections 
--------------------------------
 10
(1 row)

postgres=# show tcp_keepalives_count;
 tcp_keepalives_count 
----------------------
 0
(1 row)

postgres=# show tcp_keepalives_interval;
 tcp_keepalives_interval 
-------------------------
 0
(1 row)

postgres=# show tcp_keepalives_idle;
 tcp_keepalives_idle 
---------------------
 0
(1 row)

```

**Comment by CyberDem0n** [comment]
Have you checked what is in the $PGDATA/postgresql.conf?
I am pretty confident there are correct values.

**Comment by jicki** [comment]
> Have you checked what is in the $PGDATA/postgresql.conf? I am pretty confident there are correct values.

```bash
cat  /home/postgres/pgdata/pgroot/data/postgresql.conf |grep tcp_keepalives

tcp_keepalives_count = '5'
tcp_keepalives_idle = '300'
tcp_keepalives_interval = '60'
```

I think probably values should be of type int

but  setting type int  error

```
[spec.postgresql.parameters.tcp_keepalives_interval: Invalid value: "integer": spec.postgresql.parameters.tcp_keepalives_interval in body must be of type string: "integer", spec.postgresql.parameters.tcp_keepalives_count: Invalid value: "integer": spec.postgresql.parameters.tcp_keepalives_count in body must be of type string: "integer", spec.postgresql.parameters.tcp_keepalives_idle: Invalid value: "integer": spec.postgresql.parameters.tcp_keepalives_idle in body must be of type string: "integer"]
```

**Comment by jicki** [comment]
Sorry 

## Tip: 
> Specifies the number of TCP keepalive messages that can be lost before the server's connection to the client is considered dead. A value of 0 (the default) selects the operating system's default. This parameter is supported only on systems that support TCP_KEEPCNT or an equivalent socket option; on other systems, it must be zero. In sessions connected via a Unix-domain socket, this parameter is ignored and always reads as zero. This parameter is not supported on Windows, and must be zero.
