### ISSUE TITLE
Lag (ClusterMember.members.lag) value over int32 max value

### ISSUE THREAD

**Issue by danlenar** [zalando/postgres-operator#1890]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

One of our postgres has a lag of about 4gb which exceeds int32.
Lag should be stored as an int64.

```
time="2022-05-11T16:40:58Z" level=error msg="could not sync cluster: could not sync statefulsets: could not recreate pods: skipping switchover: failed to get Patroni cluster members: json: cannot unmarshal number 3288334336 into Go struct field ClusterMember.members.lag of type int32" cluster-name=sip-calllog/postgres-postgres pkg=controller worker=2
```

**Comment by FxKu** [comment]
Thanks @danlenar for raising. Can you provide a PR. I see, that it might not be super trivial since we use the [IntOrString](https://github.com/zalando/postgres-operator/blob/c6f2c685884a98a4121641256e4ee36b3f745ad6/pkg/util/patroni/patroni.go#L192) type.
