### ISSUE TITLE
Postgres Operator v.1.8.1 images not pullable

### ISSUE THREAD

**Issue by alfsch** [zalando/postgres-operator#1899]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**  Bare Metal K8s]
- **Are you running Postgres Operator in production?** [yes]
- **Type of issue?** [Bug report, ]

I tried to switch to postgres-operator v1.8.1 with helm chart. Postgres-operator doesn't start due to missing images (Image Pull backoff)

Then I tried to pull the images with docker like:

```
 docker pull  registry.opensource.zalan.do/acid/postgres-operator-ui:v1.8.1
 docker pull registry.opensource.zalan.do/acid/postgres-operator:v1.8.1
 docker pull registry.opensource.zalan.do/acid/spilo-14:2.2-p4
 docker pull registry.opensource.zalan.do/acid/logical-backup:v1.8.1
```

For all of these pull's I get these Errors:

```
Error response from daemon: manifest for registry.opensource.zalan.do/acid/postgres-operator-ui:v1.8.1 not found: manifest unknown: manifest unknown
Error response from daemon: manifest for registry.opensource.zalan.do/acid/postgres-operator:v1.8.1 not found: manifest unknown: manifest unknown
Error response from daemon: manifest for registry.opensource.zalan.do/acid/spilo-14:2.2-p4 not found: manifest unknown: manifest unknown
Error response from daemon: manifest for registry.opensource.zalan.do/acid/logical-backup:v1.8.1 not found: manifest unknown: manifest unknown
```

It seems that your build didn't push these images.

BR,

Alfred

**Comment by FxKu** [comment]
yeah ... :weary: 
The test pipeline has not run through yet to push the new image. It should be there within the next hours.

**Comment by FxKu** [comment]
The images should all be available, now. Thanks for using the Postgres Operator :smiley:

**Comment by alfsch** [comment]
THX for this really fast fix :+1:
