### ISSUE TITLE
Load balancing service annotations are applying to services that do not have load balancing enabled

### ISSUE THREAD

**Issue by Kaelten** [zalando/postgres-operator#1927]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** EKS
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** bug report

I'm setting up a standby cluster that I wish to be exposed via a load balancer.  I'm also using the aws-load-balancer-controller, which requires some special annotations to configure the NLB that's created.  Those annotations are setup via the operator config map.

Out of the two cluster configurations in this project, only the standby has `enableMasterLoadBalancer: true` enabled.  However, the annotations defined in the operator config map are then applied to the master and replication services for both clusters.  This results in multiple unneeded NLBs being created.  

I feel this is a bug in how the annotations are being calculated and to which services they are applying as only the standby's master service is having it's type set to `LoadBalancer`.  Ultimately, I just need a way to limit which services receive these annotations.

**Comment by FxKu** [comment]
I don't know if the operator should block annotations from triggering actions in the chosen cloud infrastructure. Maybe another option can be added to define which pod and service instances should receive the specified annotations. Master, replica or all (default). Are you using `customer_service_annotations` option of `serviceAnnotations` from the manifest?

**Comment by Kaelten** [comment]
I've been able to work around this by upgrading to the latest versions of the aws-load-balancer-controller and enabling an feature flag to only look at loadbalancer types.  Unfortunately, I had to fork the helm chart for it since that setting is not exposed through the helm chart. 

I consider this a work around, as some people may need to support load balancers for non load balancers.

**Comment by Kaelten** [comment]
> I don't know if the operator should block annotations from triggering actions in the chosen cloud infrastructure. Maybe another option can be added to define which pod and service instances should receive the specified annotations. Master, replica or all (default). Are you using `customer_service_annotations` option of `serviceAnnotations` from the manifest?

I think setting it up so the annotations from the load balancer configuration only apply to enabled load balancers would work.  Whether that means introducing need settings or not I'm not sure.  

I'm also thinking that it's possible that we would want to support a different annotation set on different load balancers since those annotations can configure the NLB in different ways.

**Comment by ljcesca** [comment]
Hi, we are also running into this issue. I'm happy to work on a PR to improve this behavior, but would like your opinion if you'd prefer to:
-  add `masterLoadBalancerServiceAnnotations` and `replicaLoadBalancerServiceAnnotations` to the `Cluster` CRD that get merged with `serviceAnnotations`
- disable pushing down `serviceAnnotations` onto the `repl` service when `enableReplicaLoadBalancer` is false (which would be a change to existing behavior)
- or another option

**Comment by rishiraj88** [comment]
Looks good to me, too.

**Comment by owenthereal** [comment]
I put together https://github.com/zalando/postgres-operator/pull/2161 to separate the master annotations & replica annotations.

**Comment by FxKu** [comment]
Thanks for continuing the discussion. Two need manifest field seem like a proper solution. I've added a few comments. I want to do a release next week, so please take a look soon so we can include the feature in 1.9.

**Comment by rishiraj88** [comment]
Great thanks to all.

**Comment by boukandouramhamed** [comment]
@owenthereal in case pooler is enabled, `masterServiceAnnotations` will add the annotation to both Postgres and PGBOUNCER services. 

Shouldn't we also have another parameter `masterPoolerServiceAnnotations` to add annotation to the PGBOUNCER service only ?

**Comment by privatecoder** [comment]
@boukandouramhamed yes, we should have that ;)

@FxKu: There should be:

`masterServiceAnnotations`
`replicaServiceAnnotations`
`masterPoolerServiceAnnotations`
`replicaPoolerServiceAnnotations`

which would only apply to the corresponding Postgres and PGBouncer service.

EDIT: I am testing [this](https://github.com/zalando/postgres-operator/compare/master...privatecoder:postgres-operator:master) right now and will submit a PR if successful.
