### ISSUE TITLE
postgres-operator:v1.8.2 is not available on the image registry

### ISSUE THREAD

**Issue by gbl-michell** [zalando/postgres-operator#1933]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** - registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s] - GCP
- **Are you running Postgres Operator in production?** [yes | no] - No
- **Type of issue?** [Bug report, question, feature request, etc.] - Bug report (?)

Hey all, I don't know where else to report this, but even though the new chart version uses v1.8.2 as image.tag, the image v1.8.2 is not available on the registry. After a ```curl -X GET --header 'Accept: application/json' 'https://registry.opensource.zalan.do/v2/acid/postgres-operator/tags/list'``` I can see that the latest image version available is "v1.8.1-1-g7d4da928"

**Comment by FxKu** [comment]
The image will be available when e2e test are finally passing which, unfortunately, has become a bit of a gamble. It's on our ToDo list to make the e2e suite more reliable. 1.8.2 should be there tomorrow.
