### ISSUE TITLE
make gcp_credentials non mandatory on Google Cloud Platform

### ISSUE THREAD

**Issue by jeremie-seguin** [zalando/postgres-operator#1980]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
registry.opensource.zalan.do/acid/postgres-operator:v1.8.0

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** 
GCP 
- **Are you running Postgres Operator in production?** 
yes
- **Type of issue?**
feature request

Hello when using WAL archiving and physical basebackups, the gcp_credentials are [mandatory](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/k8sres.go#L1896) even when the Kubernetes service account is already authenticated to gcp using [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform#authenticating_with_service_accounts)

It would be better in my opinion to still try to fetch the resources and fallback to gcp_credentials in case of failure. 

Is there any reason to authenticate the pods using this method instead of the Workload Identity ?

**Comment by FxKu** [comment]
I will close this issue in favor for #1995
