### ISSUE TITLE
Support for Kubernetes 1.25

### ISSUE THREAD

**Issue by brianpursley** [zalando/postgres-operator#1999]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/spilo-14:2.1-p6
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

If you try to use postgres-operator on a 1.25+ cluster, the psotgresql resource creation fails with a status of `CreateFailed` and the following events in describe:
```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Create     22m   postgres-operator  Started creation of new cluster resources
  Normal   Endpoints  22m   postgres-operator  Endpoint "default/acid-minimal-cluster" has been successfully created
  Normal   Services   22m   postgres-operator  The service "default/acid-minimal-cluster" for role master has been successfully created
  Normal   Services   22m   postgres-operator  The service "default/acid-minimal-cluster-repl" for role replica has been successfully created
  Normal   Secrets    22m   postgres-operator  The secrets have been successfully created
  Warning  Create     22m   postgres-operator  could not create cluster: could not create pod disruption budget: the server could not find the requested resource
```

The operator logs the following error:
```
time="2022-08-15T17:16:01Z" level=error msg="could not create cluster: could not create pod disruption budget: the server could not find the requested resource" cluster-name=default/acid-minimal-cluster pkg=controller worker=0
```

**Other Information:**
I suspect this is related to [the policy/v1beta1 version of PodDisruptionBudget no longer being served in Kubernetes 1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125).

**Comment by FxKu** [comment]
We waited a bit to not hit all users that are still running our Operator on K8s 1.20 or lower. But I think with the next release, it's about time to drop support for K8s versions older than 1.21. I created a PR.

**Comment by eyanulis** [comment]
I see both PRs related to removed resource types (#2008 and #2019) are targeted for 1.9 - does this release have a target date? As far as I can tell, this blocks running the operator entirely on 1.25, and I do have a requirement to do so.

I could patch these two PRs into a local fork but it wouldn't be my preferred way of handling this past the short term.

**Comment by Mattes83** [comment]
> I see both PRs related to removed resource types (#2008 and #2019) are targeted for 1.9 - does this release have a target date? As far as I can tell, this blocks running the operator entirely on 1.25, and I do have a requirement to do so.
> 
> I could patch these two PRs into a local fork but it wouldn't be my preferred way of handling this past the short term.

Same here...is it possible to cut a new release?

**Comment by sylvainOL** [comment]
Hello, any news on this?
I'm waiting for this to bump to version 1.25 :)

**Comment by pawelrys** [comment]
Any news? I have the same problem :/
