### ISSUE TITLE
Improve base back-up docs

### ISSUE THREAD

**Issue by rhrytskiv** [zalando/postgres-operator#2002]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [Bare Metal K8s]
- **Are you running Postgres Operator in production?** [not yet]
- **Type of issue?** [question]

The documentation is not clear on base back-up. From documentation it might seems like they are enabled by default. However using the command provided to look for backups it seems that there is no such directory as "/run/etc/wal-e.d/env".

**Comment by FxKu** [comment]
People use the Operator in various different infrastructural environments. You have to specify a location where WAL files should be pushed to. There's no default that works everywhere. AWS S3 (or compliant services), Google cloud storage or Azure storage account must be [configured](https://github.com/zalando/postgres-operator/blob/master/docs/reference/operator_parameters.md#aws-or-gcp-interaction) globally - and possibly be extended by a PodEnvironmentConfigMap/Secret. Have a look again at our [docs](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#wal-archiving-and-physical-basebackups) and point us to paragraphs which you think are unclear.

**Comment by rhrytskiv** [comment]
Thanks. For me it was unclear whether they were any back-ups enabled by default. As for 'no default that works everywhere' I think the default should be local storage, and it seems it's doing some back-ups by default, because I've not configured anything and still when I exec into the postgres pod it has populated wal-g dir and there are backup files there, so how it is configured then?
On the topic of 'People use the Operator in various different infrastructural environments', we have bare metal k8s cluster, we don't use cloud providers, and I'm not seeing, again, anything on that in docs, ssh or similar tools? Only major cloud providers are covered.
