### ISSUE TITLE
/run/etc/wal-e.d/env: file does not exist

### ISSUE THREAD

**Issue by rhrytskiv** [zalando/postgres-operator#2016]
Which image of the operator are you using? e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
Where do you run it - cloud or metal? Kubernetes or OpenShift? [Bare Metal K8s]
Are you running Postgres Operator in production? [not yet]
Type of issue? [bug report]

I've all of the required variables set-up for the wal-g backups, though when I exec into the postgres pod there is no such directory as "/run/etc/wal-e.d/env".

Backups **are** arriving to s3, btw.

I've installed this operator via helm chart repo

**Comment by maaft** [comment]
Could you please explain your solution? Thanks
