### ISSUE TITLE
Vault is rejected by pg_hba.config with message "no encryption"

### ISSUE THREAD

**Issue by laiminhtrung1997** [zalando/postgres-operator#2020]
I created a statefulset of Vault to connect with postgresql, but this error was showed up when I get logs.
`Error initializing storage of type postgresql: failed to check for native upsert: pq: pg_hba.conf rejects connection for host "xx.xxx.xxx.xx", user "vault", database "vault_db", no encryption`
Do anyone know this issue and the root cause of this? Thank you very much. I am vietnamese so I am not good at English. I am so sorry for that.

**Comment by laiminhtrung1997** [comment]
@FxKu Can you help me? :(

**Comment by Paramoshka** [comment]
> Looks like you're trying to connect without SSL (`no encryption`). Try connecting with SSL enabled :)


Please tell me how to enable. I did not find such settings except for custom tls.

**Comment by FxKu** [comment]
Which client software are you using to connect? It should have SSL settings that you can change. Set `sslmode=require`.

**Comment by laiminhtrung1997** [comment]
I think the root cause is my wrong setup. The problem is gone. So I will close this issue.

**Comment by ujala-singh** [comment]
@laiminhtrung1997 I am facing the same issue on temporal setup https://github.com/zalando/postgres-operator/issues/2734. How did you resolve this problem by fixing your setup?
