### ISSUE TITLE
Resources: ValidationError(postgresql.spec.resources.limits) not able to remove limit from postgresql object

### ISSUE THREAD

**Issue by sauerborn-git** [zalando/postgres-operator#2028]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
- registry.opensource.zalan.do/acid/postgres-operator:v1.7.1

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Bare Metal K3s

- **Type of issue?** [Bug report, question, feature request, etc.]
Bug report or feature request, not sure if the current situation is expected by the maintainers

**Description of the Error**
Postgres-Operator is successfully running and also the postgresql replica.
With the following resources specifications:
````
  resources:
    limits:
      cpu: "500m"
      memory: 500Mi
    requests:
      cpu: "50m"
      memory: 180Mi
````

Now I want to remove the cpu limit, in order to avoid throttling and get out the maximum.
I edit now the postgresql using `kubectl edit postgresql` and remove the line `cpu: "500m"`

Now if I want to save I get the following error:
````
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# postgresqls.acid.zalan.do "sericy-common-postgres-14-db-service" was not valid:
# * <nil>: Invalid value: "The edited file failed validation": ValidationError(postgresql.spec.resources.limits): missing required field "cpu" in do.zalan.acid.v1.postgresql.spec.resources.limits
#
````

I already tried specifying 0 instead (which also would be without a limit), for this I changed the `operatorconfigurations` and put there `min_cpu_limit: "0"`.
This works, but since the cpu request can not be higher then the limit, this leads to the fact, that I also need to change the cpu request to 0 which is not good, since there are good reasons for specifying a request.

I hope I described everything clear, let me know in case something is unclear or in case I am doing anything wrong :)

**Comment by FxKu** [comment]
I see, you're still using v1.7.1. We've removed the `required` flag for `resources` in the CRD schema starting from `v1.8.0`.

**Comment by sauerborn-git** [comment]
> I see, you're still using v1.7.1. We've removed the `required` flag for `resources` in the CRD schema starting from `v1.8.0`.

Thanks a lot @FxKu for your response!
This sounds verry promising, we will plan to update the version and I assume it will resolve it.
I will close this ticket and reopen it in case the update did not resolve it (the update needs to be planned and take some tim)
