### ISSUE TITLE
add arm64 support

### ISSUE THREAD

**Issue by kisdaniel** [zalando/postgres-operator#2030]
We have tried postgres-operator in arm64 based raspberry pi with rasbian and microk8s.
We get an error when operator container starts (/postgres-operator:v1.8.2 output log):

standard_init_linux.go:228: exec user process caused: exec format error

- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** raspberry pi 4 8gb, rasbian 64-bit, microk8s
- **Are you running Postgres Operator in production?** not yet
- **Type of issue?** Bug report

It seems to me that postgres-operator not supports arm64 architecture, please add an arm64 support.

**Comment by FxKu** [comment]
Thanks for raising. It's duplicate to #1109
Please, check https://github.com/zalando/spilo/issues/618.
We are already building arm64 images. We should indeed announce in the next release notes. Otherwise nobody finds it.

**Comment by mmoscher** [comment]
Hi @FxKu,

if your already building arm64 image, can you mention were to find them? Is their a chance to use them?
Would like to get the postgres-operator running on a Google Cloud Tau T2A GCE Instance (currnetly running for eval).
Thanks in advance :)

**Comment by JanCizmar** [comment]
> With some love and additional work, I could file an PR enabling arm64 builds.

I would be very grateful.

**Comment by mhaley-tignis** [comment]
For anyone else coming here, there are multiarch images published with all new releases now. See https://github.com/zalando/postgres-operator/releases/tag/v1.14.0 specifically this section:

>Multi-arch image (arm):
>Postgres Operator: ghcr.io/zalando/postgres-operator:v1.14.0
>UI: ghcr.io/zalando/postgres-operator-ui:v1.14.0
>Logical Backup: ghcr.io/zalando/postgres-operator/logical-backup:v1.14.0
