### ISSUE TITLE
postgresql deployment on openshift env

### ISSUE THREAD

**Issue by zhoudayongdennis** [zalando/postgres-operator#2044]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
postgres-operator 1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
OCP 4.11
- **Are you running Postgres Operator in production?** [yes | no]
Not yet, still in non-production, but going to be there
- **Type of issue?** [Bug report, question, feature request, etc.]
question for any special security related configuration to support OCP platform

Some general remarks when posting a bug report:
- Please, check the operator, pod (Patroni) and postgresql logs first. When copy-pasting many log lines please do it in a separate GitHub gist together with your Postgres CRD and configuration manifest.
- If you feel this issue might be more related to the [Spilo](https://github.com/zalando/spilo/issues) docker image or [Patroni](https://github.com/zalando/patroni/issues), consider opening issues in the respective repos.

had no issue for the deployment of corresponding CRD and operator charts, but got below failure during postgresql cluster chart deployment for corresponding statefulset resources.

it seems privilege issue on OCP platform, not sure what's kind of extra configuration required for it??

  Warning  FailedCreate  <invalid> (x457 over 45h)  statefulset-controller  create Pod char-pg-cluster-0 in StatefulSet char-pg-cluster failed error: pods "char-pg-cluster-0" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, spec.containers[0].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed, provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

here was part of output of "oc get sts char-pg-cluster -oyaml"

        - name: KUBERNETES_USE_CONFIGMAPS
          value: "true"
        image: ******char-pg-cluster:2.1-p6-char.1
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: 8008
            scheme: HTTP
          initialDelaySeconds: 6
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 2000Mi
          requests:
            cpu: "2"
            memory: 2000Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
        - mountPath: /dev/shm
          name: dshm
      dnsPolicy: ClusterFirst
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000730000
        runAsUser: 1000730000
      serviceAccount: postgres-pod
      serviceAccountName: postgres-pod
      terminationGracePeriodSeconds: 300

**Comment by stgrace** [comment]
Hi @zhoudayongdennis,

In the values for the postgres operator there is a value:
```
  # whether the Spilo container should run with additional permissions other than parent.
  # required by cron which needs setuid
  spilo_allow_privilege_escalation: true
```

By default this value is set to true. You can set this value to false (restart the postgres operator to be sure the config is reloaded after changing it to false). If you want to have privileged escalation on your postgres pod however, you

**Comment by zhoudayongdennis** [comment]
@stgrace, thanks for the info!

besides the parameter you provided, I also configured one more spilo_privileged as false, and with both false value, it looks good for deployment on openshift platform without privilege. this issue could be resolved now.

cat oc-values.yaml
# -- general configuration parameters
configGeneral:
  # -- Select if setup uses endpoints (default), or configmaps to manage leader (DCS=k8s)
  kubernetes_use_configmaps: true
configKubernetes:
  # -- whether the Spilo container should run in privileged mode
  spilo_privileged: false
  # -- whether the Spilo container should run with additional permissions other than parent.
  # -- required by cron which needs setuid
  spilo_allow_privilege_escalation: false
