### ISSUE TITLE
Support for env variables from secret for logical backup

### ISSUE THREAD

**Issue by stgrace** [zalando/postgres-operator#2050]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Are you running Postgres Operator in production?** yes 
- **Type of issue?** feature request

I would like to see an option to add environment variables from a secret for logical backup cronjobs. This would allow postgres config to not contain secrets and for secrets to be created from another source (sealed secrets/manual creation/external operator/...).

**Comment by nihaldivyam** [comment]
Any updates on this ?

**Comment by KlavsKlavsen** [comment]
Yeah - this is a real problem.. having s3 access secrets in the clear like this :(
And we use gitops - so we'd have to keep it in cleartext git to use it.

**Comment by FxKu** [comment]
Closing as #2051 got merged.
