### ISSUE TITLE
"the server could not find the requested resource" cluster-name=keycloak/acid-minimal-cluster pkg=cluster worker=0

### ISSUE THREAD

**Issue by alokhom** [zalando/postgres-operator#2061]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s minikube 1.25
- **Are you running Postgres Operator in production?** no
- **Type of issue?** problem

I have manually deployed 
  - operatorconfigurations.acid.zalan.do.CRD.yaml
  - postgresqls.acid.zalan.do.CRD.yaml
  - postgresstreams.CRD.yaml

deployment in zalando-operator namespace : 
https://gist.github.com/alokhom/39e54b78d0f278ee4b7f5573bea57326

I have postgresql manifest in keycloak namespace 
https://gist.github.com/alokhom/7f602a0247d5af056c93481f4f2d751f

pgo operator logs:  https://gist.github.com/alokhom/97f2e8e8b1b2be92da1f0ec65a70e491

why does pgo logs say : 

"the server could not find the requested resource" cluster-name=keycloak/acid-minimal-cluster pkg=cluster worker=0

and 

"time="2022-09-27T09:12:04Z" level=error msg="could not sync cluster: could not sync pod disruption budget: could not create pod disruption budget: the server could not find the requested resource" cluster-name=keycloak/acid-minimal-cluster pkg=controller worker=0"

**Comment by FxKu** [comment]
See #2017
