### ISSUE TITLE
ErrImagePull for postgres-operator

### ISSUE THREAD

**Issue by arezvani** [zalando/postgres-operator#2073]
Please, answer some short questions which should help us to understand your problem / question better?

- Which image of the operator are you using? registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- Where do you run it - cloud or metal? Kubernetes or OpenShift? Kubernetes 
- Are you running Postgres Operator in production? no
- Type of issue? question

I have problem when I want to use this image registry.opensource.zalan.do/acid/postgres-operator:v1.8.2 and I get this error:

Error: ErrImagePull
Error: ImagePullBackOff
Failed to pull image "registry.opensource.zalan.do/acid/postgres-operator:v1.8.2": rpc error: code = NotFound desc = failed to pull and unpack image "registry.opensource.zalan.do/acid/postgres-operator:v1.8.2": failed to copy: httpReadSeeker: failed open: could not fetch content descriptor sha256:362f48b85866cee67d1c8668cf6a83fac76520f056ed485c047f8db2fd2a3cda (application/vnd.docker.container.image.v1+json) from remote: not found
Back-off pulling image "registry.opensource.zalan.do/acid/postgres-operator:v1.8.2"

**Comment by mmoscher** [comment]
@arezvani maybe you have some connectivity issues on your side?

Pulling the image works w/o any problems:
![image](https://user-images.githubusercontent.com/2553753/195092097-96c44b75-4580-475b-92ea-064042bd0470.png)

For me, this issue seems not related to the postgres-operator itself.

**Comment by arezvani** [comment]
No need to login or do something before pulling image?
Is there any Dockerfile for that?

**Comment by mmoscher** [comment]
@arezvani nope, not at all. Just try the command you can see in the screenshot yourself.

The docker file can be found under docker/Dockerfile and docker builds can be done with `make docker`.

**Comment by arezvani** [comment]
@mmoscher Is there anyway you save this image by `docker save` and send that for me anywhere you can.
