### ISSUE TITLE
Expose Patroni Metrics endpoint

### ISSUE THREAD

**Issue by lunderhage** [zalando/postgres-operator#2080]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Openstack K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Feature request

The postgres operator does not expose the Patroni metrics endpoint (port 9547). That would be really useful and remove the need of an external exporter sidecar.

**Comment by machine424** [comment]
Hello @lunderhage 

How did you come up with the port `9547`? By default patroni listens on 8008, and exposes its metrics on 8008/metrics.
the operator does define (you could still access it even if not defined) this port in the Statefulsets manifests 
https://github.com/zalando/postgres-operator/blob/6d0117b662bc2fd7880352b58258792ff2941d0a/pkg/cluster/k8sres.go#L556-L565

Do you mean adding them to the Service? do you mean giving it a name?

**Comment by lunderhage** [comment]
@machine424 : You are right, my bad.

I got port 9547 from some list of reserved service monitor ports and the fact that the exporter I used first and later modified to export the databas lag metric uses port 9547.
