### ISSUE TITLE
Supported version of Kubernetes?

### ISSUE THREAD

**Issue by DaveDef** [zalando/postgres-operator#2094]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
registry.opensource.zalan.do/acid/postgres-operator:v1.8.2

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** 
Bare Metal K8s

- **Are you running Postgres Operator in production?** 
no

- **Type of issue?** 
question

Which versions of K8S are supported by zalando-operator?

**Comment by dmvolod** [comment]
Hi @DaveDef 
The Kubernetes version support based on the following document, called `Version Skew Policy`
https://kubernetes.io/releases/version-skew-policy/

In current case, Kubernetes API server version defined  in `go.mod` (https://github.com/zalando/postgres-operator/blob/v1.8.2/go.mod) is 
```
k8s.io/api v0.22.4
k8s.io/apiextensions-apiserver v0.22.4
k8s.io/apimachinery v0.22.4
k8s.io/client-go v0.22.4
```

This means, that supported Kubernetes version, should be 0.22.x ± 1 version.

**Comment by Lxrdknows77** [comment]
@dmvolod Is  `"_this means, that supported Kubernetes version, should be 1.22.x ± 1 release_"` based on this:
"_In [highly-available (HA) clusters](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/), the newest and oldest kube-apiserver instances must be within one minor version._" ?

**Comment by Lxrdknows77** [comment]
Another question, do you mean ± 1 release reference to minor or patch part of version?  And what is it based on?

**Comment by dmvolod** [comment]
@DaveDef please note, that Kubernetes v1.24 and later are strongly unsupported due to #2098
