### ISSUE TITLE
New layer of intelligence for redirecting read requests to replica

### ISSUE THREAD

**Issue by JulesLalu** [zalando/postgres-operator#2105]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** AWS K8s
- **Are you running Postgres Operator in production?** not yet
- **Type of issue?** question

Hi, 

If I understood well the architecture schema of the postgres-operator, an application which wants to access to the database has to precise if it wants to access the master or the replicas service. It means that if you issue a write request, you have to connect to the master service; and for issuing a read request, connect to the replicas service if you don't want your master to be flooded with requests.

However, I thought at the start that patroni was able to redirect read requests to replicas when issuing such requests to the master and vice-versa, so that my application would not worry about precising if it wants to access master or replicas. 

Is such behavior out of scope ? If yes, do you know of a workaround other than precising master or replica endpoint every time you issue a request for an application that both reads and writes into the database ?

Still, thank you very much for this operator and all its features !

**Comment by starizard** [comment]
Hey @JulesLalu, 
I was wondering the same thing, did you get an answer for this?

**Comment by JulesLalu** [comment]
Hello, 

No sadly I did not get any answer, for now our services use either the master instance or the replica instance for all their requests...

Sorry !

**Comment by JulesLalu** [comment]
Update : I found this really cool guide to enable load balancing between master and slave by using Pg-Pool II :  https://github.com/pgpool/pgpool2_on_k8s/
Haven't tried implementing it yet but I will definitely give it a go !
