### ISSUE TITLE
registry.opensource.zalan.do Resolve error

### ISSUE THREAD

**Issue by vitargelo** [zalando/postgres-operator#2111]
K8S ERROR: Failed to pull image "registry.opensource.zalan.do/acid/pgbouncer:master-24": rpc error: code = Unknown desc = Error response from daemon: Get "https://registry.opensource.zalan.do/v2/": dial tcp: lookup registry.opensource.zalan.do: no such host

Local nslookup:

Google Public DNS:
$ nslookup **registry.opensource.zalan.do** 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find registry.opensource.zalan.do: NXDOMAIN

CloudFlare Public DNS
$ nslookup **registry.opensource.zalan.do** 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

** server can't find registry.opensource.zalan.do: NXDOMAIN

**Comment by vitargelo** [comment]
Fixed after 1 hour. Hope it will not happen again.

**Comment by FxKu** [comment]
We deleted all our DNS entries. That will probably not happen again :exploding_head:
