### ISSUE TITLE
Indentation of `imagePullSecrets` in values.yaml is confusing

### ISSUE THREAD

**Issue by sieginglion** [zalando/postgres-operator#2119]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** MicroK8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

Some general remarks when posting a bug report:
- Please, check the operator, pod (Patroni) and postgresql logs first. When copy-pasting many log lines please do it in a separate GitHub gist together with your Postgres CRD and configuration manifest.
- If you feel this issue might be more related to the [Spilo](https://github.com/zalando/spilo/issues) docker image or [Patroni](https://github.com/zalando/patroni/issues), consider opening issues in the respective repos.

In `deployment.yaml`, `imagePullSecrets` is the top level key of `.Values`

**Comment by edward2a** [comment]
The indentation is indeed incorrect in the values file for the main chart.
The one in the UI chart is correct.
