### ISSUE TITLE
Updating status wait timeout setting question

### ISSUE THREAD

**Issue by yehudag-shipin** [zalando/postgres-operator#2138]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** AWS K8s
- **Are you running Postgres Operator in production?** yes 
- **Type of issue?** question
 
Hello,
I have several development deployments that I'm shutting down and starting according to development needs. I'm using the Argo Workflow mechanism to do so. My scaling-up flow starts with bringing up the Postgres Operator instances. When the databases are in the Running status, the flow continues to bring up the application pods.
The problem is that sometimes the start of the database takes too much time due to the new node spinning up, and the operator puts the resource in the Failed state. This behavior fails my workflow, and I have to re-run it again to get to success.
How can I set the longer timeout of the Operator waits before it decides that the Update is failed?
Thank you in advance for the answer.

**Comment by yehudag-shipin** [comment]
Can please anyone help?

**Comment by dmvolod** [comment]
Hi @yehudag-shipin 
You can try to decrease `repair_period` which is evaluating repair for those clusters that didn't report success as a result.
https://postgres-operator.readthedocs.io/en/latest/administrator/#running-periodic-autorepair-scans-of-k8s-objects

**Comment by yehudag-shipin** [comment]
Thank you
