### ISSUE TITLE
Pooler default service account conflicts with vault annotations

### ISSUE THREAD

**Issue by jurim76** [zalando/postgres-operator#2145]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

Pooler deployment uses "default" service account, it could be a problem with vault annotations, where vault access is restricted by service account name (ie "postgres-pod" sa). Operator uses same annotations during pooler pod creation and pod failed with "access denied" while trying to access vault, during vault-init stage.
So my question - is it possible to use same "postgres-pod" service account for pooler also? Or prevent custom annotations to taint pooler pods?

**Comment by dmvolod** [comment]
> So my question - is it possible to use same "postgres-pod" service account for pooler also? Or prevent custom annotations to taint pooler pods?

Hi @jurim76 

No, this is not possible and need to be implemented in the code. Only  `postgres-pod` name and structure can be configurable and changed via `PodServiceAccountName` and `PodServiceAccountDefinition` options.

**Comment by FxKu** [comment]
Pooler is using the same service accounts like the Spilo pods since #2352
