### ISSUE TITLE
Mismatched CRDs Packaged in Helm distribution

### ISSUE THREAD

**Issue by j-gibbings** [zalando/postgres-operator#2153]
Please, answer some short questions which should help us to understand your problem / question better?

- registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- AWS Kubernetes
- No
- Bug report

Hello, the 1.8.2 `postgres-operator` distribution seems to have mismatched CRDs. When deploying, via Helm, I observe the following validation errors:
```bash
error validating data: [ValidationError(OperatorConfiguration.configuration): unknown field "enable_team_id_clustername_prefix" in do.zalan.acid.v1.OperatorConfiguration.configuration, ValidationError(OperatorConfiguration.configuration.kubernetes): unknown field "enable_readiness_probe" in do.zalan.acid.v1.OperatorConfiguration.configuration.kubernetes]
```
If I override the CRDs using latest from the Github repo, it deploys just fine. I'm using the CRDs available at https://github.com/zalando/postgres-operator/tree/master/manifests:
  - operatorconfiguration.crd.yaml
  - postgressql.crd.yaml
  - postgresteam.crd.yaml

I've downloaded the postgres-operator-1.8.2.tgz and inspected its `operatorconfigurations.yaml` and confirmed it is missing several fields that are required by the 1.8.2. deployment.

**Comment by FxKu** [comment]
It should now work with the new release. We'll have to find a way to make helm chart from our repo usable (quick fix would be to use tag `latest`)
