### ISSUE TITLE
support to create users and databases on AWS postgres RDS

### ISSUE THREAD

**Issue by pyelulkar** [zalando/postgres-operator#2172]
Hi,

Is it possible to use zalando postgres operator to create users and databases on AWS postgres RDS?
We dont want to create postgresql cluster on k8s. We have it on AWS RDS.
Regards,
Pankaj

**Comment by dmvolod** [comment]
Hi @pyelulkar 

No, this is operator just for the PostgreSQL management on k8s powered by Patroni and doesn't support other providers, i.e. AWS RDS

**Comment by pyelulkar** [comment]
Thanks for quick reply @dmvolod .
