### ISSUE TITLE
Storage for availability zones

### ISSUE THREAD

**Issue by kkrasnov1** [zalando/postgres-operator#2176]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

Is it possible to use different storage in different availability zones or is it possible to specify different classes for master and replica?
I want to use different CEPH clusters in different availability zones.

**Comment by dmvolod** [comment]
Hi @kkrasnov1 
As master and replicas in the cluster are managing by single StatefulSet, its not possible to specify multiple storage classes for that. The single option to spread across availability zones is to specify zone name as `PodAntiAffinityTopologyKey` and have stretched rook configuration across these zones
https://github.com/rook/rook/blob/release-1.10/deploy/examples/cluster-stretched.yaml

**Comment by kkrasnov1** [comment]
Hi @dmvolod 
Is it possible to use only one stretched CEPH cluster?

**Comment by dmvolod** [comment]
> Is it possible to use only one stretched CEPH cluster?

Seems to yes, otherwise volume will not be automatically claimed on each zone

**Comment by kkrasnov1** [comment]
@dmvolod, thank you!
