### ISSUE TITLE
Identical external-dns hostnames for load balancer type services for the master and the master pooler

### ISSUE THREAD

**Issue by vhurtevent** [zalando/postgres-operator#2180]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** local build from master branch
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Kubernetes 1.24.9 on Talos on OpenStack
- **Are you running Postgres Operator in production?** not yet
- **Type of issue?** Bug or feature request

Hello,

I would like to create a cluster with pooler enabled, load balancer and external-dns.
When I enable this through configuration, the load balancer for the master_pooler has the same hostname set by external-dns annotation than the load balance service pointing to the master.
So, when I resolve the hostname through my DNS, I get 2 records for the same name, one to the master service IP, the other one to mater_pooler service.

As I could work only with master_pooler without direct service to the master, I tried to disable load balancer on master with : 

```
  enable_master_load_balancer: false
  enable_master_pooler_load_balancer: true
  enable_replica_load_balancer: false
  enable_replica_pooler_load_balancer: false
```
The master_pooler load balancer service is well created but without the external-dns annotation.

Am I missing something in the configuration to properly disable master_load_balancer and have only master_pooler balancer with external-dns woriking or to set different hostnames to the master_load_balancer and the master_pooler_load_balancer ?

Thank you,

**Comment by FxKu** [comment]
DNS entry should be different. Oversight from #1799
