### ISSUE TITLE
All secrets in all namespaces have new annotation - kopf.zalando.org/last-handled-configuration

### ISSUE THREAD

**Issue by ngnix** [zalando/postgres-operator#2182]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**  - registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal?** Kubernetes 1.24+ , Clouds - AWS and Openstack.
- **Are you running Postgres Operator in production?** yes 
- **Type of issue?** question/bug - i don't known =)

Hi team!

I have a question:

The postgres operator hangs the annotation `kopf.zalando.org/last-handled-configuration` on **absolutely any secrets inside all namespaces**, in this annotation all the content of the secret is **duplicated**. I do not understand why the operator does this for helm release history secrets (for example, the sh.helm.release.v1.keycloak.v1 secret contains the keycloak release deployment history, and annotation who duplicate all base64 release content! ). This behavior greatly increases the size of the ETCD and loads the k8s cluster - how to restrict the operator to use the annotation only on secrets with the name `*.credentials.postgresql.acid.zalan.do` ??

I couldn't find a description of this problem in the documentation.

Thanks!

**Comment by ngnix** [comment]
I calculated number of secrets in my "small" cluster , see bellow:

`$ kubectl  get secrets -A  | wc -l `

`1830`

To be honest, I'm shocked at how much my ETCD size has now grown.

**Comment by dmvolod** [comment]
Hi @ngnix 
Seems to this annotation came from the this code, not postgres operator. Can you validate for another one operator/controller?

https://github.com/zalando-incubator/kopf/search?q=kopf.zalando.org%2Flast-handled-configuration&type=code

**Comment by ngnix** [comment]
Hello @dmvolod ,  I'm sorry for your concern. 

Indeed, the problem was in another operator - synator.

Thanks for your help!
