### ISSUE TITLE
Upgrade to 1.9.0 fails with unknown field

### ISSUE THREAD

**Issue by paveljonak** [zalando/postgres-operator#2220]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.9.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** metal Kubernetes v1.22.12
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

When i am upgrading postgress operator from version 1.8.2 to version 1.9.0 i see error about uknown fields listed bellow with full error message. 

Using helm chart templating and after it deploy to kubernetes cluster using ArgoCD

enable_team_id_clustername_prefix
enable_readiness_probe
pod_antiaffinity_preferred_during_scheduling
share_pgsocket_with_sidecars
master_legacy_dns_name_format
replica_legacy_dns_name_format

error validating data: [ValidationError(OperatorConfiguration.configuration): unknown field "enable_team_id_clustername_prefix" in do.zalan.acid.v1.OperatorConfiguration.configuration, ValidationError(OperatorConfiguration.configuration.kubernetes): unknown field "enable_readiness_probe" in do.zalan.acid.v1.OperatorConfiguration.configuration.kubernetes, ValidationError(OperatorConfiguration.configuration.kubernetes): unknown field "pod_antiaffinity_preferred_during_scheduling" in do.zalan.acid.v1.OperatorConfiguration.configuration.kubernetes, ValidationError(OperatorConfiguration.configuration.kubernetes): unknown field "share_pgsocket_with_sidecars" in do.zalan.acid.v1.OperatorConfiguration.configuration.kubernetes, ValidationError(OperatorConfiguration.configuration.load_balancer): unknown field "master_legacy_dns_name_format" in do.zalan.acid.v1.OperatorConfiguration.configuration.load_balancer, ValidationError(OperatorConfiguration.configuration.load_balancer): unknown field "replica_legacy_dns_name_format" in do.zalan.acid.v1.OperatorConfiguration.configuration.load_balancer]

When I removed "problematic" fields from values.yaml file operator is upgraded successfully

CRD manifest is taken from version 1.9.0 i see these new fields

**Comment by dcardellino** [comment]
Same issue for me. Any update on this?

**Comment by FxKu** [comment]
Thanks @dcardellino . Closing this issue in favor for #2203
