### ISSUE TITLE
How to do cross-cluster / cross-region?

### ISSUE THREAD

**Issue by andres-de-castro** [zalando/postgres-operator#2221]
Hello, looking for general guidance to use this operator in future projects.

I would want to set up a master / slave cluster in one region while also having two read replicas in another region/cluster. I was wondering if features like automatic failover / using patronictl within any of the four clusters would allow us to promote across regions/different clusters?

I surmise there is some dependency on etcd - local to the cluster - which may prohibit me from using the operator.

Thank you!

**Comment by FxKu** [comment]
Have a look at [standby cluster](https://github.com/zalando/postgres-operator/blob/master/docs/user.md#setting-up-a-standby-cluster). It won't get promoted automatically, though.

**Comment by Jan-M** [comment]
Standby cluster is a good answer, using some Wal storage that is accessible or synced between regions.

Be mindful on S3 Region replication used a versioned bucket that might not get properly cleaned up.
