### ISSUE TITLE
Custom labels for PG Pods and/or PVCs

### ISSUE THREAD

**Issue by pschichtel** [zalando/postgres-operator#2222]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.9.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s (k0s)
- **Are you running Postgres Operator in production?** no (not yet)
- **Type of issue?** feature request

I'm using velero for backups in my k8s cluster and I allow it to automatically include all volumes. I then use the `velero.io/exclude-from-backup: "true"` to exclude certain PVCs or pods from the backups. All operators and helm charts except postgres-operator allow me to either specify labels on the pods or on the PVCs. The `Postgresql` CRD already had `.spec.podAnnotations` property, so a `.spec.podLabels` property would feel natural. There could also be a labels property at .spec.volume.labels` for the PVC.

**Comment by pschichtel** [comment]
It seems like either change would eventually need to end up there: https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/k8sres.go#L1419-L1446

**Comment by FxKu** [comment]
We have the following global options for labels:

`cluster_labels`: Will be added to all cluster resources, stateful set, pods, pvcs, services etc
`inherited_labels`: Label keys you allow in the Postgres manifest to get inherited to all child resources.

Sorry for the late reply.

**Comment by pschichtel** [comment]
the 1.11 release of velero might also make this unnecessary as provide a new way to define which objects to include that doesn't require adding a label to everything. Feel free to close this.

**Comment by FxKu** [comment]
Thanks for the feedback :slightly_smiling_face:

**Comment by pando85** [comment]
This problem is still not solved. Could we re-open the issue or should I create a new one?

**Comment by ErezWeiss** [comment]
+1

**Comment by ilyassikai** [comment]
+1

**Comment by mtotone** [comment]
Hello,

Could we re-open this issue please ?
