### ISSUE TITLE
Question: How can I run a replica per node?

### ISSUE THREAD

**Issue by ctoyan** [zalando/postgres-operator#2226]
Hi,

I'm looking to run a master instance on one node and a single replica instance per node, on multiple other nodes.

For example:

- Node A (label a) - master
- Node B (label b) - replica and a web service
- Node C (label b) - replica and a web service
- Node D (label b) and so on...

Also the web service must talk to the replicas via unix socket, for the sake of performance.

**What I've tried:**
I made:  
- one postgresql manifest for the master with nodeAffinity for "label a"
- one postgresql manifest for the replica with nodeAffinity for "label b"
- one postgres-operator deployment with podAntiAffinity to have a single replica pod per node with "label b"
- configmap and service accounts as per tutorials

I managed to get a replica pod per node, but I encountered some problems.

**The problems:**
- I got an authorisation problem for pg_basebackup and had to fix that by manually editing the secret used for authenticating for the master. Not ideal.
- No unix socket file in replicas. I tried setting all unix socket related parameters without success, but that might be related to not starging correctly.
- It all seems like an anti-pattern, but is what I need to setup sadly. I've made it work with "manual" setup from standard k8s resources, but it will be a nightmare to maintain. That's why I picked postgres-operator.

I can paste the configurations, but I'm looking more for guidance about the proper way of doing this, if it's even possible, instead of fixing what I have scrambled so far. My main problem is that I can't differentiate between master and replica pods, in order to set some different affinity/toleration rules on them.

**Comment by ctoyan** [comment]
Ok, so I found the `spilo-role` label, which is set to `spilo-role=master` only on the master pod, which should be enough for me to target them appropriately.

The unix socket problem still persists, but I'll reopen the issue, if I'm not able to fix it.

Closing for now.

**Comment by Jan-M** [comment]
Our operator does not want to make everything possible. You might be better supported if you define your own statefulset sometimes. You can still benefit from Spilo.
