### ISSUE TITLE
Is standalone mode supported?

### ISSUE THREAD

**Issue by Samusername** [zalando/postgres-operator#2229]
Q: Is it ok to run postgres-operator (and Patroni, with spilo) in standalone mode? == numberOfInstances: 1

I can set it in use, of course, but is it ok to run with standalone mode? 
Is standalone mode supported? Or rather: will it **continue** to be supported?

Background:
There are cases where we would like to have High Availability (HA) as an optional functionality. 
( It can be disabled to save HW resources, etc. )
It would be needed to be optional. 
Users could even switch between standalone mode and HA mode, if they want.

Currently, e.g. major version upgrade seems to work in standalone mode also. 
With latest versions of postgres-operator and spilo docker images.

**Comment by Jan-M** [comment]
Yes. You can absolutely run single node clusters if you understand the limits. We support setting min pod count in the operator config for the environment. But that can also be overwritten with an annotation, eg for Standby clusters.
