### ISSUE TITLE
replicaServiceAnnotations does not override external-dns.alpha.kubernetes.io/hostname

### ISSUE THREAD

**Issue by dcardellino** [zalando/postgres-operator#2237]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.9.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report/Issue

The newly introduced replicaServiceAnnotations do not allow to set the annotation
`external-dns.alpha.kubernetes.io/hostname` to a custom value. Every time I set this annotation in the postgresql manifest, it does not get updated in the replica service. That is somehow annoying when you creating your DNS records with external-dns and those are not going to be created at all.

Did somebody tried this?

**Comment by FxKu** [comment]
I see that we have [documented](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#load-balancers-and-allowed-ip-ranges) it wrongly. We set default annotations [after](https://github.com/zalando/postgres-operator/blob/e6fb57a6bd386feba835df1d68151bd3149f5abf/pkg/cluster/k8sres.go#L1904) custom annotation hence overriding them.

You have some control on the DNS name though via [config options](https://github.com/zalando/postgres-operator/blob/master/docs/reference/operator_parameters.md#load-balancer-related-options), though, defining hosted zone, DNS naming template. These are global options though, so I wonder if we should swap the order calling `getCustomServiceAnnotations` after `if c.shouldCreateLoadBalancerForService(role, spec) { }`.

**Comment by dcardellino** [comment]
@FxKu Sorry for the late response. Okay I could try setting those parameters via operator configuration. But would also be nice to have the `replicaServiceAnnotations` working :) 

I will close this for now 👍
