### ISSUE TITLE
what is the right way to sync postgresql dB that has LAG

### ISSUE THREAD

**Issue by vincentchong1** [zalando/postgres-operator#2275]
operator version : postgres-operator-1.7.1
env: production, kubernetes
question: what is the right way to sync postgresql dB ( dlp-postgresql-0 ) that has LAG

`
+ Cluster: dlp-postgresql (7197461503662145605) -------------------+

Member          	Host          	Role   	State  	TL	Lag in MB
---------------------------------------------------------+
dlp-postgresql-0	172.16.245.185	Replica	running	  5	        16
dlp-postgresql-1	172.16.238.156	Leader 	running	  5	          
dlp-postgresql-2	172.16.59.124 	Replica	running	  5	         0
`

**Comment by FxKu** [comment]
Let's follow up in #2205.
