### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by katlol** [zalando/postgres-operator#2286]
Like #2122, #2084, #1906, #1109,

Is ARM (ARM64) support planned for the postgres-operator image? 

Perhaps a github workflow to build the image on GHCR like [spilo](https://github.com/zalando/spilo/blob/master/.github/workflows/publish-ghcr-container.yaml) has could be a solution?

Also for registry.opensource.zalan.do/acid/pgbouncer:master-26 - Where can one find the Dockerfile for it?

**Comment by FxKu** [comment]
Yes. See #2268

**Comment by katlol** [comment]
Thank you. I see you marked this as completed but the PR is still not merged. How can I download the ARM64 image?

**Comment by katlol** [comment]
Hi,

Thank you for the new release!

Unfortunately, the github action did not succeed: https://github.com/zalando/postgres-operator/actions/runs/4756629992/jobs/8453120527

**Comment by urashidmalik** [comment]
postgres operator ui does not have ARM support

**Comment by urashidmalik** [comment]
Created pull request for ARM64 /AMD64 Operator UI Images @Jan-M 
https://github.com/zalando/postgres-operator/pull/2426
