### ISSUE TITLE
Change alpine:3.15 for ARM support in the UI

### ISSUE THREAD

**Issue by badgifter** [zalando/postgres-operator#2303]
I'm sure someone is aware and fixing. If not. 

I'm running on arm64. The operator with the github hosted image works. The UI op does not however. I pulled the repo, changed the alpine dependency to the official docker repo which shows support for arm64, build the docker image, hosted in on docker.io, changed the image dependency in the values.yml under the ui folder, installed with helm, and works. Simple fix, just host the alpine:3.15 with arm and amd support.

**Comment by jurlwin** [comment]
so, strange, but for me, I can't get the operator to install -- possibly because i'm using the helm chart?  I will look to see if I can install the operator manually on ARM64...

**Comment by badgifter** [comment]
Yea, it doesn't support arm since they are using a repo with just amd64 support. I switched back to stackgres for now but would be nice to use eventually.
