### ISSUE TITLE
postgres-operator update from 1.6.3 to 1.10.0 creates new secrets causing authentication failures

### ISSUE THREAD

**Issue by haroonb** [zalando/postgres-operator#2306]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.10.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [Bare Metal K8s]
- **Are you running Postgres Operator in production?** [yes]
- **Type of issue?** [Bug report]

Hello everyone,

I wanted to update out postgres-operator and clusters to the current versions. Currently we're running 1.6.3 with postgres 13.
Upon running some upgrade scenarios I noticed, that the new operator creates secrets with a new naming convention, but doesn't seem to read them from the old secrets. That causes the replicas to be unable to authenticate, since the standby user has another password.

```
~$ kubectl get secrets -n postgres
NAME                                                                   TYPE                 DATA   AGE
postgres.allix-postgres-cluster.credentials                            Opaque               2      7h15m
postgres.allix-postgres-cluster.credentials.postgresql.acid.zalan.do   Opaque               2      49m
postgres.ops-postgres-cluster.credentials                              Opaque               2      7h15m
postgres.ops-postgres-cluster.credentials.postgresql.acid.zalan.do     Opaque               2      49m
standby.allix-postgres-cluster.credentials                             Opaque               2      7h15m
standby.allix-postgres-cluster.credentials.postgresql.acid.zalan.do    Opaque               2      49m
standby.ops-postgres-cluster.credentials                               Opaque               2      7h15m
standby.ops-postgres-cluster.credentials.postgresql.acid.zalan.do      Opaque               2      49m
```
```
~$ for i in secrets; do kubectl get secrets -n postgres "${i}" -ojsonpath={.data.password} && echo ; done
VVZkUjJpbmoweVNJRHhUUUFMdGxXR3Z4eGJ6WHZ2aVljeFIxTVB4cVBla3VJaWV1VHl3MUdzS3JaNU9BMVZGMA==
ak40T1ZaTm1Zd2dkNmppQWlkS0VlNEdwOFM1V0dGN2NhbTZwUHp3d3R0SGlWUjZkTFdkQ0dxNlBuaU5jSFY3Wg==
elc2ZG9idDU2M3hjb2tMbnR0R3BYeW9mU2ZOOTFWUkZ3dWlWRWFPWDJvOVJycXlLYWN5V0c3SGVxamw5cG1qZg==
YXZFaWRWcGZMalZpcGJOVHlQWWdjeE5XNFlybGVGemZuTE5ickoxSEtsS1JsdDREd0NzMk1CUVA2U3ZUSFpPTA==
eFl3WW1xRTZjaVpjMGZGeEhoWTU0dTllaFRFMFhlYUg0Wm9yZGpVTHRXazlsYjFOTEdPbEY0WElBeDRpY3pkdA==
YTBQWEtUSHBrNFhrZWd2UXNBS0o4RjJkNERablZpRkl3c3ZYVlRoTEF5aUdMY0xuMkFtdlliYTZlckxBZ1JVNg==
RmhyMzhhNkZtZHg1QVgydWRCdlh6SXFUcElkQUZWUVhIZ3BENmg1TXZPNmlleHlENXdvTXVjRlNQVFgzNGttbg==
Nnh0UWVmTVF1V1VYSURQdlBjOU9salJZS1FjQWlNMnRKTDdvNXdFeTNMNWhXandXeXR4N2oxN3gwNnNMamw0eg==
```

As you can see above the newly created secrets have other data, than the previous. Is that working as intended and what would be the best way to get the old secrets data into the new secrets?

Thanks for the assistance.

**Comment by FxKu** [comment]
Hm, have we changed the example for `secret_name_template` in #1631 to match the internal default. Don't you use you own custom configmap for your deployments? The configmap file we have in this repo is just an [example](https://github.com/zalando/postgres-operator/blob/master/manifests/configmap.yaml#L146).

**Comment by haroonb** [comment]
Hello, thanks for the Information. No we don't use a custom setting for the template, we just used the default values.
