### ISSUE TITLE
Helm operator upgrade from 1.9.0 to 1.10.0: unknown field "enable_patroni_failsafe_mode"

### ISSUE THREAD

**Issue by voarsh2** [zalando/postgres-operator#2368]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.9.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** 
- K8
- **Are you running Postgres Operator in production?** [yes | no] 
- no
- **Type of issue?** 
- Bug report

When upgrading the Helm Chart to V1.10 I am met with the following error:

```
helm upgrade --history-max=5 --install=true --namespace=posthog --timeout=10m0s --values=/home/shell/helm/values-postgres-operator-1.10.0.yaml --version=1.10.0 --wait=true zalando-postgres-operator /home/shell/helm/postgres-operator-1.10.0.tgz

Thu, Jun 29 2023 11:07:08 am | Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(OperatorConfiguration.configuration.patroni): unknown field "enable_patroni_failsafe_mode" in do.zalan.acid.v1.OperatorConfiguration.configuration.patroni
```

Should be noted "enable_patroni_failsafe_mode" replaces "failsafe_mode"

**Comment by voarsh2** [comment]
I cloned and went to https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/crds/
and did:
kubectl apply -f  operatorconfigurations.yaml
customresourcedefinition.apiextensions.k8s.io/operatorconfigurations.acid.zalan.do unchanged
> k apply -f postgres                    
postgresqls.yaml    postgresteams.yaml  
> k apply -f postgresqls.yaml 
customresourcedefinition.apiextensions.k8s.io/postgresqls.acid.zalan.do unchanged

So, there seems to be no updates? But "enable_patroni_failsafe_mode" isn't accepted.......

**Comment by Lxrdknows77** [comment]
Did you apply upgrade of crd with existing postgresql instance in cluster? I just can guess, that if there is some CR exist that is using oldest field of CRD that update will skipped.

**Comment by Lxrdknows77** [comment]
Or at least try to check what version of CRD is installed now:

k get crd operatorconfigurations.acid.zalan.do | grep enable_patroni_failsafe_mode

**Comment by FxKu** [comment]
@voarsh2 this is a common issue with helm not being able to handle new fields introduced in the CRD. Read #2220 on how to update the CRD and then run the command again.
