### ISSUE TITLE
Can we deploy v1.10.0 on older kubernetes versions (1.19, 1.23 etc)

### ISSUE THREAD

**Issue by pavanreddymaley** [zalando/postgres-operator#2400]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**
registry.opensource.zalan.do/acid/postgres-operator:v1.10.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Kubernetes 
- **Are you running Postgres Operator in production?** [yes | no]
yes
- **Type of issue?** [Bug report, question, feature request, etc.]
We have multiple cluster running on different kubernetes versions like 1.19, 1.23 and 1.27 and we use postgresql operator version 1.7.1 as of now. We are planning to upgrade the operator version to v1.10.0 but as per the https://github.com/zalando/postgres-operator#supported-postgres--k8s-versions support matrix the latest versions of operator (v1.10.0) needs k8s v1.25+ but when I ran locally I am able to deploy the postgresql cluster using v1.10.0 on a k8s version 1.23. So, I would like to know if there is any specific services which will not working if we run operator on K8s 1.23.  Please let us know if it is ok to run v1.10.0 on older kubernetes versions.

**Comment by FxKu** [comment]
Oh, you're right. The matrix is wrong here. It should be 1.21+ because of code for PDBs and CronJobs was moved to v1 with #2008 and #2066 to support 1.25.
