### ISSUE TITLE
Inconsistency in v1.10.* compatibility matrix 

### ISSUE THREAD

**Issue by jeroenjacobs79** [zalando/postgres-operator#2406]
Hi,

When checking the readme.md in the master branch, it lists the following for 1.10.* compatibility:

| Release   | Postgres versions | K8s versions      | Golang  |
| :-------- | :---------------: | :---------------: | :-----: |
| v1.10.*   | 10 &rarr; 15      | 1.21+             | 1.19.8  |

However, when changing to the 1.10.0 tag, it says:

| Release   | Postgres versions | K8s versions      | Golang  |
| :-------- | :---------------: | :---------------: | :-----: |
| v1.10.*   | 10 &rarr; 15      | 1.25+             | 1.19.8  |

(source: https://github.com/zalando/postgres-operator/blob/v1.10.0/README.md)

Which one is correct? I need to upgrade a 1.24 cluster to 1.25, so having the correct compatibility matrix is kinda important.

**Comment by FxKu** [comment]
Fyi: https://github.com/zalando/postgres-operator/issues/2400

1.25 is wrong.
