### ISSUE TITLE
Logical backup v1.8 container image fails to backup postgresql 15 clusters

### ISSUE THREAD

**Issue by Ahmad-Faizan** [zalando/postgres-operator#2506]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.0
- **Where do you run it ?** cloud - Kubernetes - AWS K8s
- **Are you running Postgres Operator in production?** [yes]
- **Type of issue?** [Bug report]

PR for fix: https://github.com/zalando/postgres-operator/pull/2505

**Comment by FxKu** [comment]
Why not upgrade the Postgres Operator version? 1.8.0 is already quite old.
