### ISSUE TITLE
pgvector extension support req

### ISSUE THREAD

**Issue by cybercoder** [zalando/postgres-operator#2518]
**_This is not a bug report._**
pgvector extension ( https://github.com/pgvector/pgvector ), seems to need being supported.

**Comment by FxKu** [comment]
Thanks for raising awareness for pgvector. However, extensions are not handled by the operator but the Postgres image that you use - in our case [spilo](https://github.com/zalando/spilo/pull/896). If you follow the link you will find that support has already been merged and will be available in the next release.

**Comment by drivebyer** [comment]
pg_vector available since ghcr.io/zalando/spilo-15:3.1-p1
