### ISSUE TITLE
Question: When the next release will be available ?

### ISSUE THREAD

**Issue by jean-mercier-hivebrite** [zalando/postgres-operator#2523]
Hello,

I have the same problem as other on PDB the fix is already done and merge inside this PR 
 https://github.com/zalando/postgres-operator/pull/2364/

When do you think this pr will be available i'm using registry.opensource.zalan.do/acid/postgres-operator:v1.10.1 but PR was merge after this release

Thanks for the job already done

**Comment by gytis-ivaskevicius** [comment]
If its old bugs (not introduced since last release) I'd love if release would be done sooner. I am really excited about huge pages implementation

**Comment by stromvirvel** [comment]
@FxKu will the helm chart be updated too? I haven't found the necessary changes, but I'd volunteer to send a PR.

**Comment by ydkn** [comment]
Is there any update?
I'm eagerly looking forward to have `logical_backup_cronjob_environment_secret` released.

**Comment by gytis-ivaskevicius** [comment]
Any update?

**Comment by FxKu** [comment]
As you might have noticed it's taken up a bit more time to bake the new release. On the one hand I'm waiting for Spilo but on the other hand I identified more minor bugs or low hanging fruits to be included in the release. I will be off next week but it first week of March chances are good we can draft a new release.

**Comment by novotnej** [comment]
I don't see why there can't be more than 2 releases a year? The low-hanging fruit could have waited for the next one, while a lot of us are patiently waiting for the pdb_master_label_selector feature flag, which was implemented **6 MONTHS ago**! I don't mean to sound ungrateful, but had we known it would have taken so long to release a fix addressing undocumented behavior, I could have implemented a workaround a long time ago...

**Comment by FxKu** [comment]
It's here: https://github.com/zalando/postgres-operator/releases/tag/v1.11.0

Long overdue. Sorry. The next one will come quicker. I promise.

**Comment by gytis-ivaskevicius** [comment]
Thank you!
I would really appreciate if releases could happen more often in the future to avoid blockers <3
