### ISSUE TITLE
Logical backup v1.10.1 image uses Python 3.6.9

### ISSUE THREAD

**Issue by jpprins1** [zalando/postgres-operator#2562]
- **Which image of the operator are you using?** 
registry.opensource.zalan.do/acid/logical-backup:v1.10.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Openshift
- **Are you running Postgres Operator in production?**
Yes
- **Type of issue?**
Bug

```
$ docker pull registry.opensource.zalan.do/acid/logical-backup:v1.10.1 && docker run -ti --rm --entrypoint python3 registry.opensource.zalan.do/acid/logical-backup:v1.10.1 --version

v1.10.1: Pulling from acid/logical-backup
Digest: sha256:90c0d3a2f85f27cd13170d4368022c209b8df86a2aa58357668f8811a8794929
Status: Image is up to date for registry.opensource.zalan.do/acid/logical-backup:v1.10.1
registry.opensource.zalan.do/acid/logical-backup:v1.10.1

Python 3.6.9
```

Python 3.6 is EOL.
Note: When I build the image using the Dockerfile in this repository I get Python 3.10.12 so maybe it's part of an auto-build pipeline?

**Comment by FxKu** [comment]
Just issued a new release. So this should be resolved.
