### ISSUE TITLE
Security Vulnerabilities Found

### ISSUE THREAD

**Issue by jayantb-95** [zalando/postgres-operator#2573]
- **Which image of the operator/spilo are you using?** 
	registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
	ghcr.io/zalando/spilo-15:3.0-p1

- **Where do you run it ?**
	Bare Metal Openshift

- **Are you running Postgres Operator in production?**
	yes

- **Type of issue?** 
	Security Vulnerability

[rdbms_vulnerabilities_github.xlsx](https://github.com/zalando/postgres-operator/files/14567678/rdbms_vulnerabilities_github.xlsx)

Hi Team Zalando,
We've deployed the postgres-operator in our environment with slight modification of splitting this single repo into 3 different helm charts, mainly CRDs, Operator & the Cluster
We're reported various security vulnerabilities as part of the security scan (excel sheet attached), with reference to the CVE-ID respectively.

**Comment by cyraid** [comment]
Why is he getting thumbs down? Is it because it's just an XLSX attached file, and not just printed here? If that's the case, I agree, it should be listed here or even copy paste in pastebin or the like.

**Comment by DaDummy** [comment]
@cyraid This issue might very well just be a phishing attempt, given that it suggests that an attached Microsoft Office file from an unknown source might contain important information of some urgency.

If it is not, then please just paste the CVEs here or at the very least use some file format that isn't used to spread malware at a regular basis. How about a regular text file or if it is really too much trouble to translate into plain text, export it as CSV.

**Comment by DaDummy** [comment]
It also doesn't help, that this was posted by an GitHub account with what might be a generated name that was created just the day before which also had no public activity since.

Yeah this _really_ looks like phishing.

**Comment by cyraid** [comment]
Yeah, I mentioned I agree with not just posting the results here. The fact that he didn't respond either is very suspicious. Can someone close this issue and state in order to look into it more, post the results in plain text? (re-open issue)
