### ISSUE TITLE
SystemID on failed node

### ISSUE THREAD

**Issue by vavallee-wp** [zalando/postgres-operator#2592]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.11.0
 this one, though the database was originally 1.0
 
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
cloud, hetzner in k3s kubernetes
- **Are you running Postgres Operator in production?** [yes | no]
no
- **Type of issue?** [Bug report, question, feature request, etc.]

I have a failed kubernetes cluster and now have created a new one. When creating a new postgres cluster using the operator I am trying to attach the new node to my original postgres volume. However now the systemid is different, so it will not start.

How can I get this working?

**Comment by vavallee-wp** [comment]
Finally found the answer that google wasn't showing.
running:

patronictl remove <clustername>

on the DB instance pod fixed it.

**Comment by rishiraj88** [comment]
Wow!

@vavallee-wp
