### ISSUE TITLE
Configuration pdb_master_label_selector is not available in OperatorConfiguration CRD

### ISSUE THREAD

**Issue by peterfocko** [zalando/postgres-operator#2594]
Hello, I tried the currently latest version of the operator v1.11.0, which I deploy as a Helm chart. In the release notes it was announced that the pdb_master_label_selector setting is now available: https://github.com/zalando/postgres-operator/pull/2364.

I wanted to use this setting, but the OperatorConfiguration CRD https://github.com/zalando/postgres-operator/blob/v1.11.0/charts/postgres-operator/crds/operatorconfigurations.yaml is currently missing the field to hold the pdb_master_label_selector configuration value.

I think the CRD should have an available attribute to hold the value of this setting, otherwise I have no option to configure it, as the ConfigMap configuration target is already deprecated.

Operator version: v1.11.0
Installation method: Helm chart

**Comment by stromvirvel** [comment]
I have exact the same problem and was actually just about to open an issue. Thank you! 👍

**Comment by stromvirvel** [comment]
I patched the CRD manually and the OperatorConfigurations was updated so that `pdb_master_label_selector` was set to `false`. I removed the PDB and restarted the operator, but the operator still adds the label selector.

[crd.patch](https://github.com/zalando/postgres-operator/files/14746094/crd.patch)

**Comment by Hexcah** [comment]
> I patched the CRD manually and the OperatorConfigurations was updated so that `pdb_master_label_selector` was set to `false`. I removed the PDB and restarted the operator, but the operator still adds the label selector.
> 
> [crd.patch](https://github.com/zalando/postgres-operator/files/14746094/crd.patch)

It worked for me, the pdb was recreated without the `spilo-role: master`

**Comment by peterfocko** [comment]
@FxKu thank you very much for the fix

**Comment by stromvirvel** [comment]
@FxKu I'm not sure how I can make use of that fix. Don't we need a new chart release to deploy the fix?

**Comment by mungo312** [comment]
Any News about a Release ?
