### ISSUE TITLE
Support EKS Pod Identity.

### ISSUE THREAD

**Issue by laiminhtrung1997** [zalando/postgres-operator#2605]
Dear Zalando,

Could you guy please confirm if the spilo can use the [EKS Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html)?
https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html

**Comment by kirek007** [comment]
Hey, It is possible, just create a dedicated service account as a part of configuration:
```
configKubernetes:
  pod_service_account_name : "${pod_service_account_name}"
  pod_service_account_definition: '{"apiVersion":"v1","kind":"ServiceAccount","type":"kubernetes.io/service-account-token","metadata":{"annotations": {"eks.amazonaws.com/role-arn": "${iam_role_arm}" },"name":"postgres-pod"},"secrets":[]}'

 ```
