### ISSUE TITLE
[FEATURE] Extension pg_hint_plan not supported

### ISSUE THREAD

**Issue by rotarur** [zalando/postgres-operator#2607]
It seems that the extension `pg_hint_plan` (https://pg-hint-plan.readthedocs.io/en/latest/installation.html) is not supported. Could you please add it to the list or help me to install it?

**Comment by FxKu** [comment]
The operator is not the right place to ask for supporting certain Postgres extensions. Please, reach out to our [Spilo repo](https://github.com/zalando/spilo).

**Comment by avandras** [comment]
@FxKu you were so fast to close this one ;)  Not that you were wrong.
