### ISSUE TITLE
Timeline for next release ?

### ISSUE THREAD

**Issue by mungo312** [zalando/postgres-operator#2623]
Hi,

do you have a timeline for the next release ? Because of #2594, a release would be highly appreciated. 

Thanks !

**Comment by FxKu** [comment]
Hi @mungo312 
you're right, this fix alone justifies a new release. Some other cool features did get merged after 1.11.0. I would aim for next week to release 1.12.0 then.

**Comment by toabi** [comment]
Sorry for bothering, I know there's always something™ to do, but we'd also highly appreciate a new release.

**Comment by FxKu** [comment]
We released 1.12.2 today :partying_face:
