### ISSUE TITLE
PodDisruptionBudget master label selector Flag not working via Helm

### ISSUE THREAD

**Issue by tmechsner** [zalando/postgres-operator#2626]
- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.11.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Managed kubernetes (None of the big hosters)
- **Are you running Postgres Operator in production?** yes 
- **Type of issue?** Bug report

I was really happy about the new `pdb_master_label_selector` Feature in 1.11.0. However, it doesn't seem to work when set via helm.
I installed the postgres-operator via helm one year ago:
`helm install postgres-operator postgres-operator-charts/postgres-operator`
Recently I upgraded to 1.11.0 and set the flag:
`helm upgrade postgres-operator postgres-operator-charts/postgres-operator --set configKubernetes.pdb_master_label_selector=false --version 1.11.0`

When I do `helm -n default get all postgres-operator | grep pdb_master_label_selector` I get the following:                                                                                            
```
  pdb_master_label_selector: false
  pdb_master_label_selector: false
    pdb_master_label_selector: false
```
Also, I could verify that the new operator image is running with version 1.11.0.
So it looks to me as if my steps above were correct. 
But when I create a new cluster, the newly created pdb still has the  "spilo-role=master" selector.

**Comment by FxKu** [comment]
Hi @tmechsner,
see also https://github.com/zalando/postgres-operator/issues/2594
unfortunately an oversight and already fixed. I should plan a release for next week.
