### ISSUE TITLE
adding / removing users with manifest

### ISSUE THREAD

**Issue by masiir** [zalando/postgres-operator#263]
I have tested the operator a bit and it looks great. I have one (or couple :) issue in my setup; I'm not able to add / remove users with the cluster manifest after it is initially created by the operator. Should this be possible ?

**Comment by Jan-M** [comment]
Adding users and adding database is supposed to work, look into the logs if it is maybe complaining about something.

Removing users and removing databases is not supported and currently from our side also not planned.

**Comment by masiir** [comment]
Thanks for the quick reply! I managed to add users with the manifest by using `added_user: []` , however using simply `adding_user: ` syntax did not do anything (no error in the log either) when updating the manifest.

**Comment by Jan-M** [comment]
Is this still an issue? We are modifying manifests to add more users and databases regularly.

To do this just add new users to:

```
users:
```

And databases to

```
databases:
```

Sections of the YAML manifest.

**Comment by markosiira-arm** [comment]
This is ok. I was a bit unclear in my previous post. Having:

```
users:
  new_user: []
```
worked just fine. Using:
```
users:
   new_user:
```
did not work when adding users.

**Comment by masiir** [comment]
This was resolved by using:
```
users:
  new_user: []
```
using
```
users:
  new_user: 
```
Did not work for some reason

**Comment by FxKu** [comment]
Seems to be resolved. Feel free to reopen anytime.
