### ISSUE TITLE
No ARM64 support on Helm chart

### ISSUE THREAD

**Issue by JoelESvensson** [zalando/postgres-operator#2630]
Tried installing Postgres Operator, using Helm, on a ARM64 cluster but got `exec error`. The latest 1.11 chart was used

**Comment by FxKu** [comment]
In the chart's values.yaml file can you not change the following specs?

```
image:
  registry: registry.opensource.zalan.do
  repository: acid/postgres-operator
```

 to

```
image:
  registry: ghcr.io
  repository: zalando/postgres-operator
```

For the UI and logical-backup the images are as follows:
ghcr.io/zalando/postgres-operator-ui:v1.11.0
ghcr.io/zalando/postgres-operator/logical-backup:v1.11.0

**Comment by JoelESvensson** [comment]
No I didn't! Thank you. Maybe this should be documented somewhere? Or simply be the default `values.yaml`
