### ISSUE TITLE
Helm Chart 1.12.1 not available

### ISSUE THREAD

**Issue by siegenthalerroger** [zalando/postgres-operator#2662]
- **Which image of the operator are you using?** v1.12.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Azure AKS with FluxCD
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug

```
HelmChart 'helm/postgres-operator-helm-postgres-operator' is not ready: invalid chart reference: failed to get chart version for remote reference: no 'postgres-operator' chart with version matching '1.12.1' found
```

**Comment by FxKu** [comment]
We had to fix our arm build pipeline. Sorry. Please take the 1.12.2 image. I've just released the new helm chart.
