### ISSUE TITLE
Postgres Operator Helm Chart Version v1.10.0

### ISSUE THREAD

**Issue by sass1997** [zalando/postgres-operator#2666]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**
ghcr.io/zalando/postgres-operator:v1.10.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
cloud, rke2 k8s version 1.26
- **Are you running Postgres Operator in production?** [yes | no]
yes
- **Type of issue?** [Bug report, question, feature request, etc.]
bug

Since today 21:47 CET. I'm not able anymore to pull the helmchart version v1.10.0. Was there a deletion annoucment of this version?

**Comment by sass1997** [comment]
https://github.com/zalando/postgres-operator/pull/2639

**Comment by FxKu** [comment]
See notes: https://github.com/zalando/postgres-operator/releases/tag/v1.12.2

Please, use v1.10.1 or update.
