### ISSUE TITLE
UI: can't specific a namespace. The namespace field is missing.

### ISSUE THREAD

**Issue by droslean** [zalando/postgres-operator#2675]
![image](https://github.com/zalando/postgres-operator/assets/8650912/5db7ba9a-8a38-45f1-8924-8274ce608073)

Its either a BUG or https://postgres-operator.readthedocs.io/en/latest/operator-ui/ is out dated.

**Comment by FxKu** [comment]
Change [this setting](https://github.com/zalando/postgres-operator/blob/7cdc23fff05dd0fbd0fbe478b874f10292e618a5/ui/manifests/deployment.yaml#L48) to * you should be able to set the namespace. Docs are indeed incomplete here.

**Comment by droslean** [comment]
Thanks @FxKu . I guess in some point the docs need to be updated.
