### ISSUE TITLE
The use of `x-kubernetes-preserve-unknown-fields` stops Terrafrom from updating manifests in-place causing cluster wipes

### ISSUE THREAD

**Issue by EraYaN** [zalando/postgres-operator#2676]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.11.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Azure AKS
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Enhancement request

So this is based on https://github.com/hashicorp/terraform-provider-kubernetes/issues/1841#issuecomment-1254825692

Anyway any change to the manifests in Terraform will replace the postgresql crd causing the data to be wiped and the server to be empty.

This seems to be used in a couple of places like (6 total in that file):
https://github.com/zalando/postgres-operator/blob/37d69934394b960ea235aab963fac2650ff91f54/charts/postgres-operator/crds/postgresqls.yaml#L206
and 
https://github.com/zalando/postgres-operator/blob/37d69934394b960ea235aab963fac2650ff91f54/charts/postgres-operator/crds/postgresqls.yaml#L105

Both of these should have known specs and it would be very useful if they could be fully specced, which would resolve any problems with programs like terraform or pulumi that require fully specified schema's to do their job and use in-place updates.

An alternative would be to make the operator tolerant to replacement of CRD resources of course, but that feels a bit less clean.

**Comment by FxKu** [comment]
Hi,
please, to provide a PR. I will not spend time on this except reviewing. One problem with full specs is that we need to track changes in K8s, because the CRDs are not generated automatically like when using tools such as kubebuilder.

**Comment by EraYaN** [comment]
We are migrating away from this operator, so this can be closed.
