### ISSUE TITLE
RBAC Issue : configmaps "postgres-operator" is forbidden (GKE)

### ISSUE THREAD

**Issue by eaydogan** [zalando/postgres-operator#268]
Hi,
I have problem with rbac. 

`kubectl create namespace test`
`kubectl create -f manifests/configmap.yaml -n test`
`kubectl create -f manifests/postgres-operator.yaml -n test`

` kubectl get pods -n test`

NAME                                 READY     STATUS             RESTARTS   AGE
postgres-operator-686dfdc7fc-k42j2   0/1       CrashLoopBackOff   4          3m

`kubectl logs postgres-operator-686dfdc7fc-k42j2 -n test`

panic: configmaps "postgres-operator" is forbidden: User "system:serviceaccount:test:operator" cannot get configmaps in the namespace "test"

goroutine 1 [running]:
github.com/zalando-incubator/postgres-operator/pkg/controller.(*Controller).initOperatorConfig(0xc42049e6c0)
	/root/go/src/github.com/zalando-incubator/postgres-operator/pkg/controller/controller.go:93 +0x551
github.com/zalando-incubator/postgres-operator/pkg/controller.(*Controller).initController(0xc42049e6c0)
	/root/go/src/github.com/zalando-incubator/postgres-operator/pkg/controller/controller.go:120 +0x54
github.com/zalando-incubator/postgres-operator/pkg/controller.(*Controller).Run(0xc42049e6c0, 0xc42006c780, 0xc42019a000)
	/root/go/src/github.com/zalando-incubator/postgres-operator/pkg/controller/controller.go:212 +0x40
main.main()
	/workspace/cmd/main.go:62 +0x2a3

for ClusterRole I used this settings ... 

`https://github.com/zalando-incubator/postgres-operator/issues/233`

i'm using master branch...

**Comment by eaydogan** [comment]
After few additional steps... postgres-operator is now running...

Current settings works without error when use GKE but **dedicated clusters you need additional steps.**

```
1) role and role binding
2) cluster role and cluster role binding
3) pvc
```

I can document steps and send pull request if  this help someone.

**Comment by gsaslis** [comment]
@eaydogan please do, if you have a chance...

**Comment by FxKu** [comment]
Seems to be related to #274. Closing this issue. If you can still recall your steps, feel free to add a PR that explains running the operator on GKE.
