### ISSUE TITLE
replicaCount not being respect

### ISSUE THREAD

**Issue by zyue110026** [zalando/postgres-operator#2707]
We have noticed an instance of incorrect helming in one of your Kubernetes configuration files. Hardcoded or default configuration values in the template are considered anti-pattern and configurable values in the values.yaml file are not being respect, resulting in user-provided configurations never being applied. Additionally, we provide anecdotal evidence from [trivy-operator#729](https://github.com/aquasecurity/trivy-operator/issues/729) regarding the incorrect helming defect.

[replicaCount](https://github.com/zalando/postgres-operator/blob/73f72414f65690fe38d6892559f085e9e1f3f33d/charts/postgres-operator-ui/values.yaml#L5) does not take effect when changed to a value other than 1. This issue arises due to replicaCount value is hardcoded in deployment.yaml file:

https://github.com/zalando/postgres-operator/blob/73f72414f65690fe38d6892559f085e9e1f3f33d/charts/postgres-operator-ui/templates/deployment.yaml#L12

Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**

ghcr.io/zalando/postgres-operator:v1.12.2

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Bare Metal K8s
- **Are you running Postgres Operator in production?** [yes | no]
no
- **Type of issue?** [Bug report, question, feature request, etc.]
Bug report
Some general remarks when posting a bug report:
- Please, check the operator, pod (Patroni) and postgresql logs first. When copy-pasting many log lines please do it in a separate GitHub gist together with your Postgres CRD and configuration manifest.
- If you feel this issue might be more related to the [Spilo](https://github.com/zalando/spilo/issues) docker image or [Patroni](https://github.com/zalando/patroni/issues), consider opening issues in the respective repos.

**Comment by FxKu** [comment]
I wonder why this is even configurable? What do we gain by setting the replica count bigger than 1? Availability? It's a simple front end application, after all.

**Comment by zyue110026** [comment]
It is because you have a https://github.com/zalando/postgres-operator/blob/ce15d10aa32899e3cd5b0a430991b7ac5a31c8cb/charts/postgres-operator-ui/values.yaml#L5 in your values.yaml file, which should be considered configurable value, if configure the replica count number is meaningless, why you add this value in values.yaml file.

**Comment by FxKu** [comment]
The helm charts were for the most part provided by people from the OS community. There might inconsistencies here an there. At Zalando we don't use them so we don't care too much about them.

**Comment by zyue110026** [comment]
I see, but I still want to collect the practitioners' perceptions of the incorrect helming defect for our research purpose. Do you think it is a bug and will you fix it if you are using that helm chart?
