### ISSUE TITLE
Logical backup secret results in duplicate environment keys

### ISSUE THREAD

**Issue by nickmansrob** [zalando/postgres-operator#2716]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** Helm: postgres-operator:v1.12.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K3s
- **Are you running Postgres Operator in production?** almost
- **Type of issue?** [Bug report, question, feature request, etc.] Bug report

When generating the cronjob for the logical backup when using Azure, the account key gets fetched form the `OperatorConfiguration`, even when it's empty. This happens [here](https://github.com/zalando/postgres-operator/blob/7c7aa969350bef67d0283d93589499ae3d114edb/pkg/cluster/k8sres.go#L2492-L2495). I pass it through a SOPS encrypted secret, and this results in a duplicate environment entry in the cronjob with following kubernetes warning:
```
Warning: spec.template.spec.containers[0].env[16]: hides previous definition of "LOGICAL_BACKUP_AZURE_STORAGE_ACCOUNT_KEY"
```
Everything still works so this is a low priority bug.

A check should be added for Azure and GCP in the same way this is done for AWS.

I can fix this in a PR if needed and if I find the time.

**Comment by FxKu** [comment]
A PR to fix it is more than welcome :+1:

**Comment by FxKu** [comment]
Fix has been merged
