### ISSUE TITLE
Instructions on how to run on GKE

### ISSUE THREAD

**Issue by hjacobs** [zalando/postgres-operator#274]
It would be awesome to have a complete tutorial on how to run the PostgreSQL Operator on Google's Container Engine (GKE).

I would propose having a Markdown tutorial like External DNS provides for GKE: https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/gke.md

**Comment by aamederen** [comment]
I have tested it and the only extra step required was adding my account as a cluster admin to the kubernetes cluster. Otherwise, I would get permission errors during service account creation.

This does the trick:
```
kubectl create clusterrolebinding me-as-admin --clusterrole=cluster-admin --user=myemail@myorg.com
```

**Comment by hjacobs** [comment]
@aamederen do you want to contribute a tutorial for GKE incl. cluster creation and backup to object storage?

**Comment by aamederen** [comment]
@hjacobs no promises but I can type down the steps when I go through it once again.

**Comment by FxKu** [comment]
Recently, I came across this nice [guide](https://www.redpill-linpro.com/techblog/2019/09/28/postgres-in-kubernetes.html) to run the operator on GKE. No too different from our docs, I think. Closing this issue for now.
