### ISSUE TITLE
Orphan ClusterRole dployed

### ISSUE THREAD

**Issue by zhangyue110026** [zalando/postgres-operator#2752]
We have noticed three instances of an orphan resource in some of your Kubernetes configuration files. Deploying Kubernetes resources that are not being actively used or referenced by any other resources in the cluster can lead to orphan resources. These orphan resources consume unnecessary resources and can potentially cause confusion or clutter within the cluster. Additionally, we provide anecdotal evidence from [htopolvm-topolvm#484](https://github.com/topolvm/topolvm/issues/484) regarding the orphan resource defect.

## What happened:
cluster role postgres-pod does not have any role binding:
https://github.com/zalando/postgres-operator/blob/e71891e2bd704084e9d0bcfee864b61cec0cf20b/manifests/operator-service-account-rbac.yaml#L249

https://github.com/zalando/postgres-operator/blob/e71891e2bd704084e9d0bcfee864b61cec0cf20b/manifests/operator-service-account-rbac-openshift.yaml#L241

https://github.com/zalando/postgres-operator/blob/2e398120d2d0b3bb2b8bb239c6d49011ebe37e88/charts/postgres-operator/templates/clusterrole-postgres-pod.yaml#L5

## What you expected to happen:
cluster role postgres-pod should have a role binding, otherwise it is a orphan resource. Or delete postgres-pod to avoid deploy orphan resource.

Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** ghcr.io/zalando/postgres-operator:v1.13.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** [no]
- **Type of issue?** [Bug report]

Some general remarks when posting a bug report:
- Please, check the operator, pod (Patroni) and postgresql logs first. When copy-pasting many log lines please do it in a separate GitHub gist together with your Postgres CRD and configuration manifest.
- If you feel this issue might be more related to the [Spilo](https://github.com/zalando/spilo/issues) docker image or [Patroni](https://github.com/zalando/patroni/issues), consider opening issues in the respective repos.

**Comment by FxKu** [comment]
It’s not an orphaned role. Patroni uses it and it’s referenced in the [operator configuration](https://github.com/zalando/postgres-operator/blob/c25dc57b9614df4a89e08c9c766b6f6ee64fb41f/manifests/postgresql-operator-default-configuration.yaml#L103). Not easy to spot admittedly.
