### ISSUE TITLE
question regarding k8s 1.30 compatibility

### ISSUE THREAD

**Issue by DonOtuseGH** [zalando/postgres-operator#2771]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**
  - ghcr.io/zalando/postgres-operator:v1.13.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
  - Bare Metal K8s
- **Are you running Postgres Operator in production?**
  - yes
- **Type of issue?**
  - Question

Hello,

we'd like to update our k8s clusters (`1.28` => `1.29` => `1.30`) and we are wondering if postgres-operator version `1.13.0` is compatible with k8s version `1.30`? Your compatibility matrix says `1.27+`, but does that really include `1.30`?
I found he following pull request that deals with this compatibility and it is merged into `main` branch, but not included in `1.13.0`. That's the reason why the question came up...

Thank you for looking into this!

**Comment by FxKu** [comment]
@DonOtuseGH yes it's compatible. We are using it on 1.30.
