### ISSUE TITLE
Warn about a possible mismatch for system role passwords in a newly created cluster

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/postgres-operator#288]
Scenario:

- Someone removes the old cluster and the PVC stays there (perhaps the removal has been performed manually)
- New cluster is initialized with the same name as the previous one.

The operator will generate random passwords for both superuser and replication roles and put them in the secrets; however, since the PVCs already exist it will not be able to connect to the new cluster, as system roles are initialised by Patroni during the bootstrap of the first cluster member and those steps are bypassed if the data directory is already there.

In the situation described above, Patroni on one of the nodes will complain about inability to connect as a standby, while the other node will start complaining about the system ID mismatch.

We need to at least emit a warning in the operator, describing a possible problem, upon encountering such a cluster.

**Comment by alexeyklyukin** [comment]
Note that the operator will not remove secrets for the superuser and the standby user when deleting a cluster, so the issue above is more likely to occur when the cluster is deleted manually (perhaps because the operator was not running at the time of deletion of the manifest).

**Comment by FxKu** [comment]
This is long obsolete. Operator does delete secrets by now.
