### ISSUE TITLE
support imagePullSecrets

### ISSUE THREAD

**Issue by theRealWardo** [zalando/postgres-operator#318]
We keep the majority of our images private on Docker Hub and right now the operator does not support running those images.

I'd like to propose adding support for `imagePullSecrets` in the cluster spec in the same way it exists for other Kubernetes objects.

https://github.com/theRealWardo/postgres-operator/pull/1 has a sketch of this but it is based on #308 - I'm happy to make that change a separate PR and have it merged first if there's much more community debate on the sidecar support.

**Comment by Jan-M** [comment]
I do understand the need and use case - although I am wondering if indeed the operator needs this.

@hjacobs @mikkeloscar How do we do this? We also have a private registry.

**Comment by mikkeloscar** [comment]
We don't use the `imagePullSecrets` but instead give docker access by putting credentials in `/root/.docker/config.json` on every node.

We had too many problems with `imagePullSecrets` in the past to use it. e.g. if you create a new namespace, then there is a race condition when a new pod start with the default serviceAccount if the `imagePullSecret` has not yet been set on the serviceAccount.

It ofc. depends on how you use them, if you always have serviceaccounts ready with `imagePullSecrets` then it's not a problem and I guess postgres-operator already supports setting a custom serviceAccount? Putting `imagePullSecrets` on every pod seems like a huge hassle, but since it's a Kubernetes feature there is some argument for supporting it I guess.

**Comment by Jan-M** [comment]
Yes, we do allow specifying the service account that is created when a new cluster is created in a new namespace and that is then used by the pods in the statefulset. Alternatively we allow specifying the name of an existing service account to be used.

Does this cover everything that is needed?

**Comment by theRealWardo** [comment]
I am a bit confused. I think you are not talking about [Kubernetes Service Accounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) but rather cloud platform Service Accounts?

the [official documentation for how to handle private images](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) says to use `imagePullSecrets` and that is what we do at our company.

I understand that you can avoid this via node level configuration. we try to minimize our node level configuration as the management system there is not as matured as our system for managing our Kubernetes application/deployment manifests.

in order for us to use this project I either need to get our entire team to change their ways, or make a small patch to this project that may be useful to others as well.

**Comment by mikkeloscar** [comment]
@theRealWardo I'm talking about Kubernetes serviceaccounts: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account

**Comment by theRealWardo** [comment]
@mikkeloscar awesome! I had literally no idea that support existed. I imagine a lot of Kubernetes users are in the same position as me given how hidden this is in the docs.

I feel there is an objection to supporting `imagePullSecrets` for a cluster - is that an accurate characterization of what is being said?

**Comment by Jan-M** [comment]
No, not if this is needed. But I wanted to make sure that the service account is not working for you, as this seems like the better solution. Prefering to rely on K8S objects and features.

**Comment by theRealWardo** [comment]
"needed" is a strong word. should there be one way to do things? if so, then no this isn't needed. should the operator be simple and easy to use while closely following other Kubernetes patterns? if yes, then I would ask the team to be receptive to this feature request.

once again, using service accounts would be a change of the way that our team has been doing things and it is not what I read in a "simple" reading of the Kubernetes docs.

**Comment by Jan-M** [comment]
Please go ahead with the imagePullSecrets as you need them, sounds like more users may need this and as this is all "optional" for the user it should be ok.

**Comment by FxKu** [comment]
Seems to be solved. Feel free to reopen for more questions in this direction.

**Comment by deepd** [comment]
May be helpful for someone in future: https://github.com/zalando/postgres-operator/issues/546#issuecomment-733284774
