### ISSUE TITLE
Allow for custom annotations

### ISSUE THREAD

**Issue by angapov** [zalando/postgres-operator#329]
We are running [Istio](https://istio.io/) in Kubernetes with automatic sidecar injection. For some services like Postgres we do not use Istio injection. This is configured through pod template annotations. It would be good if it is possible to add some custom annotations on Postgres StatefulSet and pod template in cluster spec.

**Comment by alexeyklyukin** [comment]
@angapov that is not terribly hard to achieve (essentially add a parameter to the operator and/or per-cluster configuration and. then modify the `generateStatefulSet` to add those annotations (and `compareStatefulSetWith` to take it into account when deciding whether to re-create pods). We may do it in the future, but if you want to speedup thing pull-requests are welcome!
