### ISSUE TITLE
Enable schema validation for postgresql CRD

### ISSUE THREAD

**Issue by sdudoladov** [zalando/postgres-operator#388]
A few misconfigurations may be catched by [k8s-native CRD validation](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation) early

**Comment by gane5hvarma** [comment]
Hi @sdudoladov I would like to work on this issue.by the way im new to kubernetes and i would like to work on it.

**Comment by Jan-M** [comment]
@gane5hvarma PRs are always welcome ;)

**Comment by yujunz** [comment]
Absolutely needed. Any progress so far?

For example, I'd like the change being rejected if it has no effect. Otherwise the actual status will deviate from the spec.

```
postgres-operator-8886ccf-nqdvf:postgres-operator time="2019-07-09T07:11:40Z" level=warning msg="postgresql version change(\"10\" -> \"9.6\") has no effect" cluster-name=postgres-operator/hl-dev pkg=cluster worker=2
```

**Comment by Jan-M** [comment]
We are working on syntax/schema validation now. See referenced PR.

We do not yet intend to include checking "semantic" meaning and valid transitions. Which is also not supported I think by CRD schema.

And ultimately the 9.6 to 10 transition could be implemented by someone in the Docker image.

**Comment by yujunz** [comment]
How does the operator determine some modifications `has no effect` at the moment?

**Comment by Jan-M** [comment]
I think this particular change is hard coded to inform users that this is not how major version upgrade works. (Spilo does it via Clone/Restore in Custom Bootstrap).

**Comment by yujunz** [comment]
> And ultimately the 9.6 to 10 transition could be implemented by someone in the Docker image.
> (Spilo does it via Clone/Restore in Custom Bootstrap).

A bit confused on current status. Is it supported (even with some adhoc operations) or not?

**Comment by Jan-M** [comment]
The Postgres operator itself does not really support/do this. Migrating to a new major version in place is not supported right now and we are also not working on it right now.

What is supported is upgrading the major version when doing a clone or restore from AWS S3 e.g.

This is implemented in Spilo during the custom bootstrap. So we bootstrap from S3 backup. Upgrade single node and only then continue bootstraping replica nodes.

Using clone/restore is a convenient and safe flow that is still easier than dump restore.

**Comment by yujunz** [comment]
> What is supported is upgrading the major version when doing a clone or restore from AWS S3

This is good enough since major version upgrade is not that often.
