### ISSUE TITLE
Option to run containers in non-privileged mode

### ISSUE THREAD

**Issue by jpiper** [zalando/postgres-operator#395]
As far as I can see from 19dfa0c2b025a6aa9d260df13b16b7754110d01c, privileged access is used for AWS volume resizing.

However, I don't want to give my database containers privileged access so it would be great if this could be configurable.

(cc @abh)

**Comment by Jan-M** [comment]
This should go along with relying on K8S now being able to do the volume resize via "api"/"statefulset change" I believe. So is in fact not required in the future.

**Comment by aaroniscode** [comment]
Looking to run this operator in an environment with PodSecurityPolicies that restrict privileged containers. Is this still needed?  If it is, will you accept a pull request to make it optional?  Would like some guidance on how you would like to present this configuration.

**Comment by jpiper** [comment]
I had success running this without privileged mode

**Comment by aaroniscode** [comment]
@jpiper How did you run without privileged mode? As far as I can tell it's hard-coded and not able to be disabled short of modifying the source code.

**Comment by redbaron** [comment]
Privileged mode is use to do live volume resize. If you don't need this
feature it is safe to remove that part of the code like we did.

**Comment by jpiper** [comment]
Yep, had to just disable it in the code and rebuild the image

**Comment by hjacobs** [comment]
Can we make this a config option (so people don't need to rebuild the image)? Running non-privileged should IMHO be the default.
