### ISSUE TITLE
PGBouncer integration?

### ISSUE THREAD

**Issue by jens-totemic** [zalando/postgres-operator#412]
I was wondering what you think about supporting pgbouncer in the postgres operator. Would be great to have it integrated so failover could be made more seemless with the PAUSE function.
It looks like Spilo is already able to configure it through ENV variables. As far I can tell, what would be needed is exposing the PGbouncer ports through the services and possibly configuring the user needed for authentication.

**Comment by CyberDem0n** [comment]
Yes, spilo is able to start pgbouncer, but it won't work as you expect from it, because it will work in the same container with Patroni and postgres. If the master pod dies, pgbouncer will also die and as a result you won't be able to PAUSE.
On k8s that should be done differently. The pgbouncer should be deployed independently from postgres pods. In that case the operator can issue PAUSE before doing the switchover.

**Comment by jens-totemic** [comment]
Thanks @CyberDem0n for the quick response! You are right, it would be better to deploy pgbouncer as a separate container. Is the operator already providing some kind of callback mechanisms we could use to trigger behaviour upon failover (or other lifecycle events)? In the past, I used patroni with `etcd`, having a `confd` intance listening to `etcd` changes to the leader and rewriting the pgbouncer configuration files. Now running in kubernetes, the current leader is stored in the endpoints object. Is there a good way of listening to change events with that mechanism?

**Comment by Jan-M** [comment]
Reopening this, for the most basic feature idea, for apps without pooling or incidents where the client is clearly misbehaving.

### Idea
```
  enablePGBounder: true
```

Creates another service, and a deployment with 1 pod running a pgbouncer in front of the master service forwarding authentication? (does this work for md5 and the new method, no pg bouncer expert). (<team>-<name>-pgbouncer.src.cluster.local).

We would need though to find a decent pg bouncer image or our own.

Maybe a feature for a PR for someone curious.

**Comment by dominicgunn** [comment]
@Jan-M, do you know if any work was ever done on this? We would love to try out this out operator, but our older applications rely on pooling from pgbouncer, we can't really do without it.

Is there a known way we can force it on, given any of the currently available options?

**Comment by jamessewell** [comment]
Any progress here? Even if I just want the dumb Spilo config (PGBouncer on master pod only) is there a way to turn that on from the operator?

**Comment by Jan-M** [comment]
Nope, we did not do any work on this. Don't have it on our todo list either.

It should still be relatively straight forward though to setup pgbouncer in front of the service.

**Comment by FxKu** [comment]
pgBouncer support was merged today, therefore I'm closing this issue
