### ISSUE TITLE
Ensure operator moves pods from a decommisioned nodes

### ISSUE THREAD

**Issue by sdudoladov** [zalando/postgres-operator#429]
The operator supposedly gets stuck when moving master pods form a decommissioned node.
We need to reproduce and investigate this situation, which cannot be done in `minikube` cause `minikube` is a single node k8s cluster. 

one situation where it is reported to happen is the decommission of multiple nodes. The operator apparently ignores a few decommission nodes after removing master pods / finding no pods to remove from the 1st one

The current solution is simply to restart the operator pod.

**Comment by zerg-junior** [comment]
#389 adds more logs for node decommissioning

**Comment by zerg-junior** [comment]
The reason for this behavior is the race condition when replica pods run on another nodes being decommissioned.

sequence of events:

1. A replica gets respawned on another Ready node.
2. Shortly afterwards the operator attempts failover from the master to a replica, however replica is still not ready
3. failover fails, operator reports an error and never attempts another failover

Current resolution: delete the operator pod. The new operator instance will notice unhealthy node again and issue yet another failover.

the problem stems from the [masterCandidate](https://github.com/zalando-incubator/postgres-operator/blob/e1ed4b847d527104fab7edc6b246cf6d67d77fd8/pkg/cluster/pod.go#L152) method that:

1. [waits for the ready label](https://github.com/zalando-incubator/postgres-operator/blob/e1ed4b847d527104fab7edc6b246cf6d67d77fd8/pkg/cluster/pod.go#L155) that is attached very early (replica may for instance still be replaying WAL) We shall work with the Patroni API instead
2. [selects a new master candidate at random](https://github.com/zalando-incubator/postgres-operator/blob/e1ed4b847d527104fab7edc6b246cf6d67d77fd8/pkg/cluster/pod.go#L179). That randomly selected pod may not be the healthiest one.


also, the operator should retry switchover multiple times after some sleeping
