### ISSUE TITLE
Change to replication slots are not reflected

### ISSUE THREAD

**Issue by redbaron** [zalando/postgres-operator#447]
I created cluster using `manifest/complete-postgres-manifest.yaml`, edited like following:

```
diff --git a/manifests/complete-postgres-manifest.yaml b/manifests/complete-postgres-manifest.yaml
index c5f80f3..920ea64 100644
--- a/manifests/complete-postgres-manifest.yaml
+++ b/manifests/complete-postgres-manifest.yaml
@@ -44,10 +44,6 @@ spec:
     slots:
       permanent_physical_1:
         type: physical
-      permanent_logical_1:
-        type: logical
-        database: foo
-        plugin: pgoutput
     ttl: 30
     loop_wait: &loop_wait 10
     retry_timeout: 10
```

then reapplied it.

postgres-operator rolled cluster (starting from replicas) , but new master remains complaining about postgres replication slots:

```
2019-01-09 23:53:29,381 INFO: Lock owner: acid-test-cluster-1; I am acid-test-cluster-1
2019-01-09 23:53:29,389 ERROR: Failed to create logical replication slot 'permanent_logical_1' plugin='pgoutput'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql.py", line 1617, in sync_replication_slots
    (name, value['plugin'], name))
psycopg2.OperationalError: logical decoding requires wal_level >= logical

2019-01-09 23:53:29,389 INFO: no action.  i am the leader with the lock
```

Does it need rolling cluster? Can it dynamically update Patroni config ? In your view, is it Patroni or operator who should be calling `pg_drop_replication_slot` ?

It might as well be a Patroni bug, let me know if I should reopen it there.

**Comment by redbaron** [comment]
`patronictl edit-config` and then removing replication slots does the trick. What is your view on what postgres-operator should be doing here? 

Do you agree that it should not trigger roll if patroni config changes on a bootstrapped cluster?

**Comment by stang** [comment]
We're having the same issue here.

It seem that once a cluster is created by the operator, if you update the `postgresql` object (a.k.a _cluster manifest_), the operator does update the `SPILO_CONFIGURATION` in the `StatefulSet`. 

The pod restarts, but it seem that nothing changed.

When checking using `patronictl show-config` the replication slots are not reflected, and it is indeed confirmed when checking directly in the DCS (in my case, in the `<cluster-name>-config` endpoint's annotation).

Any idea? @sdudoladov do you have an opinion on that?

**Comment by stang** [comment]
I had a quick look at the source code, and once we agree on the approach, I'd be happy to start working on a fix.

Currently:
- the operator is unconditionally including and updating the `patroni.slots` settings in the `SPILO_CONFIGURATION`
- my understanding is that this is taken in account **only** when the `spilo` image bootstrap the cluster for the first time
- therefore, we can not add nor delete `slots` via the operator once the cluster has been created

The proposed behaviour would be to:
- reflect the `patroni.slots` settings in the `SPILO_CONFIGURATION` when the cluster manifest is initially created and freeze this value (no updates to avoid unnecessary pod restarts)
- when the cluster manifest includes a change of slots, use the same method approach as for the databases:
  - apply changes directly on the postgres cluster, by connecting to the database and issuing SQL commands
  - reflect the change in the DCS so they're persisted

Does this make sense?

If so, it brings the following points:
- for other postgresql objects (eg: databases, users, etc) it seem that the current choice is to _append only_. Which means that the operator can create/update these objects but never delete them. I believe that for the slots, automatically removing a slot via the operator should be possible.
- it's already the case, but I'd like it to be explicitly acknowledged: we accept that the cluster manifest (`postgresql` CR) and the `SPILO_CONFIGURATION` variable **does not** always reflect the real configuration of the cluster. The real configuration is still mirrored in the DCS.

**Comment by Jan-M** [comment]
cc @CyberDem0n

**Comment by CyberDem0n** [comment]
> my understanding is that this parameter is taken in account only when the spilo image bootstrap the cluster for the first time

Correct

> - when the cluster manifest includes a change of slots, use the same approach as for managing the roles/databases:
>   - apply changes directly on the postgres level, by connecting to the database and issuing SQL commands
>   - reflect the change in the DCS so they're persisted
>
> Does this make sense?

Nope, one should use Patroni [REST API](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html#rest-api) for such changes

**Comment by Jan-M** [comment]
We def. have an issue around rolling upgrades and the patroni api calls. Seems for changing max connections we do the call to patroni api and still do a rolling upgrade as pod spec changes. so there is in general some todos left.

**Comment by FxKu** [comment]
With #1535 merged, changes under `Patroni` section will be reflected. Closing this issue.
