### ISSUE TITLE
use finalizers avoid losing deletions

### ISSUE THREAD

**Issue by redbaron** [zalando/postgres-operator#450]
When Postgres CR is deleted it triggers deletion routine, which might not end completely due to crash, misconfiguration or intermittent Kubernetes errors. To be able to finish cleanup on restart, Postgres CR should remain present up until deletion is completed.

Kubernetes solutions for that is to use [finalizers](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers) where resources is still present and queryable until all finalizers are completed. This would allow operator to continue cleanup routine on restart

**Comment by FxKu** [comment]
related to #387

**Comment by frittentheke** [comment]
@redbaron  thanks for opening this ... I was just about to suggest this myself ;-)

Another use case for finalizers would a final basebackup or logical backup before the cluster is annihilated by the operator for good -  Just like AWS does with their final snapshot upon deletion of and RDS instance: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_DeleteInstance.html
