### ISSUE TITLE
Optionally enable init/sidecar containers

### ISSUE THREAD

**Issue by sdudoladov** [zalando/postgres-operator#464]
The operator currently support running sidecar and init containers side-by-side with Postgres containers. For maintenance reasons , we would like to be able to enable/disable these features per k8s cluster. The task is to:
1. Add relevant toggles to the operator configuration (CRD and configmap) similar to existing boolean options such as `enable_shm_volume`. 
2. Log a warning if a user attempts to use init/sidecars containers when this feature is disabled.

**Comment by redbaron** [comment]
IMHO it should be a hard error and not Postgres resources to be created

**Comment by sdudoladov** [comment]
we also may need to restrict the ability to re-write tolerations/timeouts in a similar fashion

> IMHO it should be a hard error and no Postgres resources to be created

Good point :+1:  Sadly in the present operator codebase there is no single place  where we can validate all the (un)desired properties of the PG manifest, so to make it a hard error we can, for instance, put a separate check in the beginning of Sync and Create methods.
