### ISSUE TITLE
Correctly set k8s labels in the operator

### ISSUE THREAD

**Issue by sdudoladov** [zalando/postgres-operator#471]
Spilo currently complains at startup:

> 2019-01-25 13:41:52,512 - bootstrapping - WARNING - could not parse kubernetes labels as a JSON: Expecting value: line 1 column 1 (char 0), reverting to the default: {"application": "spilo"}

**Comment by yusufgungor** [comment]
I have the same issue. What am i doing wrong? Thanks.

```
2019-12-10 17:12:15,221 - bootstrapping - WARNING - could not parse kubernetes labels as a JSON: Expecting value: line 1 column 1 (char 0), reverting to the default: {"application": "spilo"}

```

**Comment by FxKu** [comment]
@yusufgungor are you using the `v1.2.0` image of the operator. Could be, that this is already fixed in the `latest` version

**Comment by abh** [comment]
@FxKu I get the same error on 1.3.1.

**Comment by FxKu** [comment]
Hm, there's only one [place](https://github.com/zalando/postgres-operator/blob/fddaf0fb73731a6234b223596a4cb87eb33e5299/pkg/cluster/k8sres.go#L547) where the `KUBERNETES_LABELS` env variable (to be used by Spilo) is set. What `cluster_labels` you have configured in the [ConfigMap](https://github.com/zalando/postgres-operator/blob/fddaf0fb73731a6234b223596a4cb87eb33e5299/manifests/configmap.yaml#L12) or [CRD](https://github.com/zalando/postgres-operator/blob/fddaf0fb73731a6234b223596a4cb87eb33e5299/manifests/postgresql-operator-default-configuration.yaml#L23)?
