### ISSUE TITLE
allow populating pod environment from Secrets

### ISSUE THREAD

**Issue by kupson** [zalando/postgres-operator#480]
It would be nice to populate env variables from secrets e.g. `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` so they won't be exposed in ConfigMaps.

**Comment by Jan-M** [comment]
Is there a reason you cannot use iam/pod iam role for this?

**Comment by kupson** [comment]
I would like to use minio instead of Amazon S3.

**Comment by kupson** [comment]
> Is there a reason you cannot use iam/pod iam role for this?

That would be `kube_iam_role` option?
I would like to use [minio](https://github.com/minio/minio) instead of Amazon S3 and I'm not sure that `kube2iam` could handle it.

**Comment by erthalion** [comment]
Are there any other alternatives, maybe just mount these credentials and let the client library to discover it? If I'm not mistaken, this mentioned in the minio [documentation](https://github.com/minio/minio/blob/bd25f31100f44646cffae99dfec23179366593e2/docs/gateway/s3.md#using-binary-in-ec2)

**Comment by kupson** [comment]
It's the wal-g that needs those environment variables. It would need the volume with credentials mounted so the file [`~postgres/.aws/credentials`](https://github.com/wal-g/wal-g#configuration) will be available.

But all the Pods created by postgres-operator would need the volume and I see no way to create it in the [postgres-operator configuration](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md) or the [postgresql object](https://github.com/zalando/postgres-operator/blob/master/manifests/complete-postgres-manifest.yaml) right now.

Is there a way to add custom volume to add spilo containers and I'm missing it?

**Comment by erthalion** [comment]
Not yet, but probably we can leverage #535 for that purpose?

**Comment by kupson** [comment]
I find #535  suboptimal as I still would need to run some script to turn secrets from Minio format (name: value) into `.aws/credentials`:
```
[default]
aws_access_key_id=EXAMPLE
aws_secret_access_key=EXAMPLEKEY
```
or maybe keep two secrets in sync with same values but different format.
I see environment variables as more flexible solution.

**Comment by FxKu** [comment]
Closing this issue as now supported with #946 being merged.
