### ISSUE TITLE
Can't connect to the cluster from locally run nodejs app

### ISSUE THREAD

**Issue by KASOGIT** [zalando/postgres-operator#482]
Hello,
I'm trying to connect to the cluster from a fastify nodejs app running locally but the connection is rejected with that output: "pg_hba.conf rejects connection for host \"172.17.0.1\", user \"zalando\", database \"foo\", SSL off"
My uri connection line is: "postgres://zalando:pwd@192.168.99.100:30390/foo".
Connection via psql works fine.
Any idea ?

Thanks by advance :)

**Comment by sdudoladov** [comment]
Hello @KASOGIT 

> "pg_hba.conf rejects connection for host "172.17.0.1", user "zalando", database "foo", SSL off"

Check what the [`pg_hba` file ](https://www.postgresql.org/docs/10/auth-pg-hba-conf.html) tells you. I guess you need to enable SSL as a first step.

**Comment by sdudoladov** [comment]
I assume this issue is resolved due to the lack of further questions

**Comment by sipungora** [comment]
This **?ssl=true&sslmode=require** should help
"postgres://zalando:pwd@192.168.99.100:30390/foo?ssl=true&sslmode=require"
