### ISSUE TITLE
Extend affinity support for PG pods 

### ISSUE THREAD

**Issue by sdudoladov** [zalando/postgres-operator#493]
We need the ability to put pods of a particular Postgres DB on particular nodes,  for example fur purposes of load testing. 

Ideally we also need to deprecate `nodeSelector` along the way, as the k8s eventually plans to remove this feature in favor of pod affinity.
 
See [Affinity/Anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity)

related #489

**Comment by digitalassembly** [comment]
In our case, we use AWS Spot and OnDemand nodes each one label accordingly eg: nodegroup=od and nodegroup=spot.  Currently we have no way to determine node-affinity per PG cluster.
