### ISSUE TITLE
Inconsistency in S3 settings between Operator Configuration and Cluster Configuration

### ISSUE THREAD

**Issue by TeutoNet** [zalando/postgres-operator#494]
In the Operator Configuration you can specify a global s3 bucket for WAL files `wal_s3_bucket` and log files `log_s3_bucket`.

In the Spilo Env ConfigMap used to create Postgres Cluster  you can define the following additional parameters like:
* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`
* `WALE_S3_ENDPOINT`
* `AWS_S3_FORCE_PATH_STYLE`
* `AWS_INSTANCE_PROFILE`

This inconsistency causes issues once you try to clone a cluster from a s3 bucket.
The WAL files of the source database is stored in a custom s3 storage server (RADOS Gateway), but the destination instance tries to fetch the WAL files from AWS S3 storage server.

Currently I can't find any setting to propagate the required env variables for cloning.

**Comment by sdudoladov** [comment]
related #487 .
@erthalion pls have a look

**Comment by Jan-M** [comment]
@CyberDem0n probably the best one to answer the different spilo and clone vars?

**Comment by CyberDem0n** [comment]
I think [this](https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L543-L561) block of code could answer most of your questions.

Basically most of the env variables mentioned there could have `CLONE_` prefix and spilo will use them.

**Comment by TeutoNet** [comment]
@CyberDem0n yeah you're right, but the environment variables need to be pre-populated by the postgres operator otherwise clone from non AWS S3 Storage won't work.

**Comment by TeutoNet** [comment]
@CyberDem0n once I've added the missing `CLONE_` env variables to postgres operator I hit another issue, because the spilo image `registry.opensource.zalan.do/acid/spilo-cdp-11:1.5-p42` I'm using is missing the fixes from zalando/spilo#292 . 

Changed spilo image to `registry.opensource.zalan.do/acid/spilo-cdp-11:latest` and recovery works, but now backup/wal file uploads are broken, as the env variables `WALG_S3_SSE` is set to `AES256` which enables encrypted uploads and expects that an encryption key is defined:

```
2019/02/22 12:16:26 upload: failed to upload 'spilo/xyz-clone-db/4edb919d-369b-11e9-8d3c-fa163e5e93d4/wal/basebackups_005/base_000000030000000000000008/tar_partitions/part_001.tar.lz4': InvalidArgument: Server Side Encryption with KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms
        status code: 400, request id: tx000000000000000050b3f-005c6fe81a-2348349-default, host id: .
2019/02/22 12:16:26 upload: could not upload 'spilo/xyz-clone-db/4edb919d-369b-11e9-8d3c-fa163e5e93d4/wal/basebackups_005/base_000000030000000000000008/tar_partitions/part_001.tar.lz4'
2019/02/22 12:16:26 FATAL InvalidArgument: Server Side Encryption with KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms
        status code: 400, request id: tx000000000000000050b3f-005c6fe81a-2348349-default, host id: 
2019/02/22 12:16:26 Unable to complete uploads
```

Unfortunately I was not able to override the `WALG_S3_SSE` env variable.

Do you have any suggestion?

**Comment by TeutoNet** [comment]
@CyberDem0n Is there any possibility to remove the `WALG_S3_SSE` env variable from the envdir?

**Comment by FxKu** [comment]
@TeutoNet looks resolved to me. Can it be closed?

**Comment by FxKu** [comment]
Closing this now. Feel free to reopen if there are still open questions around this issue.
