### ISSUE TITLE
kubedb with spilo/patroni

### ISSUE THREAD

**Issue by ReSearchITEng** [zalando/postgres-operator#503]
Thanks for bringing PostgreSQL so close to k8s world.

We've reviewed zalando oprerator + spilo/patroni images as well as with kubedb's opr+images (along with other options).

spilo/patroni looks great (along with its patronictl)
zalando operator is good
kubedb platform looks ideal (along with its [kubedb operator](https://github.com/kubedb/operator)

Can you share if kubedb was evaluated (especially the updated one), and if there is a chance to move to it? (just an idea for your gsoc-2019 :) )

**Comment by sdudoladov** [comment]
hello @ReSearchITEng 

>  Can you share if kubedb was evaluated (especially the updated one)

not that I am aware of. @Jan-M ?

> just an idea for your gsoc-2019 :)

such evaluaiton/migration would be too much work for GSoC

**Comment by Jan-M** [comment]
We might probably give kubedb platform a look, but from our current perspective the Postgres Operator combined with Spilo is ideal and kubedb seems to be good ;-)

The Postgres Operator is an opinionated operator with some of our our learning's and features that we need and we are happy others are coming with their uses cases and contributions to make it better. The result should always be easy cluster provisioning including database bootstrapping and a great production and operational experience to reduce engineering effort on the Postgres user side.

And all control ideally goes solely via the CRD manifest, to integrate with deployment tools and restrictive environments.

There will always be different operators, there is already another good one around, but not every one has the same needs and expectations to how things should work.

We also believe that not everything needs to be solved in the operator. We do have a UI we plan to release and our monitoring as well, but they preferable interact on k8s APIs for discovery and access to not be too coupled and useful outside of the operator world too.

**Comment by ReSearchITEng** [comment]
Thanks for your quick answers.
Indeed, there are and will be many db operators. What kubedb tries to do: create one platform for such db operators. This would offload this task from the teams managing and packing the dbs: like your spilo/patroni projects. On short run, there is bigger effort, long term, less is expected.

Reg. monitoring, yes, we hear zmon in on it's way to the community. I am not aware of the details yet. Not sure if it will allow sending the metrics/logs for further processing to other tools. Reason: some groups are into aggregating all monitoring into the same stack: prometheus/grafana and logs in ES/Kibana, for all their apps (as opposed to one tool for DB and others for the rest of them).
But, it's so nice to hear you open sourcing such PG tools, as only few options exist currently. Kudos for that!

**Comment by Jan-M** [comment]
FYI: https://opensource.zalando.com/zmon/ is alraedy opensource and supports k8s discovery and a lot of systems on top of it to monitor.

The monitoring I was talking about is another view on https://github.com/CyberDem0n/bg_mon which is great for real time insights into your Postgres cluster.

**Comment by ReSearchITEng** [comment]
Thanks for the links. 
I checked the 2 github zmon links I could find:
1. https://github.com/zalando-zmon/zmon-kubernetes - is this still valid? I see there are no updates since 2016. Not sure is the right one to look at.
2. https://github.com/zalando/zmon -> I see some 2018 updates. (but no k8s manifests) . Is this the one to look into?

**Comment by FxKu** [comment]
Closing this now. Ask ZMON questions in the corresponding repos.
