### ISSUE TITLE
patroni boostrap options synchronous_mode (and others)

### ISSUE THREAD

**Issue by ReSearchITEng** [zalando/postgres-operator#505]
This might fall in a feature request list.

I am trying to setup synchronous_mode. For now the operator does not expose this patroni bootstrap option. This is similar to: #428

Initially I expected that entire spec/patroni gets passed to patroni boostrap, but I was wrong.
If this direction is not possible, will there be an option to pass another map of params from the cluster definition directly to patroni boostrap, without requiring code changes in the operator to interpreting every field?
Or, are there any other options to control patroni from my cluster request?

**Comment by jecho** [comment]
piggybacking off this question. 

I’d like to request adding synchronous_mode type fields. I’ve exposed both synchronous_mode and synchronous_mode_strict in my branch that seems to work and I'd like to contribute. However, I’m still relatively new to how _patroni_ works and maybe this is why it has been excluded?

**Comment by siku4** [comment]
I am are also very interested in this issue. 

@jecho I took a look at your fork (this [commit](https://github.com/jecho/postgres-operator-1/commit/337d018382548ed72677643ce79fdc7ddd1bb253), right?) and it looks good. Have you already tested it in production and made a pull request?

**Comment by FxKu** [comment]
@jecho +1 for opening a PR. When adding manifest fields they have to be covered by CRD validation as well, but I will guide you then.

**Comment by jecho** [comment]
@FxKu @siku4 cool, will make the PR in the next day or so
