### ISSUE TITLE
down-scaling cluster triggers downtime

### ISSUE THREAD

**Issue by ReSearchITEng** [zalando/postgres-operator#510]
Test case:
Cluster with 4 instances(pods) (numberOfInstances: 4). Leader was first instance (pod).
Instance 3 had issues which could not be solved by deleting the pod and its pvc&pv (not clear why).

As a workaround it was decided to scale numberOfInstances: 1  
The result was that even the firsts/leader instance was restarted. This came as a surprise. Of course this means downtime.
(note we used integers, so it is not known issue #269 ).

Is is a bug or per design (recreate everything at down-scaling) ?

**Comment by Jan-M** [comment]
Can you please add some info on why this was closed? I don't think the observation is correct.

For scale up we simply increase statefulset pod count and nothing else happens.

**Comment by ReSearchITEng** [comment]
@Jan-M 
Two issues were identified:
- one of the 3+ pods in the cluster was misbehaving. 
- the pods had the "pending restart" flag/label.
When this happens, up/down scaling seems to somehow trigger downtime.
IMO there should be no situation to allow downtime, but due to complex scenario we considered it to hard to replicate so closed the case.
