### ISSUE TITLE
Failing to generate spilo JSON configuration should raise an error

### ISSUE THREAD

**Issue by stang** [zalando/postgres-operator#512]
Currently, the [`generateSpiloJSONConfiguration()` returns an empty string](https://github.com/zalando/postgres-operator/blob/db72d82f14cc4a2178504efc899df8158f6e9a4d/pkg/cluster/k8sres.go#L252-L253) when it fail to JSON encode the spilo configuration.

It should return an explicit `error` so the caller can choose to act on it. Otherwise, you can end up in situations where it _silently_ fail, and a StatefulSet is generated with empty `SPILO_CONFIGURATION` in it's spec, which can leads to unexpected results.

**Comment by FxKu** [comment]
PR #516 got merged, so this can be closed
