### ISSUE TITLE
Set statefulset update and management policy explicitly

### ISSUE THREAD

**Issue by Jan-M** [zalando/postgres-operator#514]
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies

We can set the "Management Policy" to parallel. All pods can spawn in parallel, Patroni takes care of picking the leader and doing bootstrap exactly once. This also helps to scale up if there is issues in the pods 0...n-1

The "Update Strategy" needs to be "onDelete" as the operator is aware of how to deal with rolling upgrades and switchovers and not so much the kubernetes controller.

**Comment by sdudoladov** [comment]
closed by #515
