### ISSUE TITLE
Cluster domain hard-coded

### ISSUE THREAD

**Issue by mxdrenthe** [zalando/postgres-operator#521]
Problem:
On a barematel kubernetes installation cluster name isn't `cluster.local`
Because of hard-coded cluster name connecting to the instance is impossible.

Error message:
`level=error msg="could not connect to PostgreSQL database: dial tcp: lookup acid-minimal-cluster.default.svc.cluster.local on xxx.xxx.xxx.xxx:xxxx: no such host" cluster-name=default/acid-minimal-cluster pkg=cluster`

Spotted line:
https://github.com/zalando/postgres-operator/blob/5f6abfb7977abf0ba0c05f502a119e565cc6e1e6/pkg/cluster/database.go#L37

**Comment by redbaron** [comment]
It shouldn't be hardcoded indeed. As workaround you can make in cluster DNS
to serve both cluster.local and your current cluster zone

**Comment by mxdrenthe** [comment]
The workaround indeed solves the finding containers.
Noticed that the services created the selectors won't match the created pods.
label: `spilo-role: xxx` is missing

**Comment by FxKu** [comment]
PR #561 got merged. Should be solved now. Open a new issue if there are still problems regarding services.
