### ISSUE TITLE
goveralls timeouts on pull requests

### ISSUE THREAD

**Issue by kupson** [zalando/postgres-operator#523]
Hi,

It looks like the `goveralls` call from `.travis.yml` is experiencing timeout before it can [process all files](https://travis-ci.org/zalando/postgres-operator/jobs/512077943#L755).

As the result in pull requests (e.g. #481) the [coverage report](https://coveralls.io/builds/22436621) covers only the `pkg/apis`, `pkg/spec`, and `pkg/util` directories.

**Comment by CyberDem0n** [comment]
Travis experience some issues. We can retrigger builds when it recovers.

**Comment by FxKu** [comment]
I retriggered and it seem to cover all files now.
