### ISSUE TITLE
config option to allow Spilo to run non-root

### ISSUE THREAD

**Issue by aaroniscode** [zalando/postgres-operator#530]
Spilo (https://github.com/zalando/spilo) does not currently have a configuration option to run as non-root. However, it can be configured to run as non-root with minimal changes.

See: https://github.com/aaroniscode/spilo-nonroot

The issue with the Postgres Operator is that the Persistent Volume mounted for the data directory is only accessible by the root user. Kubernetes has an option `SecurityContext: fsGroup` that enables non-root users to access data on PersistentVolumes.

More information:
* https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#configuring-a-non-privileged-user
* https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod

Working on a PR for a simple config option to allow configuring the SecurityContext's fsGroup.

**Comment by aaroniscode** [comment]
Zalando team -- Can you share your thoughts on this approach?  I have a customer that requires containers run as non-root and looking for a long-term solution that doesn't require running a patched version of the operator. Happy to make changes to the design or approach.

**Comment by abh** [comment]
The latest version from GitHub has this feature, I think

**Comment by aaroniscode** [comment]
@abh I just searched the repo and couldn't find anything that would allow spilo to run as non-root. The key to enabling that is setting a SecurityContext with a fsGroup that allows the non-root user to access the PersistentVolume. The only file in the repo that deals with a SecurityContext is `k8sres.go` at line 384: https://github.com/zalando/postgres-operator/blob/15ec6a920d71282d28ce8239423c0239c7b28e02/pkg/cluster/k8sres.go#L384.

If there is something I'm missing, please let me know as this capability is important to our client. Thanks.

**Comment by Jan-M** [comment]
Thumbs up for the idea and PR, obviously running things as non root in Docker is something that should be encouraged and possible, despite us not doing it.

We will have a look.

**Comment by abh** [comment]
@aaroniscode Ah, yes -- I got it confused with the `spilo_privileged: false` option which was enough to get things going with the PodSecurityPolicies in my cluster.

**Comment by aaroniscode** [comment]
@abh no worries. The two are related!

**Comment by aaroniscode** [comment]
Closing as #531 merged. Thanks!
