### ISSUE TITLE
Fix RBAC defined by the Helm chart

### ISSUE THREAD

**Issue by sdudoladov** [zalando/postgres-operator#539]
running the operator with our Helm chart currently produces the following error:

> time="2019-04-09T19:44:37Z" level=warning msg="Pods and/or Patroni may misfunction due to the lack of permissions: could not create role binding zalando-postgres-operator : cannot bind the pod service account \"postgres-operator\" defined in the config map to the cluster role in the \"resource-usage-collector\" namespace: clusterroles.rbac.authorization.k8s.io \"zalando-postgres-operator\" not found" pkg=controller

this happens because the example RBAC configuration we provide - and the one our operator expects for local execution - uses the "zalando-postgres-operator"  name,  while the Helm uses the simple "postgres-operator" phrase. The easiest way to adjust this is to change the name in Helm. 

Olaf Klischat, thank you for the detailed issue report.

@FxKu pls have a look

**Comment by FxKu** [comment]
I think, this is duplicate to #528.

One could use `helm install --name zalando ./charts/postgres-operator` as a workaround when using an older image. We can (should) maybe update the docs, so that not more people run into this. Let's wait what Olaf says.

**Comment by multi-io** [comment]
Renaming the release to "zalando" worked. Since we didn't want to use the release name going forward (no offence haha), I instead made this temporary fix to the chart:

```commit 6b457735243ba3ab4c6f4a14bf608b8729a931f9
Author: Olaf Klischat <o.klischat@syseleven.de>
Date:   Thu Apr 11 09:53:00 2019 +0200

    postgresql operator: temporary fix for https://github.com/zalando/postgres-operator/issues/539 / https://github.com/zalando/postgres-operator/issues/528

diff --git a/postgres-operator/Makefile b/postgres-operator/Makefile
index b74c58da..f404c060 100644
--- a/postgres-operator/Makefile
+++ b/postgres-operator/Makefile
@@ -2,6 +2,6 @@ include ../../../env.make

 install: values.yaml seed_kubeconfig
 	$(HELM) init --client-only
-	$(HELM) upgrade --install --namespace postgres-operator --values values.yaml zalando helm/postgres-operator
+	$(HELM) upgrade --install --namespace postgres-operator --values values.yaml postgres-operator helm/postgres-operator

 include ../../../rules.make
diff --git a/postgres-operator/helm/postgres-operator/templates/clusterrole.yaml b/postgres-operator/helm/postgres-operator/templates/clusterrole.yaml
index cdd58f5b..b7a5aa84 100644
--- a/postgres-operator/helm/postgres-operator/templates/clusterrole.yaml
+++ b/postgres-operator/helm/postgres-operator/templates/clusterrole.yaml
@@ -2,7 +2,7 @@
 apiVersion: rbac.authorization.k8s.io/v1beta1
 kind: ClusterRole
 metadata:
-  name: {{ template "postgres-operator.fullname" . }}
+  name: zalando-postgres-operator
   labels:
     app.kubernetes.io/name: {{ template "postgres-operator.name" . }}
     helm.sh/chart: {{ template "postgres-operator.chart" . }}
@@ -137,5 +137,5 @@ rules:
   verbs:
   - bind
   resourceNames:
-  - {{ template "postgres-operator.fullname" . }}
+  - zalando-postgres-operator
 {{ end }}
diff --git a/postgres-operator/helm/postgres-operator/templates/clusterrolebinding.yaml b/postgres-operator/helm/postgres-operator/templates/clusterrolebinding.yaml
index 88c95128..f5402daa 100644
--- a/postgres-operator/helm/postgres-operator/templates/clusterrolebinding.yaml
+++ b/postgres-operator/helm/postgres-operator/templates/clusterrolebinding.yaml
@@ -11,7 +11,7 @@ metadata:
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
-  name: {{ template "postgres-operator.fullname" . }}
+  name: zalando-postgres-operator
 subjects:
 - kind: ServiceAccount
 # note: the cluster role binding needs to be defined
diff --git a/postgres-operator/helm/postgres-operator/templates/configmap.yaml b/postgres-operator/helm/postgres-operator/templates/configmap.yaml
index db8f0bda..6538c469 100644
--- a/postgres-operator/helm/postgres-operator/templates/configmap.yaml
+++ b/postgres-operator/helm/postgres-operator/templates/configmap.yaml
@@ -8,5 +8,5 @@ metadata:
     app.kubernetes.io/managed-by: {{ .Release.Service }}
     app.kubernetes.io/instance: {{ .Release.Name }}
 data:
-  pod_service_account_name: {{ template "postgres-operator.fullname" . }}
+  pod_service_account_name: zalando-{{ template "postgres-operator.fullname" . }}
 {{ toYaml .Values.config | indent 2 }}
```

Using this, any release name should work, unless I'm overlooking something.

We'll revert this once you guys tag a new release with the fix for #528 included.

**Comment by sdudoladov** [comment]
we shall also add an OperatorConf CRD to the Helm chart

**Comment by FxKu** [comment]
@sdudoladov had a quick look how to implement this and it shouldn't be too hard. The template would be the same as for the [ConfigMap](https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/templates/configmap.yaml). I would be nice to use the same list of config parameters from the [values](https://github.com/zalando/postgres-operator/blob/c1d108a8321190559e4280b440ffe448339f656f/charts/postgres-operator/values.yaml#L16). But the [CRD config](https://github.com/zalando/postgres-operator/blob/master/manifests/postgresql-operator-default-configuration.yaml) uses one more level of keys (`users`, `kubernetes` etc.). Not sure, if we could use the CRD way and change the ConfigMap template to have multiple entriers like `{{ toYaml .Values.config.kubernetes | indent 2 }}` etc.
On the other hand, Helm [docs](https://helm.sh/docs/chart_best_practices/#flat-or-nested-values) also propose to not nest too much...
