### ISSUE TITLE
Fix sample manifest namespace mismatch

### ISSUE THREAD

**Issue by IlyaSemenov** [zalando/postgres-operator#543]
The quickstart RBAC manifest sets `default` as explicit namespace here:
https://github.com/zalando/postgres-operator/blob/f25351c36a4e62e18f2af6704d9aace38b7539d6/manifests/operator-service-account-rbac.yaml#L5

However the postgres operator manifest doesn't set any namespace:
https://github.com/zalando/postgres-operator/blob/43e82887510c213878afe85e26d5293cf60e0f1a/manifests/postgres-operator.yaml#L3

Therefore following the instructions in "Manual deployment setup" (https://github.com/zalando/postgres-operator/blob/c243074083d7cb15eeb17e9ec94899bc51ac37f4/docs/quickstart.md#manual-deployment-setup) with kubectl context pointing to any namespace other than `default` leads to this error:

```console
❯ k describe replicaset postgres-operator-84b86d6446
  Warning  FailedCreate  52s (x16 over 3m36s)  replicaset-controller  Error creating: pods "postgres-operator-84b86d6446-" is forbidden: error looking up service account kube-system/zalando-postgres-operator: serviceaccount "zalando-postgres-operator" not found
```

..even though the service account **is** there:

```console
❯ k get serviceaccount --all-namespaces
NAMESPACE     NAME                                 SECRETS   AGE
default       default                              1         3h
default       zalando-postgres-operator            1         4m
```

The manual should clearly state that it requires the kubectl context to point to `default` namespace, or that the RBAC manifest must be updated accordingly for the instructions to work.

Also, I think `ServiceAccount` should not have the explicit namespace (same as other resources).

**Comment by FxKu** [comment]
The yaml files in the manifest folder can be considered only examples. It's up to the users to adjust parts of it to match their K8s environment. We should point this out a bit clearer.

With the provided helm chart it's easier to deploy the operator to a separate namespace.

**Comment by FxKu** [comment]
Closing this now as docs were updated.
