### ISSUE TITLE
quick create-delete leaves orphaned  objects

### ISSUE THREAD

**Issue by sdudoladov** [zalando/postgres-operator#551]
Orphaned pods/endpoints are left in the cluster if the `ADD` event is followed by `DELETE` within a short time period for the same cluster.

This error manifests as 
```
time="2019-04-29T12:17:52Z" level=info msg="\"ADD\" event has been queued" cluster-name=default/acid-minimal-cluster pkg=controller worker=0
...
time="2019-04-29T12:17:53Z" level=info msg="waiting for the cluster being ready" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
time="2019-04-29T12:17:56Z" level=debug msg="Waiting for 2 pods to become ready" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
time="2019-04-29T12:18:00Z" level=info msg="\"DELETE\" event has been queued" cluster-name=default/acid-minimal-cluster pkg=controller worker=0
...
time="2019-04-29T12:18:29Z" level=info msg="statefulset \"default/acid-minimal-cluster\" has been deleted" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
time="2019-04-29T12:18:29Z" level=debug msg="deleting pods" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
time="2019-04-29T12:18:29Z" level=debug msg="no pods to delete" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
...
time="2019-04-29T12:18:29Z" level=debug msg="deleting PVCs" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
time="2019-04-29T12:18:29Z" level=debug msg="no PVCs to delete" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
...
time="2019-04-29T12:18:32Z" level=debug msg="removing leftover Patroni objects (endpoints or configmaps)" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
time="2019-04-29T12:18:32Z" level=warning msg="could not remove leftover patroni objects; could not fetch Patroni Endpoint \"/\": an empty namespace may not be set when a resource name is provided" cluster-name=default/acid-minimal-cluster pkg=cluster worker=0
time="2019-04-29T12:18:32Z" level=info msg="cluster has been deleted" cluster-name=default/acid-minimal-cluster pkg=controller worker=0
```

reproducible both with `kind` and actual `k8s`

this issue also prevents creating a new cluster with the same name afterwards

**Comment by FxKu** [comment]
Aside from finalizers #450, ownerReference #498 might also help.

**Comment by Jan-M** [comment]
Both options need to be investigated with care, the only real delete we care about is the delete of the "postgresql" object. Other objects can be deleted (e.g. the statefulset) and no interruption or impact is expected.

**Comment by davisford** [comment]
> Both options need to be investigated with care, the only real delete we care about is the delete of the "postgresql" object. Other objects can be deleted (e.g. the statefulset) and no interruption or impact is expected.

@Jan-M this is what I'm seeing.  I have Terraform scripts that build and tear down the whole cluster, but the secondary read replica we spawn never gets removed even though the operator and the `postgresql` object is removed.

```
$ kc get postgresqls.acid.zalan.do -A
No resources found.
```

```
$ kc get pods -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
default       foo-cluster-1                   1/1     Running   0          19h
kube-system   coredns-5c98db65d4-fm6c5           1/1     Running   0          19h
kube-system   coredns-5c98db65d4-lptdx           1/1     Running   0          19h
kube-system   etcd-minikube                      1/1     Running   0          19h
kube-system   kube-addon-manager-minikube        1/1     Running   0          19h
kube-system   kube-apiserver-minikube            1/1     Running   0          19h
kube-system   kube-controller-manager-minikube   1/1     Running   0          19h
kube-system   kube-proxy-xdg4c                   1/1     Running   0          19h
kube-system   kube-scheduler-minikube            1/1     Running   0          19h
kube-system   storage-provisioner                1/1     Running   0          19h
```

The `foo-cluster-1` is left behind.... it is a PG db node that was part of the original cluster.

Other resources are also left behind, secrets, services, endpoints, persistent volumes + claims.

What is the best way to handle this?

**Comment by davisford** [comment]
@Jan-M looking at the code, it [appears](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/resources.go#L321) that it is just attempting to delete the `StatefulSet` as opposed to the recommended approach of scaling it down to zero prior to deletion.

**Comment by Jan-M** [comment]
But it is followed up by deletePods if I see this correctly.

But you are right, we will look into the right place of the docs on how to delete a statefulset. I did not know that the delete maybe does not delete pod.

Maybe got mixed up here, where it is mentioned that kubectl scales down too.
https://kubernetes.io/docs/tasks/run-application/delete-stateful-set/

@sdudoladov
