### ISSUE TITLE
Host your operator Chart in some repo

### ISSUE THREAD

**Issue by rockholla** [zalando/postgres-operator#552]
We're currently just manually pulling in your chart into another chart of ours to use it as a subchart. We'd love to be able to just include the chart here as a dependency in  requirements.yaml by pulling from a published repo location as opposed to manually pulling in new versions when they're available. Let us know if you think this would be possible. Thanks.

**Comment by FxKu** [comment]
It's def. on our roadmap. You're not the first one to ask ;)
Ideally it should be there with the next release. We just have to check which repo to go for.

**Comment by rockholla** [comment]
Great to hear, thanks @FxKu

**Comment by FxKu** [comment]
PR is out: https://github.com/helm/charts/pull/15836

**Comment by FxKu** [comment]
As pointed out in the PR, we are hosting now via GitHub pages, so the URL would be:
```helm install https://opensource.zalando.com/postgres-operator/charts/postgres-operator/postgres-operator-1.2.0.tgz
```
