### ISSUE TITLE
headless services are not removed when cluster is deleted

### ISSUE THREAD

**Issue by stang** [zalando/postgres-operator#566]
Since headless services were introduced in https://github.com/zalando/patroni/pull/958, those need to be cleaned after a cluster is deleted.

Initial discussion with @CyberDem0n : https://github.com/zalando/patroni/issues/1055 that led to this ticket.

#### Update:
As this fix won't cleanup already orphan services, I used [this script](https://gist.github.com/stang/4c7ee4c7f58aef94b286b727435dd522) to manually clean up the left overs.

**Comment by FxKu** [comment]
merged with 1f4267e
