### ISSUE TITLE
Need example how to restore from logical backup

### ISSUE THREAD

**Issue by excavador** [zalando/postgres-operator#568]
Hello,

I guess we need some example how to restore from logical backup

**Comment by Jan-M** [comment]
The operator and spilo currently do not support this flow.

So get a pod running with access to the logical backup (s3) and then to copy or pipe and pg restore like you would do with other logical backups.

**Comment by excavador** [comment]
@Jan-M thank you for your answer

Do I right understand, actual wal-e backups deprecated in favor of logical backup?

https://github.com/zalando/postgres-operator/issues/321#issuecomment-480395543

**Comment by Jan-M** [comment]
Absolutely not. 

This is two different kind of flavors and have different goals.

Our main motivation for logical backups is they are smaller in size and be stored for longer periods of time without wasting space. They also can help spot corruption or help when corruption has happened.

We continue to rely on WAL + Basebackup for operational issues: Point in time recovery, ... Scaling.

**Comment by vitobotta** [comment]
Hi @Jan-M , is there an update re: restore from logical backup?

**Comment by abdennour** [comment]
I think no way to restore from logical backup.
More than 6 months and no update
Does this project out of support ?
