### ISSUE TITLE
Question: Source for logical-backup image

### ISSUE THREAD

**Issue by grantlanglois** [zalando/postgres-operator#571]
I'm interested in exploring the logical backup functionality introduced in #442. Is it a reasonable request that the underlying Dockerfile and dependencies be published for the provided image? (in this repo or elsewhere)

**Comment by sdudoladov** [comment]
> Is it a reasonable request that the underlying Dockerfile and dependencies be published for the provided image? 

Yes, for sure we will look into it in. The current version is `registry.opensource.zalan.do/acid/logical-backup:master-44` that added [encryption at rest (SSE-S3)](https://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html?shortFooter=true) as in 

```bash
aws s3 cp ... --sse="AES256"
```
We still run our own internal tests for this feature, so your feedback will be greatly welcomed.
