### ISSUE TITLE
Bug: Podserviceaccount and clusterrole cannot have different names

### ISSUE THREAD

**Issue by knan-nrk** [zalando/postgres-operator#578]
Currently, controller:initRoleBinding assumes that the clusterrole and pod serviceaccount have the same name, and overwrites roleRef.name with podserviceaccount.name. Which seems like a bug.

Do we want clusterrole name as a config parameter, perhaps?

I'll send a patch decoupling them, at least.

**Comment by sdudoladov** [comment]
@FxKu please have a look

**Comment by FxKu** [comment]
It got introduced with #529 to fix #528.

We have a hard-coded default to `zalando-postgres-operator` RoleRef. When using the Helm chart a random release name can be generated so we have to update the RoleRef to make the role binding work. But yes, if the clusterrole has a different name the binding will be wrong. The hard-coded default should instead use `c.PodServiceAccount.Name`.

The default is only used if `PodServiceAccountRoleBindingDefinition` is empty which - interestingly - is a configuration parameter already. So by adding this (admittedly complex) parameter to the config it should be possible to have a different name for the clusterrole.

**Comment by FxKu** [comment]
PR #581 got merged.
