### ISSUE TITLE
rbac: user facing clusterroles

### ISSUE THREAD

**Issue by knan-nrk** [zalando/postgres-operator#584]
After postgres-operator has been installed on a cluster, non-clusteradmin users of the k8s cluster cannot view or create databases by default.

```
kubectl get postgresqls
Error from server (Forbidden): postgresqls.acid.zalan.do is forbidden: User "Erik.Inge.Bolso@nrk.no" cannot list resource "postgresqls" in API group "acid.zalan.do" in the namespace "default"

```
Should probably have some example clusterroles in the manifests directory that can be added to give users of the k8s access to view and make postgreses. I'll make a pull request.

**Comment by FxKu** [comment]
I came across these roles recently when installing the operator via operatorhub.io. This framework adds four roles:
* admin = * (aggregate-to-admin)
* edit = create, update, patch, delete (aggregate-to-edit)
* view = get, list, watch (aggregate-to-view)
* crdview = get (aggregate-to-view)

Not sure about the last one, but the other three make sense to me.

**Comment by knan-nrk** [comment]
Agreed. Updated the pull request with the three.
