### ISSUE TITLE
spilo_privileged parameter is ignored

### ISSUE THREAD

**Issue by rjbez17** [zalando/postgres-operator#590]
We are setting the `spilo_privileged` parameter to `false` in our configuration:

```
k get configmap -n services postgres-operator -o yaml | grep spilo_privileged
  spilo_privileged: "false"
```

However, when a postgres cluster is brought up, it is configured with privileged mode:

```
 k get po -n services my-service-postgres-0  -o yaml |grep privileged
      privileged: true
```

We are installing the operator via helm using `v1.1.0` of the operator.

I don't see any configuration in the [cluster manifest](https://github.com/zalando/postgres-operator/blob/master/manifests/complete-postgres-manifest.yaml) to override this either. How can we turn this off?

Happy to provide any more information needed. I didn't want to be too verbose and make it unreadable.

**Comment by rjbez17** [comment]
Here is the CR:

```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  creationTimestamp: "2019-06-17T23:52:47Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: my-service
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: my-service-postgres
    helm.sh/chart: "my-service"
  name: my-service-postgres
  namespace: services
  resourceVersion: "7554"
  selfLink: /apis/acid.zalan.do/v1/namespaces/services/postgresqls/my-service-postgres
  uid: 01dd0d95-915b-11e9-8bd6-a4bf0138ed26
spec:
  databases:
    service_db: service_account
  numberOfInstances: 3
  postgresql:
    version: "11"
  teamId: my-service
  users:
    service_account: []
  volume:
    size: 10Gi
```

**Comment by FxKu** [comment]
Are you changing the configuration after deploying the operator? When you change parameters in the ConfigMap (or CRD) you have to re-deploy the operator. Postgres cluster are only updated if you change certain manifest parameters. Yes, the docs can be a bit clearer on that.

**Comment by rjbez17** [comment]
We are not, we configure the parameter in the configmap via the helm chart. We are not editing the configmap at all after being deployed.

**Comment by FxKu** [comment]
Ah, now I know, what's the problem. `v1.1.0` does not have the `spilo_privileged` option. Therefore, it ignores your configuration. You can try the most recent image: `v1.1.0-45-g6918394`.

**Comment by rjbez17** [comment]
Thanks @FxKu, is `v1.1.0-45-g6918394` considered stable (prod ready)? There doesn't seem to be release notes for them.

**Comment by FxKu** [comment]
We are working on having a release ready this month. This image is represents the latest commit to master.

**Comment by FxKu** [comment]
Release is out, so this can be closed.
