### ISSUE TITLE
configLogicalBackup is missing in helm's configmap

### ISSUE THREAD

**Issue by laevilgenius** [zalando/postgres-operator#591]
**.Values.configLogicalBackup** is not present in [configmap.yaml](https://github.com/zalando/postgres-operator/blob/93bfed3e7562f7d6784500d7b523190b6a352e9b/charts/postgres-operator/templates/configmap.yaml).

**Comment by FxKu** [comment]
True. I think we left it out because it is commented in the manifest example ... which doesn't matter :) Will add it soon. There might be even more parameters missing in the configMap.
