### ISSUE TITLE
[logical backup] Ability to customize --endpoint-url and --sse

### ISSUE THREAD

**Issue by laevilgenius** [zalando/postgres-operator#592]
This would allow saving logical backups to a private s3.

**Comment by FxKu** [comment]
You mean something similar to what we just added for cloning? #497

**Comment by laevilgenius** [comment]
Yes. I can already inject **AWS_ACCESS_KEY_ID** and **AWS_SECRET_ACCESS_KEY** into job's pods, but there's no way to set _--endpoint-url_ and _--sse_ (which I need to be disabled) via env vars.

**Comment by Jan-M** [comment]
At some point we need a strategy or vision on which global parameters come from where. Anything that is global config for every pod or Postgres cluster can also find its place in Spilo/Docker config.

Overwriting or extending the Spilo Docker image seems to scare a lot of users away asking for more and more features in the operator.

**Comment by pierreozoux** [comment]
(Maybe outside the scope of this issue, but related to what you just said)
@Jan-M We plan to use this operator for our PG need, and the fact that [Gitlab is switching to it](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/3752) gives even more credibility on this solution moving forward.
But, to be honest, as a new comer to the PG world, this is difficult to handle all these abstractions :)
At the bottom we have patroni, wal-e, wal-g. Then we have spilo that puts all together in a Dockerfile with bash and python scripts (plus some reference to sputs).
And finally, we have the operator that wraps it all.
I think somehow these layers have to be rationalized. I understand the history of the project, and I'm amazed by the work you put it. I just think that it is a bit scary for new comers to dive in all these abstractions ;)
(And I guess it would be difficult to maintain moving forward.)
So this looks like the problem space, I have no idea how to solve it in a better way. And I also understand the history of it, and if it is working for you, it would be difficult to spend resources to refactor things.

**Comment by FxKu** [comment]
As #628 got merged, both endpoint and sse are configurable.
