### ISSUE TITLE
Use kustomize as alternative operator deployment

### ISSUE THREAD

**Issue by jakub-roman** [zalando/postgres-operator#607]
I'd like to suggest to have an alternative operator deployment using [kustomize](https://github.com/kubernetes-sigs/kustomize).

The reason is that we don't like to use helm (for various reasons) and having to apply yaml files manually is not optimal.

Kustomize would enable users to deploy the operator as easy as:
```
kubectl apply -k github.com/zalando/postgres-operator/manifests
```
while leaving the liberty of overriding properties such as `namespace` easily.

**Comment by FxKu** [comment]
added a comment in [Quickstart](https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#manual-deployment-setup). Thanks for the pointer.
