### ISSUE TITLE
Ugly format of helm template output

### ISSUE THREAD

**Issue by yujunz** [zalando/postgres-operator#610]
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name:
            RELEASE-NAME-postgres-operator
```

Rendered out of

```
  name: {{- if eq .Values.serviceAccount.name "" }}
            {{ template "postgres-operator.fullname" . }}
        {{- else }}
            {{ .Values.serviceAccount.name }}
        {{- end }}
```

It does not affect usage, but looks ugly when previewed with `helm template` or dumped to [raw manifests for kustomize](https://github.com/kustless/postgres-operator/blob/master/base/clusterrole.yaml)

**Comment by FxKu** [comment]
Yes, not super pretty. Feel free to open a PR to fix it. First, I wanted to rely on the [documented](https://helm.sh/docs/chart_best_practices/#yaml-configuration) behavior (use template if not set), but it did not work for me.
