### ISSUE TITLE
Standard Resource Definition

### ISSUE THREAD

**Issue by pierreozoux** [zalando/postgres-operator#615]
I'm trying to standardize the way we describe PostreSQL instances in kubernetes resources, and make this part of upstream, [in alpha for the 1.16 version](https://github.com/libresh/StandardResourceDefinitions/issues/6).

As one PG operator provider, I'd love your feedback on this.

As a user of your operator, would you find it useful to have a standard resource definition for PG (the same as ingress or PVCs for instance)?
As a developer of this operator, would you adopt it?
What is the biggest challenge you see in this initiative?

If you think this is valuable for the community as a whole like I do, please comment on the [draft here](https://github.com/libresh/StandardResourceDefinitions/issues/6).

Thanks for your valuable time!

**Comment by Jan-M** [comment]
Hi Pierre, thanks for reaching out!

The problem I see is that our manifest and operator do not necessarily want to become the most crazy configurable operator out there, that's what you get by writing your own statefulset. Our manifest should be the slimmest and most convenient to use manifest for the Postgres users in your K8S environment, also incl. e.g. useful and best practices for the database bootstrap itself.

Having one generic manifest and then explaining users all the options that do not work I don't see as helpful.

Curious to read other opinions though.

(My 5min reply on Friday evening)
