### ISSUE TITLE
Do you accept PRs from other companies for the operator?

### ISSUE THREAD

**Issue by Bryji** [zalando/postgres-operator#645]

**Comment by Jan-M** [comment]
We sure do, we are happy do accept contributions from other developers. We are reviewing and accepting PRs for a while now and like to see the operator gain more adoption.

**Comment by Bryji** [comment]
Awesome. My company's legal department had a question if submissions remain copyright of the submitters (or the company in this case)? Understood it would be all MIT licensed in any case.
