### ISSUE TITLE
backup with cron job without any S3

### ISSUE THREAD

**Issue by thepotatocannon** [zalando/postgres-operator#646]
Hi everyone, 
My goal is to make a simple backup with cron jobs but without having any bucket for this case. My first idea is to make an image looking similar to the one Zalando team offers for logical backups, but in the dump script i would save the data to a volume instead of a bucket.
I have a question regarding that matter:
How can I add a volume to a cron job pod? I cannot locate any yaml referring the job.

**Comment by Jan-M** [comment]
Sounds more like you should head to the Kubernetes documentation to find out how to schedule jobs and create a pod with a persistant volume.

**Comment by Jan-M** [comment]
Keep in mind depending on your environment you want to make sure this volume where your backup is is not suffering to same failure or risk as your database volume.

**Comment by thepotatocannon** [comment]
Thanks for such a quick response, but something is unclear for me, so i will try to paraphrase my question. How does operator create a cron job in this project? All i need to do is to enable a logical backup schedule with a parameter "enableLogicalBackup". What happens next? Where does the operator take a job manifest from?

**Comment by Jan-M** [comment]
Currently you cannot modify this, the tiny job spec is coded within the operator. So while you would be able to overwrite the docker image the job spec itself is not "configurable". Thus for now you would need to deploy a valid job spec yourself.

**Comment by thepotatocannon** [comment]
Thanks for clarifying :)

**Comment by thepotatocannon** [comment]
Sorry for closing and reopening, but i need to ask one more question: if i cannot modify it myself, is there a way to at least see the spec so i use it as a draft for my own manifest?

**Comment by Jan-M** [comment]
create test cluster, set logical backup to true and then use kubectl to get the cronjob/job spec?
