### ISSUE TITLE
Inject connection details into other Pods

### ISSUE THREAD

**Issue by tfluehmann** [zalando/postgres-operator#650]
I am playing around with the postgres-operator and I really like it. I just faced an issue with adding the credentials to other containers.
I asked myself if you already have some concept for PodPresets that includes a connection string into desired Pods?
Deployments with the corresponding labels would get the connection string injected into their pods.
Or how are others doing it? All manually, or are there other ways?

**Comment by Jan-M** [comment]
Our users right now do manual secret mounting to env vars in deployments/jobs.

**Comment by tfluehmann** [comment]
OK, thanks for your answer. I realized, there is an option called: secret_name_template, probably I can read the username and password from there at least, so I can minimize the manual effort.
I'll think about implementing the PodPreset feature in the future by myself as an option, to have a fully automated environment.
