### ISSUE TITLE
Docker image postgres-operator-ui:v1.2.0 is missing

### ISSUE THREAD

**Issue by niiku** [zalando/postgres-operator#656]
The docker image `registry.opensource.zalan.do/acid/postgres-operator-ui:v1.2.0` referenced in the [release notes](https://github.com/zalando/postgres-operator/releases) and its [manifest](https://github.com/zalando/postgres-operator/blob/master/ui/manifests/deployment.yaml#L23) is missing

```
$ docker pull registry.opensource.zalan.do/acid/postgres-operator-ui:v1.2.0
Trying to pull repository registry.opensource.zalan.do/acid/postgres-operator-ui ...
Pulling repository registry.opensource.zalan.do/acid/postgres-operator-ui
Error: image acid/postgres-operator-ui:v1.2.0 not found
```

**Comment by FxKu** [comment]
Just saw that our build pipeline is not using the same tag for operator and ui. The release tag for the ui is `cmaster-314`. But, I have just pushed an image with the `v1.2.0` as well, so maybe it will work now, too.

Manifests for the UI are found [here](https://github.com/zalando/postgres-operator/tree/master/ui/manifests).

**Comment by niiku** [comment]
Thanks for taking care of the issue :-)
