### ISSUE TITLE
Operator exiting on OpenShift with readOnlyRootFilesystem: true

### ISSUE THREAD

**Issue by eraserx99** [zalando/postgres-operator#662]
After some struggles, finally we got the Operator and a 3-node cluster up-and-running in our OpenShift 3.11.0 environment. However, we observed quite some restarts of the Operator itself. After checking the container logs, we found some statements like this,

log: exiting because of error: log: cannot create log: open /tmp/postgres-operator.postgres-operator-7c7f894bbc-4g5md.pgo.log.WARNING.20190907-011239.1: read-only file system

  The sample postgres-operator.yaml file from the Operator project specifies,

```
readOnlyRootFilesystem: true
```

  We think that's why the Operator exited. Of course, we can remove the readOnlyRootFilesystem restriction and test the Operator again. However, if it works, will the Operator rotate those log files so that they will not fill up the volume?

**Comment by eraserx99** [comment]
Sorry, forgot to mention earlier. Here is the image we're using,

registry.opensource.zalan.do/acid/postgres-operator:v1.2.0

**Comment by eraserx99** [comment]
After removing the line below from the deployment configuration, the Operator does not exit at all.

```
readOnlyRootFilesystem: true
```
Here is what the /tmp looks like now. Still curious if the log files will fill up the volume over time?

```
/ $ ls -al /tmp
total 24
drwxrwxrwt    1 root     root           254 Sep  7 01:39 .
drwxr-xr-x    1 root     root            40 Sep  7 01:27 ..
lrwxrwxrwx    1 pgo      pgo             83 Sep  7 01:39 postgres-operator.INFO -> postgres-operator.postgres-operator-56f4ccc6d8-69pnf.pgo.log.INFO.20190907-013918.1
lrwxrwxrwx    1 pgo      pgo             86 Sep  7 01:39 postgres-operator.WARNING -> postgres-operator.postgres-operator-56f4ccc6d8-69pnf.pgo.log.WARNING.20190907-013918.1
-rw-r--r--    1 pgo      pgo          10499 Sep  7 11:23 postgres-operator.postgres-operator-56f4ccc6d8-69pnf.pgo.log.INFO.20190907-013918.1
-rw-r--r--    1 pgo      pgo          10499 Sep  7 11:23 postgres-operator.postgres-operator-56f4ccc6d8-69pnf.pgo.log.WARNING.20190907-013918.1
```

**Comment by FxKu** [comment]
Can you check the logs of the operator pod? The `readOnlyRootFilesystem` has been [integrated](https://github.com/zalando/postgres-operator/pull/582) recently. Seems that no K8s users had troubles with this so far...

**Comment by eraserx99** [comment]
As I mentioned earlier, when the Operator was exiting, it logged the information information to STDOUT or STDERR that was caught by the OpenShift log aggregrator.

```
log: exiting because of error: log: cannot create log: open /tmp/postgres-operator.postgres-operator-7c7f894bbc-4g5md.pgo.log.WARNING.20190907-011239.1: read-only file system
```

After we remove the readOnlyRootFilesystem setting and re-deployed the Operator, it has been running without exiting for more than a day. Here is what it has written to the logs under /tmp.

```
/tmp $ ls
postgres-operator.INFO
postgres-operator.WARNING
postgres-operator.postgres-operator-56f4ccc6d8-69pnf.pgo.log.INFO.20190907-013918.1
postgres-operator.postgres-operator-56f4ccc6d8-69pnf.pgo.log.WARNING.20190907-013918.1
/tmp $ cat postgres-operator.WARNING
Log file created at: 2019/09/07 01:39:18
Running on machine: postgres-operator-56f4ccc6d8-69pnf
Binary: Built with gc go1.12 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0907 01:39:18.514943       1 reflector.go:341] github.com/zalando/postgres-operator/pkg/controller/controller.go:381: watch of *v1.Postgresql ended with: The resourceVersion for the provided watch is too old.
W0907 01:49:43.779995       1 reflector.go:341] github.com/zalando/postgres-operator/pkg/controller/controller.go:381: watch of *v1.Postgresql ended with: The resourceVersion for the provided watch is too old.
W0907 01:58:55.850479       1 reflector.go:341] github.com/zalando/postgres-operator/pkg/controller/controller.go:381: watch of *v1.Postgresql ended with: The resourceVersion for the provided watch is too old.
W0907 02:08:33.033759       1 reflector.go:341] github.com/zalando/postgres-operator/pkg/controller/controller.go:381: watch of *v1.Postgresql ended with: The resourceVersion for the provided watch is too old.
W0907 02:21:00.401270       1 reflector.go:341] github.com/zalando/postgres-operator/pkg/controller/controller.go:381: watch of *v1.Postgresql ended with: The resourceVersion for the provided watch is too old.
```

**Comment by eraserx99** [comment]
BTW, we'll be testing and using the Operator in OpenShift environment every now and then (we have been managing and running OpenShift for some medium to large systems for more than 1.5 years). We're more than glad to help the team with some testing efforts or documentation, if needed.

**Comment by FxKu** [comment]
Thanks, contributions are always welcome :)

Regarding the initial log question. Postgres logs will only be present for the last 7 days. Can't tell how K8s is managing the Pod logs.

**Comment by eraserx99** [comment]
Usually, our applications log everything to STDOUT so that Kubernetes / OpenShift would catch them and present to the users in some way without filling up the disk.

On the other side, we do have to remove the 

```
readOnlyRootFilesystem: true
```

from the deployment. Otherwise, the Operator would exit when it fails to write the logs to /tmp.

**Comment by FxKu** [comment]
Closing this one for now. Anybody feel free to reopen if the behavior in OpenShift changes and the workaround does not work anymore.
