### ISSUE TITLE
Correct way to change DB config

### ISSUE THREAD

**Issue by jamessewell** [zalando/postgres-operator#664]
Hi,

I’m having trouble changing database settings non-disruptively with Postgres-operator from master.

I’m using `kubectl edit` to change `checkpoint_completion_target` - which just needs a service reload - but Postgres gets restarted.

Is this intended to work or do all settings changes restart?

**Comment by Jan-M** [comment]
Currently in fact things that get reflected in the pod environment do trigger an unnecessary restart.

We are on this topic to be smarter on what and how this can be better executed calling the patroni api instead.

So the right way if the restart is hurting adjust this via "patronictl"

**Comment by jamessewell** [comment]
If I use patronictl how does that interact with the operator config? Will config will new pods get?

**Comment by Jan-M** [comment]
For a cluster that has already bootstraped the relevant information always comes from patroni/DCS config. So editing it with patronictl is to my knowledge safe. @CyberDem0n

**Comment by FxKu** [comment]
patronictl it is. It's not reflected in the postgres manifest however, but new pods should get their config from the other pods. Closing for now.
