### ISSUE TITLE
Debezium

### ISSUE THREAD

**Issue by akoenig** [zalando/postgres-operator#670]
👋

We are (as many others too) a Kubernetes shop and want to use Debezium for supplying services with change data. Unfortunately, the respective plugins are not available when using PostgreSQL on Google CloudSQL. That is the reason why we considering using this `postgres-operator`. We saw that `decoderbufs` is already present 👍 Any chance to configure the actual instance with `wal2json` as well? 🙂

**Comment by CyberDem0n** [comment]
wal2json is also a part of Spilo

**Comment by akoenig** [comment]
Wohoo ... that is awesome. Thanks for the clarification. 😊
