### ISSUE TITLE
Logical backup resource limits

### ISSUE THREAD

**Issue by airhorns** [zalando/postgres-operator#688]
Hey folks -- thanks for such an awesome piece of open source software!

I'm running some very big resource limits for my PGs to power a memory and IOPS hungry analytics system. We're very sensitive to how much these huge instances cost, so we don't really have much spare memory or CPU of the size we need to run the instances. Because the logical backup pods use the same resource requests as the databases, this means our logical backups are unschedule. We'd rather not overprovision our cluster to have more of these expensive instances, and the backup is streaming so it shouldn't need the crazy CPU / memory the db nodes themselves have.

I took a look at the source and it seems like there isn't a way to adjust the resource limits the backup pod requests, and it seems like that might be on [purpose](https://github.com/zalando/postgres-operator/blob/f0e29060b1fa0884fcf338e87492cd8e90bfd9e6/pkg/cluster/k8sres.go#L1429).

Would you be open to allowing operators to adjust the logical backup resource requests and make them smaller for situations like mine? For the time being I can just manage the cronjob resource outside the operator, but it'd be nice to be able to have it just work!

**Comment by FxKu** [comment]
Hm, we could think of not passing `c.Spec.Resources` in this case, so that only the default resources from the configuration are taken into account. Then it's configurable by the user.

Other suggestions? @sdudoladov @Jan-M

**Comment by Aisuko** [comment]
Hi guys, I hit the same issue. If there exist any update that would be good.

**Comment by cambierr** [comment]
UPing this one as this makes our backup not to be schedulable
