### ISSUE TITLE
Mount credentials for logical backup to AWS

### ISSUE THREAD

**Issue by stgrace** [zalando/postgres-operator#697]
I can not find how to mount my AWS credentials for logical backups in the cronjobs.
Is there a way to configure this using the operator?
It seems credentials can only be mounted in Postgres pods and not in pods created by the cronjob.

**Comment by FxKu** [comment]
With #714 merged,the additionalSecretMount is now also available in the logical backup pod. Still it's up to someone to use it in the dump.sh script. Closing this on for now.
