### ISSUE TITLE
Backup on s3 bucket

### ISSUE THREAD

**Issue by rafstef** [zalando/postgres-operator#698]
How is possible to use s3 bucket as backup storage using access key and secret key?
Where I must to configure them?
Our test is not working.

Thanks

**Comment by FxKu** [comment]
Looks duplicate to #697, if I'm not mistaken.

**Comment by FxKu** [comment]
With #628 merged, you can now configure an S3 access key for logical backups. The additionalSecretMount is now also available in the logical backup pod, but that's currently not reflected in the dump.sh script of the CronJob. Please, open a new issue if it isn't working for you.
