### ISSUE TITLE
Hello world - warning on SA name

### ISSUE THREAD

**Issue by haf-afa** [zalando/postgres-operator#700]
```

postgres-operator-76f5c5cb58-2vwgz postgres-operator 2019/10/30 12:34:50 Fully qualified configmap name: pg-system/postgres-operator
postgres-operator-76f5c5cb58-2vwgz postgres-operator 2019/10/30 12:34:50 Spilo operator v1.2.0
postgres-operator-76f5c5cb58-2vwgz postgres-operator time="2019-10-30T12:34:50Z" level=warning msg="in the operator config map, the pod service account name zalando-postgres-operator does not match the name operator given in the account definition; using the former for consistency" pkg=controller
... etc
```

With the Quickstart

**Comment by FxKu** [comment]
Don't worry. You'll get the message every time you're not using a service account called `operator`, which is an internal default. I'm not sure why it's done like this, maybe other committers can tell :smiley:

**Comment by haf-afa** [comment]
OK, thanks, good to know. :)

I still think that is an issue though; warnings need to be actionable.

**Comment by FxKu** [comment]
Now that we
1. have a defined cluster role for pods in the configuration
2. incl. a new default service account `postgres-pod`
3. and don't reuse the `postgres-operator` service account,

this warning should not appear that often anymore. And now it would even make more sense if somebody does not use the `postgres-pod` role.
