### ISSUE TITLE
helm hub

### ISSUE THREAD

**Issue by Dudesons** [zalando/postgres-operator#707]
Hi,

Do you think if it's possible to publish the helm manifests to helm hub ?
It would be awesome to facilitate the integration.

**Comment by FxKu** [comment]
We can consider it when preparing the next release, I guess. Any problems with the current hosting of the helm chart?

**Comment by Dudesons** [comment]
No I didn't have a problem, but I don't want to have the `postgres-operator` repository in local to deploy it.
It's really  for automation case :)

**Comment by FxKu** [comment]
We host via GitHub pages, see #552.

```helm install https://opensource.zalando.com/postgres-operator/charts/postgres-operator/postgres-operator-1.2.0.tgz```

**Comment by brunsgaard** [comment]
In the spirit of progressing towards a 1.3.0 release.

[Guidelines for Repository Inclusion])https://github.com/helm/hub/blob/master/Repositories.md) @FxKu I can make the PR draft and run it past you before we try to get the operator into helm hub.

Alternatively I think a link to `https://opensource.zalando.com/postgres-operator/charts/postgres-operator/postgres-operator-1.2.0.tgz` should be easier to find and a PR to the README.md/docs should be made and this ticket closed.

What do you want to do here?

**Comment by FxKu** [comment]
@brunsgaard any contribution in this direction is more than welcome. I would have started to look at it after the release, but maybe we can be quicker.

**Comment by FxKu** [comment]
Closing in favor for #1671
