### ISSUE TITLE
Option to set configure the service with "externalTrafficPolicy": "Local"

### ISSUE THREAD

**Issue by abh** [zalando/postgres-operator#708]
In our cluster we use MetalLB for the load balancer services.   With the (default) "Cluster" externalTrafficPolicy postgres doesn't get the right IP and traffic is needlessly pushed around the cluster. With "Local" set for the policy, the traffic goes straight to the right server.

It'd be nice to have an option to set this.

**Comment by FxKu** [comment]
@abh do you still need this feature? I'm about to work on #956, which would probably touch the same code parts required for adding the option you suggested.

**Comment by abh** [comment]
Yeah, I still run with a version of the operator where the only thing I changed is this. 🙂

**Comment by FxKu** [comment]
While I was in vacation, a new PR for this feature request popped up and has been merged: https://github.com/zalando/postgres-operator/pull/1136/files

So, I think we can close this issue now, right?

**Comment by abh** [comment]
that looks good, yes!
