### ISSUE TITLE
Federation support ?

### ISSUE THREAD

**Issue by venkatnsrinivasan** [zalando/postgres-operator#711]
Does the postgres-operator work with KubefedV2 to support HA across multiple data centers?

**Comment by FxKu** [comment]
Currently, the operator only watches for events in one K8s cluster. But you could easily clone a cluster in another K8s setup or create a standby that is served from WAL S3 backups. Promoting the standby however is not yet merged #596. But as Patroni is working with etcd as source of truth, there could be a letency problem when talking to etcd clusters across data centers. I think, the better setup is to use standby clusters and switch to them, if necessary.
