### ISSUE TITLE
Service account cannot access deployments under /apis/apps/v1

### ISSUE THREAD

**Issue by alejom99** [zalando/postgres-operator#720]
Hello,

I've been trying to get logical backups to run, but I keep getting a 403. The function [get_config_resource](https://github.com/zalando/postgres-operator/blob/master/docker/logical-backup/dump.sh#L70) in dump.sh is trying to access /apis/apps/v1/..., but k8s throws an error that says: service account cannot get resource \"deployments\" in API group \"apps\".

I deployed the operator using the helm chart, and looking at the clusterrole.yaml file, I don't see a section for apps/deployments. If I add:

```
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
```
then it works. So, is this missing from the configuration?

**Comment by FxKu** [comment]
@alejom99 you're right thanks! Wonder why our e2e test does not catch it. Could you add it to the [RBAC manifest](https://github.com/zalando/postgres-operator/blob/master/manifests/operator-service-account-rbac.yaml) and create a PR? I think before the statefulset is a good place to add it.

**Comment by FxKu** [comment]
@alejom99 I reverted the RBAC change, because querying the deployment is not needed anymore with #725 merged.
