### ISSUE TITLE
Add UI to the helm chart

### ISSUE THREAD

**Issue by Flowkap** [zalando/postgres-operator#722]
Hey guys. First great work!! 

I'd be very happy if the UI could be added to the setup via helm. We're maintaining a big system and have a good tooling around managing helm installs. Using the manifests is possible but it'll be great to have an UI option on the helm chart to install everything consistently. 

BR Flowkap

**Comment by FxKu** [comment]
I think, I would prefer a separate chart to allow users to go with or without the UI. Feel free to create a PR.
