### ISSUE TITLE
Pod serviceAccount RBAC permissions needed for OpenShift?

### ISSUE THREAD

**Issue by flickerfly** [zalando/postgres-operator#732]
Has anyone determined what permissions are needed under openshift for the pod service account? I gave it namespace-scoped cluster-admin, but I expect we can tighten that up. It just seems like the lack of "endpoints" in OpenShift is throwing things off as it looks for them even though I have the role bound  with full access to endpoints it isn't resolved until I give it cluster-admin for some reason.

Here is the error response I see in the logs of pod 0: 

`HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints \"services-pgsql-cluster\" is forbidden: endpoint address 10.130.5.94 is not allowed","reason":"Forbidden","details":{"name":"services-pgsql-cluster","kind":"endpoints"},"code":403}`

**Comment by FxKu** [comment]
No OpenShift experience from my side? There are no "endpoints"?
Are you using the provided [RBAC](https://github.com/zalando/postgres-operator/blob/f9487e41c1cdfc27ef461fb35fe35e0df2f0e121/manifests/operator-service-account-rbac.yaml#L39) file?

**Comment by flickerfly** [comment]
Thanks @FxKu. I'll check that one out. Sorry about the duplication.

**Comment by dejwsz** [comment]
Endpoints issue might be related to "pod_role_label" config setting which is not applied and therefore labels are not assigned to objects, as it should be, making endpoints broken.

**Comment by dejwsz** [comment]
I can see KUBERNETES_ROLE_LABEL='spilo-role' is set in cluster PODs environments but the role never gets assigned to master or replica PODs. Some kind of bug?
