### ISSUE TITLE
Set the User ID a pod runs as? 

### ISSUE THREAD

**Issue by flickerfly** [zalando/postgres-operator#733]
Is there a config in the OperatorConfiguration to identify the ID to run the cluster member pods as? I have to assign OpenShift's anyuid to get some other stuff working and would like to not run as UID 0 if I can help it.

**Comment by ReSearchITEng** [comment]
Solved now, please give it a try.
For running in non-root mode:
Operator Image should be at least:  registry.opensource.zalan.do/acid/postgres-operator:v1.4.0-21-g1249626-dirty
Operator should be configured with these values:
  kubernetes_use_configmaps: "true"
  docker_image: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p114 #or newer

To get the latest versions of the images of both operator and spilo, do:
https://registry.opensource.zalan.do/v2/acid/postgres-operator/tags/list
https://registry.opensource.zalan.do/v2/acid/spilo-cdp-12/tags/list
