### ISSUE TITLE
Comparison chrunchydata postgres operator

### ISSUE THREAD

**Issue by koh-osug** [zalando/postgres-operator#734]
While googling for postgres operator I just found also:

https://github.com/CrunchyData/postgres-operator/

Can you please summarize what are the differences in the approach or is this just a different OS project targeting similar functions?

**Comment by FxKu** [comment]
It's a different OS project with the same name. Better try it out yourself to find out the differences. It's under active development and I haven't checked it for a while.

**Comment by elgalu** [comment]
https://github.com/CrunchyData/postgres-operator/issues/992#issuecomment-677715349
