### ISSUE TITLE
Patronictl issues

### ISSUE THREAD

**Issue by YannickGekko** [zalando/postgres-operator#737]
Hello, 

We encounter an issue using the operator. 

Here are the steps we proceeded, in both AWS EKS and IBM Cloud IKS environments with the same result : 

- helm init
- helm install --name zalando ./charts/postgres-operator -f ./charts/postgres-operator/ values-crd.yaml

- kubectl create -f manifests/minimal-postgres-manifest.yaml
 
- kubectl exec -it acid-minimal-cluster-0 
 
- patronictl show-config (and most of patronictl raise the following error) 

Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd, zookeeper, exhibitor, kubernetes, consul'

Is this the normal behavior ? Or is there a config to set in order to avoid this error ? 

Thanks in advance

**Comment by FxKu** [comment]
Definitely not normal. What do the Pod logs (operator and spilo) tell you. By [default](https://github.com/zalando/postgres-operator/blob/master/pkg/util/config/config.go#L91), Patroni would use K8s as DCS, but seems it cannot talk to the K8s API. I recommend to check out the Patroni issue tracker for solutions.

**Comment by CyberDem0n** [comment]
Rule of thumb - never use root.
`su postgres` solves your issue
