### ISSUE TITLE
Helm v3 'unable to recognize "": no matches for kind "operatorConfiguration"' errors

### ISSUE THREAD

**Issue by rektide** [zalando/postgres-operator#739]
Hello all. Trying to get postgres-operator going with Helm v3, now that we have #738 (thanks!).

When I go to install with `helm install postgres-operator ./charts/postgres-operator -f ./charts/postgres-operator/values-crd.yaml`, I get:

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "OperatorConfiguration" in version "acid.zalan.do/v1"`

**Comment by brunsgaard** [comment]
`no matches for kind "OperatorConfiguration" in version "acid.zalan.do/v1"`

helm3 would have installed it if they were in the crd folder, are you sure you are running helm3 on the current master?

**Comment by rektide** [comment]
`helm version` reports `version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`. looks good to me? postgres-operator is on tag `f9487e41c` which looks to be master.
