### ISSUE TITLE
The user guide should describe the procedure for PostgreSQL major version upgrades

### ISSUE THREAD

**Issue by brunsgaard** [zalando/postgres-operator#740]
It would be great if the user guide would cover major upgrade procedures. It is a topic many people would like to have strategy for before they start migrating database workload to Kubernetes.

**Comment by FxKu** [comment]
The question popped up recently. See [this comment](https://github.com/zalando/postgres-operator/issues/721#issuecomment-555984302). I agree, that the options pointed out in this thread could be added to the docs.
