### ISSUE TITLE
Deployment with Operator Lifecycle Manager watching all namespaces

### ISSUE THREAD

**Issue by wilmardo** [zalando/postgres-operator#743]
I tried to get this going on our K8S cluster yesterday but it seems to act different then the documentation suggests.

These are steps I took:
```console
# Deploy OLM
kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.13.0/crds.yaml
kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.13.0/olm.yaml
# Subscibe to the postgres-operator
kubectl apply -f https://operatorhub.io/install/postgres-operator.yaml
```

So far so good, this results in the olm running in the olm namespace and the postgres-operator running in the operator namespace.

So I tried to create a cluster and this is the point where things starting to get                   confusing. 

I created a manifest in the namespace where I wanted to deploy the cluster but it isn't picked up by the operator (nothing in the logs). So I redeployed the manifest in the operators namespace (where the operator is running) and that results in the manifest being picked up by the operator. The cluster then gets created within the operator namespace and I seem to be hitting #663 

I tried to update the CSV to ensure the cluster domain is set but is correct that there are only CSV's per namespace no global CSV? So if I want to update the cluster domain I need to edit all the namespaced CSV's to add the `POSTGRES_OPERATOR_CONFIGURATION_OBJECT` env?

**Comment by FxKu** [comment]
When using OLM deployment, the operator is created only with internal config defaults. And one of them is to watch only the namespace where the operator is deployed. It requires a few steps to change this:

1. You can create a configuration object like this [example](https://github.com/zalando/postgres-operator/blob/551564011139d5a6cb9f635d091b2b54f56f125d/manifests/postgresql-operator-default-configuration.yaml#L49) and set `watched_namespace: "*"`.

2. To make the operator obtain this configuration you have to set the env variable as you mentioned.

3. To refresh the operator after this edit, simply delete the operator pod. It will be respawned immediatly.

4. Then it should work to create Postgres clusters in any other namespaces.

You probably agree, that this is all a bit of a hassle. Check out the helm chart or kustomization deployment as both option will launch the operator with ConfigMap or CRD-based configuration. No need to edit the deployment afterwards.

**Comment by FxKu** [comment]
Updated the OLM deployment for the v1.3.0 release to watch all namespaces. Still the configuration hassles remain. Read something that things like a ConfigMap could be included into the release bundle, but I couldn't find any example after a quick search. Closing this issue for now as question is answered.

**Comment by WolfspiritM** [comment]
@FxKu You said the OLM deployment was updated to watch all namespaces by default. Is that right? I deployed the operator via OLM and can't get it to work outside of the "operators" namespace. I even tried to edit the csv and add the environment variable but i can't safe it out of some reason. Even without any change I always get the following error after closing the editor. Any idea?

```
# clusterserviceversions.operators.coreos.com "postgres-operator.v1.3.0" was not valid:
# * : Invalid value: "The edited file failed validation": unknown object type "nil" in ClusterServiceVersion.spec.install.spec.deployments[0].spec.template.metadata.creationTimestamp
#
```
