### ISSUE TITLE
log_s3_bucket/wal_s3_bucket and S3 compatible storage

### ISSUE THREAD

**Issue by vitobotta** [zalando/postgres-operator#752]
Hi! I am new to this operator and Postgres in general, so please be patient :D

I see that it is possible to configure the s3 endpoint for logical backups so that I can use s3-compatible storage for that. What about logs/wal? How can I configure the same s3-compatible service for these? If I understood rightly logs/wal is what is required for point in time recovery.

Thanks in advance!

**Comment by georgebarbarosie** [comment]
@vitobotta did you find an answer to this question? Can you please share it, I'm struggling with the same issue, documentation is silent about how to configure PITR/continuous archiving with postgres-operator.

**Comment by vitobotta** [comment]
@georgebarbarosie Hi, not yet unfortunately. But if you are looking for info on how to backup/point-in-time-restore, check out my post at https://vitobotta.com/2020/02/05/postgres-kubernetes-zalando-operator/
