### ISSUE TITLE
Helm - CRD error: cannot convert int64 to float64

### ISSUE THREAD

**Issue by anshudutta** [zalando/postgres-operator#760]
I am getting the following error when installing with helm (using the values-crd.yaml)
```
Error: rpc error: code = Unknown desc = unable to convert to CRD type: unable to convert unstructured object to apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition: cannot convert int64 to float64
```
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

```

**Comment by FxKu** [comment]
After a quick online research, it looks like this is an issue of helm.

**Comment by anshudutta** [comment]
Yeah, I had to remove the 'minimum' and `maximum` property from crd to get it working with helm2. The documentation says it works with helm2. Should that be updated.

**Comment by FxKu** [comment]
I never had this problem with my helm2 version, but can't tell which one it was. Already updated to v3.

**Comment by thepotatocannon** [comment]
We came across the same problem, any advice how to deploy the current version of operator with helm2? Documentation says:
```The chart works with both Helm 2 and Helm 3. The crd-install hook from v2 will be skipped with warning when using v3. Documentation for installing applications with Helm 2 can be found in the v2 docs.```
This isn't very helpful though.

**Comment by Bryji** [comment]
Link to the helm issue: https://github.com/helm/helm/issues/5806

**Comment by Samusername** [comment]
I use helm 2 currently. The error occurs. 
"Error: unable to convert to CRD type: unable to convert unstructured object to apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition: cannot convert int64 to float64"

When the "minumum" and "maximum" are removed from the crds, then postgres-operator gets installed with helm.
