### ISSUE TITLE
Support for PostgreSQL-12

### ISSUE THREAD

**Issue by thomasboussekey** [zalando/postgres-operator#763]
As your last version was released before the GA-date for PostgreSQL, I want to know if this operator is supported on PostgreSQL-12?

Thanks in advance,
Thomas

**Comment by sdudoladov** [comment]
hi @thomasboussekey 

The operator works with any PG version supported by Spilo, and PG 12 is already there.

**Comment by FxKu** [comment]
@thomasboussekey just drafted a new release which includes a Spilo image that supports Postgres 12.
