### ISSUE TITLE
Logical backup configuration is not synced if the s3 bucket changes

### ISSUE THREAD

**Issue by Bryji** [zalando/postgres-operator#768]
Looks like the backup config is only considered different if the schedule or bucket changes:
https://github.com/zalando/postgres-operator/blob/f0e29060b1fa0884fcf338e87492cd8e90bfd9e6/pkg/util/k8sutil/k8sutil.go#L172

If LOGICAL_BACKUP_S3_BUCKET of LOGICAL_BACKUP_S3_BUCKET_SCOPE_SUFFIX changes in the operator config, even with forced pod restart, existing CronJobs will not get updated.

Workaround: delete existing jobs and let them resync

**Comment by FxKu** [comment]
I've also noticed this in preparation of updating the logical backup image in our infra, e.g. old cronjobs were missing env variable like `CLUSTER_NAME_LABEL` which the dump.sh now script requires. Simply toggling the `enableLogicalBackup` manifest field also did the job.

At the moment, I think this behavior aligns with way the operator works - only listening to changes in the manifest and not the configuration. The workarounds are easy enough, albeit not automatic.

**Comment by FxKu** [comment]
The logical backup containers are now diffed as well, so changing the config will lead to an update of the cronjob. Will be included in the 1.12 release.
