### ISSUE TITLE
Allow configuration of global_sidecars / sidecar_docker_images

### ISSUE THREAD

**Issue by frittentheke** [zalando/postgres-operator#781]
It's awesome to be able to "simply" inject sidecars globally via sidecar_docker_images of the operator configuration (https://github.com/zalando/postgres-operator/pull/331). 

Unfortunately there is no way to globally configure those sidecars yet ...

1.  While there is the pod_environment_configmap setting, the referenced config map has to exist in the namespace the postgresql cluster resides in (https://postgres-operator.readthedocs.io/en/latest/reference/operator_parameters/#kubernetes-resources)
2. The variables in this config map are only propagated to the postgresql container (not actually the whole pod / all containers) as the name of the variable would suggest: https://github.com/zalando/postgres-operator/issues/550

Certainly there are many use cases for globally applied sidecars, but mostly it's about applying common monitoring / logshipping, like discussed here https://github.com/zalando/postgres-operator/issues/264. 

I just ran into the same issue of being able to globally add the sidecars, but being unable to apply some common environment variables to configure those (see comment https://github.com/zalando/postgres-operator/issues/264#issuecomment-393478150)

Easiest would likely be to allow configuration of global sidecar containers just like individual postgresql custom resources (https://postgres-operator.readthedocs.io/en/latest/reference/cluster_manifest/#sidecar-definitions).

While fully exposing all PodSpec settings (https://github.com/zalando/postgres-operator/issues/479) does work as well, it is harder to validate against the postgresql CRD.

**Comment by FxKu** [comment]
I think propagating the content of the pod_environment_configmap to all sidecars should be relatively easy to implement. Have nothing against this idea. As you said, the name already sounds like it would be available to all containers. Feel free to open PR.

**Comment by frittentheke** [comment]
@FxKu  thanks for looking into this. 

While propagation of pod_environment_configmap to all containers makes sense in itself, this still means such a configmap has to exist in each namespace to "solve " the issue about configuration of the global sidecars. Do you have any thoughts on that?

**Comment by FxKu** [comment]
I wonder if the type of PodEnvironmentConfigMap could be changed to `spec.NamespacedName` like we have it [elsewhere](https://github.com/zalando/postgres-operator/blob/077f9af4e399d7d50177c0c5074672911d88fc1c/pkg/util/config/config.go#L55). Then we simply extract the namespace from the given parameter or use default, if not set. [Here's](https://github.com/zalando/postgres-operator/blob/077f9af4e399d7d50177c0c5074672911d88fc1c/pkg/cluster/k8sres.go#L801) the codeline.

**Comment by FxKu** [comment]
Can be closed now with #890 merged.
