### ISSUE TITLE
How can i move to non-default namespace?

### ISSUE THREAD

**Issue by sergeyshaykhullin** [zalando/postgres-operator#783]
### Problem
PG-cluster pods is not starting in different namespace

### What i tried to do
- I applied configmap.yaml, operator-service-account-rbac.yaml, postgres-operator.yaml, minimal-postgres-manifest.yaml and it perfectly worked.
- Then i delete all resources (+ PVs), create namespace `postgres` and change all namespaces in manifests to it
- Run all again and have `postgres-operator` and `postgresql` resource applied, but no pods with pg started, no pvcs, no events in `postgresql` primitive
- I tried same thing on a new cluster, but all the same

### Desired state
- I have postgres namespace
- I have ServiceAccount inside
- I have ConfigMap inside
- I have running operator inside
- I have running pg cluster inside

What am i doing wrong?

### Links
- Merged yamls i applied (I waited for operator startup and then applied postgresql primitive) 
https://gist.github.com/sergeyshaykhullin/75f342b56782553c091a90080f75c948
- Operator describe https://gist.github.com/sergeyshaykhullin/3f46d08ed5d960664977817e6ad50e68
- Postgresql describe https://gist.github.com/sergeyshaykhullin/4ce27db4ba08be445caa987e024b33e9

**Comment by FxKu** [comment]
Strange. Your operator is configured to watch all namespaces so this should work. Could you check the logs of the operator pod and post errors in some gists, too? Are you using the lastest `v1.3.1` image? Which K8s version?

**Comment by sergeyshaykhullin** [comment]
@FxKu 
- I am using 1.3.1 on 1.17.0 k8s version: https://gist.github.com/sergeyshaykhullin/75f342b56782553c091a90080f75c948#file-postgresql_namespace-yml-L147
- Controller logs, something failed, but seems that message about pg cluster: https://gist.github.com/sergeyshaykhullin/5ae48c282de96755f354ec8cccb38a7e

- Most interesting is `
cluster name must match {TEAM}-{NAME} format. Got cluster name 'postgres', team name 'tocoany'" cluster-name=postgres/postgres pkg=controller
` should i use
```yml
kind: postgresql
metadata:
  name: tocoany-postgres # {TEAM}-{NAME}
```
in my cluster name? Can i disable this convention?

- My cluster nodes running and working: https://gist.github.com/sergeyshaykhullin/de176e8e8cae5b3bce5cda04e6fdb813

**Comment by sergeyshaykhullin** [comment]
Pg cluster is formed, thank you!
Maybe add this case to the documentation? Or is there something already?

**Comment by FxKu** [comment]
Ah you found it yourself. Yes, this is a convention we use and you [can not configure](https://github.com/zalando/postgres-operator/issues/667) it at the moment. It should also work if you deploy the minimal manifest with teamId `acid` in another namespace.

People have [asked](https://github.com/zalando/postgres-operator/issues/617) about the meaning of teams before and I tried to update the docs in this regard. Added a note [here](https://github.com/zalando/postgres-operator/blob/master/docs/user.md#create-a-manifest-for-a-new-postgresql-cluster) and [there](https://github.com/zalando/postgres-operator/blob/master/docs/user.md#teams-api-roles). But maybe, it's also good to have add checklist to avoid the most common mistakes :)
