### ISSUE TITLE
Add option to disable CRD creation on operator start

### ISSUE THREAD

**Issue by Glorf** [zalando/postgres-operator#785]
Hello, thanks for all the amazing work on this operator.

I'm currently working on getting this operator working in a single namespace environment (eg. with only Roles and RoleBindings instead of Cluster ones).
The only things that seem to be an issue are CRD createOrReplace operations that are performed at the very beginning of the controller run. Since I have the CRDs already installed, I'd like to have an option to omit this check. Or maybe there is some other way to overcome this?

Specific line that causes problems: https://github.com/zalando/postgres-operator/blob/master/pkg/controller/controller.go#L259

**Comment by FxKu** [comment]
Creating an [additional option](https://github.com/zalando/postgres-operator/blob/master/docs/developer.md#introduce-additional-configuration-parameters) isn't hard. But, if you look at the operator RBAC you see it also contains other cluster-level resources as well: `nodes`, `persistentvolumes`, `namespaces`. If you strip this further down, more things will stop working.

But it's true that the postgres pods do not require the powerful ClusterRole. I have just created a PR to use namespaced Roles instead #786. Have a look and tell me if this setup would work for you.

**Comment by FxKu** [comment]
Closing, since a corresponding option has been merged with #1733.
