### ISSUE TITLE
Update timescaledb to latest version (1.5.1)

### ISSUE THREAD

**Issue by Thorsten-Totemic** [zalando/postgres-operator#787]
By using postgres-operator we're locked in to use the version of timescaledb that is defined in the [Spilo docker file](https://github.com/zalando/spilo/blob/09b4cc3c18c0b1d8e666157171794a2a181cdc14/postgres-appliance/Dockerfile#L2)
Is there any way we can make that configurable in the postgres operator or always use the latest? I can raise an issue in the Spilo repository as well, but figured it's important that this is supported by the postgres-operator as well.

**Comment by FxKu** [comment]
Yes, this is something the operator has no control of. We try to update extension versions regularly. There's already a [feature branch](https://github.com/zalando/spilo/blob/feature/timescale-1.5.1/postgres-appliance/Dockerfile) for timescale 1.5.1 available. Use your own Spilo as long as we release an updated image.

**Comment by CyberDem0n** [comment]
@Thorsten-Totemic, @FxKu please also pay attention that there is Apache2 only version (you will not get compression).

**Comment by Thorsten-Totemic** [comment]
Thanks @CyberDem0n. We were actually looking at the compression feature and I wasn't aware that it is community license only. Do you know what is the easiest to replace the timescale extension when using postgres operator (Basically use the community edition)? Build from source  and copy the extension into each postgres instance? Or is there an easier way where we can bake this into our configuration?

**Comment by FxKu** [comment]
Newest Spilo [release](https://github.com/zalando/spilo/releases/tag/1.6-p2) supports timescale 1.6.0. Regarding your last question, the easiest would probably be to use your own Spilo image, to have control over it.

Closing now. Feel free to reopen.
