### ISSUE TITLE
Error performing backup using Postgres 12

### ISSUE THREAD

**Issue by mdemri** [zalando/postgres-operator#790]
│ + dump                                                                                                                                                                                                │
│ + /usr/lib/postgresql//12/bin/pg_dumpall                                                                                                                                                              │
│ + compress                                                                                                                                                                                            │
│ + pigz                                                                                                                                                                                                │
│ /dump.sh: line 23: **/usr/lib/postgresql//12/bin/pg_dumpall**: No such file or directory                                                                                                                  │
│ ++ estimate_size                                                                                                                                                                                      │
│ ++ /usr/lib/postgresql//12/bin/psql -tqAc 'select sum(pg_database_size(datname)::numeric) from pg_database;'                                                                                          │
│ /dump.sh: line 18: /usr/lib/postgresql//12/bin/psql: No such file or directory                                                                                                                        │
│ /dump.sh: line 94: / DUMP_SIZE_COEFF: syntax error: operand expected (error token is "/ DUMP_SIZE_COEFF")                                                                                             │
│

**Comment by FxKu** [comment]
Thanks for finding this. Could reproduce it. For some reason the double slash works with all other versions. Let me see, if removing the tailing `/` from `PG_DIR` env variable will work everywhere.

**Comment by mdemri** [comment]
@FxKu That's that default image for backups.. The operator is taking the latest version every backup task invokation?

**Comment by FxKu** [comment]
yes, as there is no tag, it's `latest`
