### ISSUE TITLE
missing owner reference

### ISSUE THREAD

**Issue by phin1x** [zalando/postgres-operator#793]
the operator should set an owner reference to the corresponding postgresql crd object on all objects (statefulsets, service, etc...) it creates. This would simplify the deletion of a cluster as kubernetes would partly (or full) take care of the deletion.

**Comment by FxKu** [comment]
I find `kubectl delete postgresql my-cluster` quite simple :smiley: 

But, I know what you mean. When there are errors in the start up process, sometimes this doesn't work properly. Also when you delete the operator first, the cluster keeps running (which is what we want) and deletion gets trickier (but usually you shouldn't do this).

Feel free to create a PR for it. It's on our [list](https://github.com/zalando/postgres-operator/issues/537), but hasn't a high priority.
