### ISSUE TITLE
Cluster stuck in no leader situation

### ISSUE THREAD

**Issue by thepotatocannon** [zalando/postgres-operator#805]
Hi, we met some issues earlier this week. We have a test cluster made of 3 pods. After the weekend all of  pods were demoted to replicas. Unfortunately, we don't have logs saved, but all nodes claimed that they failed acquiring lock and follow another leader. We cannot tell what caused the issue.
Restarting pods resolved the problem and cluster started working fine. 
Does anybody know what could be the reason and also if it is healthy state that cluster cannot elect the master and demotes every node to replica?

**Comment by CyberDem0n** [comment]
Without logs it is not possible to tell what was wrong.

**Comment by CyberDem0n** [comment]
At least it would be nice if you specify what spilo version you run

**Comment by thepotatocannon** [comment]
> At least it would be nice if you specify what spilo version you run

It is:
```
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p16
```

**Comment by CyberDem0n** [comment]
I see...
There is one suspect: https://github.com/zalando/patroni/pull/1366/files, but no new image yet released

**Comment by thepotatocannon** [comment]
Thanks a lot for the answer.
Any insights when the new image is being released on zalando registry?

**Comment by dejwsz** [comment]
maybe this is related somehow? https://github.com/zalando/postgres-operator/issues/855
