### ISSUE TITLE
running more than 10 replicas

### ISSUE THREAD

**Issue by eafzali** [zalando/postgres-operator#807]
Setting the `numberOfInstances` any number greater than 11 will cause following error on the operator:
```
ERROR: Failed to create physical replication slot '..._11'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 236, in _query
    cursor.execute(sql, params)
psycopg2.errors.ConfigurationLimitExceeded: all replication slots are in use
 
HINT:  Free one or increase max_replication_slots.
 ```
and setting the `max_replication_slots` in `postgres.parameters` doesn't change the setting on the db, `show max_replication_slots`  returns `10` regardless of what I've set in the manifest.

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: team1-db1
spec:
  teamId: "team1"
  volume:
    size: 10Gi
    storageClass: ssd
  numberOfInstances: 15
  users:
    user1:
    - superuser
    - createdb
  databases:
    db1: user1
  postgresql:
    version: "11"
    parameters: 
        shared_buffers: "2GB"
        temp_buffers: "512MB"
        work_mem: "8GB"
        max_connections: "200"
        random_page_cost: "1"
        max_replication_slots: "50"
```

How should I create more replicas?

**Comment by Jan-M** [comment]
I could ask "why" but fair point, increasing slot count should work.

**Comment by eafzali** [comment]
you mean *why* do I need more than 10 replicas?

**Comment by Jan-M** [comment]
Yeah exactly, but I also like this to be possible if it is needed as I am not aware of any limits. Maybe also worth looking into how to do cascading replication instead of single source.

**Comment by eafzali** [comment]
Yea cascading replication would be great, but for now I need to know how to set `max_replication_slots` `and `max_wal_senders` using the operator.

**Comment by FxKu** [comment]
should be with `patronictl edit-config` when execed into the master
