### ISSUE TITLE
Cluster pod label selector mismatch in UI

### ISSUE THREAD

**Issue by dmayle** [zalando/postgres-operator#815]
The operator UI depends on the API call found at: `/statefulsets/<namespace>/<cluster>/pods`

This API call does a search for pods with the label "version=<cluster_name>", and if they don't exist, won't report the cluster as being ready.

There are four ways to get this label on cluster pods:

1.  Set `cluster_name_label` to `version`
2.  Add `version` to the list of `inherited_labels` and set the label on your Postgresql manifest
3. Add `version: <cluster_name>` to cluster_labels, but this only works for one cluster at a time
4. Manually add the label after pod creation.

Either the cluster_name_label should be updated to default to 'version', the UI code should be updated not to use `version`, or the inherited_labels should have a default that includes `version` with updated docs suggesting to use that.

**Comment by FxKu** [comment]
Yep, hardcoded [here](https://github.com/zalando/postgres-operator/blob/8794e4f9acad87c8acbb0e4dd13b952fcd38f89e/ui/operator_ui/spiloutils.py#L140).

Changed it to `cluster-name` in PR #782, but better we make it configurable somehow. Good to know, you've found a workaround.

**Comment by FxKu** [comment]
The cluster name label can now be [set](https://github.com/zalando/postgres-operator/blob/master/ui/manifests/deployment.yaml#L45) for the UI
