### ISSUE TITLE
Operator UI v1.2.0 does not work with kubernetes v1.16.0 and above

### ISSUE THREAD

**Issue by dmayle** [zalando/postgres-operator#817]
As of kubernetes 1.16.0, apps/v1beta1 is no longer being served without special contortions (there's a runtime config flag to enable it).

as of UI 1.2.0 (July of 2019), the python app hardcoded apps/v1beta1 for the statefulset lookup, which means that it is no longer found by the UI, and clusters status is stuck.

There was already a fix committed, but there has been no new release of the UI since 1.2.0.

Please release an updated UI image on docker

**Comment by FxKu** [comment]
Good catch! Wanted to make a v1.3.0 release for the UI today, anyway. But this would have slipped through. Thanks

**Comment by FxKu** [comment]
Took a bit longer, sorry. I've just pushed a `v1.3.0` release image for the UI.
