### ISSUE TITLE
Error Installation Rancher

### ISSUE THREAD

**Issue by excme** [zalando/postgres-operator#827]
`
failed to install app postgres-operator. Error: unable to convert to CRD type: unable to convert unstructured object to apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition: cannot convert int64 to float64\n
`
Do you have Chart for helm2 ?
**Helm:** v2.14.3-rancher1

**Comment by FxKu** [comment]
Remove all [`minimum`](https://github.com/zalando/postgres-operator/blob/3b10dc645dd3f4112df7d15042f335b86c01b3fc/charts/postgres-operator/crds/postgresqls.yaml#L146) [fields](https://github.com/zalando/postgres-operator/blob/3b10dc645dd3f4112df7d15042f335b86c01b3fc/charts/postgres-operator/crds/operatorconfigurations.yaml#L71) from the CRDs and it should work. Or use helm3 :)
