### ISSUE TITLE
Postgres Operator should not assume it is the only operator

### ISSUE THREAD

**Issue by flickerfly** [zalando/postgres-operator#828]
It would be nice if this operator didn't build up like it was the only operator in town. Using a systemaccount called "operator" and being configured by a CRD of kind "OperatorConfiguration" is a bit awkward when implemented among other operators. It would save questions about what operator is associated with OperatorConfiguration. I do support the config by CR rather than ConfigMap concept though.

I wouldn't mind so much if it assumed it was the only postgres operator. That seems reasonable, but not sure why even that confusion couldn't be avoided.

**Comment by FxKu** [comment]
I agree, that the name `OperatorConfiguration` is too generic. You have too see that the project started about three years ago, where operators in K8s were pretty new. I think that's why the original authors chose this name.

The operator service account will be eliminated with #786

**Comment by flickerfly** [comment]
Yeah, totally get that history. :-) Cool to hear the serviceaccount is
already on the block.
