### ISSUE TITLE
Logical backup dump.sh fails with unbound LOGICAL_BACKUP_S3_REGION variable

### ISSUE THREAD

**Issue by kichay** [zalando/postgres-operator#831]
Good day.
I can see "nounset" option enabled in https://github.com/zalando/postgres-operator/blob/master/docker/logical-backup/dump.sh#L5 which blows up dump.sh script execution on "[[ -z "$someUnboudVariable" ]] ...". Logical backup script execution seems imposible with $LOGICAL_BACKUP_S3_REGION unbounded.

**Comment by FxKu** [comment]
Sounds very similar to #826 . Which logical backup image are you using? `registry.opensource.zalan.do/acid/logical-backup` or do you build from the OS repo? I've merged support for `LOGICAL_BACKUP_S3_REGION` in our internal repo, but reverted it now until we have a new operator release.

**Comment by kichay** [comment]
I have tried to use registry.opensource.zalan.do/acid/logical-backup image.

You can check this for bug understanding:
```
stagig@pet-projects:~$ cat test.bash 
#! /usr/bin/env bash

set -o nounset
[[ ! -z "$LOGICAL_BACKUP_S3_REGION" ]] && echo Helo!
stagig@pet-projects:~$ ./test.bash 
./test.bash: line 4: LOGICAL_BACKUP_S3_REGION: unbound variable
```

**Comment by DanArlowski** [comment]
Hello, Im having a similar problem with a different variable:

```bash
/dump.sh: line 56: LOGICAL_BACKUP_PROVIDER: unbound variable
```

seems like it just not mounted correctly from the operator, but the values do persist in the operator config as they should.
any other values for the logical backup are mounted correctly.
Have you got a solution for that?
