### ISSUE TITLE
Invalid type of value

### ISSUE THREAD

**Issue by thepotatocannon** [zalando/postgres-operator#838]
Hi, I try to recreate my cluster from s3 and I currently fight with the following issue:
In my clone section of cluster manifest I configure the value: `s3_force_path_style: true ` among the others needed to restore from a backup.
If I don't use quotes, this is what I get after trying to apply via kubectl:
```
The postgresql "test-postgres" is invalid: spec.clone.s3_force_path_style: Invalid value: "boolean": spec.clone.s3_force_path_style in body must be of type string: "boolean"
```

So I tried to use quotes(`s3_force_path_style: "true" `), but then again operator cannot work with it:
```
time="2020-02-21T14:52:53Z" level=debug msg="skipping \"ADD\" event for the invalid cluster: json: cannot unmarshal string into Go struct field CloneDescription.s3_force_path_style of type bool" cluster-name=kamil/test-postgres pkg=controller
```

**Comment by FxKu** [comment]
oha, that's a bug in the validation. Will fix it now. Thanks for finding it. Simply edit your postgresql CRD as a quick work around.
