### ISSUE TITLE
How to run on Openshift 3.11 ?

### ISSUE THREAD

**Issue by dejwsz** [zalando/postgres-operator#853]
I tried to run the operator in version 1.3.1 or 1.4.0 with default "restricted" security context constraints (SCC) with no luck. Is there any official doc telling how to do it without root permission and with dynamic UID as it takes place usually on Openshift? Anyone did it with provided docker images? Or I need to prepare some modified ones tailored to Openshift?

**Comment by flickerfly** [comment]
There are a few closed issues on this which should provide the answers you are looking for:
https://github.com/zalando/postgres-operator/issues?q=is%3Aissue+openshift+is%3Aclosed

**Comment by dejwsz** [comment]
Yeah I saw them, first I am trying to check all in privileged mode just to tun it. And I am pretty close but "pod_role_label" does not work well and endpoints are not working because of this making cluster sync not possible. If I resolve this then I will try to check everything in restricted mode. I tried before but failed.

**Comment by dejwsz** [comment]
I did it in the privileged mode so far:

https://github.com/zalando/postgres-operator/issues/852#issuecomment-595219861

**Comment by ReSearchITEng** [comment]
Thanks @dejwsz for your hints.
We've build the image using PR (https://github.com/zalando/spilo/pull/414) on an openshift 4.2 without privileged mode.
We've added the KUBERNETES_USE_CONFIGMAPS: "true"
All permissions issues seem to be gone in non-privileged mode.

Still, something is not working: the cluster goes in error: CreateFailed.
Operator complains it's not able to connect to the service to create users/etc.
There are no errors in the pod logs.
Connecting to the pod I can run pql and connect locally.

Any suggestions are welcome.

(btw, should anyone else want to test the image based on that PR (commit 2f68d40) as of 18 March, is here: docker pull docker.io/researchiteng/spilo:latest )

**Comment by ReSearchITEng** [comment]
For running in non-root mode:
Operator Image should be at least:  registry.opensource.zalan.do/acid/postgres-operator:v1.4.0-21-g1249626-dirty
Operator should be configured with these values:
  kubernetes_use_configmaps: "true"
  docker_image: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p114 #or newer

To get the latest versions of the images of both operator and spilo, do:
https://registry.opensource.zalan.do/v2/acid/postgres-operator/tags/list
https://registry.opensource.zalan.do/v2/acid/spilo-cdp-12/tags/list

**Comment by FxKu** [comment]
Thanks @ReSearchITEng for providing infos about rootless Spilo and new operator options. Closing this issue now. Anybody feel free to reopen, if you still face problems.
