### ISSUE TITLE
Can operator postgis database?

### ISSUE THREAD

**Issue by kashif68** [zalando/postgres-operator#857]
The operator only creates postgres database?
Do we have to extend the operator to use PostGis extension?

**Comment by CyberDem0n** [comment]
Just connect as superuser and run `CREATE EXTENSION postgis;`

**Comment by kashif68** [comment]
Ok. 
The question was about way to specify in the CRD manifest for enduser.
Is there a way in the manifest so operator can do this automatically for us.
