### ISSUE TITLE
Helm chart tar.gz files contain tar.gz files of previous releases

### ISSUE THREAD

**Issue by frittentheke** [zalando/postgres-operator#864]
While the postgres-operator-1.2.0.tgz only contains the plain Helm template files and other scaffolding, when looking into the tar.gz. file for the Helm chart version 1.3.0 you can find _postgres-operator-1.2.0.tgz_ inside there. 

With postgres-operator-1.4.0.tgz the two previous versions are in there:
 postgres-operator-1.2.0.tgz
 postgres-operator-1.3.0.tgz

I suppose your `tar cfz` simply lacks an exclude for the existing *.tar.gz files :-)

**Comment by FxKu** [comment]
Yeah, for the next release I should delete the index files and archive and generate a new helm release. There's no need to keep these outdated archives. I've only used helm command to produce these files: `helm package .` and `helm repo index .`

**Comment by frittentheke** [comment]
Thanks for looking into this @FxKu .
The "old" archives are certainly required to allow installing an older chart via Helm. The issue is more that one archive contains all the older ones ...
