### ISSUE TITLE
Cannot evict master pod

### ISSUE THREAD

**Issue by muff1nman** [zalando/postgres-operator#867]
I have a cluster with 2 instances and today needed to cordon and drain the node the master was on. However, the pod disruption budget prevented me from doing so. Reading other issues on here it sounds like this operator is mis-using the pod disruption budget to prevent failovers rather than to prevent a complete outage of the db.

**Comment by FxKu** [comment]
This seems to be duplicate to #611. There is an [option](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#pod-disruption-budget) to disable the PodDisruptionBudget.

**Comment by muff1nman** [comment]
I'd like to use the pdb, how can I do so and retain the ability to drain nodes with just kubectl?

**Comment by FxKu** [comment]
Have you already read the discussion #547? I think, it's explained there. Iirc only works with workarounds.
