### ISSUE TITLE
Disabling SSL

### ISSUE THREAD

**Issue by Repulser** [zalando/postgres-operator#868]
From what it seems the default `pg_hba.conf` requires SSL, Is there a simple way to allow non-ssl connections?

**Comment by FxKu** [comment]
Since [this PR](https://github.com/zalando/spilo/pull/366) Spilo has option to run without SSL. You could define an additional [pod environment configmap](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#custom-pod-environment-variables) where you set this field.

**Comment by Zorlin** [comment]
Hi there!

Has there been any changes to this? I've been struggling to figure out how to enable non-SSL connections as there's an Apache Guacamole helm chart that doesn't seem to support TLS/SSL connections as it stands.

**Comment by caniko** [comment]
> Since [this PR](https://github.com/zalando/spilo/pull/366) Spilo has an option to run without SSL. You could define an additional [pod environment configmap](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#custom-pod-environment-variables) where you set this field.

This doesn't seem like a real solution, looking at the current [discussions](https://github.com/zalando/postgres-operator/issues/1034#issuecomment-984760984)

**Comment by thangamani-arun** [comment]
@caniko : You are right. 

@FxKu: with pg_hba entries and **ALLOW_NOSSL** in configmap it doesn't resolbve the clients to connect without SSL.  tested in chart **v1.8.1**
