### ISSUE TITLE
[Question] How often is WAL archiving to S3 done?

### ISSUE THREAD

**Issue by vitobotta** [zalando/postgres-operator#881]
Hi, I was wondering how often the archiving is performed. Also, is there a better place for questions rather than issues? Thanks!

**Comment by frittentheke** [comment]
It is done "continuously"  (https://www.postgresql.org/docs/12/continuous-archiving.html) - each time the _archive_command_ (powered by WAL-E) is invoked.

The actual rate depends on the configuration of PostgreSQL (done via Spilo / Patroni):
One setting that creates an upper limit is _archive_timeout_ (https://www.postgresql.org/docs/12/runtime-config-wal.html#RUNTIME-CONFIG-WAL-ARCHIVING) forcing PostgreSQL to switch to a new WAL file even if there is not enough data yet to fill up the current one.

**Comment by vitobotta** [comment]
Hi @frittentheke ! By "continuously" are you referring to archiving to disk only, or also to s3? Thanks!

**Comment by frittentheke** [comment]
@vitobotta  While somewhat related due the use of the WAL (files) please don't mix up replication and archiving.

The replication between two or more PostgreSQL instances (so the master and the slaves) happens between them and does not involve archiving of the WAL files. Usually the changes are "streamed" (thus why it's called streaming replication) right from one host to the other. If the slave lags or is offline for a while there is a configurable amount of WAL files / data that the master keeps in order for the slave to replay when it comes back online.

Archiving is more a question of being able to do point-in-time recovery (PITR) and means that the WAL files (even if they are not even used to replicate to any slaves) are stored for a longer period of time (or shipped of the host, i.e. by uploading them to S3).

All of this is more or less PostgreSQL functionality and has nothing to do with the postgres-operator.

**Comment by vitobotta** [comment]
@frittentheke I am very new to Postgres so thanks for the clarification!
