### ISSUE TITLE
Logical backup's cronjob not recreated when configuration change or deleted

### ISSUE THREAD

**Issue by donovanmuller** [zalando/postgres-operator#897]
If you configure and enable a logical backup successfully, which creates the expected `cronjob` using the configuration specified on the `operatorconfigurations.acid.zalan.do` resource. 

Then you update the logical backup configuration (the `logical_backup_s3_endpoint` value for example) on the `operatorconfigurations.acid.zalan.do` resource, the existing managed `cronjob` resource is not recreated with the new configuration. Furthermore, deleting the `cronjob` does not result in the operator recreating the `cronjob`.

If you delete the `cronjob` and _restart_ the operator, only then will the `cronjob` be recreated with the new configuration. I would expect the lifecycle of the managed `cronjob` to be totally managed by the operator, both from configuration updates as well as replacing on external deletion.

**Comment by FxKu** [comment]
Duplicate to #768 :)
