### ISSUE TITLE
Issue with "Checking status of cluster"

### ISSUE THREAD

**Issue by evilezh** [zalando/postgres-operator#899]
When I click on cluster, it shows me "Waiting for 1st container to spawn", meanwhile postgres is up and working. I did sping single node cluster in this particular case.
It does not impact anything, just let you know.
![image](https://user-images.githubusercontent.com/5277173/78464914-1fb99380-76e7-11ea-9e1a-a72948586368.png)

p.s. 
I think this is one of the best operators I've seen so far :) gj :)

**Comment by FxKu** [comment]
I'm pretty sure, there's a mismatch between the cluster name label used by the operator and UI - as I've seen this error before. For the latter, it was hard-coded to `version` before `v1.4.0`. Now it can be [set](https://github.com/zalando/postgres-operator/blob/64389b8bad2940e829047799850645b02c55da5e/ui/manifests/deployment.yaml#L45). It must be the same label than in your [configmap](https://github.com/zalando/postgres-operator/blob/64389b8bad2940e829047799850645b02c55da5e/manifests/configmap.yaml#L13) or [OperatorConfiguration](https://github.com/zalando/postgres-operator/blob/64389b8bad2940e829047799850645b02c55da5e/manifests/postgresql-operator-default-configuration.yaml#L26).
