### ISSUE TITLE
disk is filling up with crash file within 30 mins of patroni postgresql cluster is launched

### ISSUE THREAD

**Issue by amunaf** [zalando/postgres-operator#902]
I have created a three node cluster with patroni postgresql cluster. Below is my seup:

[amunaf@vitest-pg-cluster ~]$ kubectl get nodes
NAME                STATUS   ROLES    AGE   VERSION
vitest-pg-cluster   Ready    master   15d   v1.17.4
vitest-pg-ha1       Ready    <none>   15d   v1.17.4
vitest-pg-ha2       Ready    <none>   15d   v1.17.4

[amunaf@vitest-pg-cluster ~]$ helm install postgres incubator/patroni --set kubernetes.configmaps.enable=true,replicaCount=3

NAME                 READY   STATUS    RESTARTS   AGE   SPILO-ROLE
postgres-patroni-0   1/1     Running   0          27s   master
postgres-patroni-1   1/1     Running   0          22s   replica
postgres-patroni-2   1/1     Running   0          19s

within 15 mins of cluster creation 200Gb of disk is filled up with crash logs. 

[root@vitest-pg-ha1 data]# df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdc1       200G  200G   24K 100% /mnt/postgresdb

[root@vitest-pg-ha1 data]# ls
base       core.1358  core.1761  core.4592  core.850          patroni.dynamic.json  pg_ident.conf.backup  pg_snapshots  PG_VERSION                   postgresql.conf
core.1053  core.1397  core.1854  core.4682  core.926          pg_commit_ts          pg_logical            pg_stat       pg_wal                       postgresql.conf.backup
core.1160  core.1457  core.1957  core.471   core.951          pg_dynshmem           pg_multixact          pg_stat_tmp   pg_xact                      postmaster.opts
core.1183  core.1460  core.4297  core.4768  core.983          pg_hba.conf           pg_notify             pg_subtrans   postgresql.auto.conf         recovery.conf
core.1259  core.1553  core.4389  core.4808  current_logfiles  pg_hba.conf.backup    pg_replslot           pg_tblspc     postgresql.base.conf         recovery.done
core.1320  core.1660  core.4481  core.701   global            pg_ident.conf         pg_serial             pg_twophase   postgresql.base.conf.backup

I have created the default setup.

[amunaf@vitest-pg-cluster ~]$ kubectl get pods -L spilo-role -o wide
NAME                 READY   STATUS    RESTARTS   AGE   IP              NODE            NOMINATED NODE   READINESS GATES   SPILO-ROLE
postgres-patroni-0   1/1     Running   0          48m   192.168.17.76   vitest-pg-ha1   <none>           <none>
postgres-patroni-1   1/1     Running   0          47m   192.168.17.77   vitest-pg-ha1   <none>           <none>
postgres-patroni-2   1/1     Running   0          47m   192.168.17.72   vitest-pg-ha1   <none>           <none>

**Comment by Chwetion** [comment]
anyone can help? @alexeyklyukin @erthalion @Jan-M

**Comment by erthalion** [comment]
> disk is filling up with crash file
> core.1358 core.1761 core.4592 core.850

By crash files you mean those core dumps? In general it has nothing to do with the operator and probably this is a question more fitting to spilo repository. But the first thing would be to post postgres logs & content of core dumps I guess.

**Comment by Chwetion** [comment]
i solved this problem by modifying the kernel parameters. the operator will keep pulling up postgresql, but due to constant crashes, it will generate core files with different pids. Modify the kernel.core_uses_pid parameter so that every time Only keep the dump file of the last crash. 
thx for help @erthalion 
`echo kernel.core_uses_pid=0 >> /etc/sysctl.conf && sysctl -p`

**Comment by erthalion** [comment]
> echo kernel.core_uses_pid=0 >> /etc/sysctl.conf && sysctl -p

Unfortunately this is not a solution, but rather hiding the problem. If it doesn't crash anymore it's fine, if it still crashes, the reason needs to be investigated. But of course it's up to you :)

**Comment by Chwetion** [comment]
> > echo kernel.core_uses_pid=0 >> /etc/sysctl.conf && sysctl -p
> 
> Unfortunately this is not a solution, but rather hiding the problem. If it doesn't crash anymore it's fine, if it still crashes, the reason needs to be investigated. But of course it's up to you :)

yes, the crash still needs to be solved, but I don’t want the dumped files to be filled up without me noticing the crash, this is what I really worry about in this issue

**Comment by erthalion** [comment]
Then I would suggest to open an issue in spilo about that. We already reduce size of core dumps there, maybe it makes sense also to enforce keeping only one dump for such extreme situations. Thanks for reporting, close the issue for now.
