### ISSUE TITLE
Question for 'increase volume size' in statefulset 

### ISSUE THREAD

**Issue by jacobzhang0110** [zalando/postgres-operator#904]
In https://github.com/zalando/postgres-operator/blob/master/docs/user.md#increase-volume-size 

To enlarge persistent volumes attached to the running pods, the operator performs the following actions:
    call AWS API to change the volume size
    connect to pod using kubectl exec and resize filesystem with resize2fs.

Do you know is there any impact (functional or non-functional) towards DB client during the period of above 2 actions?

**Comment by FxKu** [comment]
It does not trigger a rolling update hence no downtime. WIth the the new `v1.6.0` release, you can now use the K8s-native resizing where only PVCs are updated and then your storage class should do the rest. Closing this question.
