### ISSUE TITLE
Cpu limit value cannot be set

### ISSUE THREAD

**Issue by iustinlita** [zalando/postgres-operator#905]
After the latest update for the following input in the cluster manifest:
requests:
      cpu: "1"
limits:
      cpu: "4"
The bellow error occurred:
"level=error msg="could not create cluster: could not enforce minimum resource limits: could not compare defined CPU limit 4 with configured minimum value : could not parse limit  : quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
The same for like "500m" format also.

**Comment by FxKu** [comment]
Sounds like [min_cpu_limit](https://github.com/zalando/postgres-operator/blob/4dee8918bd45e4356e10acf15b9f71bf0a43f9bd/manifests/postgresql-operator-default-configuration.yaml#L62) is nil. Which configuration are you using? ConfigMap or CRD (OperatorConfiguration)? Which version of the operator are you running?

**Comment by iustinlita** [comment]
The version is 1.4.0 and the config is done using the CRD with values set like in the default-configuration.

**Comment by FxKu** [comment]
a quick workaround would be to set a value for `min_cpu_limit`. I think we noticed it before that defaults do no apply correctly when using CRD-config, unfortunately. Should be handled like [this](https://github.com/zalando/postgres-operator/blob/a1f2bd05b978b4dac384eb14a06a39f590cf5f57/pkg/controller/operator_config.go#L62).

**Comment by hzliangbin** [comment]
@FxKu I guess it might be a problem about "qoute", just similar with [#951 ](https://github.com/zalando/postgres-operator/pull/951). i gonna checki it later.
