### ISSUE TITLE
Disable WAL archiving on cluster

### ISSUE THREAD

**Issue by spohner** [zalando/postgres-operator#907]
We regularly create temporary database clusters to do computations and data processing. It would be great to turn off WAL archiving and uploading to S3 for these types of workloads. We do not need backups for these and disabling it will reduce costs.

Will submit a PR adding a disableWALArchiving option in the cluster-spec allowing to override the WAL_S3_BUCKET environment variable and setting it to blank. This will tell Spilo to disable the WAL archiving.

**Comment by spohner** [comment]
Related PR: https://github.com/zalando/postgres-operator/pull/908

**Comment by Jan-M** [comment]
If you need this already, you could build a new Spilo Docker Image with setting the WAL_S3_Bucket path to empty and using this in the manifest.

We will look into the PR nontheless. Also in regards to preventable errors.

**Comment by spohner** [comment]
Maintaining a fork with this change atm, and seems to work just fine. Anyway thanks for the tip, @Jan-M!
