### ISSUE TITLE
postgres operator chart version-1.4.0 package out-of-date with master

### ISSUE THREAD

**Issue by boopathykpm** [zalando/postgres-operator#909]
Postgres operator chart is not in sync with the master. The pod service account name is hardcoded, and it's passing errors when creating multiple operator releases. 

This restricted me from creating multiple Postgres operator on the Kubernetes cluster, as the ClusterRole name was hardcoded on clusterrole-postgres-pod.yaml and found it got fixed 14days back.

**Comment by FxKu** [comment]
unless you not using a new image [here](https://github.com/zalando/postgres-operator/blob/7232326159a9f77766260bc3e7b49f79dd101bd8/charts/postgres-operator/values.yaml#L4), new operator features will not work. You have to work with the `latest` version of the master and wait for the next release, which is planned for end of April.

**Comment by boopathykpm** [comment]
The problem I'm facing currently with the latest helm package is as mentioned above, "postgres-pod" is hardcoded in `clusterrole-postgres-pod.yaml ` so I'm not able to install multiple operators in the cluster. which is a kind of blocker. Using the `latest` version of the master fixes my problem?

**Comment by FxKu** [comment]
Running multiple operators with configurable clusterrole was fixed in #876

**Comment by boopathykpm** [comment]
Yes, that is not packaged in the helm. I'm trying to consume the helm chart directly from the repo, like
```bash
 helm repo add zalando-postgres https://opensource.zalando.com/postgres-operator/charts/postgres-operator
 helm install vmn-zalando-test  zalando-postgres/postgres-operator 
```
While doing that, the archived code has the old code for the clusterrole-postgres-pod.yaml , at that time it's failing.

**Comment by boopathykpm** [comment]
@FxKu I don't think that image version will be a problem for the helm chart current version (1.4.0), already the chart is using that image version, and my package has only the fix on `clusterrole-postgres-pod.yaml ` so anyway people using the latest helm chart will end up using `v1.4.0`. I hope the release change going to be made on April end is the new version of the chart and not the same version, so it makes sense to accept this PR. 

Please, let me know your thoughts as well.

**Comment by FxKu** [comment]
Hm, ok why holding it back? I was afraid that the new bundle would also off fields which are not supported by `v1.4.0` release. But afaik, they would just be omitted and not cause errors. So gave my +1

**Comment by boopathykpm** [comment]
Thanks, @FxKu .

I have tested on my end with `v1.4.0` i didn't face any error.
