### ISSUE TITLE
Allow propagating annotations to the StatefulSet

### ISSUE THREAD

**Issue by hjacobs** [zalando/postgres-operator#913]
We use the `deployment-time` annotation in Zalando to denote the "last update" time.
This annotation is automatically injected to all resources, incl. the Postgres CRD. The problem: the annotation is not passed to the StatefulSet which is therefore not considered to be "updated".
This creates an issue in combination with [kube-downscaler](https://github.com/hjacobs/kube-downscaler/).

My request: allow configuring certain annotations to be "propagated" to the StatefulSet.
Example annotations I would want to propagate:

* `deployment-time`
* `downscaler/exclude`
* `downscaler/exclude-until`
* `downscaler/uptime`
* `downscaler/downtime`

My implementation proposal would be:

* add a configuration option `statefulset_propagate_annotations` (for the ConfigMap) to specify a list of patterns for annotations to propagate (e.g. `deployment-time,downscaler/.*`)
* change the operator to take all annotations (filtered by the pattern list above) from the CRD and apply them on the StatefulSet

This allows users to configure the underlying StatefulSet via the CRD.

**Comment by hjacobs** [comment]
As far as I can see, this line needs to be changed and dynamically build annotations (instead of hardcoded map with one entry): https://github.com/zalando/postgres-operator/blob/4dee8918bd45e4356e10acf15b9f71bf0a43f9bd/pkg/cluster/k8sres.go#L1138

**Comment by FxKu** [comment]
Only for stateful set? For services and pods we already provide annotation options (local per manifest: `podAnnotations`, `service_annotations`, global per config: `custom_pod_annotations`, `custom_service_annotations`). It's not hard to add yet another option :smile:

**Comment by hjacobs** [comment]
@FxKu I would like to avoid a custom config (like `podAnnotations`) as the annotation `deployment-time` is automatically injected by the CI/CD pipeline. I don't want to add some custom logic just for the Postgres CRD. Regarding the `Service` resource: yes, I think the annotation should also be propagated to the `Service`. I would see the Pods a bit different as they are managed by the StatefulSet itself, so they don't map 1-1 to the Postgres CRD and also don't need the `deployment-time` or `downscaler/*` annotations.

**Comment by Jan-M** [comment]
Seems like something we can add, as much as I am not immediately a fan of scaling up and down Postgres stateful sets. But it works and works also well for single pod clusters e.g. in test environments outside of office hours.

Propagating this to pods I agree I do not see useful, in fact the opposite, we see many deployments of CRDs without change and pod annotations should not change.

The pattern sounds like a good solution in this case.

**Comment by sdudoladov** [comment]
@hjacobs 
```
My request: allow configuring certain annotations to be "propagated" to the StatefulSet.
Example annotations I would want to propagate
```

Must the annotations be always present for all operator-managed stateful sets in a k8s cluster or can it be that  one must remove them from individual stateful sets ?
