### ISSUE TITLE
support for logical replication 

### ISSUE THREAD

**Issue by mkhodave** [zalando/postgres-operator#931]
we are using postgres operator with numberofInstances: 2 , we have requirement of following postgres parameter for logical replication
wal_level = logical

is it possible to set this parameter on postgres operator configuration, if yes what will be configuration in postgres operator manifest file

**Comment by FxKu** [comment]
Config parameters can be set in the manifest in the `postgresql` [section](https://github.com/zalando/postgres-operator/blob/master/manifests/complete-postgres-manifest.yaml#L26). Haven't tried `wal_level` yet myself.

**Comment by mkhodave** [comment]
Yes, I am aware of cloning feature of postgres operator, but in our use case we need to use database with combination of other replicated databases in one place so we are using logical replication
By the way suggested steps worked for us, Thanks a lot

**Comment by FxKu** [comment]
You're welcome. Closing it then.

**Comment by haf** [comment]
Where's this postgresql section documented?
