### ISSUE TITLE
Typo in AdditionalVolume struct that makes it impossible to specify volumeSource in cluster manifest

### ISSUE THREAD

**Issue by siku4** [zalando/postgres-operator#934]
related to PR #736:

It is not possible to specify a `volumeSource` based on the given cluster manifests examples and the documentation: The name of the json field within the `AdditionalVolume` struct is `volume`:
https://github.com/zalando/postgres-operator/blob/3c91bdeffadb5ec736a63548b5ffa08517c59de8/pkg/apis/acid.zalan.do/v1/postgresql_type.go#L107 The name specified in the CRD is `volumeSource`:
https://github.com/zalando/postgres-operator/blob/3c91bdeffadb5ec736a63548b5ffa08517c59de8/manifests/postgresql.crd.yaml#L45-L48

The unit tests don't cover this case and there is no error when creating a cluster because k8s falls back to `emptyDir` when no volume type is provided.

After adding a `volume` field with the desired settings (`volumeSource` has to remain because it is a mandatory field) everything works fine. 

I have fixed it in PR #933

**Comment by FxKu** [comment]
left a comment in the PR. Good catch, thanks.

**Comment by siku4** [comment]
fixed with https://github.com/zalando/postgres-operator/commit/f32c615a531426804d031b16967d69a4ec364c16
