### ISSUE TITLE
Patroni/Postgres restarts with multiple databases

### ISSUE THREAD

**Issue by muhlba91** [zalando/postgres-operator#935]
Our setup looks like this:
- postgres-operator: 1.4.0
- kubernetes: RKE 1.17.4
- postres version: 11 and/or 12

We use the sample postresql yaml you provide for simple testing with out Java application (Hikari pool).
This works quite well for one service and one database within the bootstrapped cluster.

However, once we add another database in the `databases` array and try to connect a second service to it, postres seems to be killed and restarted every few seconds and patroni, therefore, also gets killed with code 1, signal 9.

Additionally, for all databases (except the first one), we receive a warning that it uses the default timeout and an error `connection error: PQConnectPoll`.

Are multiple databases supported or are there any other parameters to set to get it working?

I also tried increasing `max_conmections` without any success.
However, e.g. increasing it to 1000 let the `post_init.sh` script get killed and bootstrapping failed.

**Comment by CyberDem0n** [comment]
You have to "give" it more memory, i.e. increase memory requests and limits.

**Comment by muhlba91** [comment]
I had the same thought but increasing the limits has not worked:
- cpu: 500m
- memory: 258M and I have also tried with 384M

Also when I was looking into the `kubectl top pod` I have not received much more than ~110M memory and 100m cpu before it crashed.

Any ideas on why setting the max. connections property to 1000 fails? In the end, we want to have about 13 services being connected, each with a connection pool of at least 10, some even higher due to the expected load.

**Comment by CyberDem0n** [comment]
> 258M and I have also tried with 384M

We live in the 21 century.
Patroni needs ~70MB. For postgres we set shared_buffers to 20% of memory
Every connection consumes about 10MB.
Besides that there are auxiliary processes, like checkpointer, autovacuum launcher, bgwriter, walwriter and so on.
There is also pgq and wal-e in the container.
Besides that postgres heavily relies on page cache, so it doesn't always need to read something from disk when it is not in the shared_buffers.

300MB is a bare minimum which is required just to start the container.

> Also when I was looking into the kubectl top pod I have not received much more than ~110M memory and 100m cpu before it crashed.

Depending on the situation the `kubectl top pod` for postgres shows weather on Mars than the real memory usage.

It could be never too much memory for the database (except when there is no data).

Don't be greedy, give it _at least_ 1Gi for the start.

**Comment by muhlba91** [comment]
Awesome! Thanks for the detailed explanation of all running processes which makes it completely clear now.

Yeah, this discrepancy is interesting.
Anyhow, I‘ll close this issue now as I totally understand the cause and clears the requirements. :)
