### ISSUE TITLE
postgres specify minor versions

### ISSUE THREAD

**Issue by haroonb** [zalando/postgres-operator#936]
Hello I'm looking to specify the minor version of the postgres db to be used. As I understand currently only versions on the [versioning site](https://www.postgresql.org/support/versioning/) are supported. Is it planned to be able to specify minor versions.

thanks.

**Comment by FxKu** [comment]
With each Spilo release we update to the latest minor versions. I think, this is something DBaaS users would expect. They don't want to fiddle with minors. I you want to run a specific Pg version you need to either use the Spilo image which has it, or patch it yourself.

**Comment by haroonb** [comment]
Alright, where can I check which spilo image the specific minor version is there a list?

**Comment by FxKu** [comment]
There is no list or matrix, unfortunately. Was already requested before #666.
