### ISSUE TITLE
Why the secret_name_template is different between helm and helm crd?

### ISSUE THREAD

**Issue by jbagot** [zalando/postgres-operator#944]
Hi, I installed the helm without crd, using the `chart/values.yaml` where there is this line:
`secret_name_template: '{username}.{cluster}.credentials'`

But I was expecting to have these credentials: `"{username}.{cluster}.credentials.{tprkind}.{tprgroup}"`
That's because I installed the helm chart using the crd previously.

Now I figured out that in the `values-crd.yaml` has this line:
`secret_name_template: "{username}.{cluster}.credentials.{tprkind}.{tprgroup}"`

Then my question is, why this value is different between these 2 ways of install the same thing?

Thank you.

**Comment by FxKu** [comment]
You're right. They should be aligned - at least in the helm chart. Fixed with #955
