### ISSUE TITLE
How to schedule to the master of postgresql cluster?

### ISSUE THREAD

**Issue by jiandanshifu** [zalando/postgres-operator#957]
How does k8s schedule to the master of postgresql to operate the database cluster, instead of scheduling to the slave node？

**Comment by frittentheke** [comment]
@jiandanshifu can you explain a little more in detail what issues you have?

Are you talking about the scheduling of the pods by the Kubernetes scheduler to either masters or nodes. Or the database master / replica roles of PostgreSQL?

**Comment by jiandanshifu** [comment]
Ok, thank you! I know, the cluster load is achieved through configuration parameters。The parameters are as follows:
enableMasterLoadBalancer 
enableReplicaLoadBalancer
