### ISSUE TITLE
logical replication not resuming after postgres operator pod restart

### ISSUE THREAD

**Issue by mkhodave** [zalando/postgres-operator#963]
Hi,
We are using postgres operator v1.2.0, also created replication slot using this parameter [configuration](https://github.com/zalando/postgres-operator/blob/master/manifests/complete-postgres-manifest.yaml#L94), we are using this replication slot for logical wal streaming on our own datawarehouse database.

Issue which we are observing that , whenever there is restart postgres operator container, subscriptions (replication) created at datawarehouse  can not resume on its own & need to re-establish again.

Do I need to do any configuration to resolve this issue ?

**Comment by FxKu** [comment]
I think, this is the same like what clients have to do after a failover: They have to reconnect.
Btw, you might consider upgrading to v1.5.0 which runs with a newer Patroni and Spilo version.

**Comment by mkhodave** [comment]
Yes, we have upgraded postgres operator v1.5.0 , let's see
