### ISSUE TITLE
PSQLException: FATAL: pg_hba.conf rejects connection

### ISSUE THREAD

**Issue by youtongbin** [zalando/postgres-operator#964]
Hello, I have created a cluster and set "enable_master_load_balancer = true". In the Springboot project, when using JDBC to connect to the database, the following error occurs:
`org.postgresql.util.PSQLException: FATAL: pg_hba.config rejects connection for host "xxx.xxx.xx.xxx", user "xxx", database "xxx", SSL off`,What causes this error? How can I change my configuration to use JDBC to connect to the Postgresql cluster normally?

**Comment by FxKu** [comment]
SSL mode must be set to `required`. Only encrypted traffic is allowed.
