### ISSUE TITLE
Helm deploy broken in v1.5.0

### ISSUE THREAD

**Issue by thiagonache** [zalando/postgres-operator#966]
Hi there,

Using version 1.5.0 the installation of operator-ui does not work via helm. I think it's related to a syntax issue, but I didn't troubleshoot it. See the error message below:
Deployment in version "v1" cannot be handled as a Deployment

How to reproduce:
1- Deploy operator using helm
$ helm install postgres-operator ./charts/postgres-operator -f ./charts/postgres-operator/values-crd.yaml

2- Try to deploy operator ui
helm install postgres-operator-ui ./charts/postgres-operator-ui

If you check out the previous version the operator-ui is deployed with no issue

**Comment by FxKu** [comment]
@thiagonache thanks for raising this. It's an env variable which we set to `"False"`, which got interpreted as a bool. Bummer. Replaced the helm chart zip. Does not affect the docker image.

**Comment by FxKu** [comment]
Merged my fix. Uploaded a new image: Please use `v1.5.0-dirty`.
