### ISSUE TITLE
Cluster in SYNC FAILED state

### ISSUE THREAD

**Issue by aditya1808** [zalando/postgres-operator#971]
Hi, i can see following logs in postgre-operator

![image](https://user-images.githubusercontent.com/6763803/81575399-9e7bad80-93c4-11ea-8635-181ae06b5d12.png)

![image](https://user-images.githubusercontent.com/6763803/81575445-ab989c80-93c4-11ea-8315-bd4df7777a4c.png)

Could someone help regarding this? Initially the cluster was deployed successfully and no errors in logs..but for past few days i could see this in logs..

what could have caused the postgres operator to cause this?
**postgre-operator version - v1.3.1**

**Comment by FxKu** [comment]
@aditya1808 and you did not change anything in the Postgres manifest. Can you check if the service resources for master, replica and config are there?
