### ISSUE TITLE
Order of env variables in sidecontainers changed

### ISSUE THREAD

**Issue by spohner** [zalando/postgres-operator#979]
We use https://github.com/wrouesnel/postgres_exporter as a global sidecar to export metrics. In the manifest file we define environment variables based on the injected environment variables like this: 

    env:
    - name: DATA_SOURCE_URI
      value: localhost/postgres?sslmode=disable
    - name: DATA_SOURCE_USER
      value: $(POSTGRES_USER)
    - name: DATA_SOURCE_PASS
      value: $(POSTGRES_PASSWORD)

With the merge of https://github.com/zalando/postgres-operator/pull/890 the order of which environment variables are added changed. The order of the env variables is actually a part of the API spec according to https://github.com/kubernetes/kubernetes/issues/40373 (could not find it in the spec docs directly).

By adding the common fields last in the env array a pattern like the one above is no longer supported and this could break some apps.

Should be an easy fix by swapping the order in the append method here https://github.com/zalando/postgres-operator/blob/d52296c3235956ea4cb34f78f6e4cf0aa374d09d/pkg/cluster/k8sres.go#L534. 

I will create a simple PR for this ASAP.

**Comment by spohner** [comment]
PR: https://github.com/zalando/postgres-operator/pull/980

**Comment by FxKu** [comment]
@fischerman can you also comment on this, as you are using are probably using this feature in prod?

**Comment by fischerman** [comment]
Makes sense to have the operator environment variables first. Didn't think about that. PR from @spohner looks good!

**Comment by frittentheke** [comment]
I sent in the PR https://github.com/zalando/postgres-operator/pull/946 which sources env variables from a secret. There I particularly allow to "override" certain variables related to backups and buckets - but in general those used by the operator for core functionality should come first if there is not use-case  and this would rather create unintended effects.
