### ISSUE TITLE
Generate index.yaml for charts/ repository

### ISSUE THREAD

**Issue by CermakM** [zalando/postgres-operator#991]
I want to be able to add your charts repository to helm like so:
```
$ helm repo add zalando https://raw.githubusercontent.com/zalando/postgres-operator/<revision>/charts/
```

However, as the repo is currently missing the index.yaml file, it's not possible to do so and I am only able to add single charts. That is clumsy, however, as I need to make separate helm repo for each of them, i.e. zalando-postgres-operator and zalando-postgres-operator-ui.

It should be easy to generate the index.yaml, simply include the following in your release pipeline:

```
# from the charts/ repo
$ helm repo index .
```

**Comment by FxKu** [comment]
Huh, it's [there](https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/index.yaml)? Wrong place?

**Comment by patrickleet** [comment]
`helm repo add zalando https://raw.githubusercontent.com/zalando/postgres-operator/v1.5.0/charts/postgres-operator/` works

**Comment by CermakM** [comment]
@patrickleet Yes, I know it does. But you can't have both `zalando/postgres-operator` and `zalando/postgres-operator-ui` that way.

@FxKu No, that's an index just for the `postgres-operator` chart.

**Comment by FxKu** [comment]
We want to keep it separate.

**Comment by Jan-M** [comment]
I also think there is nothing to be done here, there seems to be two different index.yaml files. One for each project that can be added invidually. We do not want to enforce anyone to add both.
