### ISSUE TITLE
Issue when using synchronous and synchronous_mode_strict in manifest.yaml

### ISSUE THREAD

**Issue by aditya1808** [zalando/postgres-operator#996]
Hi, 
im using synchronous_mode and synchronous_mode_strict = true in my manifest file. the status of pods are 

![image](https://user-images.githubusercontent.com/6763803/83235218-2a584c80-a1af-11ea-9b0a-4bf85869aced.png)

i can see these logs in one of pods. Its not able to contest for leader election

![image](https://user-images.githubusercontent.com/6763803/83235195-1f9db780-a1af-11ea-9891-2323dd01b47d.png)

and below error in pg-operator logs

![image](https://user-images.githubusercontent.com/6763803/83235296-4956de80-a1af-11ea-960d-fa825a6b5d00.png)

**If i use only synchronouse mode  without synchronous_mode_strict i dont see this issue**

**Comment by Jan-M** [comment]
@CyberDem0n any input?

As we dont use this there maybe some bootstrap issue.

Suggest you look into the Postgres log files what is actually going on.

**Comment by aditya1808** [comment]
@Jan-M Do i need to post this in spilo group? or adding the label is enough

**Comment by CyberDem0n** [comment]
The [commit](https://github.com/zalando/spilo/commit/fd74b36c19257aca95d8481d80b28e67c60e6461#diff-ab31b078396f155439631156cf699b44R5-R160) should fix the issue.
You can test it with: `registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p120`
