### ISSUE TITLE
WAL-E not able to push backup to ceph S3 API

### ISSUE THREAD

**Issue by vishu-roy12** [zalando/postgres-operator#999]
Hi
I'm facing a problem, hoping to get some help or guidance.

I have a k8s cluster on VMs ( not on any cloud ), i'm trying to use WAL-E to send backups to S3 compatible API, so i'm using ceph object storage ( radosgw ), so i have configured the object storage and got the keys and the bucket is also created, now when i follow the documentation to set up wal-e bucket, its not able to reach the bucket, however the S3 API is reachable. Below are the configs and the erorr i'm getting.

``` 
configAwsOrGcp:
   wal_s3_bucket: "pg-bucket"
 ```
So thats the bucket name i'm putting in operator values file.

Below is the configmap i'm creating to pass the AWS keys and WALE_S3_ENDPOINT

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: database
data:
  AWS_ACCESS_KEY_ID: <key>
  AWS_SECRET_ACCESS_KEY: <secret>
  WALE_S3_ENDPOINT: http+path://rook-ceph-rgw-my-store.rook-ceph
  WALG_DISABLE_S3_SSE: "true"
  USE_WALG_BACKUP: "true"
```

So below is the error i'm getting, its coming in master database logs.

```
2020-05-11 22:14:36,765 INFO: no action.  i am the leader with the lock
ERROR: 2020/05/11 22:14:37.628708 failed to upload 'spilo/database-cluster/1e1300d2-5fcb-4665-a91f-04fac5d477f8/wal/basebackups_005/base_000000010000000000000002/tar_partitions/part_001.tar.lz4' to bucket 'pg-bucket': RequestError: send request failed
caused by: Put http://pg-bucket.rook-ceph-rgw-my-store.rook-ceph/spilo/database-cluster/1e1300d2-5fcb-4665-a91f-04fac5d477f8/wal/basebackups_005/base_000000010000000000000002/tar_partitions/part_001.tar.lz4: dial tcp: lookup pg-bucket.rook-ceph-rgw-my-store.rook-ceph on 169.254.25.10:53: no such host
ERROR: 2020/05/11 22:14:37.628727 upload: could not upload 'base_000000010000000000000002/tar_partitions/part_001.tar.lz4'
ERROR: 2020/05/11 22:14:37.628733 failed to upload 'spilo/database-cluster/1e1300d2-5fcb-4665-a91f-04fac5d477f8/wal/basebackups_005/base_000000010000000000000002/tar_partitions/part_001.tar.lz4' to bucket 'pg-bucket': RequestError: send request failed
caused by: Put http://pg-bucket.rook-ceph-rgw-my-store.rook-ceph/spilo/database-cluster/1e1300d2-5fcb-4665-a91f-04fac5d477f8/wal/basebackups_005/base_000000010000000000000002/tar_partitions/part_001.tar.lz4: dial tcp: lookup pg-bucket.rook-ceph-rgw-my-store.rook-ceph on 169.254.25.10:53: no such host
ERROR: 2020/05/11 22:14:37.628741 Unable to complete uploads
```

**Comment by redscaresu** [comment]
@vishu-roy12 this looks like a DNS lookup failure to me, is ceph presenting a dns resolvable address to you in the format you have specified from inside your postgres-cluster namespace?

**Comment by vishu-roy12** [comment]
> @vishu-roy12 this looks like a DNS lookup failure to me, is ceph presenting a dns resolvable address to you in the format you have specified from inside your postgres-cluster namespace?

Thanks for replying @redscaresu
Yes, It looks like a DNS problem, so the ceph is presenting with DNS as "rook-ceph-rgw-my-store.rook-ceph" which is resolvable from pods, but when we give bucket name in operator values file, wal-e adds bucket-name as a prefix to the endpoint, so wal-e tries to reach "pg-bucket.rook-ceph-rgw-my-store.rook-ceph" which will not be resolvable from the pods.

**Comment by redscaresu** [comment]
> > @vishu-roy12 this looks like a DNS lookup failure to me, is ceph presenting a dns resolvable address to you in the format you have specified from inside your postgres-cluster namespace?
> 
> Thanks for replying @redscaresu
> Yes, It looks like a DNS problem, so the ceph is presenting with DNS as "rook-ceph-rgw-my-store.rook-ceph" which is resolvable from pods, but when we give bucket name in operator values file, wal-e adds bucket-name as a prefix to the endpoint, so wal-e tries to reach "pg-bucket.rook-ceph-rgw-my-store.rook-ceph" which will not be resolvable from the pods.

nice, do you know how you will resolve that?

**Comment by vishu-roy12** [comment]
> > > @vishu-roy12 this looks like a DNS lookup failure to me, is ceph presenting a dns resolvable address to you in the format you have specified from inside your postgres-cluster namespace?
> > 
> > 
> > Thanks for replying @redscaresu
> > Yes, It looks like a DNS problem, so the ceph is presenting with DNS as "rook-ceph-rgw-my-store.rook-ceph" which is resolvable from pods, but when we give bucket name in operator values file, wal-e adds bucket-name as a prefix to the endpoint, so wal-e tries to reach "pg-bucket.rook-ceph-rgw-my-store.rook-ceph" which will not be resolvable from the pods.
> 
> nice, do you know how you will resolve that?

I don't know yet, that's why hoping if someone came across this problem and can help or guide in this scenario.

**Comment by redscaresu** [comment]
I have a similar issue https://github.com/zalando/postgres-operator/issues/1006.  What we need is a way to push to custom s3 compatible endpoint.  Does anyone know a way this is possible?

One thing I tried was to commenting out   

# wal_s3_bucket: <<bucket name>>

but then providing the entire path I need in WALE_S3_ENDPOINT but it looks like that unless wal_s3_bucket is set from the operator it will not attempt to make a WAL.

**Comment by vishu-roy12** [comment]
@redscaresu Yes, if you comment out wal_s3_bucket, then it will not use WAL-E , instead it will bootstrap the cluster through local backups.

**Comment by senthilcodr** [comment]
This gist might be helpful here: https://gist.github.com/senthilcodr/55f26072c0e33dad985f5311ea13af5a

**Comment by vishu-roy12** [comment]
Thanks @senthilcodr and @redscaresu for your help. I did already solved the problem, forgot to update the issue, my bad.
So i was only missing 
`AWS_S3_FORCE_PATH_STYLE: "true"`

I added this as env variable and it was able to push backup to ceph storage.
